LUT = {
    "calculations": {
        10: {"id":"ID_WEB_Temperatur_TVL","conversion":"celsius"},
        11: {"id":"ID_WEB_Temperatur_TRL","conversion":"celsius"},
        12: {"id":"ID_WEB_Sollwert_TRL_HZ","conversion":"celsius"},
        13: {"id":"ID_WEB_Temperatur_TRL_ext","conversion":"celsius"},
        14: {"id":"ID_WEB_Temperatur_THG","conversion":"celsius"},
        15: {"id":"ID_WEB_Temperatur_TA","conversion":"celsius"},
        16: {"id":"ID_WEB_Mitteltemperatur","conversion":"celsius"},
        17: {"id":"ID_WEB_Temperatur_TBW","conversion":"celsius"},
        18: {"id":"ID_WEB_Einst_BWS_akt","conversion":"celsius"},
        19: {"id":"ID_WEB_Temperatur_TWE","conversion":"celsius"},
        20: {"id":"ID_WEB_Temperatur_TWA","conversion":"celsius"},
        21: {"id":"ID_WEB_Temperatur_TFB1","conversion":"celsius"},
        22: {"id":"ID_WEB_Sollwert_TVL_MK1","conversion":"celsius"},
        23: {"id":"ID_WEB_Temperatur_RFV","conversion":"celsius"},
        24: {"id":"ID_WEB_Temperatur_TFB2","conversion":"celsius"},
        25: {"id":"ID_WEB_Sollwert_TVL_MK2","conversion":"celsius"},
        26: {"id":"ID_WEB_Temperatur_TSK","conversion":"celsius"},
        27: {"id":"ID_WEB_Temperatur_TSS","conversion":"celsius"},
        28: {"id":"ID_WEB_Temperatur_TEE","conversion":"celsius"},
        29: {"id":"ID_WEB_ASDin","conversion":"bool"},
        30: {"id":"ID_WEB_BWTin","conversion":"bool"},
        31: {"id":"ID_WEB_EVUin","conversion":"bool"},
        32: {"id":"ID_WEB_HDin","conversion":"bool"},
        33: {"id":"ID_WEB_MOTin","conversion":"bool"},
        34: {"id":"ID_WEB_NDin","conversion":"bool"},
        35: {"id":"ID_WEB_PEXin","conversion":"bool"},
        36: {"id":"ID_WEB_SWTin","conversion":"bool"},
        37: {"id":"ID_WEB_AVout","conversion":"bool"},
        38: {"id":"ID_WEB_BUPout","conversion":"bool"},
        39: {"id":"ID_WEB_HUPout","conversion":"bool"},
        40: {"id":"ID_WEB_MA1out","conversion":"bool"},
        41: {"id":"ID_WEB_MZ1out","conversion":"bool"},
        42: {"id":"ID_WEB_VENout","conversion":"bool"},
        43: {"id":"ID_WEB_VBOout","conversion":"bool"},
        44: {"id":"ID_WEB_VD1out","conversion":"bool"},
        45: {"id":"ID_WEB_VD2out","conversion":"bool"},
        46: {"id":"ID_WEB_ZIPout","conversion":"bool"},
        47: {"id":"ID_WEB_ZUPout","conversion":"bool"},
        48: {"id":"ID_WEB_ZW1out","conversion":"bool"},
        49: {"id":"ID_WEB_ZW2SSTout","conversion":"bool"},
        50: {"id":"ID_WEB_ZW3SSTout","conversion":"bool"},
        51: {"id":"ID_WEB_FP2out","conversion":"bool"},
        52: {"id":"ID_WEB_SLPout","conversion":"bool"},
        53: {"id":"ID_WEB_SUPout","conversion":"bool"},
        54: {"id":"ID_WEB_MZ2out","conversion":"bool"},
        55: {"id":"ID_WEB_MA2out","conversion":"bool"},
        56: {"id":"ID_WEB_Zaehler_BetrZeitVD1","conversion":"seconds"},
        57: {"id":"ID_WEB_Zaehler_BetrZeitImpVD1","conversion":"pulses"},
        58: {"id":"ID_WEB_Zaehler_BetrZeitVD2","conversion":"seconds"},
        59: {"id":"ID_WEB_Zaehler_BetrZeitImpVD2","conversion":"pulses"},
        60: {"id":"ID_WEB_Zaehler_BetrZeitZWE1","conversion":"seconds"},
        61: {"id":"ID_WEB_Zaehler_BetrZeitZWE2","conversion":"seconds"},
        62: {"id":"ID_WEB_Zaehler_BetrZeitZWE3","conversion":"seconds"},
        63: {"id":"ID_WEB_Zaehler_BetrZeitWP","conversion":"seconds"},
        64: {"id":"ID_WEB_Zaehler_BetrZeitHz","conversion":"seconds"},
        65: {"id":"ID_WEB_Zaehler_BetrZeitBW","conversion":"seconds"},
        66: {"id":"ID_WEB_Zaehler_BetrZeitKue","conversion":"seconds"},
        67: {"id":"ID_WEB_Time_WPein_akt","conversion":"seconds"},
        68: {"id":"ID_WEB_Time_ZWE1_akt","conversion":"seconds"},
        69: {"id":"ID_WEB_Time_ZWE2_akt","conversion":"seconds"},
        70: {"id":"ID_WEB_Timer_EinschVerz","conversion":"seconds"},
        71: {"id":"ID_WEB_Time_SSPAUS_akt","conversion":"seconds"},
        72: {"id":"ID_WEB_Time_SSPEIN_akt","conversion":"seconds"},
        73: {"id":"ID_WEB_Time_VDStd_akt","conversion":"seconds"},
        74: {"id":"ID_WEB_Time_HRM_akt","conversion":"seconds"},
        75: {"id":"ID_WEB_Time_HRW_akt","conversion":"seconds"},
        76: {"id":"ID_WEB_Time_LGS_akt","conversion":"seconds"},
        77: {"id":"ID_WEB_Time_SBW_akt","conversion":"seconds"},
        78: {"id":"ID_WEB_Code_WP_akt","conversion":
                {0: "ERC",1: "SW1",2: "SW2",3: "WW1",4: "WW2",5: "L1I",6: "L2I",7: "L1A",8: "L2A",9: "KSW",10: "KLW",11: "SWC",12: "LWC",13: "L2G",14: "WZS",
                 15: "L1I407",16: "L2I407",17: "L1A407",18: "L2A407",19: "L2G407",20: "LWC407",21: "L1AREV",22: "L2AREV",23: "WWC1",24: "WWC2",25: "L2G404",
                 26: "WZW",27: "L1S",28: "L1H",29: "L2H",30: "WZWD",31: "ERC",40: "WWB_20",41: "LD5",42: "LD7",43: "SW 37_45",44: "SW 58_69",45: "SW 29_56",
                 46: "LD5 (230V)",47: "LD7 (230 V)",48: "LD9",49: "LD5 REV",50: "LD7 REV",51: "LD5 REV 230V",52: "LD7 REV 230V",53: "LD9 REV 230V",54: "SW 291",
                 55: "LW SEC",56: "HMD 2",57: "MSW 4",58: "MSW 6",59: "MSW 8",60: "MSW 10",61: "MSW 12",62: "MSW 14",63: "MSW 17",64: "MSW 19",65: "MSW 23",
                 66: "MSW 26",67: "MSW 30",68: "MSW 4S",69: "MSW 6S",70: "MSW 8S",71: "MSW 10S",72: "MSW 13S",73: "MSW 16S",74: "MSW2-6S",75: "MSW4-16"}},
        79: {"id":"ID_WEB_BIV_Stufe_akt","conversion":
            { 1: "one compressor allowed to run", 2: "two compressors allowed to run", 3: "additional compressor allowed to run"}},
        80: {"id":"ID_WEB_WP_BZ_akt","conversion":
            { 0: "heating",1: "hot water",2: "swimming pool/solar",3: "evu",4: "defrost",5: "no request",6: "heating external source",7: "cooling"}},
        81: {"id":"ID_WEB_SoftStand","conversion":"version"},
        91: {"id":"ID_WEB_AdresseIP_akt","conversion":"ipaddress"},
        92: {"id":"ID_WEB_SubNetMask_akt","conversion":"ipaddress"},
        93: {"id":"ID_WEB_Add_Broadcast","conversion":"ipaddress"},
        94: {"id":"ID_WEB_Add_StdGateway","conversion":"ipaddress"},
        95: {"id":"ID_WEB_ERROR_Time0","conversion":"timestamp"},
        96: {"id":"ID_WEB_ERROR_Time1","conversion":"timestamp"},
        97: {"id":"ID_WEB_ERROR_Time2","conversion":"timestamp"},
        98: {"id":"ID_WEB_ERROR_Time3","conversion":"timestamp"},
        99: {"id":"ID_WEB_ERROR_Time4","conversion":"timestamp"},
        100: {"id":"ID_WEB_ERROR_Nr0","conversion":"errorcode"},
        101: {"id":"ID_WEB_ERROR_Nr1","conversion":"errorcode"},
        102: {"id":"ID_WEB_ERROR_Nr2","conversion":"errorcode"},
        103: {"id":"ID_WEB_ERROR_Nr3","conversion":"errorcode"},
        104: {"id":"ID_WEB_ERROR_Nr4","conversion":"errorcode"},
        105: {"id":"ID_WEB_AnzahlFehlerInSpeicher","conversion":"count"},
        106: {"id":"ID_WEB_Switchoff_file_Nr0","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        107: {"id":"ID_WEB_Switchoff_file_Nr1","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        108: {"id":"ID_WEB_Switchoff_file_Nr2","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        109: {"id":"ID_WEB_Switchoff_file_Nr3","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        110: {"id":"ID_WEB_Switchoff_file_Nr4","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        111: {"id":"ID_WEB_Switchoff_file_Time0","conversion":"timestamp"},
        112: {"id":"ID_WEB_Switchoff_file_Time1","conversion":"timestamp"},
        113: {"id":"ID_WEB_Switchoff_file_Time2","conversion":"timestamp"},
        114: {"id":"ID_WEB_Switchoff_file_Time3","conversion":"timestamp"},
        115: {"id":"ID_WEB_Switchoff_file_Time4","conversion":"timestamp"},
        116: {"id":"ID_WEB_Comfort_exists","conversion":"bool"},
        117: {"id":"ID_WEB_HauptMenuStatus_Zeile1","conversion":
            {0: "heatpump running",1: "heatpump idle",2: "heatpump coming",3: "errorcode slot 0",4: "defrost",5: "witing on LIN connection",6: "compressor heating up",7: "pump forerun"}},
        118: {"id":"ID_WEB_HauptMenuStatus_Zeile2","conversion":
            {0: "since",1: "in"}},
        119: {"id":"ID_WEB_HauptMenuStatus_Zeile3","conversion":
            {0: "heating",1: "no request",2: "grid switch on delay",3: "cycle lock",4: "lock time",5: "domestic water",6: "info bake out program",
             7: "defrost",8: "pump forerun",9: "thermal desinfection",10: "cooling",12: "swimming pool/solar",13: "heating external engery source", 
             14: "domestic water external energy source",16: "flow monitoring",17: "second heat generator 1 active"}},
        120: {"id":"ID_WEB_HauptMenuStatus_Zeit","conversion":"seconds"},
        121: {"id":"ID_WEB_HauptMenuAHP_Stufe","conversion":"level"},
        122: {"id":"ID_WEB_HauptMenuAHP_Temp","conversion":"celsius"},
        123: {"id":"ID_WEB_HauptMenuAHP_Zeit","conversion":"seconds"},
        124: {"id":"ID_WEB_SH_BWW","conversion":"bool"},
        125: {"id":"ID_WEB_SH_HZ","conversion":"icon"},
        126: {"id":"ID_WEB_SH_MK1","conversion":"icon"},
        127: {"id":"ID_WEB_SH_MK2","conversion":"icon"},
        128: {"id":"ID_WEB_Einst_Kurzrpgramm","conversion":"unknown"},
        129: {"id":"ID_WEB_StatusSlave_1","conversion":"unknown"},
        130: {"id":"ID_WEB_StatusSlave_2","conversion":"unknown"},
        131: {"id":"ID_WEB_StatusSlave_3","conversion":"unknown"},
        132: {"id":"ID_WEB_StatusSlave_4","conversion":"unknown"},
        133: {"id":"ID_WEB_StatusSlave_5","conversion":"unknown"},
        134: {"id":"ID_WEB_AktuelleTimeStamp","conversion":"timestamp"},
        135: {"id":"ID_WEB_SH_MK3","conversion":"icon"},
        136: {"id":"ID_WEB_Sollwert_TVL_MK3","conversion":"celsius"},
        137: {"id":"ID_WEB_Temperatur_TFB3","conversion":"celsius"},
        138: {"id":"ID_WEB_MZ3out","conversion":"bool"},
        139: {"id":"ID_WEB_MA3out","conversion":"bool"},
        140: {"id":"ID_WEB_FP3out","conversion":"bool"},
        141: {"id":"ID_WEB_Time_AbtIn","conversion":"seconds"},
        142: {"id":"ID_WEB_Temperatur_RFV2","conversion":"celsius"},
        143: {"id":"ID_WEB_Temperatur_RFV3","conversion":"celsius"},
        144: {"id":"ID_WEB_SH_SW","conversion":"icon"},
        145: {"id":"ID_WEB_Zaehler_BetrZeitSW","conversion":"hours"},
        146: {"id":"ID_WEB_FreigabKuehl","conversion":"bool"},
        147: {"id":"ID_WEB_AnalogIn","conversion":"voltage"},
        148: {"id":"ID_WEB_SonderZeichen","conversion":"unknown"},
        149: {"id":"ID_WEB_SH_ZIP","conversion":"icon"},
        150: {"id":"ID_WEB_WebsrvProgrammWerteBeobarten","conversion":"icon"},
        151: {"id":"ID_WEB_WMZ_Heizung","conversion":"kwh"},
        152: {"id":"ID_WEB_WMZ_Brauchwasser","conversion":"kwh"},
        153: {"id":"ID_WEB_WMZ_Schwimmbad","conversion":"kwh"},
        154: {"id":"ID_WEB_WMZ_Seit","conversion":"kwh"},
        155: {"id":"ID_WEB_WMZ_Durchfluss","conversion":"flow"},
        156: {"id":"ID_WEB_AnalogOut1","conversion":"voltage"},
        157: {"id":"ID_WEB_AnalogOut2","conversion":"voltage"},
        158: {"id":"ID_WEB_Time_Heissgas","conversion":"seconds"},
        159: {"id":"ID_WEB_Temp_Lueftung_Zuluft","conversion":"celsius"},
        160: {"id":"ID_WEB_Temp_Lueftung_Abluft","conversion":"celsius"},
        161: {"id":"ID_WEB_Zaehler_BetrZeitSolar","conversion":"seconds"},
        162: {"id":"ID_WEB_AnalogOut3","conversion":"voltage"},
        163: {"id":"ID_WEB_AnalogOut4","conversion":"voltage"},
        164: {"id":"ID_WEB_Out_VZU","conversion":"voltage"},
        165: {"id":"ID_WEB_Out_VAB","conversion":"voltage"},
        166: {"id":"ID_WEB_Out_VSK","conversion":"bool"},
        167: {"id":"ID_WEB_Out_FRH","conversion":"bool"},
        168: {"id":"ID_WEB_AnalogIn2","conversion":"voltage"},
        169: {"id":"ID_WEB_AnalogIn3","conversion":"voltage"},
        170: {"id":"ID_WEB_SAXin","conversion":"bool"},
        171: {"id":"ID_WEB_SPLin","conversion":"bool"},
        172: {"id":"ID_WEB_Compact_exists","conversion":"bool"},
        173: {"id":"ID_WEB_Durchfluss_WQ","conversion":"bool"},
        174: {"id":"ID_WEB_LIN_exists","conversion":"bool"},
        175: {"id":"ID_WEB_LIN_ANSAUG_VERDAMPFER","conversion":"celsius"},
        176: {"id":"ID_WEB_LIN_ANSAUG_VERDICHTER","conversion":"celsius"},
        177: {"id":"ID_WEB_LIN_VDH","conversion":"celsius"},
        178: {"id":"ID_WEB_LIN_UH","conversion":"kelvin"},
        179: {"id":"ID_WEB_LIN_UH_Soll","conversion":"kelvin"},
        180: {"id":"ID_WEB_LIN_HD","conversion":"pressure"},
        181: {"id":"ID_WEB_LIN_ND","conversion":"pressure"},
        182: {"id":"ID_WEB_LIN_VDH_out","conversion":"bool"},
        183: {"id":"ID_WEB_HZIO_PWM","conversion":"percent"},
        184: {"id":"ID_WEB_HZIO_VEN","conversion":"speed"},
        185: {"id":"ID_WEB_HZIO_EVU2","conversion":"unknown"},
        186: {"id":"ID_WEB_HZIO_STB","conversion":"bool"},
        187: {"id":"ID_WEB_SEC_Qh_Soll","conversion":"kwh"},
        188: {"id":"ID_WEB_SEC_Qh_Ist","conversion":"kwh"},
        189: {"id":"ID_WEB_SEC_TVL_Soll","conversion":"celsius"},
        190: {"id":"ID_WEB_SEC_Software","conversion":"unknown"},
        191: {"id":"ID_WEB_SEC_BZ","conversion":
            {0: "off",1: "cooling",2: "heating",3: "fault",4: "transition",5: "defrost", 6: "waiting", 7: "waiting", 8:"transition",9: "stop",10: "manual",11: "simulation start",12:"evu lock"}},
        192: {"id":"ID_WEB_SEC_VWV","conversion":"unknown"},
        193: {"id":"ID_WEB_SEC_VD","conversion":"speed"},
        194: {"id":"ID_WEB_SEC_VerdEVI","conversion":"celsius"},
        195: {"id":"ID_WEB_SEC_AnsEVI","conversion":"celsius"},
        196: {"id":"ID_WEB_SEC_UEH_EVI","conversion":"kelvin"},
        197: {"id":"ID_WEB_SEC_UEH_EVI_S","conversion":"kelvin"},
        198: {"id":"ID_WEB_SEC_KondTemp","conversion":"celsius"},
        199: {"id":"ID_WEB_SEC_FlussigEx","conversion":"celsius"},
        200: {"id":"ID_WEB_SEC_UK_EEV","conversion":"celsius"},
        201: {"id":"ID_WEB_SEC_EVI_Druck","conversion":"pressure"},
        202: {"id":"ID_WEB_SEC_U_Inv","conversion":"voltage"},
        203: {"id":"ID_WEB_Temperatur_THG_2","conversion":"celsius"},
        204: {"id":"ID_WEB_Temperatur_TWE_2","conversion":"celsius"},
        205: {"id":"ID_WEB_LIN_ANSAUG_VERDAMPFER_2","conversion":"celsius"},
        206: {"id":"ID_WEB_LIN_ANSAUG_VERDICHTER_2","conversion":"celsius"},
        207: {"id":"ID_WEB_LIN_VDH_2","conversion":"celsius"},
        208: {"id":"ID_WEB_LIN_UH_2","conversion":"kelvin"},
        209: {"id":"ID_WEB_LIN_UH_Soll_2","conversion":"kelvin"},
        210: {"id":"ID_WEB_LIN_HD_2","conversion":"pressure"},
        211: {"id":"ID_WEB_LIN_ND_2","conversion":"pressure"},
        212: {"id":"ID_WEB_HDin_2","conversion":"bool"},
        213: {"id":"ID_WEB_AVout_2","conversion":"bool"},
        214: {"id":"ID_WEB_VBOout_2","conversion":"bool"},
        215: {"id":"ID_WEB_VD1out_2","conversion":"bool"},
        216: {"id":"ID_WEB_LIN_VDH_out_2","conversion":"bool"},
        217: {"id":"ID_WEB_Switchoff2_file_Nr0","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        218: {"id":"ID_WEB_Switchoff2_file_Nr1","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        219: {"id":"ID_WEB_Switchoff2_file_Nr2","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        220: {"id":"ID_WEB_Switchoff2_file_Nr3","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        221: {"id":"ID_WEB_Switchoff2_file_Nr4","conversion":
            {1: "heatpump error",2: "system error",3: "evu lock",4: "operation mode second heat generator",5: "air defrost",6: "maximal usage temprature",7: "minimal usage temperature",8: "lower usage limit",9: "no request"}},
        222: {"id":"ID_WEB_Switchoff2_file_Time0","conversion":"timestamp"},
        223: {"id":"ID_WEB_Switchoff2_file_Time1","conversion":"timestamp"},
        224: {"id":"ID_WEB_Switchoff2_file_Time2","conversion":"timestamp"},
        225: {"id":"ID_WEB_Switchoff2_file_Time3","conversion":"timestamp"},
        226: {"id":"ID_WEB_Switchoff2_file_Time4","conversion":"timestamp"},
        227: {"id":"ID_WEB_RBE_RT_Ist","conversion":"celsius"},
        228: {"id":"ID_WEB_RBE_RT_Soll","conversion":"celsius"},
        229: {"id":"ID_WEB_Temperatur_BW_oben","conversion":"celsius"},
        230: {"id":"ID_WEB_Code_WP_akt_2","conversion":
            {0: "ERC",1: "SW1",2: "SW2",3: "WW1",4: "WW2",5: "L1I",6: "L2I",7: "L1A",8: "L2A",9: "KSW",10: "KLW",11: "SWC",12: "LWC",13: "L2G",14: "WZS",
             15: "L1I407",16: "L2I407",17: "L1A407",18: "L2A407",19: "L2G407",20: "LWC407",21: "L1AREV",22: "L2AREV",23: "WWC1",24: "WWC2",25: "L2G404",
             26: "WZW",27: "L1S",28: "L1H",29: "L2H",30: "WZWD",31: "ERC",40: "WWB_20",41: "LD5",42: "LD7",43: "SW 37_45",44: "SW 58_69",45: "SW 29_56",
             46: "LD5 (230V)",47: "LD7 (230 V)",48: "LD9",49: "LD5 REV",50: "LD7 REV",51: "LD5 REV 230V",52: "LD7 REV 230V",53: "LD9 REV 230V",54: "SW 291",
             55: "LW SEC",56: "HMD 2",57: "MSW 4",58: "MSW 6",59: "MSW 8",60: "MSW 10",61: "MSW 12",62: "MSW 14",63: "MSW 17",64: "MSW 19",65: "MSW 23",
             66: "MSW 26",67: "MSW 30",68: "MSW 4S",69: "MSW 6S",70: "MSW 8S",71: "MSW 10S",72: "MSW 13S",73: "MSW 16S",74: "MSW2-6S",75: "MSW4-16"}},
        231: {"id":"ID_WEB_Freq_VD","conversion":"celsius"}
    }
}


    ID_Transfert_LuxNet,
    ID_Einst_WK_akt,
    ID_Einst_BWS_akt,
    ID_Ba_Hz_akt,
    ID_Ba_Bw_akt,
    ID_Ba_Al_akt,
    ID_SU_FrkdHz,
    ID_SU_FrkdBw,
    ID_SU_FrkdAl,
    ID_Einst_HReg_akt,
    ID_Einst_HzHwMAt_akt,
    ID_Einst_HzHwHKE_akt,
    ID_Einst_HzHKRANH_akt,
    ID_Einst_HzHKRABS_akt,
    ID_Einst_HzMK1E_akt,
    ID_Einst_HzMK1ANH_akt,
    ID_Einst_HzMK1ABS_akt,
    ID_Einst_HzFtRl_akt,
    ID_Einst_HzFtMK1Vl_akt,
    ID_Einst_SUBW_akt,
    ID_Einst_BwTDI_akt_MO,
    ID_Einst_BwTDI_akt_DI,
    ID_Einst_BwTDI_akt_MI,
    ID_Einst_BwTDI_akt_DO,
    ID_Einst_BwTDI_akt_FR,
    ID_Einst_BwTDI_akt_SA,
    ID_Einst_BwTDI_akt_SO,
    ID_Einst_BwTDI_akt_AL,
    ID_Einst_AnlKonf_akt,
    ID_Einst_Sprache_akt,
    ID_Switchoff_Zahler,
    ID_Switchoff_index,
    ID_Einst_EvuTyp_akt,
    ID_Einst_RFVEinb_akt,
    ID_Einst_AbtZykMax_akt,
    ID_Einst_HREinb_akt,
    ID_Einst_ZWE1Art_akt,
    ID_Einst_ZWE1Fkt_akt,
    ID_Einst_ZWE2Art_akt,
    ID_Einst_ZWE2Fkt_akt,
    ID_Einst_BWBer_akt,
    ID_Einst_En_Inst,
    ID_Einst_MK1Typ_akt,
    ID_Einst_ABTLuft_akt,
    ID_Einst_TLAbt_akt,
    ID_Einst_LAbtTime_akt,
    ID_Einst_ASDTyp_akt,
    ID_Einst_LGST_akt,
    ID_Einst_BwWpTime_akt,
    ID_Einst_Popt_akt,
    ID_Einst_Kurzprog_akt,
    ID_Timer_Kurzprog_akt,
    ID_Einst_ManAbt_akt,
    ID_Einst_Ahz_akt,
    ID_Einst_TVL_Ahz_1,
    ID_Einst_TVL_Ahz_2,
    ID_Einst_TVL_Ahz_3,
    ID_Einst_TVL_Ahz_4,
    ID_Einst_TVL_Ahz_5,
    ID_Einst_TVL_Ahz_6,
    ID_Einst_TVL_Ahz_7,
    ID_Einst_TVL_Ahz_8,
    ID_Einst_TVL_Ahz_9,
    ID_Einst_TVL_Ahz_10,
    ID_Einst_TVL_Std_1,
    ID_Einst_TVL_Std_2,
    ID_Einst_TVL_Std_3,
    ID_Einst_TVL_Std_4,
    ID_Einst_TVL_Std_5,
    ID_Einst_TVL_Std_6,
    ID_Einst_TVL_Std_7,
    ID_Einst_TVL_Std_8,
    ID_Einst_TVL_Std_9,
    ID_Einst_TVL_Std_10,
    ID_Einst_BWS_Hyst_akt,
    ID_Temp_TBW_BwHD_saved,
    ID_Einst_ABT1_akt,
    ID_Einst_LABTpaus_akt,
    ID_AHZ_state_akt,
    ID_Sollwert_TRL_HZ_AHZ,
    ID_AHP_valid_records,
    ID_Timer_AHZ_akt,
    ID_Einst_BWTINP_akt,
    ID_Einst_ZUPTYP_akt,
    ID_Sollwert_TLG_max,
    ID_Einst_BWZIP_akt,
    ID_Einst_ERRmZWE_akt,
    ID_Einst_TRBegr_akt,
    ID_Einst_HRHyst_akt,
    ID_Einst_TRErhmax_akt,
    ID_Einst_ZWEFreig_akt,
    ID_Einst_TAmax_akt,
    ID_Einst_TAmin_akt,
    ID_Einst_TWQmin_akt,
    ID_Einst_THGmax_akt,
    ID_Einst_FRGT2VD_akt,
    ID_Einst_TV2VDBW_akt,
    ID_Einst_SuAll_akt,
    ID_Einst_TAbtEnd_akt,
    ID_Einst_NrKlingel_akt,
    ID_Einst_BWStyp_akt,
    ID_Einst_ABT2_akt,
    ID_Einst_UeVd_akt,
    ID_Einst_RTyp_akt,
    ID_Einst_AhpM_akt,
    ID_Soll_BWS_akt,
    ID_Timer_Password,
    ID_Einst_Zugangscode,
    ID_Einst_BA_Kuehl_akt,
    ID_Sollwert_Kuehl1_akt,
    ID_Einst_KuehlFreig_akt,
    ID_Einst_TAbsMin_akt,
    ID_TWQmin_saved,
    ID_CWP_saved,
    ID_Einst_Anode_akt,
    ID_Timer_pexoff_akt,
    ID_Einst_AnlPrio_Hzakt,
    ID_Einst_AnlPrio_Bwakt,
    ID_Einst_AnlPrio_Swakt,
    ID_Ba_Sw_akt,
    ID_Einst_RTypMK1_akt,
    ID_Einst_RTypMK2_akt,
    ID_Einst_TDC_Ein_akt,
    ID_Einst_TDC_Aus_akt,
    ID_Einst_TDC_Max_akt,
    ID_Einst_HysHzExEn_akt,
    ID_Einst_HysBwExEn_akt,
    ID_Einst_ZWE3Art_akt,
    ID_Einst_ZWE3Fkt_akt,
    ID_Einst_HzSup_akt,
    ID_Einst_MK2Typ_akt,
    ID_Einst_KuTyp_akt,
    ID_Sollwert_KuCft1_akt,
    ID_Sollwert_KuCft2_akt,
    ID_Sollwert_AtDif1_akt,
    ID_Sollwert_AtDif2_akt,
    ID_SU_FrkdSwb,
    ID_Einst_SwbBer_akt,
    ID_Einst_TV2VDSWB_akt,
    ID_Einst_MinSwan_Time_akt,
    ID_Einst_SuMk2_akt,
    ID_Einst_HzMK2E_akt,
    ID_Einst_HzMK2ANH_akt,
    ID_Einst_HzMK2ABS_akt,
    ID_Einst_HzMK2Hgr_akt,
    ID_Einst_HzFtMK2Vl_akt,
    ID_Temp_THG_BwHD_saved,
    ID_Temp_TA_BwHD_saved,
    ID_Einst_BwHup_akt,
    ID_Einst_TVLmax_akt,
    ID_Einst_MK1LzFaktor_akt,
    ID_Einst_MK2LzFaktor_akt,
    ID_Einst_MK1PerFaktor_akt,
    ID_Einst_MK2PerFaktor_akt,
    ID_Entl_Zyklus_akt,
    ID_Einst_Entl_time_akt,
    ID_Entl_Pause,
    ID_Entl_timer,
    ID_Einst_Entl_akt,
    ID_Ahz_HLeist_confirmed,
    ID_FirstInit_akt,
    ID_Einst_SuAll_akt2,
    ID_Einst_SuAllWo_zeit_0_0,
    ID_Einst_SuAllWo_zeit_0_1,
    ID_Einst_SuAllWo_zeit_1_0,
    ID_Einst_SuAllWo_zeit_1_1,
    ID_Einst_SuAllWo_zeit_2_0,
    ID_Einst_SuAllWo_zeit_2_1,
    ID_Einst_SuAll25_zeit_0_0,
    ID_Einst_SuAll25_zeit_0_1,
    ID_Einst_SuAll25_zeit_1_0,
    ID_Einst_SuAll25_zeit_1_1,
    ID_Einst_SuAll25_zeit_2_0,
    ID_Einst_SuAll25_zeit_2_1,
    ID_Einst_SuAll25_zeit_0_2,
    ID_Einst_SuAll25_zeit_0_3,
    ID_Einst_SuAll25_zeit_1_2,
    ID_Einst_SuAll25_zeit_1_3,
    ID_Einst_SuAll25_zeit_2_2,
    ID_Einst_SuAll25_zeit_2_3,
    ID_Einst_SuAllTg_zeit_0_0,
    ID_Einst_SuAllTg_zeit_0_1,
    ID_Einst_SuAllTg_zeit_1_0,
    ID_Einst_SuAllTg_zeit_1_1,
    ID_Einst_SuAllTg_zeit_2_0,
    ID_Einst_SuAllTg_zeit_2_1,
    ID_Einst_SuAllTg_zeit_0_2,
    ID_Einst_SuAllTg_zeit_0_3,
    ID_Einst_SuAllTg_zeit_1_2,
    ID_Einst_SuAllTg_zeit_1_3,
    ID_Einst_SuAllTg_zeit_2_2,
    ID_Einst_SuAllTg_zeit_2_3,
    ID_Einst_SuAllTg_zeit_0_4,
    ID_Einst_SuAllTg_zeit_0_5,
    ID_Einst_SuAllTg_zeit_1_4,
    ID_Einst_SuAllTg_zeit_1_5,
    ID_Einst_SuAllTg_zeit_2_4,
    ID_Einst_SuAllTg_zeit_2_5,
    ID_Einst_SuAllTg_zeit_0_6,
    ID_Einst_SuAllTg_zeit_0_7,
    ID_Einst_SuAllTg_zeit_1_6,
    ID_Einst_SuAllTg_zeit_1_7,
    ID_Einst_SuAllTg_zeit_2_6,
    ID_Einst_SuAllTg_zeit_2_7,
    ID_Einst_SuAllTg_zeit_0_8,
    ID_Einst_SuAllTg_zeit_0_9,
    ID_Einst_SuAllTg_zeit_1_8,
    ID_Einst_SuAllTg_zeit_1_9,
    ID_Einst_SuAllTg_zeit_2_8,
    ID_Einst_SuAllTg_zeit_2_9,
    ID_Einst_SuAllTg_zeit_0_10,
    ID_Einst_SuAllTg_zeit_0_11,
    ID_Einst_SuAllTg_zeit_1_10,
    ID_Einst_SuAllTg_zeit_1_11,
    ID_Einst_SuAllTg_zeit_2_10,
    ID_Einst_SuAllTg_zeit_2_11,
    ID_Einst_SuAllTg_zeit_0_12,
    ID_Einst_SuAllTg_zeit_0_13,
    ID_Einst_SuAllTg_zeit_1_12,
    ID_Einst_SuAllTg_zeit_1_13,
    ID_Einst_SuAllTg_zeit_2_12,
    ID_Einst_SuAllTg_zeit_2_13,
    ID_Einst_SuHkr_akt,
    ID_Einst_SuHkrW0_zeit_0_0,
    ID_Einst_SuHkrW0_zeit_0_1,
    ID_Einst_SuHkrW0_zeit_1_0,
    ID_Einst_SuHkrW0_zeit_1_1,
    ID_Einst_SuHkrW0_zeit_2_0,
    ID_Einst_SuHkrW0_zeit_2_1,
    ID_Einst_SuHkr25_zeit_0_0,
    ID_Einst_SuHkr25_zeit_0_1,
    ID_Einst_SuHkr25_zeit_1_0,
    ID_Einst_SuHkr25_zeit_1_1,
    ID_Einst_SuHkr25_zeit_2_0,
    ID_Einst_SuHkr25_zeit_2_1,
    ID_Einst_SuHkr25_zeit_0_2,
    ID_Einst_SuHkr25_zeit_0_3,
    ID_Einst_SuHkr25_zeit_1_2,
    ID_Einst_SuHkr25_zeit_1_3,
    ID_Einst_SuHkr25_zeit_2_2,
    ID_Einst_SuHkr25_zeit_2_3,
    ID_Einst_SuHkrTG_zeit_0_0,
    ID_Einst_SuHkrTG_zeit_0_1,
    ID_Einst_SuHkrTG_zeit_1_0,
    ID_Einst_SuHkrTG_zeit_1_1,
    ID_Einst_SuHkrTG_zeit_2_0,
    ID_Einst_SuHkrTG_zeit_2_1,
    ID_Einst_SuHkrTG_zeit_0_2,
    ID_Einst_SuHkrTG_zeit_0_3,
    ID_Einst_SuHkrTG_zeit_1_2,
    ID_Einst_SuHkrTG_zeit_1_3,
    ID_Einst_SuHkrTG_zeit_2_2,
    ID_Einst_SuHkrTG_zeit_2_3,
    ID_Einst_SuHkrTG_zeit_0_4,
    ID_Einst_SuHkrTG_zeit_0_5,
    ID_Einst_SuHkrTG_zeit_1_4,
    ID_Einst_SuHkrTG_zeit_1_5,
    ID_Einst_SuHkrTG_zeit_2_4,
    ID_Einst_SuHkrTG_zeit_2_5,
    ID_Einst_SuHkrTG_zeit_0_6,
    ID_Einst_SuHkrTG_zeit_0_7,
    ID_Einst_SuHkrTG_zeit_1_6,
    ID_Einst_SuHkrTG_zeit_1_7,
    ID_Einst_SuHkrTG_zeit_2_6,
    ID_Einst_SuHkrTG_zeit_2_7,
    ID_Einst_SuHkrTG_zeit_0_8,
    ID_Einst_SuHkrTG_zeit_0_9,
    ID_Einst_SuHkrTG_zeit_1_8,
    ID_Einst_SuHkrTG_zeit_1_9,
    ID_Einst_SuHkrTG_zeit_2_8,
    ID_Einst_SuHkrTG_zeit_2_9,
    ID_Einst_SuHkrTG_zeit_0_10,
    ID_Einst_SuHkrTG_zeit_0_11,
    ID_Einst_SuHkrTG_zeit_1_10,
    ID_Einst_SuHkrTG_zeit_1_11,
    ID_Einst_SuHkrTG_zeit_2_10,
    ID_Einst_SuHkrTG_zeit_2_11,
    ID_Einst_SuHkrTG_zeit_0_12,
    ID_Einst_SuHkrTG_zeit_0_13,
    ID_Einst_SuHkrTG_zeit_1_12,
    ID_Einst_SuHkrTG_zeit_1_13,
    ID_Einst_SuHkrTG_zeit_2_12,
    ID_Einst_SuHkrTG_zeit_2_13,
    ID_Einst_SuMk1_akt,
    ID_Einst_SuMk1W0_zeit_0_0,
    ID_Einst_SuMk1W0_zeit_0_1,
    ID_Einst_SuMk1W0_zeit_1_0,
    ID_Einst_SuMk1W0_zeit_1_1,
    ID_Einst_SuMk1W0_zeit_2_0,
    ID_Einst_SuMk1W0_zeit_2_1,
    ID_Einst_SuMk125_zeit_0_0,
    ID_Einst_SuMk125_zeit_0_1,
    ID_Einst_SuMk125_zeit_1_0,
    ID_Einst_SuMk125_zeit_1_1,
    ID_Einst_SuMk125_zeit_2_0,
    ID_Einst_SuMk125_zeit_2_1,
    ID_Einst_SuMk125_zeit_0_2,
    ID_Einst_SuMk125_zeit_0_3,
    ID_Einst_SuMk125_zeit_1_2,
    ID_Einst_SuMk125_zeit_1_3,
    ID_Einst_SuMk125_zeit_2_2,
    ID_Einst_SuMk125_zeit_2_3,
    ID_Einst_SuMk1TG_zeit_0_0,
    ID_Einst_SuMk1TG_zeit_0_1,
    ID_Einst_SuMk1TG_zeit_1_0,
    ID_Einst_SuMk1TG_zeit_1_1,
    ID_Einst_SuMk1TG_zeit_2_0,
    ID_Einst_SuMk1TG_zeit_2_1,
    ID_Einst_SuMk1TG_zeit_0_2,
    ID_Einst_SuMk1TG_zeit_0_3,
    ID_Einst_SuMk1TG_zeit_1_2,
    ID_Einst_SuMk1TG_zeit_1_3,
    ID_Einst_SuMk1TG_zeit_2_2,
    ID_Einst_SuMk1TG_zeit_2_3,
    ID_Einst_SuMk1TG_zeit_0_4,
    ID_Einst_SuMk1TG_zeit_0_5,
    ID_Einst_SuMk1TG_zeit_1_4,
    ID_Einst_SuMk1TG_zeit_1_5,
    ID_Einst_SuMk1TG_zeit_2_4,
    ID_Einst_SuMk1TG_zeit_2_5,
    ID_Einst_SuMk1TG_zeit_0_6,
    ID_Einst_SuMk1TG_zeit_0_7,
    ID_Einst_SuMk1TG_zeit_1_6,
    ID_Einst_SuMk1TG_zeit_1_7,
    ID_Einst_SuMk1TG_zeit_2_6,
    ID_Einst_SuMk1TG_zeit_2_7,
    ID_Einst_SuMk1TG_zeit_0_8,
    ID_Einst_SuMk1TG_zeit_0_9,
    ID_Einst_SuMk1TG_zeit_1_8,
    ID_Einst_SuMk1TG_zeit_1_9,
    ID_Einst_SuMk1TG_zeit_2_8,
    ID_Einst_SuMk1TG_zeit_2_9,
    ID_Einst_SuMk1TG_zeit_0_10,
    ID_Einst_SuMk1TG_zeit_0_11,
    ID_Einst_SuMk1TG_zeit_1_10,
    ID_Einst_SuMk1TG_zeit_1_11,
    ID_Einst_SuMk1TG_zeit_2_10,
    ID_Einst_SuMk1TG_zeit_2_11,
    ID_Einst_SuMk1TG_zeit_0_12,
    ID_Einst_SuMk1TG_zeit_0_13,
    ID_Einst_SuMk1TG_zeit_1_12,
    ID_Einst_SuMk1TG_zeit_1_13,
    ID_Einst_SuMk1TG_zeit_2_12,
    ID_Einst_SuMk1TG_zeit_2_13,
    ID_Einst_SuMk2_akt2,
    ID_Einst_SuMk2Wo_zeit_0_0,
    ID_Einst_SuMk2Wo_zeit_0_1,
    ID_Einst_SuMk2Wo_zeit_1_0,
    ID_Einst_SuMk2Wo_zeit_1_1,
    ID_Einst_SuMk2Wo_zeit_2_0,
    ID_Einst_SuMk2Wo_zeit_2_1,
    ID_Einst_SuMk225_zeit_0_0,
    ID_Einst_SuMk225_zeit_0_1,
    ID_Einst_SuMk225_zeit_1_0,
    ID_Einst_SuMk225_zeit_1_1,
    ID_Einst_SuMk225_zeit_2_0,
    ID_Einst_SuMk225_zeit_2_1,
    ID_Einst_SuMk225_zeit_0_2,
    ID_Einst_SuMk225_zeit_0_3,
    ID_Einst_SuMk225_zeit_1_2,
    ID_Einst_SuMk225_zeit_1_3,
    ID_Einst_SuMk225_zeit_2_2,
    ID_Einst_SuMk225_zeit_2_3,
    ID_Einst_SuMk2Tg_zeit_0_0,
    ID_Einst_SuMk2Tg_zeit_0_1,
    ID_Einst_SuMk2Tg_zeit_1_0,
    ID_Einst_SuMk2Tg_zeit_1_1,
    ID_Einst_SuMk2Tg_zeit_2_0,
    ID_Einst_SuMk2Tg_zeit_2_1,
    ID_Einst_SuMk2Tg_zeit_0_2,
    ID_Einst_SuMk2Tg_zeit_0_3,
    ID_Einst_SuMk2Tg_zeit_1_2,
    ID_Einst_SuMk2Tg_zeit_1_3,
    ID_Einst_SuMk2Tg_zeit_2_2,
    ID_Einst_SuMk2Tg_zeit_2_3,
    ID_Einst_SuMk2Tg_zeit_0_4,
    ID_Einst_SuMk2Tg_zeit_0_5,
    ID_Einst_SuMk2Tg_zeit_1_4,
    ID_Einst_SuMk2Tg_zeit_1_5,
    ID_Einst_SuMk2Tg_zeit_2_4,
    ID_Einst_SuMk2Tg_zeit_2_5,
    ID_Einst_SuMk2Tg_zeit_0_6,
    ID_Einst_SuMk2Tg_zeit_0_7,
    ID_Einst_SuMk2Tg_zeit_1_6,
    ID_Einst_SuMk2Tg_zeit_1_7,
    ID_Einst_SuMk2Tg_zeit_2_6,
    ID_Einst_SuMk2Tg_zeit_2_7,
    ID_Einst_SuMk2Tg_zeit_0_8,
    ID_Einst_SuMk2Tg_zeit_0_9,
    ID_Einst_SuMk2Tg_zeit_1_8,
    ID_Einst_SuMk2Tg_zeit_1_9,
    ID_Einst_SuMk2Tg_zeit_2_8,
    ID_Einst_SuMk2Tg_zeit_2_9,
    ID_Einst_SuMk2Tg_zeit_0_10,
    ID_Einst_SuMk2Tg_zeit_0_11,
    ID_Einst_SuMk2Tg_zeit_1_10,
    ID_Einst_SuMk2Tg_zeit_1_11,
    ID_Einst_SuMk2Tg_zeit_2_10,
    ID_Einst_SuMk2Tg_zeit_2_11,
    ID_Einst_SuMk2Tg_zeit_0_12,
    ID_Einst_SuMk2Tg_zeit_0_13,
    ID_Einst_SuMk2Tg_zeit_1_12,
    ID_Einst_SuMk2Tg_zeit_1_13,
    ID_Einst_SuMk2Tg_zeit_2_12,
    ID_Einst_SuMk2Tg_zeit_2_13,
    ID_Einst_SUBW_akt2,
    ID_Einst_SuBwWO_zeit_0_0,
    ID_Einst_SuBwWO_zeit_0_1,
    ID_Einst_SuBwWO_zeit_1_0,
    ID_Einst_SuBwWO_zeit_1_1,
    ID_Einst_SuBwWO_zeit_2_0,
    ID_Einst_SuBwWO_zeit_2_1,
    ID_Einst_SuBwWO_zeit_3_0,
    ID_Einst_SuBwWO_zeit_3_1,
    ID_Einst_SuBwWO_zeit_4_0,
    ID_Einst_SuBwWO_zeit_4_1,
    ID_Einst_SuBw25_zeit_0_0,
    ID_Einst_SuBw25_zeit_0_1,
    ID_Einst_SuBw25_zeit_1_0,
    ID_Einst_SuBw25_zeit_1_1,
    ID_Einst_SuBw25_zeit_2_0,
    ID_Einst_SuBw25_zeit_2_1,
    ID_Einst_SuBw25_zeit_3_0,
    ID_Einst_SuBw25_zeit_3_1,
    ID_Einst_SuBw25_zeit_4_0,
    ID_Einst_SuBw25_zeit_4_1,
    ID_Einst_SuBw25_zeit_0_2,
    ID_Einst_SuBw25_zeit_0_3,
    ID_Einst_SuBw25_zeit_1_2,
    ID_Einst_SuBw25_zeit_1_3,
    ID_Einst_SuBw25_zeit_2_2,
    ID_Einst_SuBw25_zeit_2_3,
    ID_Einst_SuBw25_zeit_3_2,
    ID_Einst_SuBw25_zeit_3_3,
    ID_Einst_SuBw25_zeit_4_2,
    ID_Einst_SuBw25_zeit_4_3,
    ID_Einst_SuBwTG_zeit_0_0,
    ID_Einst_SuBwTG_zeit_0_1,
    ID_Einst_SuBwTG_zeit_1_0,
    ID_Einst_SuBwTG_zeit_1_1,
    ID_Einst_SuBwTG_zeit_2_0,
    ID_Einst_SuBwTG_zeit_2_1,
    ID_Einst_SuBwTG_zeit_3_0,
    ID_Einst_SuBwTG_zeit_3_1,
    ID_Einst_SuBwTG_zeit_4_0,
    ID_Einst_SuBwTG_zeit_4_1,
    ID_Einst_SuBwTG_zeit_0_2,
    ID_Einst_SuBwTG_zeit_0_3,
    ID_Einst_SuBwTG_zeit_1_2,
    ID_Einst_SuBwTG_zeit_1_3,
    ID_Einst_SuBwTG_zeit_2_2,
    ID_Einst_SuBwTG_zeit_2_3,
    ID_Einst_SuBwTG_zeit_3_2,
    ID_Einst_SuBwTG_zeit_3_3,
    ID_Einst_SuBwTG_zeit_4_2,
    ID_Einst_SuBwTG_zeit_4_3,
    ID_Einst_SuBwTG_zeit_0_4,
    ID_Einst_SuBwTG_zeit_0_5,
    ID_Einst_SuBwTG_zeit_1_4,
    ID_Einst_SuBwTG_zeit_1_5,
    ID_Einst_SuBwTG_zeit_2_4,
    ID_Einst_SuBwTG_zeit_2_5,
    ID_Einst_SuBwTG_zeit_3_4,
    ID_Einst_SuBwTG_zeit_3_5,
    ID_Einst_SuBwTG_zeit_4_4,
    ID_Einst_SuBwTG_zeit_4_5,
    ID_Einst_SuBwTG_zeit_0_6,
    ID_Einst_SuBwTG_zeit_0_7,
    ID_Einst_SuBwTG_zeit_1_6,
    ID_Einst_SuBwTG_zeit_1_7,
    ID_Einst_SuBwTG_zeit_2_6,
    ID_Einst_SuBwTG_zeit_2_7,
    ID_Einst_SuBwTG_zeit_3_6,
    ID_Einst_SuBwTG_zeit_3_7,
    ID_Einst_SuBwTG_zeit_4_6,
    ID_Einst_SuBwTG_zeit_4_7,
    ID_Einst_SuBwTG_zeit_0_8,
    ID_Einst_SuBwTG_zeit_0_9,
    ID_Einst_SuBwTG_zeit_1_8,
    ID_Einst_SuBwTG_zeit_1_9,
    ID_Einst_SuBwTG_zeit_2_8,
    ID_Einst_SuBwTG_zeit_2_9,
    ID_Einst_SuBwTG_zeit_3_8,
    ID_Einst_SuBwTG_zeit_3_9,
    ID_Einst_SuBwTG_zeit_4_8,
    ID_Einst_SuBwTG_zeit_4_9,
    ID_Einst_SuBwTG_zeit_0_10,
    ID_Einst_SuBwTG_zeit_0_11,
    ID_Einst_SuBwTG_zeit_1_10,
    ID_Einst_SuBwTG_zeit_1_11,
    ID_Einst_SuBwTG_zeit_2_10,
    ID_Einst_SuBwTG_zeit_2_11,
    ID_Einst_SuBwTG_zeit_3_10,
    ID_Einst_SuBwTG_zeit_3_11,
    ID_Einst_SuBwTG_zeit_4_10,
    ID_Einst_SuBwTG_zeit_4_11,
    ID_Einst_SuBwTG_zeit_0_12,
    ID_Einst_SuBwTG_zeit_0_13,
    ID_Einst_SuBwTG_zeit_1_12,
    ID_Einst_SuBwTG_zeit_1_13,
    ID_Einst_SuBwTG_zeit_2_12,
    ID_Einst_SuBwTG_zeit_2_13,
    ID_Einst_SuBwTG_zeit_3_12,
    ID_Einst_SuBwTG_zeit_3_13,
    ID_Einst_SuBwTG_zeit_4_12,
    ID_Einst_SuBwTG_zeit_4_13,
    ID_Einst_SuZIP_akt,
    ID_Einst_SuZIPWo_zeit_0_0,
    ID_Einst_SuZIPWo_zeit_0_1,
    ID_Einst_SuZIPWo_zeit_1_0,
    ID_Einst_SuZIPWo_zeit_1_1,
    ID_Einst_SuZIPWo_zeit_2_0,
    ID_Einst_SuZIPWo_zeit_2_1,
    ID_Einst_SuZIPWo_zeit_3_0,
    ID_Einst_SuZIPWo_zeit_3_1,
    ID_Einst_SuZIPWo_zeit_4_0,
    ID_Einst_SuZIPWo_zeit_4_1,
    ID_Einst_SuZIP25_zeit_0_0,
    ID_Einst_SuZIP25_zeit_0_1,
    ID_Einst_SuZIP25_zeit_1_0,
    ID_Einst_SuZIP25_zeit_1_1,
    ID_Einst_SuZIP25_zeit_2_0,
    ID_Einst_SuZIP25_zeit_2_1,
    ID_Einst_SuZIP25_zeit_3_0,
    ID_Einst_SuZIP25_zeit_3_1,
    ID_Einst_SuZIP25_zeit_4_0,
    ID_Einst_SuZIP25_zeit_4_1,
    ID_Einst_SuZIP25_zeit_0_2,
    ID_Einst_SuZIP25_zeit_0_3,
    ID_Einst_SuZIP25_zeit_1_2,
    ID_Einst_SuZIP25_zeit_1_3,
    ID_Einst_SuZIP25_zeit_2_2,
    ID_Einst_SuZIP25_zeit_2_3,
    ID_Einst_SuZIP25_zeit_3_2,
    ID_Einst_SuZIP25_zeit_3_3,
    ID_Einst_SuZIP25_zeit_4_2,
    ID_Einst_SuZIP25_zeit_4_3,
    ID_Einst_SuZIPTg_zeit_0_0,
    ID_Einst_SuZIPTg_zeit_0_1,
    ID_Einst_SuZIPTg_zeit_1_0,
    ID_Einst_SuZIPTg_zeit_1_1,
    ID_Einst_SuZIPTg_zeit_2_0,
    ID_Einst_SuZIPTg_zeit_2_1,
    ID_Einst_SuZIPTg_zeit_3_0,
    ID_Einst_SuZIPTg_zeit_3_1,
    ID_Einst_SuZIPTg_zeit_4_0,
    ID_Einst_SuZIPTg_zeit_4_1,
    ID_Einst_SuZIPTg_zeit_0_2,
    ID_Einst_SuZIPTg_zeit_0_3,
    ID_Einst_SuZIPTg_zeit_1_2,
    ID_Einst_SuZIPTg_zeit_1_3,
    ID_Einst_SuZIPTg_zeit_2_2,
    ID_Einst_SuZIPTg_zeit_2_3,
    ID_Einst_SuZIPTg_zeit_3_2,
    ID_Einst_SuZIPTg_zeit_3_3,
    ID_Einst_SuZIPTg_zeit_4_2,
    ID_Einst_SuZIPTg_zeit_4_3,
    ID_Einst_SuZIPTg_zeit_0_4,
    ID_Einst_SuZIPTg_zeit_0_5,
    ID_Einst_SuZIPTg_zeit_1_4,
    ID_Einst_SuZIPTg_zeit_1_5,
    ID_Einst_SuZIPTg_zeit_2_4,
    ID_Einst_SuZIPTg_zeit_2_5,
    ID_Einst_SuZIPTg_zeit_3_4,
    ID_Einst_SuZIPTg_zeit_3_5,
    ID_Einst_SuZIPTg_zeit_4_4,
    ID_Einst_SuZIPTg_zeit_4_5,
    ID_Einst_SuZIPTg_zeit_0_6,
    ID_Einst_SuZIPTg_zeit_0_7,
    ID_Einst_SuZIPTg_zeit_1_6,
    ID_Einst_SuZIPTg_zeit_1_7,
    ID_Einst_SuZIPTg_zeit_2_6,
    ID_Einst_SuZIPTg_zeit_2_7,
    ID_Einst_SuZIPTg_zeit_3_6,
    ID_Einst_SuZIPTg_zeit_3_7,
    ID_Einst_SuZIPTg_zeit_4_6,
    ID_Einst_SuZIPTg_zeit_4_7,
    ID_Einst_SuZIPTg_zeit_0_8,
    ID_Einst_SuZIPTg_zeit_0_9,
    ID_Einst_SuZIPTg_zeit_1_8,
    ID_Einst_SuZIPTg_zeit_1_9,
    ID_Einst_SuZIPTg_zeit_2_8,
    ID_Einst_SuZIPTg_zeit_2_9,
    ID_Einst_SuZIPTg_zeit_3_8,
    ID_Einst_SuZIPTg_zeit_3_9,
    ID_Einst_SuZIPTg_zeit_4_8,
    ID_Einst_SuZIPTg_zeit_4_9,
    ID_Einst_SuZIPTg_zeit_0_10,
    ID_Einst_SuZIPTg_zeit_0_11,
    ID_Einst_SuZIPTg_zeit_1_10,
    ID_Einst_SuZIPTg_zeit_1_11,
    ID_Einst_SuZIPTg_zeit_2_10,
    ID_Einst_SuZIPTg_zeit_2_11,
    ID_Einst_SuZIPTg_zeit_3_10,
    ID_Einst_SuZIPTg_zeit_3_11,
    ID_Einst_SuZIPTg_zeit_4_10,
    ID_Einst_SuZIPTg_zeit_4_11,
    ID_Einst_SuZIPTg_zeit_0_12,
    ID_Einst_SuZIPTg_zeit_0_13,
    ID_Einst_SuZIPTg_zeit_1_12,
    ID_Einst_SuZIPTg_zeit_1_13,
    ID_Einst_SuZIPTg_zeit_2_12,
    ID_Einst_SuZIPTg_zeit_2_13,
    ID_Einst_SuZIPTg_zeit_3_12,
    ID_Einst_SuZIPTg_zeit_3_13,
    ID_Einst_SuZIPTg_zeit_4_12,
    ID_Einst_SuZIPTg_zeit_4_13,
    ID_Einst_SuSwb_akt,
    ID_Einst_SuSwbWo_zeit_0_0,
    ID_Einst_SuSwbWo_zeit_0_1,
    ID_Einst_SuSwbWo_zeit_1_0,
    ID_Einst_SuSwbWo_zeit_1_1,
    ID_Einst_SuSwbWo_zeit_2_0,
    ID_Einst_SuSwbWo_zeit_2_1,
    ID_Einst_SuSwb25_zeit_0_0,
    ID_Einst_SuSwb25_zeit_0_1,
    ID_Einst_SuSwb25_zeit_1_0,
    ID_Einst_SuSwb25_zeit_1_1,
    ID_Einst_SuSwb25_zeit_2_0,
    ID_Einst_SuSwb25_zeit_2_1,
    ID_Einst_SuSwb25_zeit_0_2,
    ID_Einst_SuSwb25_zeit_0_3,
    ID_Einst_SuSwb25_zeit_1_2,
    ID_Einst_SuSwb25_zeit_1_3,
    ID_Einst_SuSwb25_zeit_2_2,
    ID_Einst_SuSwb25_zeit_2_3,
    ID_Einst_SuSwbTg_zeit_0_0,
    ID_Einst_SuSwbTg_zeit_0_1,
    ID_Einst_SuSwbTg_zeit_1_0,
    ID_Einst_SuSwbTg_zeit_1_1,
    ID_Einst_SuSwbTg_zeit_2_0,
    ID_Einst_SuSwbTg_zeit_2_1,
    ID_Einst_SuSwbTg_zeit_0_2,
    ID_Einst_SuSwbTg_zeit_0_3,
    ID_Einst_SuSwbTg_zeit_1_2,
    ID_Einst_SuSwbTg_zeit_1_3,
    ID_Einst_SuSwbTg_zeit_2_2,
    ID_Einst_SuSwbTg_zeit_2_3,
    ID_Einst_SuSwbTg_zeit_0_4,
    ID_Einst_SuSwbTg_zeit_0_5,
    ID_Einst_SuSwbTg_zeit_1_4,
    ID_Einst_SuSwbTg_zeit_1_5,
    ID_Einst_SuSwbTg_zeit_2_4,
    ID_Einst_SuSwbTg_zeit_2_5,
    ID_Einst_SuSwbTg_zeit_0_6,
    ID_Einst_SuSwbTg_zeit_0_7,
    ID_Einst_SuSwbTg_zeit_1_6,
    ID_Einst_SuSwbTg_zeit_1_7,
    ID_Einst_SuSwbTg_zeit_2_6,
    ID_Einst_SuSwbTg_zeit_2_7,
    ID_Einst_SuSwbTg_zeit_0_8,
    ID_Einst_SuSwbTg_zeit_0_9,
    ID_Einst_SuSwbTg_zeit_1_8,
    ID_Einst_SuSwbTg_zeit_1_9,
    ID_Einst_SuSwbTg_zeit_2_8,
    ID_Einst_SuSwbTg_zeit_2_9,
    ID_Einst_SuSwbTg_zeit_0_10,
    ID_Einst_SuSwbTg_zeit_0_11,
    ID_Einst_SuSwbTg_zeit_1_10,
    ID_Einst_SuSwbTg_zeit_1_11,
    ID_Einst_SuSwbTg_zeit_2_10,
    ID_Einst_SuSwbTg_zeit_2_11,
    ID_Einst_SuSwbTg_zeit_0_12,
    ID_Einst_SuSwbTg_zeit_0_13,
    ID_Einst_SuSwbTg_zeit_1_12,
    ID_Einst_SuSwbTg_zeit_1_13,
    ID_Einst_SuSwbTg_zeit_2_12,
    ID_Einst_SuSwbTg_zeit_2_13,
    ID_Zaehler_BetrZeitWP,
    ID_Zaehler_BetrZeitVD1,
    ID_Zaehler_BetrZeitVD2,
    ID_Zaehler_BetrZeitZWE1,
    ID_Zaehler_BetrZeitZWE2,
    ID_Zaehler_BetrZeitZWE3,
    ID_Zaehler_BetrZeitImpVD1,
    ID_Zaehler_BetrZeitImpVD2,
    ID_Zaehler_BetrZeitEZMVD1,
    ID_Zaehler_BetrZeitEZMVD2,
    ID_Einst_Entl_Typ_0,
    ID_Einst_Entl_Typ_1,
    ID_Einst_Entl_Typ_2,
    ID_Einst_Entl_Typ_3,
    ID_Einst_Entl_Typ_4,
    ID_Einst_Entl_Typ_5,
    ID_Einst_Entl_Typ_6,
    ID_Einst_Entl_Typ_7,
    ID_Einst_Entl_Typ_8,
    ID_Einst_Entl_Typ_9,
    ID_Einst_Entl_Typ_10,
    ID_Einst_Entl_Typ_11,
    ID_Einst_Entl_Typ_12,
    ID_Einst_Vorl_max_MK1,
    ID_Einst_Vorl_max_MK2,
    ID_SU_FrkdMK1,
    ID_SU_FrkdMK2,
    ID_Ba_Hz_MK1_akt,
    ID_Ba_Hz_MK2_akt,
    ID_Einst_Zirk_Ein_akt,
    ID_Einst_Zirk_Aus_akt,
    ID_Einst_Heizgrenze,
    ID_Einst_Heizgrenze_Temp,
    ID_VariablenIBNgespeichert,
    ID_SchonIBNAssistant,
    ID_Heizgrenze_0,
    ID_Heizgrenze_1,
    ID_Heizgrenze_2,
    ID_Heizgrenze_3,
    ID_Heizgrenze_4,
    ID_Heizgrenze_5,
    ID_Heizgrenze_6,
    ID_Heizgrenze_7,
    ID_Heizgrenze_8,
    ID_Heizgrenze_9,
    ID_Heizgrenze_10,
    ID_Heizgrenze_11,
    ID_SchemenIBNgewahlt,
    ID_Switchoff_file_0_0,
    ID_Switchoff_file_1_0,
    ID_Switchoff_file_2_0,
    ID_Switchoff_file_3_0,
    ID_Switchoff_file_4_0,
    ID_Switchoff_file_0_1,
    ID_Switchoff_file_1_1,
    ID_Switchoff_file_2_1,
    ID_Switchoff_file_3_1,
    ID_Switchoff_file_4_1,
    ID_DauerDatenLoggerAktiv,
    ID_Laufvar_Heizgrenze,
    ID_Zaehler_BetrZeitHz,
    ID_Zaehler_BetrZeitBW,
    ID_Zaehler_BetrZeitKue,
    ID_SU_FstdHz,
    ID_SU_FstdBw,
    ID_SU_FstdSwb,
    ID_SU_FstdMK1,
    ID_SU_FstdMK2,
    ID_FerienAbsenkungHz,
    ID_FerienAbsenkungMK1,
    ID_FerienAbsenkungMK2,
    ID_FerienModusAktivHz,
    ID_FerienModusAktivBw,
    ID_FerienModusAktivSwb,
    ID_FerienModusAktivMk1,
    ID_FerienModusAktivMk2,
    ID_DisplayContrast_akt,
    ID_Ba_Hz_saved,
    ID_Ba_Bw_saved,
    ID_Ba_Sw_saved,
    ID_Ba_Hz_MK1_saved,
    ID_Ba_Hz_MK2_saved,
    ID_AdresseIP_akt,
    ID_SubNetMask_akt,
    ID_Add_Broadcast_akt,
    ID_Add_StdGateway_akt,
    ID_DHCPServerAktiv_akt,
    ID_WebserverPasswort_1_akt,
    ID_WebserverPasswort_2_akt,
    ID_WebserverPasswort_3_akt,
    ID_WebserverPasswort_4_akt,
    ID_WebserverPasswort_5_akt,
    ID_WebserverPasswort_6_akt,
    ID_WebServerWerteBekommen,
    ID_Einst_ParBetr_akt,
    ID_Einst_WpAnz_akt,
    ID_Einst_PhrTime_akt,
    ID_Einst_HysPar_akt,
    ID_IP_PB_Slave_0,
    ID_IP_PB_Slave_1,
    ID_IP_PB_Slave_2,
    ID_IP_PB_Slave_3,
    ID_IP_PB_Slave_4,
    ID_IP_PB_Slave_5,
    ID_Einst_BwHup_akt_backup,
    ID_Einst_SuMk3_akt,
    ID_Einst_HzMK3E_akt,
    ID_Einst_HzMK3ANH_akt,
    ID_Einst_HzMK3ABS_akt,
    ID_Einst_HzMK3Hgr_akt,
    ID_Einst_HzFtMK3Vl_akt,
    ID_Ba_Hz_MK3_akt,
    ID_Einst_MK3Typ_akt,
    ID_Einst_RTypMK3_akt,
    ID_Einst_MK3LzFaktor_akt,
    ID_Einst_MK3PerFaktor_akt,
    ID_FerienModusAktivMk3,
    ID_SU_FrkdMK3,
    ID_FerienAbsenkungMK3,
    ID_SU_FstdMK3,
    ID_Einst_SuMk3_akt2,
    ID_Einst_SuMk3Wo_zeit_0_0,
    ID_Einst_SuMk3Wo_zeit_0_1,
    ID_Einst_SuMk3Wo_zeit_1_0,
    ID_Einst_SuMk3Wo_zeit_1_1,
    ID_Einst_SuMk3Wo_zeit_2_0,
    ID_Einst_SuMk3Wo_zeit_2_1,
    ID_Einst_SuMk325_zeit_0_0,
    ID_Einst_SuMk325_zeit_0_1,
    ID_Einst_SuMk325_zeit_1_0,
    ID_Einst_SuMk325_zeit_1_1,
    ID_Einst_SuMk325_zeit_2_0,
    ID_Einst_SuMk325_zeit_2_1,
    ID_Einst_SuMk325_zeit_0_2,
    ID_Einst_SuMk325_zeit_0_3,
    ID_Einst_SuMk325_zeit_1_2,
    ID_Einst_SuMk325_zeit_1_3,
    ID_Einst_SuMk325_zeit_2_2,
    ID_Einst_SuMk325_zeit_2_3,
    ID_Einst_SuMk3Tg_zeit_0_0,
    ID_Einst_SuMk3Tg_zeit_0_1,
    ID_Einst_SuMk3Tg_zeit_1_0,
    ID_Einst_SuMk3Tg_zeit_1_1,
    ID_Einst_SuMk3Tg_zeit_2_0,
    ID_Einst_SuMk3Tg_zeit_2_1,
    ID_Einst_SuMk3Tg_zeit_0_2,
    ID_Einst_SuMk3Tg_zeit_0_3,
    ID_Einst_SuMk3Tg_zeit_1_2,
    ID_Einst_SuMk3Tg_zeit_1_3,
    ID_Einst_SuMk3Tg_zeit_2_2,
    ID_Einst_SuMk3Tg_zeit_2_3,
    ID_Einst_SuMk3Tg_zeit_0_4,
    ID_Einst_SuMk3Tg_zeit_0_5,
    ID_Einst_SuMk3Tg_zeit_1_4,
    ID_Einst_SuMk3Tg_zeit_1_5,
    ID_Einst_SuMk3Tg_zeit_2_4,
    ID_Einst_SuMk3Tg_zeit_2_5,
    ID_Einst_SuMk3Tg_zeit_0_6,
    ID_Einst_SuMk3Tg_zeit_0_7,
    ID_Einst_SuMk3Tg_zeit_1_6,
    ID_Einst_SuMk3Tg_zeit_1_7,
    ID_Einst_SuMk3Tg_zeit_2_6,
    ID_Einst_SuMk3Tg_zeit_2_7,
    ID_Einst_SuMk3Tg_zeit_0_8,
    ID_Einst_SuMk3Tg_zeit_0_9,
    ID_Einst_SuMk3Tg_zeit_1_8,
    ID_Einst_SuMk3Tg_zeit_1_9,
    ID_Einst_SuMk3Tg_zeit_2_8,
    ID_Einst_SuMk3Tg_zeit_2_9,
    ID_Einst_SuMk3Tg_zeit_0_10,
    ID_Einst_SuMk3Tg_zeit_0_11,
    ID_Einst_SuMk3Tg_zeit_1_10,
    ID_Einst_SuMk3Tg_zeit_1_11,
    ID_Einst_SuMk3Tg_zeit_2_10,
    ID_Einst_SuMk3Tg_zeit_2_11,
    ID_Einst_SuMk3Tg_zeit_0_12,
    ID_Einst_SuMk3Tg_zeit_0_13,
    ID_Einst_SuMk3Tg_zeit_1_12,
    ID_Einst_SuMk3Tg_zeit_1_13,
    ID_Einst_SuMk3Tg_zeit_2_12,
    ID_Einst_SuMk3Tg_zeit_2_13,
    ID_Ba_Hz_MK3_saved,
    ID_Einst_Kuhl_Zeit_Ein_akt,
    ID_Einst_Kuhl_Zeit_Aus_akt,
    ID_Waermemenge_Seit,
    ID_Waermemenge_WQ,
    ID_Waermemenge_Hz,
    ID_Waermemenge_WQ_ges,
    ID_Einst_Entl_Typ_13,
    ID_Einst_Entl_Typ_14,
    ID_Einst_Entl_Typ_15,
    ID_Zaehler_BetrZeitSW,
    ID_Einst_Fernwartung_akt,
    ID_AdresseIPServ_akt,
    ID_Einst_TA_EG_akt,
    ID_Einst_TVLmax_EG_akt,
    ID_Einst_Popt_Nachlauf_akt,
    ID_FernwartungVertrag_akt,
    ID_FernwartungAktuZeit,
    ID_Einst_Effizienzpumpe_Nominal_akt,
    ID_Einst_Effizienzpumpe_Minimal_akt,
    ID_Einst_Effizienzpumpe_akt,
    ID_Einst_Waermemenge_akt,
    ID_Einst_Wm_Versorgung_Korrektur_akt,
    ID_Einst_Wm_Auswertung_Korrektur_akt,
    ID_SoftwareUpdateJetztGemacht_akt,
    ID_WP_SerienNummer_DATUM,
    ID_WP_SerienNummer_HEX,
    ID_WP_SerienNummer_INDEX,
    ID_ProgWerteWebSrvBeobarten,
    ID_Waermemenge_BW,
    ID_Waermemenge_SW,
    ID_Waermemenge_Datum,
    ID_Einst_Solar_akt,
    ID_BSTD_Solar,
    ID_Einst_TDC_Koll_Max_akt,
    ID_Einst_Akt_Kuehlung_akt,
    ID_Einst_Vorlauf_VBO_akt,
    ID_Einst_KRHyst_akt,
    ID_Einst_Akt_Kuehl_Speicher_min_akt,
    ID_Einst_Akt_Kuehl_Freig_WQE_akt,
    ID_NDAB_WW_Anzahl,
    ID_NDS_WW_KD_Quitt,
    ID_Einst_AbtZykMin_akt,
    ID_Einst_VD2_Zeit_Min_akt,
    ID_Einst_Hysterese_HR_verkuerzt_akt,
    ID_Einst_BA_Lueftung_akt,
    ID_Einst_SuLuf_akt,
    ID_Einst_SuLufWo_zeit_0_0_0,
    ID_Einst_SuLufWo_zeit_0_1_0,
    ID_Einst_SuLufWo_zeit_0_2_0,
    ID_Einst_SuLuf25_zeit_0_0_0,
    ID_Einst_SuLuf25_zeit_0_1_0,
    ID_Einst_SuLuf25_zeit_0_2_0,
    ID_Einst_SuLuf25_zeit_0_0_2,
    ID_Einst_SuLuf25_zeit_0_1_2,
    ID_Einst_SuLuf25_zeit_0_2_2,
    ID_Einst_SuLufTg_zeit_0_0_0,
    ID_Einst_SuLufTg_zeit_0_1_0,
    ID_Einst_SuLufTg_zeit_0_2_0,
    ID_Einst_SuLufTg_zeit_0_0_2,
    ID_Einst_SuLufTg_zeit_0_1_2,
    ID_Einst_SuLufTg_zeit_0_2_2,
    ID_Einst_SuLufTg_zeit_0_0_4,
    ID_Einst_SuLufTg_zeit_0_1_4,
    ID_Einst_SuLufTg_zeit_0_2_4,
    ID_Einst_SuLufTg_zeit_0_0_6,
    ID_Einst_SuLufTg_zeit_0_1_6,
    ID_Einst_SuLufTg_zeit_0_2_6,
    ID_Einst_SuLufTg_zeit_0_0_8,
    ID_Einst_SuLufTg_zeit_0_1_8,
    ID_Einst_SuLufTg_zeit_0_2_8,
    ID_Einst_SuLufTg_zeit_0_0_10,
    ID_Einst_SuLufTg_zeit_0_1_10,
    ID_Einst_SuLufTg_zeit_0_2_10,
    ID_Einst_SuLufTg_zeit_0_0_12,
    ID_Einst_SuLufTg_zeit_0_1_12,
    ID_Einst_SuLufTg_zeit_0_2_12,
    ID_Einst_SuLufWo_zeit_1_0_0,
    ID_Einst_SuLufWo_zeit_1_1_0,
    ID_Einst_SuLufWo_zeit_1_2_0,
    ID_Einst_SuLuf25_zeit_1_0_0,
    ID_Einst_SuLuf25_zeit_1_1_0,
    ID_Einst_SuLuf25_zeit_1_2_0,
    ID_Einst_SuLuf25_zeit_1_0_2,
    ID_Einst_SuLuf25_zeit_1_1_2,
    ID_Einst_SuLuf25_zeit_1_2_2,
    ID_Einst_SuLufTg_zeit_1_0_0,
    ID_Einst_SuLufTg_zeit_1_1_0,
    ID_Einst_SuLufTg_zeit_1_2_0,
    ID_Einst_SuLufTg_zeit_1_0_2,
    ID_Einst_SuLufTg_zeit_1_1_2,
    ID_Einst_SuLufTg_zeit_1_2_2,
    ID_Einst_SuLufTg_zeit_1_0_4,
    ID_Einst_SuLufTg_zeit_1_1_4,
    ID_Einst_SuLufTg_zeit_1_2_4,
    ID_Einst_SuLufTg_zeit_1_0_6,
    ID_Einst_SuLufTg_zeit_1_1_6,
    ID_Einst_SuLufTg_zeit_1_2_6,
    ID_Einst_SuLufTg_zeit_1_0_8,
    ID_Einst_SuLufTg_zeit_1_1_8,
    ID_Einst_SuLufTg_zeit_1_2_8,
    ID_Einst_SuLufTg_zeit_1_0_10,
    ID_Einst_SuLufTg_zeit_1_1_10,
    ID_Einst_SuLufTg_zeit_1_2_10,
    ID_Einst_SuLufTg_zeit_1_0_12,
    ID_Einst_SuLufTg_zeit_1_1_12,
    ID_Einst_SuLufTg_zeit_1_2_12,
    ID_FerienModusAktivLueftung,
    ID_Einst_BA_Lueftung_saved,
    ID_SU_FrkdLueftung,
    ID_SU_FstdLueftung,
    ID_Einst_Luf_Feuchteschutz_akt,
    ID_Einst_Luf_Reduziert_akt,
    ID_Einst_Luf_Nennlueftung_akt,
    ID_Einst_Luf_Intensivlueftung_akt,
    ID_Timer_Fil_4Makt,
    ID_Timer_Fil_WoAkt,
    ID_Sollwert_KuCft3_akt,
    ID_Sollwert_AtDif3_akt,
    ID_Bitmaske_0,
    ID_Einst_Lueftungsstufen,
    ID_SysEin_Meldung_TDI,
    ID_SysEin_Typ_WZW,
    ID_Einst_GLT_aktiviert,
    ID_Einst_BW_max,
    ID_Einst_Sollwert_TRL_Kuehlen,
    ID_Einst_Medium_Waermequelle,
    ID_Einst_Photovoltaik_akt,
    ID_Einst_Multispeicher_akt,
    ID_Einst_PKuehlTime_akt,
    ID_Einst_Minimale_Ruecklaufsolltemperatur,
    ID_RBE_Einflussfaktor_RT_akt,
    ID_RBE_Freigabe_Kuehlung_akt,
    ID_RBE_Waermeverteilsystem_akt,
    ID_RBE_Zeit_Heizstab_aktiv,
    ID_SEC_ND_Alarmgrenze,
    ID_SEC_HD_Alarmgrenze,
    ID_SEC_Abtauendtemperatur,
    ID_Einst_Min_RPM_BW,
    ID_Einst_Luf_Feuchteschutz_Faktor_akt,
    ID_Einst_Luf_Reduziert_Faktor_akt,
    ID_Einst_Luf_Nennlueftung_Faktor_akt,
    ID_Einst_Luf_Intensivlueftung_Faktor_akt,
    ID_Einst_Freigabe_Zeit_ZWE,
    ID_Einst_min_VL_Kuehl,
    ID_Einst_Warmwasser_Nachheizung,
    ID_Switchoff_file_LWD2_0_0,
    ID_Switchoff_file_LWD2_1_0,
    ID_Switchoff_file_LWD2_2_0,
    ID_Switchoff_file_LWD2_3_0,
    ID_Switchoff_file_LWD2_4_0,
    ID_Switchoff_file_LWD2_0_1,
    ID_Switchoff_file_LWD2_1_1,
    ID_Switchoff_file_LWD2_2_1,
    ID_Switchoff_file_LWD2_3_1,
    ID_Switchoff_file_LWD2_4_1,
    ID_Switchoff_index_LWD2,
    ID_Einst_Effizienzpumpe_Nominal_2,
    ID_Einst_Effizienzpumpe_Minimal_2,
    ID_Einst_Wm_Versorgung_Korrektur_2,
    ID_Einst_Wm_Auswertung_Korrektur_2,
    ID_Einst_isTwin,
    ID_Einst_TAmin_2,
    ID_Einst_TVLmax_2,
    ID_Einst_TA_EG_2,
    ID_Einst_TVLmax_EG_2,
    ID_Waermemenge_Hz_2,
    ID_Waermemenge_BW_2,
    ID_Waermemenge_SW_2,
    ID_Waermemenge_Seit_2,
    ID_Einst_Entl_Typ_15_2,
    ID_Einst_WW_Nachheizung_max,
    ID_Einst_Kuhl_Zeit_Ein_RT,
    ID_Einst_ZWE1_Pos,
    ID_Einst_ZWE2_Pos,
    ID_Einst_ZWE3_Pos,
    ID_Einst_Leistung_ZWE,
    ID_WP_SN2_DATUM,
    ID_WP_SN2_HEX,
    ID_WP_SN2_INDEX,
    ID_CWP_saved2,
    ID_Einst_SmartGrid,
    ID_Einst_P155_HDS,
    ID_Einst_P155_PumpHeat_Max,
    ID_Einst_P155_PumpHeatCtrl,
    ID_Einst_P155_PumpDHWCtrl,
    ID_Einst_P155_PumpDHW_RPM,
    ID_Einst_P155_PumpPoolCtrl,
    ID_Einst_P155_PumpPool_RPM,
    ID_Einst_P155_PumpCool_RPM,
    ID_Einst_P155_PumpVBOCtrl,
    ID_Einst_P155_PumpVBO_RPM_C,
    ID_Einst_P155_PumpDHW_Max,
    ID_Einst_P155_PumpPool_Max,
    ID_Einst_P155_Sperrband_1,
    ID_Einst_P155_Leistungsfreigabe,
    ID_Einst_P155_DHW_Freq,
    ID_Einst_SWHUP,
    ID_Einst_P155_SWB_Freq,
    ID_Einst_MK1_Regelung,
    ID_Einst_MK2_Regelung,
    ID_Einst_MK3_Regelung,
    ID_Einst_PV_WW_Sperrzeit,
    ID_Einst_Warmwasser_extra,
    ID_Einst_Vorl_akt_Kuehl,
    ID_WP_SN3_DATUM,
    ID_WP_SN3_HEX,
    ID_WP_SN3_INDEX,
    ID_Einst_Vorlauf_ZUP,
    ID_Einst_Abtauen_im_Warmwasser,
    ID_Waermemenge_ZWE,
    ID_Waermemenge_Reset,
    ID_Waermemenge_Reset_2,
    ID_Einst_Brunnenpumpe_min,
    ID_Einst_Brunnenpumpe_max,
    ID_Einst_SmartHomeID,
    ID_Einst_SmartHK,
    ID_Einst_SmartMK1,
    ID_Einst_SmartMK2,
    ID_Einst_SmartMK3,
    ID_Einst_SmartWW,
    ID_Einst_SmartDefrost,
    ID_Einst_Empty1071,
    ID_Einst_MinVLMK1,
    ID_Einst_MinVLMK2,
    ID_Einst_MinVLMK3,
    ID_Einst_MaxVLMK1,
    ID_Einst_MaxVLMK2,
    ID_Einst_MaxVLMK3,
    ID_Einst_SmartPlusHz,
    ID_Einst_SmartMinusHz,
    ID_Einst_SmartPlusMK1,
    ID_Einst_SmartMinusMK1,
    ID_Einst_SmartPlusMK2,
    ID_Einst_SmartMinusMK2,
    ID_Einst_SmartPlusMK3,
    ID_Einst_SmartMinusMK3,
