# pylint: disable=too-many-lines

"""Parse luxtronik parameters."""
import logging

from luxtronik.data_vector import DataVector

from luxtronik.datatypes import (
    AccessLevel,
    Bool,
    Count,
    Energy,
    Kelvin,
    Celsius,
    CoolingMode,
    HeatingMode,
    HotWaterMode,
    Hours,
    Hours2,
    Minutes,
    MixedCircuitMode,
    OnOffMode,
    PoolMode,
    Seconds,
    SolarMode,
    Timestamp,
    Unknown,
    VentilationMode,
    TimerProgram,
    TimeOfDay,
    TimeOfDay2,
)


class Parameters(DataVector):
    """Class that holds all parameters."""

    logger = logging.getLogger("Luxtronik.Parameters")
    name = "Parameter"

    def __init__(self, safe=True):
        """Initialize parameters class."""
        super().__init__()
        self.safe = safe
        self.queue = {}

        self._data = {
            0: Unknown(["ID_Transfert_LuxNet", "Unknown_Parameter_0"]),
            1: Celsius(["ID_Einst_WK_akt", "Unknown_Parameter_1"], True),
            2: Celsius(["ID_Einst_BWS_akt", "Unknown_Parameter_2"], True),
            3: HeatingMode(["ID_Ba_Hz_akt", "Unknown_Parameter_3"], True),
            4: HotWaterMode(["ID_Ba_Bw_akt", "Unknown_Parameter_4"], True),
            5: Unknown(["ID_Ba_Al_akt", "Unknown_Parameter_5"]),
            6: Unknown(["ID_SU_FrkdHz", "Unknown_Parameter_6"]),
            7: Unknown(["ID_SU_FrkdBw", "Unknown_Parameter_7"]),
            8: Unknown(["ID_SU_FrkdAl", "Unknown_Parameter_8"]),
            9: Unknown(["ID_Einst_HReg_akt", "Unknown_Parameter_9"]),
            10: Unknown(["ID_Einst_HzHwMAt_akt", "Unknown_Parameter_10"]),
            11: Celsius(["ID_Einst_HzHwHKE_akt", "Unknown_Parameter_11"], True),
            12: Celsius(["ID_Einst_HzHKRANH_akt", "Unknown_Parameter_12"], True),
            13: Celsius(["ID_Einst_HzHKRABS_akt", "Unknown_Parameter_13"], True),
            14: Celsius(["ID_Einst_HzMK1E_akt", "Unknown_Parameter_14"], True),
            15: Celsius(["ID_Einst_HzMK1ANH_akt", "Unknown_Parameter_15"], True),
            16: Celsius(["ID_Einst_HzMK1ABS_akt", "Unknown_Parameter_16"], True),
            17: Unknown(["ID_Einst_HzFtRl_akt", "Unknown_Parameter_17"]),
            18: Unknown(["ID_Einst_HzFtMK1Vl_akt", "Unknown_Parameter_18"]),
            19: Unknown(["ID_Einst_SUBW_akt", "Unknown_Parameter_19"]),
            20: Unknown(["ID_Einst_BwTDI_akt_MO", "Unknown_Parameter_20"]),
            21: Unknown(["ID_Einst_BwTDI_akt_DI", "Unknown_Parameter_21"]),
            22: Unknown(["ID_Einst_BwTDI_akt_MI", "Unknown_Parameter_22"]),
            23: Unknown(["ID_Einst_BwTDI_akt_DO", "Unknown_Parameter_23"]),
            24: Unknown(["ID_Einst_BwTDI_akt_FR", "Unknown_Parameter_24"]),
            25: Unknown(["ID_Einst_BwTDI_akt_SA", "Unknown_Parameter_25"]),
            26: Unknown(["ID_Einst_BwTDI_akt_SO", "Unknown_Parameter_26"]),
            27: Unknown(["ID_Einst_BwTDI_akt_AL", "Unknown_Parameter_27"]),
            28: Unknown(["ID_Einst_AnlKonf_akt", "Unknown_Parameter_28"]),
            29: Unknown(["ID_Einst_Sprache_akt", "Unknown_Parameter_29"]),
            30: Unknown(["ID_Switchoff_Zahler", "Unknown_Parameter_30"]),
            31: Unknown(["ID_Switchoff_index", "Unknown_Parameter_31"]),
            32: Unknown(["ID_Einst_EvuTyp_akt", "Unknown_Parameter_32"]),
            33: Unknown(["ID_Einst_RFVEinb_akt", "Unknown_Parameter_33"]),
            34: Unknown(["ID_Einst_AbtZykMax_akt", "Unknown_Parameter_34"]),
            35: Unknown(["ID_Einst_HREinb_akt", "Unknown_Parameter_35"]),
            36: Unknown(["ID_Einst_ZWE1Art_akt", "Unknown_Parameter_36"]),
            37: Unknown(["ID_Einst_ZWE1Fkt_akt", "Unknown_Parameter_37"]),
            38: Unknown(["ID_Einst_ZWE2Art_akt", "Unknown_Parameter_38"]),
            39: Unknown(["ID_Einst_ZWE2Fkt_akt", "Unknown_Parameter_39"]),
            40: Unknown(["ID_Einst_BWBer_akt", "Unknown_Parameter_40"]),
            41: Unknown(["ID_Einst_En_Inst", "Unknown_Parameter_41"]),
            42: Unknown(["ID_Einst_MK1Typ_akt", "Unknown_Parameter_42"]),
            43: Unknown(["ID_Einst_ABTLuft_akt", "Unknown_Parameter_43"]),
            44: Unknown(["ID_Einst_TLAbt_akt", "Unknown_Parameter_44"]),
            45: Unknown(["ID_Einst_LAbtTime_akt", "Unknown_Parameter_45"]),
            46: Unknown(["ID_Einst_ASDTyp_akt", "Unknown_Parameter_46"]),
            47: Celsius(["ID_Einst_LGST_akt", "Unknown_Parameter_47"], True),
            48: Unknown(["ID_Einst_BwWpTime_akt", "Unknown_Parameter_48"]),
            49: Unknown(["ID_Einst_Popt_akt", "Unknown_Parameter_49"]),
            50: Unknown(["ID_Einst_Kurzprog_akt", "Unknown_Parameter_50"]),
            51: Unknown(["ID_Timer_Kurzprog_akt", "Unknown_Parameter_51"]),
            52: Unknown(["ID_Einst_ManAbt_akt", "Unknown_Parameter_52"]),
            53: Unknown(["ID_Einst_Ahz_akt", "Unknown_Parameter_53"]),
            54: Unknown(["ID_Einst_TVL_Ahz_1", "Unknown_Parameter_54"]),
            55: Unknown(["ID_Einst_TVL_Ahz_2", "Unknown_Parameter_55"]),
            56: Unknown(["ID_Einst_TVL_Ahz_3", "Unknown_Parameter_56"]),
            57: Unknown(["ID_Einst_TVL_Ahz_4", "Unknown_Parameter_57"]),
            58: Unknown(["ID_Einst_TVL_Ahz_5", "Unknown_Parameter_58"]),
            59: Unknown(["ID_Einst_TVL_Ahz_6", "Unknown_Parameter_59"]),
            60: Unknown(["ID_Einst_TVL_Ahz_7", "Unknown_Parameter_60"]),
            61: Unknown(["ID_Einst_TVL_Ahz_8", "Unknown_Parameter_61"]),
            62: Unknown(["ID_Einst_TVL_Ahz_9", "Unknown_Parameter_62"]),
            63: Unknown(["ID_Einst_TVL_Ahz_10", "Unknown_Parameter_63"]),
            64: Unknown(["ID_Einst_TVL_Std_1", "Unknown_Parameter_64"]),
            65: Unknown(["ID_Einst_TVL_Std_2", "Unknown_Parameter_65"]),
            66: Unknown(["ID_Einst_TVL_Std_3", "Unknown_Parameter_66"]),
            67: Unknown(["ID_Einst_TVL_Std_4", "Unknown_Parameter_67"]),
            68: Unknown(["ID_Einst_TVL_Std_5", "Unknown_Parameter_68"]),
            69: Unknown(["ID_Einst_TVL_Std_6", "Unknown_Parameter_69"]),
            70: Unknown(["ID_Einst_TVL_Std_7", "Unknown_Parameter_70"]),
            71: Unknown(["ID_Einst_TVL_Std_8", "Unknown_Parameter_71"]),
            72: Unknown(["ID_Einst_TVL_Std_9", "Unknown_Parameter_72"]),
            73: Unknown(["ID_Einst_TVL_Std_10", "Unknown_Parameter_73"]),
            74: Kelvin(["ID_Einst_BWS_Hyst_akt", "Unknown_Parameter_74"], True),
            75: Unknown(["ID_Temp_TBW_BwHD_saved", "Unknown_Parameter_75"]),
            76: Unknown(["ID_Einst_ABT1_akt", "Unknown_Parameter_76"]),
            77: Unknown(["ID_Einst_LABTpaus_akt", "Unknown_Parameter_77"]),
            78: Unknown(["ID_AHZ_state_akt", "Unknown_Parameter_78"]),
            79: Celsius(["ID_Sollwert_TRL_HZ_AHZ", "Unknown_Parameter_79"], True),
            80: Unknown(["ID_AHP_valid_records", "Unknown_Parameter_80"]),
            81: Unknown(["ID_Timer_AHZ_akt", "Unknown_Parameter_81"]),
            82: Unknown(["ID_Einst_BWTINP_akt", "Unknown_Parameter_82"]),
            83: Unknown(["ID_Einst_ZUPTYP_akt", "Unknown_Parameter_83"]),
            84: Unknown(["ID_Sollwert_TLG_max", "Unknown_Parameter_84"]),
            85: Unknown(["ID_Einst_BWZIP_akt", "Unknown_Parameter_85"]),
            86: Unknown(["ID_Einst_ERRmZWE_akt", "Unknown_Parameter_86"]),
            87: Unknown(["ID_Einst_TRBegr_akt", "Unknown_Parameter_87"]),
            88: Kelvin(["ID_Einst_HRHyst_akt", "Unknown_Parameter_88"], True),
            89: Kelvin(["ID_Einst_TRErhmax_akt", "Unknown_Parameter_89"], True),
            90: Celsius(["ID_Einst_ZWEFreig_akt", "Unknown_Parameter_90"], True),
            91: Unknown(["ID_Einst_TAmax_akt", "Unknown_Parameter_91"]),
            92: Unknown(["ID_Einst_TAmin_akt", "Unknown_Parameter_92"]),
            93: Unknown(["ID_Einst_TWQmin_akt", "Unknown_Parameter_93"]),
            94: Unknown(["ID_Einst_THGmax_akt", "Unknown_Parameter_94"]),
            95: Unknown(["ID_Einst_FRGT2VD_akt", "Unknown_Parameter_95"]),
            96: Unknown(["ID_Einst_TV2VDBW_akt", "Unknown_Parameter_96"]),
            97: Unknown(["ID_Einst_SuAll_akt", "Unknown_Parameter_97"]),
            98: Unknown(["ID_Einst_TAbtEnd_akt", "Unknown_Parameter_98"]),
            99: Unknown(["ID_Einst_NrKlingel_akt", "Unknown_Parameter_99"]),
            100: Unknown(["ID_Einst_BWStyp_akt", "Unknown_Parameter_100"]),
            101: Unknown(["ID_Einst_ABT2_akt", "Unknown_Parameter_101"]),
            102: Unknown(["ID_Einst_UeVd_akt", "Unknown_Parameter_102"]),
            103: Unknown(["ID_Einst_RTyp_akt", "Unknown_Parameter_103"]),
            104: Unknown(["ID_Einst_AhpM_akt", "Unknown_Parameter_104"]),
            105: Celsius(["ID_Soll_BWS_akt", "Unknown_Parameter_105"], True),
            106: Unknown(["ID_Timer_Password", "Unknown_Parameter_106"]),
            107: AccessLevel(["ID_Einst_Zugangscode", "Unknown_Parameter_107"], True),
            108: CoolingMode(["ID_Einst_BA_Kuehl_akt", "Unknown_Parameter_108"], True),
            109: Unknown(["ID_Sollwert_Kuehl1_akt", "Unknown_Parameter_109"]),
            110: Celsius(["ID_Einst_KuehlFreig_akt", "Unknown_Parameter_110"], True),
            111: Celsius(["ID_Einst_TAbsMin_akt", "Unknown_Parameter_111"], True),
            112: Unknown(["ID_TWQmin_saved", "Unknown_Parameter_112"]),
            113: Unknown(["ID_CWP_saved", "Unknown_Parameter_113"]),
            114: Unknown(["ID_Einst_Anode_akt", "Unknown_Parameter_114"]),
            115: Unknown(["ID_Timer_pexoff_akt", "Unknown_Parameter_115"]),
            116: Unknown(["ID_Einst_AnlPrio_Hzakt", "Unknown_Parameter_116"]),
            117: Unknown(["ID_Einst_AnlPrio_Bwakt", "Unknown_Parameter_117"]),
            118: Unknown(["ID_Einst_AnlPrio_Swakt", "Unknown_Parameter_118"]),
            119: PoolMode(["ID_Ba_Sw_akt", "Unknown_Parameter_119"], True),
            120: Unknown(["ID_Einst_RTypMK1_akt", "Unknown_Parameter_120"]),
            121: Unknown(["ID_Einst_RTypMK2_akt", "Unknown_Parameter_121"]),
            122: Kelvin(["ID_Einst_TDC_Ein_akt", "Unknown_Parameter_122"]),
            123: Kelvin(["ID_Einst_TDC_Aus_akt", "Unknown_Parameter_123"]),
            124: Celsius(["ID_Einst_TDC_Max_akt", "Unknown_Parameter_124"], True),
            125: Unknown(["ID_Einst_HysHzExEn_akt", "Unknown_Parameter_125"]),
            126: Unknown(["ID_Einst_HysBwExEn_akt", "Unknown_Parameter_126"]),
            127: Unknown(["ID_Einst_ZWE3Art_akt", "Unknown_Parameter_127"]),
            128: Unknown(["ID_Einst_ZWE3Fkt_akt", "Unknown_Parameter_128"]),
            129: Unknown(["ID_Einst_HzSup_akt", "Unknown_Parameter_129"]),
            130: Unknown(["ID_Einst_MK2Typ_akt", "Unknown_Parameter_130"]),
            131: Unknown(["ID_Einst_KuTyp_akt", "Unknown_Parameter_131"]),
            132: Celsius(["ID_Sollwert_KuCft1_akt", "Unknown_Parameter_132"], True),
            133: Celsius(["ID_Sollwert_KuCft2_akt", "Unknown_Parameter_133"], True),
            134: Celsius(["ID_Sollwert_AtDif1_akt", "Unknown_Parameter_134"], True),
            135: Celsius(["ID_Sollwert_AtDif2_akt", "Unknown_Parameter_135"], True),
            136: Unknown(["ID_SU_FrkdSwb", "Unknown_Parameter_136"]),
            137: Unknown(["ID_Einst_SwbBer_akt", "Unknown_Parameter_137"]),
            138: Unknown(["ID_Einst_TV2VDSWB_akt", "Unknown_Parameter_138"]),
            139: Unknown(["ID_Einst_MinSwan_Time_akt", "Unknown_Parameter_139"]),
            140: Unknown(["ID_Einst_SuMk2_akt", "Unknown_Parameter_140"]),
            141: Celsius(["ID_Einst_HzMK2E_akt", "Unknown_Parameter_141"], True),
            142: Celsius(["ID_Einst_HzMK2ANH_akt", "Unknown_Parameter_142"], True),
            143: Celsius(["ID_Einst_HzMK2ABS_akt", "Unknown_Parameter_143"], True),
            144: Unknown(["ID_Einst_HzMK2Hgr_akt", "Unknown_Parameter_144"]),
            145: Unknown(["ID_Einst_HzFtMK2Vl_akt", "Unknown_Parameter_145"]),
            146: Unknown(["ID_Temp_THG_BwHD_saved", "Unknown_Parameter_146"]),
            147: Unknown(["ID_Temp_TA_BwHD_saved", "Unknown_Parameter_147"]),
            148: Unknown(["ID_Einst_BwHup_akt", "Unknown_Parameter_148"]),
            149: Unknown(["ID_Einst_TVLmax_akt", "Unknown_Parameter_149"]),
            150: Unknown(["ID_Einst_MK1LzFaktor_akt", "Unknown_Parameter_150"]),
            151: Unknown(["ID_Einst_MK2LzFaktor_akt", "Unknown_Parameter_151"]),
            152: Unknown(["ID_Einst_MK1PerFaktor_akt", "Unknown_Parameter_152"]),
            153: Unknown(["ID_Einst_MK2PerFaktor_akt", "Unknown_Parameter_153"]),
            154: Unknown(["ID_Entl_Zyklus_akt", "Unknown_Parameter_154"]),
            155: Unknown(["ID_Einst_Entl_time_akt", "Unknown_Parameter_155"]),
            156: Unknown(["ID_Entl_Pause", "Unknown_Parameter_156"]),
            157: Unknown(["ID_Entl_timer", "Unknown_Parameter_157"]),
            158: Unknown(["ID_Einst_Entl_akt", "Unknown_Parameter_158"]),
            159: Unknown(["ID_Ahz_HLeist_confirmed", "Unknown_Parameter_159"]),
            160: Unknown(["ID_FirstInit_akt", "Unknown_Parameter_160"]),
            161: Unknown(["ID_Einst_SuAll_akt2", "Unknown_Parameter_161"]),
            162: Unknown(["ID_Einst_SuAllWo_zeit_0_0", "Unknown_Parameter_162"]),
            163: Unknown(["ID_Einst_SuAllWo_zeit_0_1", "Unknown_Parameter_163"]),
            164: Unknown(["ID_Einst_SuAllWo_zeit_1_0", "Unknown_Parameter_164"]),
            165: Unknown(["ID_Einst_SuAllWo_zeit_1_1", "Unknown_Parameter_165"]),
            166: Unknown(["ID_Einst_SuAllWo_zeit_2_0", "Unknown_Parameter_166"]),
            167: Unknown(["ID_Einst_SuAllWo_zeit_2_1", "Unknown_Parameter_167"]),
            168: Unknown(["ID_Einst_SuAll25_zeit_0_0", "Unknown_Parameter_168"]),
            169: Unknown(["ID_Einst_SuAll25_zeit_0_1", "Unknown_Parameter_169"]),
            170: Unknown(["ID_Einst_SuAll25_zeit_1_0", "Unknown_Parameter_170"]),
            171: Unknown(["ID_Einst_SuAll25_zeit_1_1", "Unknown_Parameter_171"]),
            172: Unknown(["ID_Einst_SuAll25_zeit_2_0", "Unknown_Parameter_172"]),
            173: Unknown(["ID_Einst_SuAll25_zeit_2_1", "Unknown_Parameter_173"]),
            174: Unknown(["ID_Einst_SuAll25_zeit_0_2", "Unknown_Parameter_174"]),
            175: Unknown(["ID_Einst_SuAll25_zeit_0_3", "Unknown_Parameter_175"]),
            176: Unknown(["ID_Einst_SuAll25_zeit_1_2", "Unknown_Parameter_176"]),
            177: Unknown(["ID_Einst_SuAll25_zeit_1_3", "Unknown_Parameter_177"]),
            178: Unknown(["ID_Einst_SuAll25_zeit_2_2", "Unknown_Parameter_178"]),
            179: Unknown(["ID_Einst_SuAll25_zeit_2_3", "Unknown_Parameter_179"]),
            180: Unknown(["ID_Einst_SuAllTg_zeit_0_0", "Unknown_Parameter_180"]),
            181: Unknown(["ID_Einst_SuAllTg_zeit_0_1", "Unknown_Parameter_181"]),
            182: Unknown(["ID_Einst_SuAllTg_zeit_1_0", "Unknown_Parameter_182"]),
            183: Unknown(["ID_Einst_SuAllTg_zeit_1_1", "Unknown_Parameter_183"]),
            184: Unknown(["ID_Einst_SuAllTg_zeit_2_0", "Unknown_Parameter_184"]),
            185: Unknown(["ID_Einst_SuAllTg_zeit_2_1", "Unknown_Parameter_185"]),
            186: Unknown(["ID_Einst_SuAllTg_zeit_0_2", "Unknown_Parameter_186"]),
            187: Unknown(["ID_Einst_SuAllTg_zeit_0_3", "Unknown_Parameter_187"]),
            188: Unknown(["ID_Einst_SuAllTg_zeit_1_2", "Unknown_Parameter_188"]),
            189: Unknown(["ID_Einst_SuAllTg_zeit_1_3", "Unknown_Parameter_189"]),
            190: Unknown(["ID_Einst_SuAllTg_zeit_2_2", "Unknown_Parameter_190"]),
            191: Unknown(["ID_Einst_SuAllTg_zeit_2_3", "Unknown_Parameter_191"]),
            192: Unknown(["ID_Einst_SuAllTg_zeit_0_4", "Unknown_Parameter_192"]),
            193: Unknown(["ID_Einst_SuAllTg_zeit_0_5", "Unknown_Parameter_193"]),
            194: Unknown(["ID_Einst_SuAllTg_zeit_1_4", "Unknown_Parameter_194"]),
            195: Unknown(["ID_Einst_SuAllTg_zeit_1_5", "Unknown_Parameter_195"]),
            196: Unknown(["ID_Einst_SuAllTg_zeit_2_4", "Unknown_Parameter_196"]),
            197: Unknown(["ID_Einst_SuAllTg_zeit_2_5", "Unknown_Parameter_197"]),
            198: Unknown(["ID_Einst_SuAllTg_zeit_0_6", "Unknown_Parameter_198"]),
            199: Unknown(["ID_Einst_SuAllTg_zeit_0_7", "Unknown_Parameter_199"]),
            200: Unknown(["ID_Einst_SuAllTg_zeit_1_6", "Unknown_Parameter_200"]),
            201: Unknown(["ID_Einst_SuAllTg_zeit_1_7", "Unknown_Parameter_201"]),
            202: Unknown(["ID_Einst_SuAllTg_zeit_2_6", "Unknown_Parameter_202"]),
            203: Unknown(["ID_Einst_SuAllTg_zeit_2_7", "Unknown_Parameter_203"]),
            204: Unknown(["ID_Einst_SuAllTg_zeit_0_8", "Unknown_Parameter_204"]),
            205: Unknown(["ID_Einst_SuAllTg_zeit_0_9", "Unknown_Parameter_205"]),
            206: Unknown(["ID_Einst_SuAllTg_zeit_1_8", "Unknown_Parameter_206"]),
            207: Unknown(["ID_Einst_SuAllTg_zeit_1_9", "Unknown_Parameter_207"]),
            208: Unknown(["ID_Einst_SuAllTg_zeit_2_8", "Unknown_Parameter_208"]),
            209: Unknown(["ID_Einst_SuAllTg_zeit_2_9", "Unknown_Parameter_209"]),
            210: Unknown(["ID_Einst_SuAllTg_zeit_0_10", "Unknown_Parameter_210"]),
            211: Unknown(["ID_Einst_SuAllTg_zeit_0_11", "Unknown_Parameter_211"]),
            212: Unknown(["ID_Einst_SuAllTg_zeit_1_10", "Unknown_Parameter_212"]),
            213: Unknown(["ID_Einst_SuAllTg_zeit_1_11", "Unknown_Parameter_213"]),
            214: Unknown(["ID_Einst_SuAllTg_zeit_2_10", "Unknown_Parameter_214"]),
            215: Unknown(["ID_Einst_SuAllTg_zeit_2_11", "Unknown_Parameter_215"]),
            216: Unknown(["ID_Einst_SuAllTg_zeit_0_12", "Unknown_Parameter_216"]),
            217: Unknown(["ID_Einst_SuAllTg_zeit_0_13", "Unknown_Parameter_217"]),
            218: Unknown(["ID_Einst_SuAllTg_zeit_1_12", "Unknown_Parameter_218"]),
            219: Unknown(["ID_Einst_SuAllTg_zeit_1_13", "Unknown_Parameter_219"]),
            220: Unknown(["ID_Einst_SuAllTg_zeit_2_12", "Unknown_Parameter_220"]),
            221: Unknown(["ID_Einst_SuAllTg_zeit_2_13", "Unknown_Parameter_221"]),
            222: TimerProgram(["ID_Einst_SuHkr_akt", "Unknown_Parameter_222"], True),
            223: TimeOfDay(["ID_Einst_SuHkrW0_zeit_0_0", "Unknown_Parameter_223"], True),
            224: TimeOfDay(["ID_Einst_SuHkrW0_zeit_0_1", "Unknown_Parameter_224"], True),
            225: TimeOfDay(["ID_Einst_SuHkrW0_zeit_1_0", "Unknown_Parameter_225"], True),
            226: TimeOfDay(["ID_Einst_SuHkrW0_zeit_1_1", "Unknown_Parameter_226"], True),
            227: TimeOfDay(["ID_Einst_SuHkrW0_zeit_2_0", "Unknown_Parameter_227"], True),
            228: TimeOfDay(["ID_Einst_SuHkrW0_zeit_2_1", "Unknown_Parameter_228"], True),
            229: TimeOfDay(["ID_Einst_SuHkr25_zeit_0_0", "Unknown_Parameter_229"], True),
            230: TimeOfDay(["ID_Einst_SuHkr25_zeit_0_1", "Unknown_Parameter_230"], True),
            231: TimeOfDay(["ID_Einst_SuHkr25_zeit_1_0", "Unknown_Parameter_231"], True),
            232: TimeOfDay(["ID_Einst_SuHkr25_zeit_1_1", "Unknown_Parameter_232"], True),
            233: TimeOfDay(["ID_Einst_SuHkr25_zeit_2_0", "Unknown_Parameter_233"], True),
            234: TimeOfDay(["ID_Einst_SuHkr25_zeit_2_1", "Unknown_Parameter_234"], True),
            235: TimeOfDay(["ID_Einst_SuHkr25_zeit_0_2", "Unknown_Parameter_235"], True),
            236: TimeOfDay(["ID_Einst_SuHkr25_zeit_0_3", "Unknown_Parameter_236"], True),
            237: TimeOfDay(["ID_Einst_SuHkr25_zeit_1_2", "Unknown_Parameter_237"], True),
            238: TimeOfDay(["ID_Einst_SuHkr25_zeit_1_3", "Unknown_Parameter_238"], True),
            239: TimeOfDay(["ID_Einst_SuHkr25_zeit_2_2", "Unknown_Parameter_239"], True),
            240: TimeOfDay(["ID_Einst_SuHkr25_zeit_2_3", "Unknown_Parameter_240"], True),
            241: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_0", "Unknown_Parameter_241"], True),
            242: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_1", "Unknown_Parameter_242"], True),
            243: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_0", "Unknown_Parameter_243"], True),
            244: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_1", "Unknown_Parameter_244"], True),
            245: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_0", "Unknown_Parameter_245"], True),
            246: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_1", "Unknown_Parameter_246"], True),
            247: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_2", "Unknown_Parameter_247"], True),
            248: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_3", "Unknown_Parameter_248"], True),
            249: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_2", "Unknown_Parameter_249"], True),
            250: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_3", "Unknown_Parameter_250"], True),
            251: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_2", "Unknown_Parameter_251"], True),
            252: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_3", "Unknown_Parameter_252"], True),
            253: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_4", "Unknown_Parameter_253"], True),
            254: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_5", "Unknown_Parameter_254"], True),
            255: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_4", "Unknown_Parameter_255"], True),
            256: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_5", "Unknown_Parameter_256"], True),
            257: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_4", "Unknown_Parameter_257"], True),
            258: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_5", "Unknown_Parameter_258"], True),
            259: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_6", "Unknown_Parameter_259"], True),
            260: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_7", "Unknown_Parameter_260"], True),
            261: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_6", "Unknown_Parameter_261"], True),
            262: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_7", "Unknown_Parameter_262"], True),
            263: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_6", "Unknown_Parameter_263"], True),
            264: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_7", "Unknown_Parameter_264"], True),
            265: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_8", "Unknown_Parameter_265"], True),
            266: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_9", "Unknown_Parameter_266"], True),
            267: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_8", "Unknown_Parameter_267"], True),
            268: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_9", "Unknown_Parameter_268"], True),
            269: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_8", "Unknown_Parameter_269"], True),
            270: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_9", "Unknown_Parameter_270"], True),
            271: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_10", "Unknown_Parameter_271"], True),
            272: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_11", "Unknown_Parameter_272"], True),
            273: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_10", "Unknown_Parameter_273"], True),
            274: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_11", "Unknown_Parameter_274"], True),
            275: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_10", "Unknown_Parameter_275"], True),
            276: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_11", "Unknown_Parameter_276"], True),
            277: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_12", "Unknown_Parameter_277"], True),
            278: TimeOfDay(["ID_Einst_SuHkrTG_zeit_0_13", "Unknown_Parameter_278"], True),
            279: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_12", "Unknown_Parameter_279"], True),
            280: TimeOfDay(["ID_Einst_SuHkrTG_zeit_1_13", "Unknown_Parameter_280"], True),
            281: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_12", "Unknown_Parameter_281"], True),
            282: TimeOfDay(["ID_Einst_SuHkrTG_zeit_2_13", "Unknown_Parameter_282"], True),
            283: TimerProgram(["ID_Einst_SuMk1_akt", "Unknown_Parameter_283"]),
            284: TimeOfDay(["ID_Einst_SuMk1W0_zeit_0_0", "Unknown_Parameter_284"]),
            285: TimeOfDay(["ID_Einst_SuMk1W0_zeit_0_1", "Unknown_Parameter_285"]),
            286: TimeOfDay(["ID_Einst_SuMk1W0_zeit_1_0", "Unknown_Parameter_286"]),
            287: TimeOfDay(["ID_Einst_SuMk1W0_zeit_1_1", "Unknown_Parameter_287"]),
            288: TimeOfDay(["ID_Einst_SuMk1W0_zeit_2_0", "Unknown_Parameter_288"]),
            289: TimeOfDay(["ID_Einst_SuMk1W0_zeit_2_1", "Unknown_Parameter_289"]),
            290: TimeOfDay(["ID_Einst_SuMk125_zeit_0_0", "Unknown_Parameter_290"]),
            291: TimeOfDay(["ID_Einst_SuMk125_zeit_0_1", "Unknown_Parameter_291"]),
            292: TimeOfDay(["ID_Einst_SuMk125_zeit_1_0", "Unknown_Parameter_292"]),
            293: TimeOfDay(["ID_Einst_SuMk125_zeit_1_1", "Unknown_Parameter_293"]),
            294: TimeOfDay(["ID_Einst_SuMk125_zeit_2_0", "Unknown_Parameter_294"]),
            295: TimeOfDay(["ID_Einst_SuMk125_zeit_2_1", "Unknown_Parameter_295"]),
            296: TimeOfDay(["ID_Einst_SuMk125_zeit_0_2", "Unknown_Parameter_296"]),
            297: TimeOfDay(["ID_Einst_SuMk125_zeit_0_3", "Unknown_Parameter_297"]),
            298: TimeOfDay(["ID_Einst_SuMk125_zeit_1_2", "Unknown_Parameter_298"]),
            299: TimeOfDay(["ID_Einst_SuMk125_zeit_1_3", "Unknown_Parameter_299"]),
            300: TimeOfDay(["ID_Einst_SuMk125_zeit_2_2", "Unknown_Parameter_300"]),
            301: TimeOfDay(["ID_Einst_SuMk125_zeit_2_3", "Unknown_Parameter_301"]),
            302: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_0", "Unknown_Parameter_302"]),
            303: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_1", "Unknown_Parameter_303"]),
            304: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_0", "Unknown_Parameter_304"]),
            305: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_1", "Unknown_Parameter_305"]),
            306: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_0", "Unknown_Parameter_306"]),
            307: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_1", "Unknown_Parameter_307"]),
            308: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_2", "Unknown_Parameter_308"]),
            309: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_3", "Unknown_Parameter_309"]),
            310: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_2", "Unknown_Parameter_310"]),
            311: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_3", "Unknown_Parameter_311"]),
            312: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_2", "Unknown_Parameter_312"]),
            313: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_3", "Unknown_Parameter_313"]),
            314: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_4", "Unknown_Parameter_314"]),
            315: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_5", "Unknown_Parameter_315"]),
            316: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_4", "Unknown_Parameter_316"]),
            317: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_5", "Unknown_Parameter_317"]),
            318: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_4", "Unknown_Parameter_318"]),
            319: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_5", "Unknown_Parameter_319"]),
            320: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_6", "Unknown_Parameter_320"]),
            321: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_7", "Unknown_Parameter_321"]),
            322: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_6", "Unknown_Parameter_322"]),
            323: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_7", "Unknown_Parameter_323"]),
            324: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_6", "Unknown_Parameter_324"]),
            325: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_7", "Unknown_Parameter_325"]),
            326: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_8", "Unknown_Parameter_326"]),
            327: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_9", "Unknown_Parameter_327"]),
            328: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_8", "Unknown_Parameter_328"]),
            329: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_9", "Unknown_Parameter_329"]),
            330: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_8", "Unknown_Parameter_330"]),
            331: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_9", "Unknown_Parameter_331"]),
            332: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_10", "Unknown_Parameter_332"]),
            333: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_11", "Unknown_Parameter_333"]),
            334: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_10", "Unknown_Parameter_334"]),
            335: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_11", "Unknown_Parameter_335"]),
            336: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_10", "Unknown_Parameter_336"]),
            337: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_11", "Unknown_Parameter_337"]),
            338: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_12", "Unknown_Parameter_338"]),
            339: TimeOfDay(["ID_Einst_SuMk1TG_zeit_0_13", "Unknown_Parameter_339"]),
            340: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_12", "Unknown_Parameter_340"]),
            341: TimeOfDay(["ID_Einst_SuMk1TG_zeit_1_13", "Unknown_Parameter_341"]),
            342: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_12", "Unknown_Parameter_342"]),
            343: TimeOfDay(["ID_Einst_SuMk1TG_zeit_2_13", "Unknown_Parameter_343"]),
            344: TimerProgram(["ID_Einst_SuMk2_akt2", "Unknown_Parameter_344"]),
            345: TimeOfDay(["ID_Einst_SuMk2Wo_zeit_0_0", "Unknown_Parameter_345"]),
            346: TimeOfDay(["ID_Einst_SuMk2Wo_zeit_0_1", "Unknown_Parameter_346"]),
            347: TimeOfDay(["ID_Einst_SuMk2Wo_zeit_1_0", "Unknown_Parameter_347"]),
            348: TimeOfDay(["ID_Einst_SuMk2Wo_zeit_1_1", "Unknown_Parameter_348"]),
            349: TimeOfDay(["ID_Einst_SuMk2Wo_zeit_2_0", "Unknown_Parameter_349"]),
            350: TimeOfDay(["ID_Einst_SuMk2Wo_zeit_2_1", "Unknown_Parameter_350"]),
            351: TimeOfDay(["ID_Einst_SuMk225_zeit_0_0", "Unknown_Parameter_351"]),
            352: TimeOfDay(["ID_Einst_SuMk225_zeit_0_1", "Unknown_Parameter_352"]),
            353: TimeOfDay(["ID_Einst_SuMk225_zeit_1_0", "Unknown_Parameter_353"]),
            354: TimeOfDay(["ID_Einst_SuMk225_zeit_1_1", "Unknown_Parameter_354"]),
            355: TimeOfDay(["ID_Einst_SuMk225_zeit_2_0", "Unknown_Parameter_355"]),
            356: TimeOfDay(["ID_Einst_SuMk225_zeit_2_1", "Unknown_Parameter_356"]),
            357: TimeOfDay(["ID_Einst_SuMk225_zeit_0_2", "Unknown_Parameter_357"]),
            358: TimeOfDay(["ID_Einst_SuMk225_zeit_0_3", "Unknown_Parameter_358"]),
            359: TimeOfDay(["ID_Einst_SuMk225_zeit_1_2", "Unknown_Parameter_359"]),
            360: TimeOfDay(["ID_Einst_SuMk225_zeit_1_3", "Unknown_Parameter_360"]),
            361: TimeOfDay(["ID_Einst_SuMk225_zeit_2_2", "Unknown_Parameter_361"]),
            362: TimeOfDay(["ID_Einst_SuMk225_zeit_2_3", "Unknown_Parameter_362"]),
            363: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_0", "Unknown_Parameter_363"]),
            364: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_1", "Unknown_Parameter_364"]),
            365: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_0", "Unknown_Parameter_365"]),
            366: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_1", "Unknown_Parameter_366"]),
            367: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_0", "Unknown_Parameter_367"]),
            368: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_1", "Unknown_Parameter_368"]),
            369: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_2", "Unknown_Parameter_369"]),
            370: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_3", "Unknown_Parameter_370"]),
            371: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_2", "Unknown_Parameter_371"]),
            372: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_3", "Unknown_Parameter_372"]),
            373: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_2", "Unknown_Parameter_373"]),
            374: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_3", "Unknown_Parameter_374"]),
            375: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_4", "Unknown_Parameter_375"]),
            376: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_5", "Unknown_Parameter_376"]),
            377: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_4", "Unknown_Parameter_377"]),
            378: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_5", "Unknown_Parameter_378"]),
            379: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_4", "Unknown_Parameter_379"]),
            380: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_5", "Unknown_Parameter_380"]),
            381: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_6", "Unknown_Parameter_381"]),
            382: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_7", "Unknown_Parameter_382"]),
            383: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_6", "Unknown_Parameter_383"]),
            384: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_7", "Unknown_Parameter_384"]),
            385: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_6", "Unknown_Parameter_385"]),
            386: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_7", "Unknown_Parameter_386"]),
            387: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_8", "Unknown_Parameter_387"]),
            388: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_9", "Unknown_Parameter_388"]),
            389: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_8", "Unknown_Parameter_389"]),
            390: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_9", "Unknown_Parameter_390"]),
            391: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_8", "Unknown_Parameter_391"]),
            392: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_9", "Unknown_Parameter_392"]),
            393: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_10", "Unknown_Parameter_393"]),
            394: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_11", "Unknown_Parameter_394"]),
            395: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_10", "Unknown_Parameter_395"]),
            396: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_11", "Unknown_Parameter_396"]),
            397: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_10", "Unknown_Parameter_397"]),
            398: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_11", "Unknown_Parameter_398"]),
            399: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_12", "Unknown_Parameter_399"]),
            400: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_0_13", "Unknown_Parameter_400"]),
            401: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_12", "Unknown_Parameter_401"]),
            402: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_1_13", "Unknown_Parameter_402"]),
            403: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_12", "Unknown_Parameter_403"]),
            404: TimeOfDay(["ID_Einst_SuMk2Tg_zeit_2_13", "Unknown_Parameter_404"]),
            405: TimerProgram(["ID_Einst_SUBW_akt2", "Unknown_Parameter_405"], True),
            406: TimeOfDay(["ID_Einst_SuBwWO_zeit_0_0", "Unknown_Parameter_406"], True),
            407: TimeOfDay(["ID_Einst_SuBwWO_zeit_0_1", "Unknown_Parameter_407"], True),
            408: TimeOfDay(["ID_Einst_SuBwWO_zeit_1_0", "Unknown_Parameter_408"], True),
            409: TimeOfDay(["ID_Einst_SuBwWO_zeit_1_1", "Unknown_Parameter_409"], True),
            410: TimeOfDay(["ID_Einst_SuBwWO_zeit_2_0", "Unknown_Parameter_410"], True),
            411: TimeOfDay(["ID_Einst_SuBwWO_zeit_2_1", "Unknown_Parameter_411"], True),
            412: TimeOfDay(["ID_Einst_SuBwWO_zeit_3_0", "Unknown_Parameter_412"], True),
            413: TimeOfDay(["ID_Einst_SuBwWO_zeit_3_1", "Unknown_Parameter_413"], True),
            414: TimeOfDay(["ID_Einst_SuBwWO_zeit_4_0", "Unknown_Parameter_414"], True),
            415: TimeOfDay(["ID_Einst_SuBwWO_zeit_4_1", "Unknown_Parameter_415"], True),
            416: TimeOfDay(["ID_Einst_SuBw25_zeit_0_0", "Unknown_Parameter_416"], True),
            417: TimeOfDay(["ID_Einst_SuBw25_zeit_0_1", "Unknown_Parameter_417"], True),
            418: TimeOfDay(["ID_Einst_SuBw25_zeit_1_0", "Unknown_Parameter_418"], True),
            419: TimeOfDay(["ID_Einst_SuBw25_zeit_1_1", "Unknown_Parameter_419"], True),
            420: TimeOfDay(["ID_Einst_SuBw25_zeit_2_0", "Unknown_Parameter_420"], True),
            421: TimeOfDay(["ID_Einst_SuBw25_zeit_2_1", "Unknown_Parameter_421"], True),
            422: TimeOfDay(["ID_Einst_SuBw25_zeit_3_0", "Unknown_Parameter_422"], True),
            423: TimeOfDay(["ID_Einst_SuBw25_zeit_3_1", "Unknown_Parameter_423"], True),
            424: TimeOfDay(["ID_Einst_SuBw25_zeit_4_0", "Unknown_Parameter_424"], True),
            425: TimeOfDay(["ID_Einst_SuBw25_zeit_4_1", "Unknown_Parameter_425"], True),
            426: TimeOfDay(["ID_Einst_SuBw25_zeit_0_2", "Unknown_Parameter_426"], True),
            427: TimeOfDay(["ID_Einst_SuBw25_zeit_0_3", "Unknown_Parameter_427"], True),
            428: TimeOfDay(["ID_Einst_SuBw25_zeit_1_2", "Unknown_Parameter_428"], True),
            429: TimeOfDay(["ID_Einst_SuBw25_zeit_1_3", "Unknown_Parameter_429"], True),
            430: TimeOfDay(["ID_Einst_SuBw25_zeit_2_2", "Unknown_Parameter_430"], True),
            431: TimeOfDay(["ID_Einst_SuBw25_zeit_2_3", "Unknown_Parameter_431"], True),
            432: TimeOfDay(["ID_Einst_SuBw25_zeit_3_2", "Unknown_Parameter_432"], True),
            433: TimeOfDay(["ID_Einst_SuBw25_zeit_3_3", "Unknown_Parameter_433"], True),
            434: TimeOfDay(["ID_Einst_SuBw25_zeit_4_2", "Unknown_Parameter_434"], True),
            435: TimeOfDay(["ID_Einst_SuBw25_zeit_4_3", "Unknown_Parameter_435"], True),
            436: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_0", "Unknown_Parameter_436"], True),
            437: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_1", "Unknown_Parameter_437"], True),
            438: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_0", "Unknown_Parameter_438"], True),
            439: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_1", "Unknown_Parameter_439"], True),
            440: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_0", "Unknown_Parameter_440"], True),
            441: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_1", "Unknown_Parameter_441"], True),
            442: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_0", "Unknown_Parameter_442"], True),
            443: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_1", "Unknown_Parameter_443"], True),
            444: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_0", "Unknown_Parameter_444"], True),
            445: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_1", "Unknown_Parameter_445"], True),
            446: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_2", "Unknown_Parameter_446"], True),
            447: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_3", "Unknown_Parameter_447"], True),
            448: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_2", "Unknown_Parameter_448"], True),
            449: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_3", "Unknown_Parameter_449"], True),
            450: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_2", "Unknown_Parameter_450"], True),
            451: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_3", "Unknown_Parameter_451"], True),
            452: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_2", "Unknown_Parameter_452"], True),
            453: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_3", "Unknown_Parameter_453"], True),
            454: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_2", "Unknown_Parameter_454"], True),
            455: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_3", "Unknown_Parameter_455"], True),
            456: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_4", "Unknown_Parameter_456"], True),
            457: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_5", "Unknown_Parameter_457"], True),
            458: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_4", "Unknown_Parameter_458"], True),
            459: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_5", "Unknown_Parameter_459"], True),
            460: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_4", "Unknown_Parameter_460"], True),
            461: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_5", "Unknown_Parameter_461"], True),
            462: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_4", "Unknown_Parameter_462"], True),
            463: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_5", "Unknown_Parameter_463"], True),
            464: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_4", "Unknown_Parameter_464"], True),
            465: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_5", "Unknown_Parameter_465"], True),
            466: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_6", "Unknown_Parameter_466"], True),
            467: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_7", "Unknown_Parameter_467"], True),
            468: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_6", "Unknown_Parameter_468"], True),
            469: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_7", "Unknown_Parameter_469"], True),
            470: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_6", "Unknown_Parameter_470"], True),
            471: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_7", "Unknown_Parameter_471"], True),
            472: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_6", "Unknown_Parameter_472"], True),
            473: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_7", "Unknown_Parameter_473"], True),
            474: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_6", "Unknown_Parameter_474"], True),
            475: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_7", "Unknown_Parameter_475"], True),
            476: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_8", "Unknown_Parameter_476"], True),
            477: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_9", "Unknown_Parameter_477"], True),
            478: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_8", "Unknown_Parameter_478"], True),
            479: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_9", "Unknown_Parameter_479"], True),
            480: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_8", "Unknown_Parameter_480"], True),
            481: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_9", "Unknown_Parameter_481"], True),
            482: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_8", "Unknown_Parameter_482"], True),
            483: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_9", "Unknown_Parameter_483"], True),
            484: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_8", "Unknown_Parameter_484"], True),
            485: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_9", "Unknown_Parameter_485"], True),
            486: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_10", "Unknown_Parameter_486"], True),
            487: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_11", "Unknown_Parameter_487"], True),
            488: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_10", "Unknown_Parameter_488"], True),
            489: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_11", "Unknown_Parameter_489"], True),
            490: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_10", "Unknown_Parameter_490"], True),
            491: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_11", "Unknown_Parameter_491"], True),
            492: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_10", "Unknown_Parameter_492"], True),
            493: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_11", "Unknown_Parameter_493"], True),
            494: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_10", "Unknown_Parameter_494"], True),
            495: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_11", "Unknown_Parameter_495"], True),
            496: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_12", "Unknown_Parameter_496"], True),
            497: TimeOfDay(["ID_Einst_SuBwTG_zeit_0_13", "Unknown_Parameter_497"], True),
            498: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_12", "Unknown_Parameter_498"], True),
            499: TimeOfDay(["ID_Einst_SuBwTG_zeit_1_13", "Unknown_Parameter_499"], True),
            500: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_12", "Unknown_Parameter_500"], True),
            501: TimeOfDay(["ID_Einst_SuBwTG_zeit_2_13", "Unknown_Parameter_501"], True),
            502: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_12", "Unknown_Parameter_502"], True),
            503: TimeOfDay(["ID_Einst_SuBwTG_zeit_3_13", "Unknown_Parameter_503"], True),
            504: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_12", "Unknown_Parameter_504"], True),
            505: TimeOfDay(["ID_Einst_SuBwTG_zeit_4_13", "Unknown_Parameter_505"], True),
            506: TimerProgram(["ID_Einst_SuZIP_akt", "Unknown_Parameter_506"], True),
            507: TimeOfDay(["ID_Einst_SuZIPWo_zeit_0_0", "Unknown_Parameter_507"], True),
            508: TimeOfDay(["ID_Einst_SuZIPWo_zeit_0_1", "Unknown_Parameter_508"], True),
            509: TimeOfDay(["ID_Einst_SuZIPWo_zeit_1_0", "Unknown_Parameter_509"], True),
            510: TimeOfDay(["ID_Einst_SuZIPWo_zeit_1_1", "Unknown_Parameter_510"], True),
            511: TimeOfDay(["ID_Einst_SuZIPWo_zeit_2_0", "Unknown_Parameter_511"], True),
            512: TimeOfDay(["ID_Einst_SuZIPWo_zeit_2_1", "Unknown_Parameter_512"], True),
            513: TimeOfDay(["ID_Einst_SuZIPWo_zeit_3_0", "Unknown_Parameter_513"], True),
            514: TimeOfDay(["ID_Einst_SuZIPWo_zeit_3_1", "Unknown_Parameter_514"], True),
            515: TimeOfDay(["ID_Einst_SuZIPWo_zeit_4_0", "Unknown_Parameter_515"], True),
            516: TimeOfDay(["ID_Einst_SuZIPWo_zeit_4_1", "Unknown_Parameter_516"], True),
            517: TimeOfDay(["ID_Einst_SuZIP25_zeit_0_0", "Unknown_Parameter_517"], True),
            518: TimeOfDay(["ID_Einst_SuZIP25_zeit_0_1", "Unknown_Parameter_518"], True),
            519: TimeOfDay(["ID_Einst_SuZIP25_zeit_1_0", "Unknown_Parameter_519"], True),
            520: TimeOfDay(["ID_Einst_SuZIP25_zeit_1_1", "Unknown_Parameter_520"], True),
            521: TimeOfDay(["ID_Einst_SuZIP25_zeit_2_0", "Unknown_Parameter_521"], True),
            522: TimeOfDay(["ID_Einst_SuZIP25_zeit_2_1", "Unknown_Parameter_522"], True),
            523: TimeOfDay(["ID_Einst_SuZIP25_zeit_3_0", "Unknown_Parameter_523"], True),
            524: TimeOfDay(["ID_Einst_SuZIP25_zeit_3_1", "Unknown_Parameter_524"], True),
            525: TimeOfDay(["ID_Einst_SuZIP25_zeit_4_0", "Unknown_Parameter_525"], True),
            526: TimeOfDay(["ID_Einst_SuZIP25_zeit_4_1", "Unknown_Parameter_526"], True),
            527: TimeOfDay(["ID_Einst_SuZIP25_zeit_0_2", "Unknown_Parameter_527"], True),
            528: TimeOfDay(["ID_Einst_SuZIP25_zeit_0_3", "Unknown_Parameter_528"], True),
            529: TimeOfDay(["ID_Einst_SuZIP25_zeit_1_2", "Unknown_Parameter_529"], True),
            530: TimeOfDay(["ID_Einst_SuZIP25_zeit_1_3", "Unknown_Parameter_530"], True),
            531: TimeOfDay(["ID_Einst_SuZIP25_zeit_2_2", "Unknown_Parameter_531"], True),
            532: TimeOfDay(["ID_Einst_SuZIP25_zeit_2_3", "Unknown_Parameter_532"], True),
            533: TimeOfDay(["ID_Einst_SuZIP25_zeit_3_2", "Unknown_Parameter_533"], True),
            534: TimeOfDay(["ID_Einst_SuZIP25_zeit_3_3", "Unknown_Parameter_534"], True),
            535: TimeOfDay(["ID_Einst_SuZIP25_zeit_4_2", "Unknown_Parameter_535"], True),
            536: TimeOfDay(["ID_Einst_SuZIP25_zeit_4_3", "Unknown_Parameter_536"], True),
            537: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_0", "Unknown_Parameter_537"], True),
            538: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_1", "Unknown_Parameter_538"], True),
            539: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_0", "Unknown_Parameter_539"], True),
            540: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_1", "Unknown_Parameter_540"], True),
            541: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_0", "Unknown_Parameter_541"], True),
            542: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_1", "Unknown_Parameter_542"], True),
            543: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_0", "Unknown_Parameter_543"], True),
            544: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_1", "Unknown_Parameter_544"], True),
            545: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_0", "Unknown_Parameter_545"], True),
            546: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_1", "Unknown_Parameter_546"], True),
            547: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_2", "Unknown_Parameter_547"], True),
            548: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_3", "Unknown_Parameter_548"], True),
            549: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_2", "Unknown_Parameter_549"], True),
            550: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_3", "Unknown_Parameter_550"], True),
            551: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_2", "Unknown_Parameter_551"], True),
            552: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_3", "Unknown_Parameter_552"], True),
            553: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_2", "Unknown_Parameter_553"], True),
            554: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_3", "Unknown_Parameter_554"], True),
            555: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_2", "Unknown_Parameter_555"], True),
            556: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_3", "Unknown_Parameter_556"], True),
            557: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_4", "Unknown_Parameter_557"], True),
            558: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_5", "Unknown_Parameter_558"], True),
            559: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_4", "Unknown_Parameter_559"], True),
            560: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_5", "Unknown_Parameter_560"], True),
            561: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_4", "Unknown_Parameter_561"], True),
            562: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_5", "Unknown_Parameter_562"], True),
            563: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_4", "Unknown_Parameter_563"], True),
            564: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_5", "Unknown_Parameter_564"], True),
            565: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_4", "Unknown_Parameter_565"], True),
            566: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_5", "Unknown_Parameter_566"], True),
            567: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_6", "Unknown_Parameter_567"], True),
            568: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_7", "Unknown_Parameter_568"], True),
            569: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_6", "Unknown_Parameter_569"], True),
            570: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_7", "Unknown_Parameter_570"], True),
            571: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_6", "Unknown_Parameter_571"], True),
            572: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_7", "Unknown_Parameter_572"], True),
            573: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_6", "Unknown_Parameter_573"], True),
            574: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_7", "Unknown_Parameter_574"], True),
            575: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_6", "Unknown_Parameter_575"], True),
            576: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_7", "Unknown_Parameter_576"], True),
            577: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_8", "Unknown_Parameter_577"], True),
            578: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_9", "Unknown_Parameter_578"], True),
            579: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_8", "Unknown_Parameter_579"], True),
            580: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_9", "Unknown_Parameter_580"], True),
            581: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_8", "Unknown_Parameter_581"], True),
            582: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_9", "Unknown_Parameter_582"], True),
            583: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_8", "Unknown_Parameter_583"], True),
            584: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_9", "Unknown_Parameter_584"], True),
            585: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_8", "Unknown_Parameter_585"], True),
            586: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_9", "Unknown_Parameter_586"], True),
            587: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_10", "Unknown_Parameter_587"], True),
            588: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_11", "Unknown_Parameter_588"], True),
            589: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_10", "Unknown_Parameter_589"], True),
            590: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_11", "Unknown_Parameter_590"], True),
            591: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_10", "Unknown_Parameter_591"], True),
            592: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_11", "Unknown_Parameter_592"], True),
            593: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_10", "Unknown_Parameter_593"], True),
            594: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_11", "Unknown_Parameter_594"], True),
            595: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_10", "Unknown_Parameter_595"], True),
            596: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_11", "Unknown_Parameter_596"], True),
            597: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_12", "Unknown_Parameter_597"], True),
            598: TimeOfDay(["ID_Einst_SuZIPTg_zeit_0_13", "Unknown_Parameter_598"], True),
            599: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_12", "Unknown_Parameter_599"], True),
            600: TimeOfDay(["ID_Einst_SuZIPTg_zeit_1_13", "Unknown_Parameter_600"], True),
            601: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_12", "Unknown_Parameter_601"], True),
            602: TimeOfDay(["ID_Einst_SuZIPTg_zeit_2_13", "Unknown_Parameter_602"], True),
            603: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_12", "Unknown_Parameter_603"], True),
            604: TimeOfDay(["ID_Einst_SuZIPTg_zeit_3_13", "Unknown_Parameter_604"], True),
            605: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_12", "Unknown_Parameter_605"], True),
            606: TimeOfDay(["ID_Einst_SuZIPTg_zeit_4_13", "Unknown_Parameter_606"], True),
            607: TimerProgram(["ID_Einst_SuSwb_akt", "Unknown_Parameter_607"]),
            608: TimeOfDay(["ID_Einst_SuSwbWo_zeit_0_0", "Unknown_Parameter_608"]),
            609: TimeOfDay(["ID_Einst_SuSwbWo_zeit_0_1", "Unknown_Parameter_609"]),
            610: TimeOfDay(["ID_Einst_SuSwbWo_zeit_1_0", "Unknown_Parameter_610"]),
            611: TimeOfDay(["ID_Einst_SuSwbWo_zeit_1_1", "Unknown_Parameter_611"]),
            612: TimeOfDay(["ID_Einst_SuSwbWo_zeit_2_0", "Unknown_Parameter_612"]),
            613: TimeOfDay(["ID_Einst_SuSwbWo_zeit_2_1", "Unknown_Parameter_613"]),
            614: TimeOfDay(["ID_Einst_SuSwb25_zeit_0_0", "Unknown_Parameter_614"]),
            615: TimeOfDay(["ID_Einst_SuSwb25_zeit_0_1", "Unknown_Parameter_615"]),
            616: TimeOfDay(["ID_Einst_SuSwb25_zeit_1_0", "Unknown_Parameter_616"]),
            617: TimeOfDay(["ID_Einst_SuSwb25_zeit_1_1", "Unknown_Parameter_617"]),
            618: TimeOfDay(["ID_Einst_SuSwb25_zeit_2_0", "Unknown_Parameter_618"]),
            619: TimeOfDay(["ID_Einst_SuSwb25_zeit_2_1", "Unknown_Parameter_619"]),
            620: TimeOfDay(["ID_Einst_SuSwb25_zeit_0_2", "Unknown_Parameter_620"]),
            621: TimeOfDay(["ID_Einst_SuSwb25_zeit_0_3", "Unknown_Parameter_621"]),
            622: TimeOfDay(["ID_Einst_SuSwb25_zeit_1_2", "Unknown_Parameter_622"]),
            623: TimeOfDay(["ID_Einst_SuSwb25_zeit_1_3", "Unknown_Parameter_623"]),
            624: TimeOfDay(["ID_Einst_SuSwb25_zeit_2_2", "Unknown_Parameter_624"]),
            625: TimeOfDay(["ID_Einst_SuSwb25_zeit_2_3", "Unknown_Parameter_625"]),
            626: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_0", "Unknown_Parameter_626"]),
            627: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_1", "Unknown_Parameter_627"]),
            628: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_0", "Unknown_Parameter_628"]),
            629: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_1", "Unknown_Parameter_629"]),
            630: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_0", "Unknown_Parameter_630"]),
            631: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_1", "Unknown_Parameter_631"]),
            632: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_2", "Unknown_Parameter_632"]),
            633: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_3", "Unknown_Parameter_633"]),
            634: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_2", "Unknown_Parameter_634"]),
            635: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_3", "Unknown_Parameter_635"]),
            636: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_2", "Unknown_Parameter_636"]),
            637: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_3", "Unknown_Parameter_637"]),
            638: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_4", "Unknown_Parameter_638"]),
            639: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_5", "Unknown_Parameter_639"]),
            640: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_4", "Unknown_Parameter_640"]),
            641: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_5", "Unknown_Parameter_641"]),
            642: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_4", "Unknown_Parameter_642"]),
            643: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_5", "Unknown_Parameter_643"]),
            644: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_6", "Unknown_Parameter_644"]),
            645: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_7", "Unknown_Parameter_645"]),
            646: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_6", "Unknown_Parameter_646"]),
            647: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_7", "Unknown_Parameter_647"]),
            648: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_6", "Unknown_Parameter_648"]),
            649: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_7", "Unknown_Parameter_649"]),
            650: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_8", "Unknown_Parameter_650"]),
            651: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_9", "Unknown_Parameter_651"]),
            652: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_8", "Unknown_Parameter_652"]),
            653: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_9", "Unknown_Parameter_653"]),
            654: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_8", "Unknown_Parameter_654"]),
            655: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_9", "Unknown_Parameter_655"]),
            656: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_10", "Unknown_Parameter_656"]),
            657: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_11", "Unknown_Parameter_657"]),
            658: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_10", "Unknown_Parameter_658"]),
            659: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_11", "Unknown_Parameter_659"]),
            660: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_10", "Unknown_Parameter_660"]),
            661: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_11", "Unknown_Parameter_661"]),
            662: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_12", "Unknown_Parameter_662"]),
            663: TimeOfDay(["ID_Einst_SuSwbTg_zeit_0_13", "Unknown_Parameter_663"]),
            664: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_12", "Unknown_Parameter_664"]),
            665: TimeOfDay(["ID_Einst_SuSwbTg_zeit_1_13", "Unknown_Parameter_665"]),
            666: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_12", "Unknown_Parameter_666"]),
            667: TimeOfDay(["ID_Einst_SuSwbTg_zeit_2_13", "Unknown_Parameter_667"]),
            668: Seconds(["ID_Zaehler_BetrZeitWP", "Unknown_Parameter_668"]),
            669: Seconds(["ID_Zaehler_BetrZeitVD1", "Unknown_Parameter_669"]),
            670: Seconds(["ID_Zaehler_BetrZeitVD2", "Unknown_Parameter_670"]),
            671: Seconds(["ID_Zaehler_BetrZeitZWE1", "Unknown_Parameter_671"]),
            672: Seconds(["ID_Zaehler_BetrZeitZWE2", "Unknown_Parameter_672"]),
            673: Seconds(["ID_Zaehler_BetrZeitZWE3", "Unknown_Parameter_673"]),
            674: Count(["ID_Zaehler_BetrZeitImpVD1", "Unknown_Parameter_674"]),
            675: Count(["ID_Zaehler_BetrZeitImpVD2", "Unknown_Parameter_675"]),
            676: Unknown(["ID_Zaehler_BetrZeitEZMVD1", "Unknown_Parameter_676"]),
            677: Unknown(["ID_Zaehler_BetrZeitEZMVD2", "Unknown_Parameter_677"]),
            678: Unknown(["ID_Einst_Entl_Typ_0", "Unknown_Parameter_678"]),
            679: Unknown(["ID_Einst_Entl_Typ_1", "Unknown_Parameter_679"]),
            680: Unknown(["ID_Einst_Entl_Typ_2", "Unknown_Parameter_680"]),
            681: Unknown(["ID_Einst_Entl_Typ_3", "Unknown_Parameter_681"]),
            682: Unknown(["ID_Einst_Entl_Typ_4", "Unknown_Parameter_682"]),
            683: Unknown(["ID_Einst_Entl_Typ_5", "Unknown_Parameter_683"]),
            684: Unknown(["ID_Einst_Entl_Typ_6", "Unknown_Parameter_684"]),
            685: Unknown(["ID_Einst_Entl_Typ_7", "Unknown_Parameter_685"]),
            686: Unknown(["ID_Einst_Entl_Typ_8", "Unknown_Parameter_686"]),
            687: Unknown(["ID_Einst_Entl_Typ_9", "Unknown_Parameter_687"]),
            688: Unknown(["ID_Einst_Entl_Typ_10", "Unknown_Parameter_688"]),
            689: Unknown(["ID_Einst_Entl_Typ_11", "Unknown_Parameter_689"]),
            690: Unknown(["ID_Einst_Entl_Typ_12", "Unknown_Parameter_690"]),
            691: Unknown(["ID_Einst_Vorl_max_MK1", "Unknown_Parameter_691"]),
            692: Unknown(["ID_Einst_Vorl_max_MK2", "Unknown_Parameter_692"]),
            693: Unknown(["ID_SU_FrkdMK1", "Unknown_Parameter_693"]),
            694: Unknown(["ID_SU_FrkdMK2", "Unknown_Parameter_694"]),
            695: MixedCircuitMode(["ID_Ba_Hz_MK1_akt", "Unknown_Parameter_695"]),
            696: MixedCircuitMode(["ID_Ba_Hz_MK2_akt", "Unknown_Parameter_696"]),
            697: Unknown(["ID_Einst_Zirk_Ein_akt", "Unknown_Parameter_697"]),
            698: Unknown(["ID_Einst_Zirk_Aus_akt", "Unknown_Parameter_698"]),
            699: Unknown(["ID_Einst_Heizgrenze", "Unknown_Parameter_699"]),
            700: Celsius(["ID_Einst_Heizgrenze_Temp", "Unknown_Parameter_700"]),
            701: Unknown(["ID_VariablenIBNgespeichert", "Unknown_Parameter_701"]),
            702: Unknown(["ID_SchonIBNAssistant", "Unknown_Parameter_702"]),
            703: Unknown(["ID_Heizgrenze_0", "Unknown_Parameter_703"]),
            704: Unknown(["ID_Heizgrenze_1", "Unknown_Parameter_704"]),
            705: Unknown(["ID_Heizgrenze_2", "Unknown_Parameter_705"]),
            706: Unknown(["ID_Heizgrenze_3", "Unknown_Parameter_706"]),
            707: Unknown(["ID_Heizgrenze_4", "Unknown_Parameter_707"]),
            708: Unknown(["ID_Heizgrenze_5", "Unknown_Parameter_708"]),
            709: Unknown(["ID_Heizgrenze_6", "Unknown_Parameter_709"]),
            710: Unknown(["ID_Heizgrenze_7", "Unknown_Parameter_710"]),
            711: Unknown(["ID_Heizgrenze_8", "Unknown_Parameter_711"]),
            712: Unknown(["ID_Heizgrenze_9", "Unknown_Parameter_712"]),
            713: Unknown(["ID_Heizgrenze_10", "Unknown_Parameter_713"]),
            714: Unknown(["ID_Heizgrenze_11", "Unknown_Parameter_714"]),
            715: Unknown(["ID_SchemenIBNgewahlt", "Unknown_Parameter_715"]),
            716: Unknown(["ID_Switchoff_file_0_0", "Unknown_Parameter_716"]),
            717: Unknown(["ID_Switchoff_file_1_0", "Unknown_Parameter_717"]),
            718: Unknown(["ID_Switchoff_file_2_0", "Unknown_Parameter_718"]),
            719: Unknown(["ID_Switchoff_file_3_0", "Unknown_Parameter_719"]),
            720: Unknown(["ID_Switchoff_file_4_0", "Unknown_Parameter_720"]),
            721: Unknown(["ID_Switchoff_file_0_1", "Unknown_Parameter_721"]),
            722: Unknown(["ID_Switchoff_file_1_1", "Unknown_Parameter_722"]),
            723: Unknown(["ID_Switchoff_file_2_1", "Unknown_Parameter_723"]),
            724: Unknown(["ID_Switchoff_file_3_1", "Unknown_Parameter_724"]),
            725: Unknown(["ID_Switchoff_file_4_1", "Unknown_Parameter_725"]),
            726: Unknown(["ID_DauerDatenLoggerAktiv", "Unknown_Parameter_726"]),
            727: Unknown(["ID_Laufvar_Heizgrenze", "Unknown_Parameter_727"]),
            728: Seconds(["ID_Zaehler_BetrZeitHz", "Unknown_Parameter_728"]),
            729: Seconds(["ID_Zaehler_BetrZeitBW", "Unknown_Parameter_729"]),
            730: Seconds(["ID_Zaehler_BetrZeitKue", "Unknown_Parameter_730"]),
            731: Unknown(["ID_SU_FstdHz", "Unknown_Parameter_731"]),
            732: Unknown(["ID_SU_FstdBw", "Unknown_Parameter_732"]),
            733: Unknown(["ID_SU_FstdSwb", "Unknown_Parameter_733"]),
            734: Unknown(["ID_SU_FstdMK1", "Unknown_Parameter_734"]),
            735: Unknown(["ID_SU_FstdMK2", "Unknown_Parameter_735"]),
            736: Unknown(["ID_FerienAbsenkungHz", "Unknown_Parameter_736"]),
            737: Unknown(["ID_FerienAbsenkungMK1", "Unknown_Parameter_737"]),
            738: Unknown(["ID_FerienAbsenkungMK2", "Unknown_Parameter_738"]),
            739: Unknown(["ID_FerienModusAktivHz", "Unknown_Parameter_739"]),
            740: Unknown(["ID_FerienModusAktivBw", "Unknown_Parameter_740"]),
            741: Unknown(["ID_FerienModusAktivSwb", "Unknown_Parameter_741"]),
            742: Unknown(["ID_FerienModusAktivMk1", "Unknown_Parameter_742"]),
            743: Unknown(["ID_FerienModusAktivMk2", "Unknown_Parameter_743"]),
            744: Unknown(["ID_DisplayContrast_akt", "Unknown_Parameter_744"]),
            745: Unknown(["ID_Ba_Hz_saved", "Unknown_Parameter_745"]),
            746: Unknown(["ID_Ba_Bw_saved", "Unknown_Parameter_746"]),
            747: Unknown(["ID_Ba_Sw_saved", "Unknown_Parameter_747"]),
            748: Unknown(["ID_Ba_Hz_MK1_saved", "Unknown_Parameter_748"]),
            749: Unknown(["ID_Ba_Hz_MK2_saved", "Unknown_Parameter_749"]),
            750: Unknown(["ID_AdresseIP_akt", "Unknown_Parameter_750"]),
            751: Unknown(["ID_SubNetMask_akt", "Unknown_Parameter_751"]),
            752: Unknown(["ID_Add_Broadcast_akt", "Unknown_Parameter_752"]),
            753: Unknown(["ID_Add_StdGateway_akt", "Unknown_Parameter_753"]),
            754: Unknown(["ID_DHCPServerAktiv_akt", "Unknown_Parameter_754"]),
            755: Unknown(["ID_WebserverPasswort_1_akt", "Unknown_Parameter_755"]),
            756: Unknown(["ID_WebserverPasswort_2_akt", "Unknown_Parameter_756"]),
            757: Unknown(["ID_WebserverPasswort_3_akt", "Unknown_Parameter_757"]),
            758: Unknown(["ID_WebserverPasswort_4_akt", "Unknown_Parameter_758"]),
            759: Unknown(["ID_WebserverPasswort_5_akt", "Unknown_Parameter_759"]),
            760: Unknown(["ID_WebserverPasswort_6_akt", "Unknown_Parameter_760"]),
            761: Unknown(["ID_WebServerWerteBekommen", "Unknown_Parameter_761"]),
            762: Unknown(["ID_Einst_ParBetr_akt", "Unknown_Parameter_762"]),
            763: Unknown(["ID_Einst_WpAnz_akt", "Unknown_Parameter_763"]),
            764: Unknown(["ID_Einst_PhrTime_akt", "Unknown_Parameter_764"]),
            765: Unknown(["ID_Einst_HysPar_akt", "Unknown_Parameter_765"]),
            766: Unknown(["ID_IP_PB_Slave_0", "Unknown_Parameter_766"]),
            767: Unknown(["ID_IP_PB_Slave_1", "Unknown_Parameter_767"]),
            768: Unknown(["ID_IP_PB_Slave_2", "Unknown_Parameter_768"]),
            769: Unknown(["ID_IP_PB_Slave_3", "Unknown_Parameter_769"]),
            770: Unknown(["ID_IP_PB_Slave_4", "Unknown_Parameter_770"]),
            771: Unknown(["ID_IP_PB_Slave_5", "Unknown_Parameter_771"]),
            772: Unknown(["ID_Einst_BwHup_akt_backup", "Unknown_Parameter_772"]),
            773: Unknown(["ID_Einst_SuMk3_akt", "Unknown_Parameter_773"]),
            774: Celsius(["ID_Einst_HzMK3E_akt", "Unknown_Parameter_774"], True),
            775: Celsius(["ID_Einst_HzMK3ANH_akt", "Unknown_Parameter_775"], True),
            776: Celsius(["ID_Einst_HzMK3ABS_akt", "Unknown_Parameter_776"], True),
            777: Unknown(["ID_Einst_HzMK3Hgr_akt", "Unknown_Parameter_777"]),
            778: Unknown(["ID_Einst_HzFtMK3Vl_akt", "Unknown_Parameter_778"]),
            779: MixedCircuitMode(["ID_Ba_Hz_MK3_akt", "Unknown_Parameter_779"], True),
            780: Unknown(["ID_Einst_MK3Typ_akt", "Unknown_Parameter_780"]),
            781: Unknown(["ID_Einst_RTypMK3_akt", "Unknown_Parameter_781"]),
            782: Unknown(["ID_Einst_MK3LzFaktor_akt", "Unknown_Parameter_782"]),
            783: Unknown(["ID_Einst_MK3PerFaktor_akt", "Unknown_Parameter_783"]),
            784: Unknown(["ID_FerienModusAktivMk3", "Unknown_Parameter_784"]),
            785: Unknown(["ID_SU_FrkdMK3", "Unknown_Parameter_785"]),
            786: Unknown(["ID_FerienAbsenkungMK3", "Unknown_Parameter_786"]),
            787: Unknown(["ID_SU_FstdMK3", "Unknown_Parameter_787"]),
            788: TimerProgram(["ID_Einst_SuMk3_akt2", "Unknown_Parameter_788"]),
            789: TimeOfDay(["ID_Einst_SuMk3Wo_zeit_0_0", "Unknown_Parameter_789"]),
            790: TimeOfDay(["ID_Einst_SuMk3Wo_zeit_0_1", "Unknown_Parameter_790"]),
            791: TimeOfDay(["ID_Einst_SuMk3Wo_zeit_1_0", "Unknown_Parameter_791"]),
            792: TimeOfDay(["ID_Einst_SuMk3Wo_zeit_1_1", "Unknown_Parameter_792"]),
            793: TimeOfDay(["ID_Einst_SuMk3Wo_zeit_2_0", "Unknown_Parameter_793"]),
            794: TimeOfDay(["ID_Einst_SuMk3Wo_zeit_2_1", "Unknown_Parameter_794"]),
            795: TimeOfDay(["ID_Einst_SuMk325_zeit_0_0", "Unknown_Parameter_795"]),
            796: TimeOfDay(["ID_Einst_SuMk325_zeit_0_1", "Unknown_Parameter_796"]),
            797: TimeOfDay(["ID_Einst_SuMk325_zeit_1_0", "Unknown_Parameter_797"]),
            798: TimeOfDay(["ID_Einst_SuMk325_zeit_1_1", "Unknown_Parameter_798"]),
            799: TimeOfDay(["ID_Einst_SuMk325_zeit_2_0", "Unknown_Parameter_799"]),
            800: TimeOfDay(["ID_Einst_SuMk325_zeit_2_1", "Unknown_Parameter_800"]),
            801: TimeOfDay(["ID_Einst_SuMk325_zeit_0_2", "Unknown_Parameter_801"]),
            802: TimeOfDay(["ID_Einst_SuMk325_zeit_0_3", "Unknown_Parameter_802"]),
            803: TimeOfDay(["ID_Einst_SuMk325_zeit_1_2", "Unknown_Parameter_803"]),
            804: TimeOfDay(["ID_Einst_SuMk325_zeit_1_3", "Unknown_Parameter_804"]),
            805: TimeOfDay(["ID_Einst_SuMk325_zeit_2_2", "Unknown_Parameter_805"]),
            806: TimeOfDay(["ID_Einst_SuMk325_zeit_2_3", "Unknown_Parameter_806"]),
            807: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_0", "Unknown_Parameter_807"]),
            808: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_1", "Unknown_Parameter_808"]),
            809: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_0", "Unknown_Parameter_809"]),
            810: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_1", "Unknown_Parameter_810"]),
            811: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_0", "Unknown_Parameter_811"]),
            812: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_1", "Unknown_Parameter_812"]),
            813: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_2", "Unknown_Parameter_813"]),
            814: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_3", "Unknown_Parameter_814"]),
            815: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_2", "Unknown_Parameter_815"]),
            816: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_3", "Unknown_Parameter_816"]),
            817: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_2", "Unknown_Parameter_817"]),
            818: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_3", "Unknown_Parameter_818"]),
            819: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_4", "Unknown_Parameter_819"]),
            820: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_5", "Unknown_Parameter_820"]),
            821: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_4", "Unknown_Parameter_821"]),
            822: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_5", "Unknown_Parameter_822"]),
            823: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_4", "Unknown_Parameter_823"]),
            824: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_5", "Unknown_Parameter_824"]),
            825: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_6", "Unknown_Parameter_825"]),
            826: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_7", "Unknown_Parameter_826"]),
            827: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_6", "Unknown_Parameter_827"]),
            828: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_7", "Unknown_Parameter_828"]),
            829: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_6", "Unknown_Parameter_829"]),
            830: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_7", "Unknown_Parameter_830"]),
            831: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_8", "Unknown_Parameter_831"]),
            832: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_9", "Unknown_Parameter_832"]),
            833: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_8", "Unknown_Parameter_833"]),
            834: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_9", "Unknown_Parameter_834"]),
            835: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_8", "Unknown_Parameter_835"]),
            836: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_9", "Unknown_Parameter_836"]),
            837: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_10", "Unknown_Parameter_837"]),
            838: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_11", "Unknown_Parameter_838"]),
            839: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_10", "Unknown_Parameter_839"]),
            840: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_11", "Unknown_Parameter_840"]),
            841: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_10", "Unknown_Parameter_841"]),
            842: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_11", "Unknown_Parameter_842"]),
            843: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_12", "Unknown_Parameter_843"]),
            844: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_0_13", "Unknown_Parameter_844"]),
            845: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_12", "Unknown_Parameter_845"]),
            846: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_1_13", "Unknown_Parameter_846"]),
            847: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_12", "Unknown_Parameter_847"]),
            848: TimeOfDay(["ID_Einst_SuMk3Tg_zeit_2_13", "Unknown_Parameter_848"]),
            849: Unknown(["ID_Ba_Hz_MK3_saved", "Unknown_Parameter_849"]),
            850: Hours(["ID_Einst_Kuhl_Zeit_Ein_akt", "Unknown_Parameter_850"], True),
            851: Hours(["ID_Einst_Kuhl_Zeit_Aus_akt", "Unknown_Parameter_851"], True),
            852: Energy(["ID_Waermemenge_Seit", "Unknown_Parameter_852"]),
            853: Unknown(["ID_Waermemenge_WQ", "Unknown_Parameter_853"]),
            854: Energy(["ID_Waermemenge_Hz", "Unknown_Parameter_854"]),
            855: Unknown(["ID_Waermemenge_WQ_ges", "Unknown_Parameter_855"]),
            856: Unknown(["ID_Einst_Entl_Typ_13", "Unknown_Parameter_856"]),
            857: Unknown(["ID_Einst_Entl_Typ_14", "Unknown_Parameter_857"]),
            858: Unknown(["ID_Einst_Entl_Typ_15", "Unknown_Parameter_858"]),
            859: Seconds(["ID_Zaehler_BetrZeitSW", "Unknown_Parameter_859"]),
            860: Unknown(["ID_Einst_Fernwartung_akt", "Unknown_Parameter_860"]),
            861: Unknown(["ID_AdresseIPServ_akt", "Unknown_Parameter_861"]),
            862: Unknown(["ID_Einst_TA_EG_akt", "Unknown_Parameter_862"]),
            863: Unknown(["ID_Einst_TVLmax_EG_akt", "Unknown_Parameter_863"]),
            864: Minutes(["ID_Einst_Popt_Nachlauf_akt", "Unknown_Parameter_864"], True),
            865: Unknown(["ID_FernwartungVertrag_akt", "Unknown_Parameter_865"]),
            866: Unknown(["ID_FernwartungAktuZeit", "Unknown_Parameter_866"]),
            867: Unknown(["ID_Einst_Effizienzpumpe_Nominal_akt", "Unknown_Parameter_867"]),
            868: Unknown(["ID_Einst_Effizienzpumpe_Minimal_akt", "Unknown_Parameter_868"]),
            869: Unknown(["ID_Einst_Effizienzpumpe_akt", "Unknown_Parameter_869"]),
            870: Unknown(["ID_Einst_Waermemenge_akt", "Unknown_Parameter_870"]),
            871: Unknown(["ID_Einst_Wm_Versorgung_Korrektur_akt", "Unknown_Parameter_871"]),
            872: Unknown(["ID_Einst_Wm_Auswertung_Korrektur_akt", "Unknown_Parameter_872"]),
            873: Unknown(["ID_SoftwareUpdateJetztGemacht_akt", "Unknown_Parameter_873"]),
            874: Unknown(["ID_WP_SerienNummer_DATUM", "Unknown_Parameter_874"]),
            875: Unknown(["ID_WP_SerienNummer_HEX", "Unknown_Parameter_875"]),
            876: Unknown(["ID_WP_SerienNummer_INDEX", "Unknown_Parameter_876"]),
            877: Unknown(["ID_ProgWerteWebSrvBeobarten", "Unknown_Parameter_877"]),
            878: Energy(["ID_Waermemenge_BW", "Unknown_Parameter_878"]),
            879: Energy(["ID_Waermemenge_SW", "Unknown_Parameter_879"]),
            880: Timestamp(["ID_Waermemenge_Datum", "Unknown_Parameter_880"]),
            881: SolarMode(["ID_Einst_Solar_akt", "Unknown_Parameter_881"], True),
            882: Unknown(["ID_BSTD_Solar", "Unknown_Parameter_882"]),
            883: Celsius(["ID_Einst_TDC_Koll_Max_akt", "Unknown_Parameter_883"]),
            884: Unknown(["ID_Einst_Akt_Kuehlung_akt", "Unknown_Parameter_884"]),
            885: Unknown(["ID_Einst_Vorlauf_VBO_akt", "Unknown_Parameter_885"]),
            886: Unknown(["ID_Einst_KRHyst_akt", "Unknown_Parameter_886"]),
            887: Unknown(["ID_Einst_Akt_Kuehl_Speicher_min_akt", "Unknown_Parameter_887"]),
            888: Unknown(["ID_Einst_Akt_Kuehl_Freig_WQE_akt", "Unknown_Parameter_888"]),
            889: Unknown(["ID_NDAB_WW_Anzahl", "Unknown_Parameter_889"]),
            890: Unknown(["ID_NDS_WW_KD_Quitt", "Unknown_Parameter_890"]),
            891: Unknown(["ID_Einst_AbtZykMin_akt", "Unknown_Parameter_891"]),
            892: Unknown(["ID_Einst_VD2_Zeit_Min_akt", "Unknown_Parameter_892"]),
            893: Unknown(["ID_Einst_Hysterese_HR_verkuerzt_akt", "Unknown_Parameter_893"]),
            894: VentilationMode(["ID_Einst_BA_Lueftung_akt", "Unknown_Parameter_894"], True),
            895: TimerProgram(["ID_Einst_SuLuf_akt", "Unknown_Parameter_895"]),
            896: TimeOfDay2(["ID_Einst_SuLufWo_zeit_0_0_0", "Unknown_Parameter_896"]),
            897: TimeOfDay2(["ID_Einst_SuLufWo_zeit_0_1_0", "Unknown_Parameter_897"]),
            898: TimeOfDay2(["ID_Einst_SuLufWo_zeit_0_2_0", "Unknown_Parameter_898"]),
            899: TimeOfDay2(["ID_Einst_SuLuf25_zeit_0_0_0", "Unknown_Parameter_899"]),
            900: TimeOfDay2(["ID_Einst_SuLuf25_zeit_0_1_0", "Unknown_Parameter_900"]),
            901: TimeOfDay2(["ID_Einst_SuLuf25_zeit_0_2_0", "Unknown_Parameter_901"]),
            902: TimeOfDay2(["ID_Einst_SuLuf25_zeit_0_0_2", "Unknown_Parameter_902"]),
            903: TimeOfDay2(["ID_Einst_SuLuf25_zeit_0_1_2", "Unknown_Parameter_903"]),
            904: TimeOfDay2(["ID_Einst_SuLuf25_zeit_0_2_2", "Unknown_Parameter_904"]),
            905: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_0_0", "Unknown_Parameter_905"]),
            906: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_1_0", "Unknown_Parameter_906"]),
            907: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_2_0", "Unknown_Parameter_907"]),
            908: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_0_2", "Unknown_Parameter_908"]),
            909: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_1_2", "Unknown_Parameter_909"]),
            910: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_2_2", "Unknown_Parameter_910"]),
            911: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_0_4", "Unknown_Parameter_911"]),
            912: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_1_4", "Unknown_Parameter_912"]),
            913: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_2_4", "Unknown_Parameter_913"]),
            914: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_0_6", "Unknown_Parameter_914"]),
            915: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_1_6", "Unknown_Parameter_915"]),
            916: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_2_6", "Unknown_Parameter_916"]),
            917: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_0_8", "Unknown_Parameter_917"]),
            918: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_1_8", "Unknown_Parameter_918"]),
            919: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_2_8", "Unknown_Parameter_919"]),
            920: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_0_10", "Unknown_Parameter_920"]),
            921: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_1_10", "Unknown_Parameter_921"]),
            922: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_2_10", "Unknown_Parameter_922"]),
            923: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_0_12", "Unknown_Parameter_923"]),
            924: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_1_12", "Unknown_Parameter_924"]),
            925: TimeOfDay2(["ID_Einst_SuLufTg_zeit_0_2_12", "Unknown_Parameter_925"]),
            926: TimeOfDay2(["ID_Einst_SuLufWo_zeit_1_0_0", "Unknown_Parameter_926"]),
            927: TimeOfDay2(["ID_Einst_SuLufWo_zeit_1_1_0", "Unknown_Parameter_927"]),
            928: TimeOfDay2(["ID_Einst_SuLufWo_zeit_1_2_0", "Unknown_Parameter_928"]),
            929: TimeOfDay2(["ID_Einst_SuLuf25_zeit_1_0_0", "Unknown_Parameter_929"]),
            930: TimeOfDay2(["ID_Einst_SuLuf25_zeit_1_1_0", "Unknown_Parameter_930"]),
            931: TimeOfDay2(["ID_Einst_SuLuf25_zeit_1_2_0", "Unknown_Parameter_931"]),
            932: TimeOfDay2(["ID_Einst_SuLuf25_zeit_1_0_2", "Unknown_Parameter_932"]),
            933: TimeOfDay2(["ID_Einst_SuLuf25_zeit_1_1_2", "Unknown_Parameter_933"]),
            934: TimeOfDay2(["ID_Einst_SuLuf25_zeit_1_2_2", "Unknown_Parameter_934"]),
            935: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_0_0", "Unknown_Parameter_935"]),
            936: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_1_0", "Unknown_Parameter_936"]),
            937: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_2_0", "Unknown_Parameter_937"]),
            938: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_0_2", "Unknown_Parameter_938"]),
            939: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_1_2", "Unknown_Parameter_939"]),
            940: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_2_2", "Unknown_Parameter_940"]),
            941: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_0_4", "Unknown_Parameter_941"]),
            942: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_1_4", "Unknown_Parameter_942"]),
            943: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_2_4", "Unknown_Parameter_943"]),
            944: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_0_6", "Unknown_Parameter_944"]),
            945: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_1_6", "Unknown_Parameter_945"]),
            946: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_2_6", "Unknown_Parameter_946"]),
            947: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_0_8", "Unknown_Parameter_947"]),
            948: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_1_8", "Unknown_Parameter_948"]),
            949: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_2_8", "Unknown_Parameter_949"]),
            950: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_0_10", "Unknown_Parameter_950"]),
            951: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_1_10", "Unknown_Parameter_951"]),
            952: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_2_10", "Unknown_Parameter_952"]),
            953: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_0_12", "Unknown_Parameter_953"]),
            954: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_1_12", "Unknown_Parameter_954"]),
            955: TimeOfDay2(["ID_Einst_SuLufTg_zeit_1_2_12", "Unknown_Parameter_955"]),
            956: Unknown(["ID_FerienModusAktivLueftung", "Unknown_Parameter_956"]),
            957: Unknown(["ID_Einst_BA_Lueftung_saved", "Unknown_Parameter_957"]),
            958: Unknown(["ID_SU_FrkdLueftung", "Unknown_Parameter_958"]),
            959: Unknown(["ID_SU_FstdLueftung", "Unknown_Parameter_959"]),
            960: Unknown(["ID_Einst_Luf_Feuchteschutz_akt", "Unknown_Parameter_960"]),
            961: Unknown(["ID_Einst_Luf_Reduziert_akt", "Unknown_Parameter_961"]),
            962: Unknown(["ID_Einst_Luf_Nennlueftung_akt", "Unknown_Parameter_962"]),
            963: Unknown(["ID_Einst_Luf_Intensivlueftung_akt", "Unknown_Parameter_963"]),
            964: Unknown(["ID_Timer_Fil_4Makt", "Unknown_Parameter_964"]),
            965: Unknown(["ID_Timer_Fil_WoAkt", "Unknown_Parameter_965"]),
            966: Celsius(["ID_Sollwert_KuCft3_akt", "Unknown_Parameter_966"], True),
            967: Celsius(["ID_Sollwert_AtDif3_akt", "Unknown_Parameter_967"], True),
            968: Unknown(["ID_Bitmaske_0", "Unknown_Parameter_968"]),
            969: Unknown(["ID_Einst_Lueftungsstufen", "Unknown_Parameter_969"]),
            970: Unknown(["ID_SysEin_Meldung_TDI", "Unknown_Parameter_970"]),
            971: Unknown(["ID_SysEin_Typ_WZW", "Unknown_Parameter_971"]),
            972: Unknown(["ID_Einst_GLT_aktiviert", "Unknown_Parameter_972"]),
            973: Unknown(["ID_Einst_BW_max", "Unknown_Parameter_973"]),
            974: Unknown(["ID_Einst_Sollwert_TRL_Kuehlen", "Unknown_Parameter_974"]),
            975: Unknown(["ID_Einst_Medium_Waermequelle", "Unknown_Parameter_975"]),
            976: Unknown(["ID_Einst_Photovoltaik_akt", "Unknown_Parameter_976"]),
            977: Unknown(["ID_Einst_Multispeicher_akt", "Unknown_Parameter_977"]),
            978: Unknown(["ID_Einst_PKuehlTime_akt", "Unknown_Parameter_978"]),
            979: Celsius(["ID_Einst_Minimale_Ruecklaufsolltemperatur", "Unknown_Parameter_979"], True),
            980: Unknown(["ID_RBE_Einflussfaktor_RT_akt", "Unknown_Parameter_980"]),
            981: Unknown(["ID_RBE_Freigabe_Kuehlung_akt", "Unknown_Parameter_981"]),
            982: Unknown(["ID_RBE_Waermeverteilsystem_akt", "Unknown_Parameter_982"]),
            983: Unknown(["ID_RBE_Zeit_Heizstab_aktiv", "Unknown_Parameter_983"]),
            984: Unknown(["ID_SEC_ND_Alarmgrenze", "Unknown_Parameter_984"]),
            985: Unknown(["ID_SEC_HD_Alarmgrenze", "Unknown_Parameter_985"]),
            986: Unknown(["ID_SEC_Abtauendtemperatur", "Unknown_Parameter_986"]),
            987: Unknown(["ID_Einst_Min_RPM_BW", "Unknown_Parameter_987"]),
            988: Unknown(["ID_Einst_Luf_Feuchteschutz_Faktor_akt", "Unknown_Parameter_988"]),
            989: Unknown(["ID_Einst_Luf_Reduziert_Faktor_akt", "Unknown_Parameter_989"]),
            990: Unknown(["ID_Einst_Luf_Nennlueftung_Faktor_akt", "Unknown_Parameter_990"]),
            991: Unknown(["ID_Einst_Luf_Intensivlueftung_Faktor_akt", "Unknown_Parameter_991"]),
            992: Minutes(["ID_Einst_Freigabe_Zeit_ZWE", "Unknown_Parameter_992"], True),
            993: Unknown(["ID_Einst_min_VL_Kuehl", "Unknown_Parameter_993"]),
            994: Bool(["ID_Einst_Warmwasser_Nachheizung", "Unknown_Parameter_994"], True),
            995: Unknown(["ID_Switchoff_file_LWD2_0_0", "Unknown_Parameter_995"]),
            996: Unknown(["ID_Switchoff_file_LWD2_1_0", "Unknown_Parameter_996"]),
            997: Unknown(["ID_Switchoff_file_LWD2_2_0", "Unknown_Parameter_997"]),
            998: Unknown(["ID_Switchoff_file_LWD2_3_0", "Unknown_Parameter_998"]),
            999: Unknown(["ID_Switchoff_file_LWD2_4_0", "Unknown_Parameter_999"]),
            1000: Unknown(["ID_Switchoff_file_LWD2_0_1", "Unknown_Parameter_1000"]),
            1001: Unknown(["ID_Switchoff_file_LWD2_1_1", "Unknown_Parameter_1001"]),
            1002: Unknown(["ID_Switchoff_file_LWD2_2_1", "Unknown_Parameter_1002"]),
            1003: Unknown(["ID_Switchoff_file_LWD2_3_1", "Unknown_Parameter_1003"]),
            1004: Unknown(["ID_Switchoff_file_LWD2_4_1", "Unknown_Parameter_1004"]),
            1005: Unknown(["ID_Switchoff_index_LWD2", "Unknown_Parameter_1005"]),
            1006: Unknown(["ID_Einst_Effizienzpumpe_Nominal_2", "Unknown_Parameter_1006"]),
            1007: Unknown(["ID_Einst_Effizienzpumpe_Minimal_2", "Unknown_Parameter_1007"]),
            1008: Unknown(["ID_Einst_Wm_Versorgung_Korrektur_2", "Unknown_Parameter_1008"]),
            1009: Unknown(["ID_Einst_Wm_Auswertung_Korrektur_2", "Unknown_Parameter_1009"]),
            1010: Unknown(["ID_Einst_isTwin", "Unknown_Parameter_1010"]),
            1011: Unknown(["ID_Einst_TAmin_2", "Unknown_Parameter_1011"]),
            1012: Unknown(["ID_Einst_TVLmax_2", "Unknown_Parameter_1012"]),
            1013: Unknown(["ID_Einst_TA_EG_2", "Unknown_Parameter_1013"]),
            1014: Unknown(["ID_Einst_TVLmax_EG_2", "Unknown_Parameter_1014"]),
            1015: Unknown(["ID_Waermemenge_Hz_2", "Unknown_Parameter_1015"]),
            1016: Unknown(["ID_Waermemenge_BW_2", "Unknown_Parameter_1016"]),
            1017: Unknown(["ID_Waermemenge_SW_2", "Unknown_Parameter_1017"]),
            1018: Unknown(["ID_Waermemenge_Seit_2", "Unknown_Parameter_1018"]),
            1019: Unknown(["ID_Einst_Entl_Typ_15_2", "Unknown_Parameter_1019"]),
            1020: Hours2(["ID_Einst_WW_Nachheizung_max", "Unknown_Parameter_1020"], True),
            1021: Unknown(["ID_Einst_Kuhl_Zeit_Ein_RT", "Unknown_Parameter_1021"]),
            1022: Unknown(["ID_Einst_ZWE1_Pos", "Unknown_Parameter_1022"]),
            1023: Unknown(["ID_Einst_ZWE2_Pos", "Unknown_Parameter_1023"]),
            1024: Unknown(["ID_Einst_ZWE3_Pos", "Unknown_Parameter_1024"]),
            1025: Unknown(["ID_Einst_Leistung_ZWE", "Unknown_Parameter_1025"]),
            1026: Unknown(["ID_WP_SN2_DATUM", "Unknown_Parameter_1026"]),
            1027: Unknown(["ID_WP_SN2_HEX", "Unknown_Parameter_1027"]),
            1028: Unknown(["ID_WP_SN2_INDEX", "Unknown_Parameter_1028"]),
            1029: Unknown(["ID_CWP_saved2", "Unknown_Parameter_1029"]),
            1030: Unknown(["ID_Einst_SmartGrid", "Unknown_Parameter_1030"]),
            1031: Unknown(["ID_Einst_P155_HDS", "Unknown_Parameter_1031"]),
            1032: Unknown(["ID_Einst_P155_PumpHeat_Max", "Unknown_Parameter_1032"]),
            1033: Unknown(["ID_Einst_P155_PumpHeatCtrl", "Unknown_Parameter_1033"]),
            1034: Unknown(["ID_Einst_P155_PumpDHWCtrl", "Unknown_Parameter_1034"]),
            1035: Unknown(["ID_Einst_P155_PumpDHW_RPM", "Unknown_Parameter_1035"]),
            1036: Unknown(["ID_Einst_P155_PumpPoolCtrl", "Unknown_Parameter_1036"]),
            1037: Unknown(["ID_Einst_P155_PumpPool_RPM", "Unknown_Parameter_1037"]),
            1038: Unknown(["ID_Einst_P155_PumpCool_RPM", "Unknown_Parameter_1038"]),
            1039: Unknown(["ID_Einst_P155_PumpVBOCtrl", "Unknown_Parameter_1039"]),
            1040: Unknown(["ID_Einst_P155_PumpVBO_RPM_C", "Unknown_Parameter_1040"]),
            1041: Unknown(["ID_Einst_P155_PumpDHW_Max", "Unknown_Parameter_1041"]),
            1042: Unknown(["ID_Einst_P155_PumpPool_Max", "Unknown_Parameter_1042"]),
            1043: Unknown(["ID_Einst_P155_Sperrband_1", "Unknown_Parameter_1043"]),
            1044: Unknown(["ID_Einst_P155_Leistungsfreigabe", "Unknown_Parameter_1044"]),
            1045: Unknown(["ID_Einst_P155_DHW_Freq", "Unknown_Parameter_1045"]),
            1046: Unknown(["ID_Einst_SWHUP", "Unknown_Parameter_1046"]),
            1047: Unknown(["ID_Einst_P155_SWB_Freq", "Unknown_Parameter_1047"]),
            1048: Unknown(["ID_Einst_MK1_Regelung", "Unknown_Parameter_1048"]),
            1049: Unknown(["ID_Einst_MK2_Regelung", "Unknown_Parameter_1049"]),
            1050: Unknown(["ID_Einst_MK3_Regelung", "Unknown_Parameter_1050"]),
            1051: Unknown(["ID_Einst_PV_WW_Sperrzeit", "Unknown_Parameter_1051"]),
            1052: Unknown(["ID_Einst_Warmwasser_extra", "Unknown_Parameter_1052"]),
            1053: Unknown(["ID_Einst_Vorl_akt_Kuehl", "Unknown_Parameter_1053"]),
            1054: Unknown(["ID_WP_SN3_DATUM", "Unknown_Parameter_1054"]),
            1055: Unknown(["ID_WP_SN3_HEX", "Unknown_Parameter_1055"]),
            1056: Unknown(["ID_WP_SN3_INDEX", "Unknown_Parameter_1056"]),
            1057: Unknown(["ID_Einst_Vorlauf_ZUP", "Unknown_Parameter_1057"]),
            1058: Unknown(["ID_Einst_Abtauen_im_Warmwasser", "Unknown_Parameter_1058"]),
            1059: Energy(["ID_Waermemenge_ZWE", "Unknown_Parameter_1059"]),
            1060: Energy(["ID_Waermemenge_Reset", "Unknown_Parameter_1060"]),
            1061: Unknown(["ID_Waermemenge_Reset_2", "Unknown_Parameter_1061"]),
            1062: Unknown(["ID_Einst_Brunnenpumpe_min", "Unknown_Parameter_1062"]),
            1063: Unknown(["ID_Einst_Brunnenpumpe_max", "Unknown_Parameter_1063"]),
            1064: Unknown(["ID_Einst_SmartHomeID", "Unknown_Parameter_1064"]),
            1065: Unknown(["ID_Einst_SmartHK", "Unknown_Parameter_1065"]),
            1066: Unknown(["ID_Einst_SmartMK1", "Unknown_Parameter_1066"]),
            1067: Unknown(["ID_Einst_SmartMK2", "Unknown_Parameter_1067"]),
            1068: Unknown(["ID_Einst_SmartMK3", "Unknown_Parameter_1068"]),
            1069: Unknown(["ID_Einst_SmartWW", "Unknown_Parameter_1069"]),
            1070: Unknown(["ID_Einst_SmartDefrost", "Unknown_Parameter_1070"]),
            1071: Unknown(["ID_Einst_Empty1071", "Unknown_Parameter_1071"]),
            1072: Unknown(["ID_Einst_MinVLMK1", "Unknown_Parameter_1072"]),
            1073: Unknown(["ID_Einst_MinVLMK2", "Unknown_Parameter_1073"]),
            1074: Unknown(["ID_Einst_MinVLMK3", "Unknown_Parameter_1074"]),
            1075: Unknown(["ID_Einst_MaxVLMK1", "Unknown_Parameter_1075"]),
            1076: Unknown(["ID_Einst_MaxVLMK2", "Unknown_Parameter_1076"]),
            1077: Unknown(["ID_Einst_MaxVLMK3", "Unknown_Parameter_1077"]),
            1078: Unknown(["ID_Einst_SmartPlusHz", "Unknown_Parameter_1078"]),
            1079: Unknown(["ID_Einst_SmartMinusHz", "Unknown_Parameter_1079"]),
            1080: Unknown(["ID_Einst_SmartPlusMK1", "Unknown_Parameter_1080"]),
            1081: Unknown(["ID_Einst_SmartMinusMK1", "Unknown_Parameter_1081"]),
            1082: Unknown(["ID_Einst_SmartPlusMK2", "Unknown_Parameter_1082"]),
            1083: Unknown(["ID_Einst_SmartMinusMK2", "Unknown_Parameter_1083"]),
            1084: Unknown(["ID_Einst_SmartPlusMK3", "Unknown_Parameter_1084"]),
            1085: Unknown(["ID_Einst_SmartMinusMK3", "Unknown_Parameter_1085"]),
            1086: Unknown("Unknown_Parameter_1086"),
            1087: OnOffMode(["SILENT_MODE", "Unknown_Parameter_1087"]),
            1088: Unknown("Unknown_Parameter_1088"),
            1089: Unknown("Unknown_Parameter_1089"),
            1090: Unknown("Unknown_Parameter_1090"),
            1091: Unknown("Unknown_Parameter_1091"),
            1092: TimerProgram(["ID_Einst_SuSilence", "Unknown_Parameter_1092"]),
            1093: TimeOfDay2(["ID_Einst_SilenceTimer_0", "Unknown_Parameter_1093"]),
            1094: TimeOfDay2(["ID_Einst_SilenceTimer_1", "Unknown_Parameter_1094"]),
            1095: TimeOfDay2(["ID_Einst_SilenceTimer_2", "Unknown_Parameter_1095"]),
            1096: TimeOfDay2(["ID_Einst_SilenceTimer_3", "Unknown_Parameter_1096"]),
            1097: TimeOfDay2(["ID_Einst_SilenceTimer_4", "Unknown_Parameter_1097"]),
            1098: TimeOfDay2(["ID_Einst_SilenceTimer_5", "Unknown_Parameter_1098"]),
            1099: TimeOfDay2(["ID_Einst_SilenceTimer_6", "Unknown_Parameter_1099"]),
            1100: TimeOfDay2(["ID_Einst_SilenceTimer_7", "Unknown_Parameter_1100"]),
            1101: TimeOfDay2(["ID_Einst_SilenceTimer_8", "Unknown_Parameter_1101"]),
            1102: TimeOfDay2(["ID_Einst_SilenceTimer_9", "Unknown_Parameter_1102"]),
            1103: TimeOfDay2(["ID_Einst_SilenceTimer_10", "Unknown_Parameter_1103"]),
            1104: TimeOfDay2(["ID_Einst_SilenceTimer_11", "Unknown_Parameter_1104"]),
            1105: TimeOfDay2(["ID_Einst_SilenceTimer_12", "Unknown_Parameter_1105"]),
            1106: TimeOfDay2(["ID_Einst_SilenceTimer_13", "Unknown_Parameter_1106"]),
            1107: TimeOfDay2(["ID_Einst_SilenceTimer_14", "Unknown_Parameter_1107"]),
            1108: TimeOfDay2(["ID_Einst_SilenceTimer_15", "Unknown_Parameter_1108"]),
            1109: TimeOfDay2(["ID_Einst_SilenceTimer_16", "Unknown_Parameter_1109"]),
            1110: TimeOfDay2(["ID_Einst_SilenceTimer_17", "Unknown_Parameter_1110"]),
            1111: TimeOfDay2(["ID_Einst_SilenceTimer_18", "Unknown_Parameter_1111"]),
            1112: TimeOfDay2(["ID_Einst_SilenceTimer_19", "Unknown_Parameter_1112"]),
            1113: TimeOfDay2(["ID_Einst_SilenceTimer_20", "Unknown_Parameter_1113"]),
            1114: Unknown("Unknown_Parameter_1114"),
            1115: Unknown("Unknown_Parameter_1115"),
            1116: Unknown("Unknown_Parameter_1116"),
            1117: Unknown("Unknown_Parameter_1117"),
            1118: Unknown("Unknown_Parameter_1118"),
            1119: Timestamp(["LAST_DEFROST_TIMESTAMP", "Unknown_Parameter_1119"]),
            1120: Unknown("Unknown_Parameter_1120"),
            1121: Unknown("Unknown_Parameter_1121"),
            1122: Unknown("Unknown_Parameter_1122"),
            1123: Unknown("Unknown_Parameter_1123"),
            1124: Unknown("Unknown_Parameter_1124"),
            1125: Unknown("Unknown_Parameter_1125"),
            1126: Unknown("Unknown_Parameter_1126"),
            1127: Unknown("Unknown_Parameter_1127"),
            1128: Unknown("Unknown_Parameter_1128"),
            1129: Unknown("Unknown_Parameter_1129"),
            1130: Unknown("Unknown_Parameter_1130"),
            1131: Unknown("Unknown_Parameter_1131"),
            1132: Unknown("Unknown_Parameter_1132"),
            1133: Unknown("Unknown_Parameter_1133"),
            1134: Unknown("Unknown_Parameter_1134"),
            1135: Unknown("Unknown_Parameter_1135"),
            1136: Energy(["HEAT_ENERGY_INPUT", "Unknown_Parameter_1136"]),
            1137: Energy(["DHW_ENERGY_INPUT", "Unknown_Parameter_1137"]),
            1138: Unknown("Unknown_Parameter_1138"),
            1139: Energy(["COOLING_ENERGY_INPUT", "Unknown_Parameter_1139"]),
            1140: Unknown(["SECOND_HEAT_GENERATOR_AMOUNT_COUNTER", "Unknown_Parameter_1140"]),
            1141: Unknown("Unknown_Parameter_1141"),
            1142: Unknown("Unknown_Parameter_1142"),
            1143: Unknown("Unknown_Parameter_1143"),
            1144: Unknown("Unknown_Parameter_1144"),
            1145: Unknown("Unknown_Parameter_1145"),
            1146: Unknown("Unknown_Parameter_1146"),
            1147: Unknown("Unknown_Parameter_1147"),
            1148: Celsius(["HEATING_TARGET_TEMP_ROOM_THERMOSTAT", "Unknown_Parameter_1148"], True),
            1149: Unknown("Unknown_Parameter_1149"),
            1150: Unknown("Unknown_Parameter_1150"),
            1151: Unknown("Unknown_Parameter_1151"),
            1152: Unknown("Unknown_Parameter_1152"),
            1153: Unknown("Unknown_Parameter_1153"),
            1154: Unknown("Unknown_Parameter_1154"),
            1155: Unknown("Unknown_Parameter_1155"),
            1156: Unknown("Unknown_Parameter_1156"),
            1157: Unknown("Unknown_Parameter_1157"),
            1158: Unknown(["POWER_LIMIT_SWITCH", "Unknown_Parameter_1158"]),
            1159: Unknown(["POWER_LIMIT_VALUE", "Unknown_Parameter_1159"]),
        }

    @property
    def parameters(self):
        return self._data

    def set(self, target, value):
        """Set parameter to new value."""
        index, parameter = self._lookup(target, with_index=True)
        if index is not None:
            if parameter.writeable or not self.safe:
                raw = parameter.to_heatpump(value)
                if isinstance(raw, int):
                    self.queue[index] = raw
                else:
                    self.logger.error("Value '%s' for Parameter '%s' not valid!", value, parameter.name)
            else:
                self.logger.warning("Parameter '%s' not safe for writing!", parameter.name)
        else:
            self.logger.warning("Parameter '%s' not found", target)
