# pylint: disable=too-many-lines

"""Parse luxtronik parameters."""
import logging

from luxtronik.data_vector import DataVector

from luxtronik.datatypes import (
    AccessLevel,
    Bool,
    Count,
    Energy,
    Kelvin,
    Celsius,
    CoolingMode,
    HeatingMode,
    HotWaterMode,
    Hours,
    Hours2,
    Minutes,
    MixedCircuitMode,
    PoolMode,
    Seconds,
    SolarMode,
    Timestamp,
    Unknown,
    VentilationMode,
    TimerProgram,
    TimeOfDay,
    TimeOfDay2,
)


class Parameters(DataVector):
    """Class that holds all parameters."""

    logger = logging.getLogger("Luxtronik.Parameters")
    name = "Parameter"

    def __init__(self, safe=True):
        """Initialize parameters class."""
        super().__init__()
        self.safe = safe
        self.queue = {}

        self._data = {
            0: Unknown("ID_Transfert_LuxNet"),
            1: Celsius("ID_Einst_WK_akt", True),
            2: Celsius("ID_Einst_BWS_akt", True),
            3: HeatingMode("ID_Ba_Hz_akt", True),
            4: HotWaterMode("ID_Ba_Bw_akt", True),
            5: Unknown("ID_Ba_Al_akt"),
            6: Unknown("ID_SU_FrkdHz"),
            7: Unknown("ID_SU_FrkdBw"),
            8: Unknown("ID_SU_FrkdAl"),
            9: Unknown("ID_Einst_HReg_akt"),
            10: Unknown("ID_Einst_HzHwMAt_akt"),
            11: Celsius("ID_Einst_HzHwHKE_akt", True),
            12: Celsius("ID_Einst_HzHKRANH_akt", True),
            13: Celsius("ID_Einst_HzHKRABS_akt", True),
            14: Celsius("ID_Einst_HzMK1E_akt", True),
            15: Celsius("ID_Einst_HzMK1ANH_akt", True),
            16: Celsius("ID_Einst_HzMK1ABS_akt", True),
            17: Unknown("ID_Einst_HzFtRl_akt"),
            18: Unknown("ID_Einst_HzFtMK1Vl_akt"),
            19: Unknown("ID_Einst_SUBW_akt"),
            20: Unknown("ID_Einst_BwTDI_akt_MO"),
            21: Unknown("ID_Einst_BwTDI_akt_DI"),
            22: Unknown("ID_Einst_BwTDI_akt_MI"),
            23: Unknown("ID_Einst_BwTDI_akt_DO"),
            24: Unknown("ID_Einst_BwTDI_akt_FR"),
            25: Unknown("ID_Einst_BwTDI_akt_SA"),
            26: Unknown("ID_Einst_BwTDI_akt_SO"),
            27: Unknown("ID_Einst_BwTDI_akt_AL"),
            28: Unknown("ID_Einst_AnlKonf_akt"),
            29: Unknown("ID_Einst_Sprache_akt"),
            30: Unknown("ID_Switchoff_Zahler"),
            31: Unknown("ID_Switchoff_index"),
            32: Unknown("ID_Einst_EvuTyp_akt"),
            33: Unknown("ID_Einst_RFVEinb_akt"),
            34: Unknown("ID_Einst_AbtZykMax_akt"),
            35: Unknown("ID_Einst_HREinb_akt"),
            36: Unknown("ID_Einst_ZWE1Art_akt"),
            37: Unknown("ID_Einst_ZWE1Fkt_akt"),
            38: Unknown("ID_Einst_ZWE2Art_akt"),
            39: Unknown("ID_Einst_ZWE2Fkt_akt"),
            40: Unknown("ID_Einst_BWBer_akt"),
            41: Unknown("ID_Einst_En_Inst"),
            42: Unknown("ID_Einst_MK1Typ_akt"),
            43: Unknown("ID_Einst_ABTLuft_akt"),
            44: Unknown("ID_Einst_TLAbt_akt"),
            45: Unknown("ID_Einst_LAbtTime_akt"),
            46: Unknown("ID_Einst_ASDTyp_akt"),
            47: Celsius("ID_Einst_LGST_akt", True),
            48: Unknown("ID_Einst_BwWpTime_akt"),
            49: Unknown("ID_Einst_Popt_akt"),
            50: Unknown("ID_Einst_Kurzprog_akt"),
            51: Unknown("ID_Timer_Kurzprog_akt"),
            52: Unknown("ID_Einst_ManAbt_akt"),
            53: Unknown("ID_Einst_Ahz_akt"),
            54: Unknown("ID_Einst_TVL_Ahz_1"),
            55: Unknown("ID_Einst_TVL_Ahz_2"),
            56: Unknown("ID_Einst_TVL_Ahz_3"),
            57: Unknown("ID_Einst_TVL_Ahz_4"),
            58: Unknown("ID_Einst_TVL_Ahz_5"),
            59: Unknown("ID_Einst_TVL_Ahz_6"),
            60: Unknown("ID_Einst_TVL_Ahz_7"),
            61: Unknown("ID_Einst_TVL_Ahz_8"),
            62: Unknown("ID_Einst_TVL_Ahz_9"),
            63: Unknown("ID_Einst_TVL_Ahz_10"),
            64: Unknown("ID_Einst_TVL_Std_1"),
            65: Unknown("ID_Einst_TVL_Std_2"),
            66: Unknown("ID_Einst_TVL_Std_3"),
            67: Unknown("ID_Einst_TVL_Std_4"),
            68: Unknown("ID_Einst_TVL_Std_5"),
            69: Unknown("ID_Einst_TVL_Std_6"),
            70: Unknown("ID_Einst_TVL_Std_7"),
            71: Unknown("ID_Einst_TVL_Std_8"),
            72: Unknown("ID_Einst_TVL_Std_9"),
            73: Unknown("ID_Einst_TVL_Std_10"),
            74: Kelvin("ID_Einst_BWS_Hyst_akt", True),
            75: Unknown("ID_Temp_TBW_BwHD_saved"),
            76: Unknown("ID_Einst_ABT1_akt"),
            77: Unknown("ID_Einst_LABTpaus_akt"),
            78: Unknown("ID_AHZ_state_akt"),
            79: Celsius("ID_Sollwert_TRL_HZ_AHZ", True),
            80: Unknown("ID_AHP_valid_records"),
            81: Unknown("ID_Timer_AHZ_akt"),
            82: Unknown("ID_Einst_BWTINP_akt"),
            83: Unknown("ID_Einst_ZUPTYP_akt"),
            84: Unknown("ID_Sollwert_TLG_max"),
            85: Unknown("ID_Einst_BWZIP_akt"),
            86: Unknown("ID_Einst_ERRmZWE_akt"),
            87: Unknown("ID_Einst_TRBegr_akt"),
            88: Kelvin("ID_Einst_HRHyst_akt", True),
            89: Kelvin("ID_Einst_TRErhmax_akt", True),
            90: Celsius("ID_Einst_ZWEFreig_akt", True),
            91: Unknown("ID_Einst_TAmax_akt"),
            92: Unknown("ID_Einst_TAmin_akt"),
            93: Unknown("ID_Einst_TWQmin_akt"),
            94: Unknown("ID_Einst_THGmax_akt"),
            95: Unknown("ID_Einst_FRGT2VD_akt"),
            96: Unknown("ID_Einst_TV2VDBW_akt"),
            97: Unknown("ID_Einst_SuAll_akt"),
            98: Unknown("ID_Einst_TAbtEnd_akt"),
            99: Unknown("ID_Einst_NrKlingel_akt"),
            100: Unknown("ID_Einst_BWStyp_akt"),
            101: Unknown("ID_Einst_ABT2_akt"),
            102: Unknown("ID_Einst_UeVd_akt"),
            103: Unknown("ID_Einst_RTyp_akt"),
            104: Unknown("ID_Einst_AhpM_akt"),
            105: Celsius("ID_Soll_BWS_akt", True),
            106: Unknown("ID_Timer_Password"),
            107: AccessLevel("ID_Einst_Zugangscode", True),
            108: CoolingMode("ID_Einst_BA_Kuehl_akt", True),
            109: Unknown("ID_Sollwert_Kuehl1_akt"),
            110: Celsius("ID_Einst_KuehlFreig_akt", True),
            111: Celsius("ID_Einst_TAbsMin_akt", True),
            112: Unknown("ID_TWQmin_saved"),
            113: Unknown("ID_CWP_saved"),
            114: Unknown("ID_Einst_Anode_akt"),
            115: Unknown("ID_Timer_pexoff_akt"),
            116: Unknown("ID_Einst_AnlPrio_Hzakt"),
            117: Unknown("ID_Einst_AnlPrio_Bwakt"),
            118: Unknown("ID_Einst_AnlPrio_Swakt"),
            119: PoolMode("ID_Ba_Sw_akt", True),
            120: Unknown("ID_Einst_RTypMK1_akt"),
            121: Unknown("ID_Einst_RTypMK2_akt"),
            122: Kelvin("ID_Einst_TDC_Ein_akt"),
            123: Kelvin("ID_Einst_TDC_Aus_akt"),
            124: Celsius("ID_Einst_TDC_Max_akt", True),
            125: Unknown("ID_Einst_HysHzExEn_akt"),
            126: Unknown("ID_Einst_HysBwExEn_akt"),
            127: Unknown("ID_Einst_ZWE3Art_akt"),
            128: Unknown("ID_Einst_ZWE3Fkt_akt"),
            129: Unknown("ID_Einst_HzSup_akt"),
            130: Unknown("ID_Einst_MK2Typ_akt"),
            131: Unknown("ID_Einst_KuTyp_akt"),
            132: Celsius("ID_Sollwert_KuCft1_akt", True),
            133: Celsius("ID_Sollwert_KuCft2_akt", True),
            134: Celsius("ID_Sollwert_AtDif1_akt", True),
            135: Celsius("ID_Sollwert_AtDif2_akt", True),
            136: Unknown("ID_SU_FrkdSwb"),
            137: Unknown("ID_Einst_SwbBer_akt"),
            138: Unknown("ID_Einst_TV2VDSWB_akt"),
            139: Unknown("ID_Einst_MinSwan_Time_akt"),
            140: Unknown("ID_Einst_SuMk2_akt"),
            141: Celsius("ID_Einst_HzMK2E_akt", True),
            142: Celsius("ID_Einst_HzMK2ANH_akt", True),
            143: Celsius("ID_Einst_HzMK2ABS_akt", True),
            144: Unknown("ID_Einst_HzMK2Hgr_akt"),
            145: Unknown("ID_Einst_HzFtMK2Vl_akt"),
            146: Unknown("ID_Temp_THG_BwHD_saved"),
            147: Unknown("ID_Temp_TA_BwHD_saved"),
            148: Unknown("ID_Einst_BwHup_akt"),
            149: Unknown("ID_Einst_TVLmax_akt"),
            150: Unknown("ID_Einst_MK1LzFaktor_akt"),
            151: Unknown("ID_Einst_MK2LzFaktor_akt"),
            152: Unknown("ID_Einst_MK1PerFaktor_akt"),
            153: Unknown("ID_Einst_MK2PerFaktor_akt"),
            154: Unknown("ID_Entl_Zyklus_akt"),
            155: Unknown("ID_Einst_Entl_time_akt"),
            156: Unknown("ID_Entl_Pause"),
            157: Unknown("ID_Entl_timer"),
            158: Unknown("ID_Einst_Entl_akt"),
            159: Unknown("ID_Ahz_HLeist_confirmed"),
            160: Unknown("ID_FirstInit_akt"),
            161: Unknown("ID_Einst_SuAll_akt2"),
            162: Unknown("ID_Einst_SuAllWo_zeit_0_0"),
            163: Unknown("ID_Einst_SuAllWo_zeit_0_1"),
            164: Unknown("ID_Einst_SuAllWo_zeit_1_0"),
            165: Unknown("ID_Einst_SuAllWo_zeit_1_1"),
            166: Unknown("ID_Einst_SuAllWo_zeit_2_0"),
            167: Unknown("ID_Einst_SuAllWo_zeit_2_1"),
            168: Unknown("ID_Einst_SuAll25_zeit_0_0"),
            169: Unknown("ID_Einst_SuAll25_zeit_0_1"),
            170: Unknown("ID_Einst_SuAll25_zeit_1_0"),
            171: Unknown("ID_Einst_SuAll25_zeit_1_1"),
            172: Unknown("ID_Einst_SuAll25_zeit_2_0"),
            173: Unknown("ID_Einst_SuAll25_zeit_2_1"),
            174: Unknown("ID_Einst_SuAll25_zeit_0_2"),
            175: Unknown("ID_Einst_SuAll25_zeit_0_3"),
            176: Unknown("ID_Einst_SuAll25_zeit_1_2"),
            177: Unknown("ID_Einst_SuAll25_zeit_1_3"),
            178: Unknown("ID_Einst_SuAll25_zeit_2_2"),
            179: Unknown("ID_Einst_SuAll25_zeit_2_3"),
            180: Unknown("ID_Einst_SuAllTg_zeit_0_0"),
            181: Unknown("ID_Einst_SuAllTg_zeit_0_1"),
            182: Unknown("ID_Einst_SuAllTg_zeit_1_0"),
            183: Unknown("ID_Einst_SuAllTg_zeit_1_1"),
            184: Unknown("ID_Einst_SuAllTg_zeit_2_0"),
            185: Unknown("ID_Einst_SuAllTg_zeit_2_1"),
            186: Unknown("ID_Einst_SuAllTg_zeit_0_2"),
            187: Unknown("ID_Einst_SuAllTg_zeit_0_3"),
            188: Unknown("ID_Einst_SuAllTg_zeit_1_2"),
            189: Unknown("ID_Einst_SuAllTg_zeit_1_3"),
            190: Unknown("ID_Einst_SuAllTg_zeit_2_2"),
            191: Unknown("ID_Einst_SuAllTg_zeit_2_3"),
            192: Unknown("ID_Einst_SuAllTg_zeit_0_4"),
            193: Unknown("ID_Einst_SuAllTg_zeit_0_5"),
            194: Unknown("ID_Einst_SuAllTg_zeit_1_4"),
            195: Unknown("ID_Einst_SuAllTg_zeit_1_5"),
            196: Unknown("ID_Einst_SuAllTg_zeit_2_4"),
            197: Unknown("ID_Einst_SuAllTg_zeit_2_5"),
            198: Unknown("ID_Einst_SuAllTg_zeit_0_6"),
            199: Unknown("ID_Einst_SuAllTg_zeit_0_7"),
            200: Unknown("ID_Einst_SuAllTg_zeit_1_6"),
            201: Unknown("ID_Einst_SuAllTg_zeit_1_7"),
            202: Unknown("ID_Einst_SuAllTg_zeit_2_6"),
            203: Unknown("ID_Einst_SuAllTg_zeit_2_7"),
            204: Unknown("ID_Einst_SuAllTg_zeit_0_8"),
            205: Unknown("ID_Einst_SuAllTg_zeit_0_9"),
            206: Unknown("ID_Einst_SuAllTg_zeit_1_8"),
            207: Unknown("ID_Einst_SuAllTg_zeit_1_9"),
            208: Unknown("ID_Einst_SuAllTg_zeit_2_8"),
            209: Unknown("ID_Einst_SuAllTg_zeit_2_9"),
            210: Unknown("ID_Einst_SuAllTg_zeit_0_10"),
            211: Unknown("ID_Einst_SuAllTg_zeit_0_11"),
            212: Unknown("ID_Einst_SuAllTg_zeit_1_10"),
            213: Unknown("ID_Einst_SuAllTg_zeit_1_11"),
            214: Unknown("ID_Einst_SuAllTg_zeit_2_10"),
            215: Unknown("ID_Einst_SuAllTg_zeit_2_11"),
            216: Unknown("ID_Einst_SuAllTg_zeit_0_12"),
            217: Unknown("ID_Einst_SuAllTg_zeit_0_13"),
            218: Unknown("ID_Einst_SuAllTg_zeit_1_12"),
            219: Unknown("ID_Einst_SuAllTg_zeit_1_13"),
            220: Unknown("ID_Einst_SuAllTg_zeit_2_12"),
            221: Unknown("ID_Einst_SuAllTg_zeit_2_13"),
            222: TimerProgram("ID_Einst_SuHkr_akt", True),
            223: TimeOfDay("ID_Einst_SuHkrW0_zeit_0_0", True),
            224: TimeOfDay("ID_Einst_SuHkrW0_zeit_0_1", True),
            225: TimeOfDay("ID_Einst_SuHkrW0_zeit_1_0", True),
            226: TimeOfDay("ID_Einst_SuHkrW0_zeit_1_1", True),
            227: TimeOfDay("ID_Einst_SuHkrW0_zeit_2_0", True),
            228: TimeOfDay("ID_Einst_SuHkrW0_zeit_2_1", True),
            229: TimeOfDay("ID_Einst_SuHkr25_zeit_0_0", True),
            230: TimeOfDay("ID_Einst_SuHkr25_zeit_0_1", True),
            231: TimeOfDay("ID_Einst_SuHkr25_zeit_1_0", True),
            232: TimeOfDay("ID_Einst_SuHkr25_zeit_1_1", True),
            233: TimeOfDay("ID_Einst_SuHkr25_zeit_2_0", True),
            234: TimeOfDay("ID_Einst_SuHkr25_zeit_2_1", True),
            235: TimeOfDay("ID_Einst_SuHkr25_zeit_0_2", True),
            236: TimeOfDay("ID_Einst_SuHkr25_zeit_0_3", True),
            237: TimeOfDay("ID_Einst_SuHkr25_zeit_1_2", True),
            238: TimeOfDay("ID_Einst_SuHkr25_zeit_1_3", True),
            239: TimeOfDay("ID_Einst_SuHkr25_zeit_2_2", True),
            240: TimeOfDay("ID_Einst_SuHkr25_zeit_2_3", True),
            241: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_0", True),
            242: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_1", True),
            243: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_0", True),
            244: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_1", True),
            245: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_0", True),
            246: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_1", True),
            247: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_2", True),
            248: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_3", True),
            249: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_2", True),
            250: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_3", True),
            251: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_2", True),
            252: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_3", True),
            253: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_4", True),
            254: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_5", True),
            255: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_4", True),
            256: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_5", True),
            257: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_4", True),
            258: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_5", True),
            259: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_6", True),
            260: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_7", True),
            261: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_6", True),
            262: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_7", True),
            263: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_6", True),
            264: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_7", True),
            265: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_8", True),
            266: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_9", True),
            267: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_8", True),
            268: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_9", True),
            269: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_8", True),
            270: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_9", True),
            271: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_10", True),
            272: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_11", True),
            273: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_10", True),
            274: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_11", True),
            275: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_10", True),
            276: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_11", True),
            277: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_12", True),
            278: TimeOfDay("ID_Einst_SuHkrTG_zeit_0_13", True),
            279: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_12", True),
            280: TimeOfDay("ID_Einst_SuHkrTG_zeit_1_13", True),
            281: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_12", True),
            282: TimeOfDay("ID_Einst_SuHkrTG_zeit_2_13", True),
            283: TimerProgram("ID_Einst_SuMk1_akt"),
            284: TimeOfDay("ID_Einst_SuMk1W0_zeit_0_0"),
            285: TimeOfDay("ID_Einst_SuMk1W0_zeit_0_1"),
            286: TimeOfDay("ID_Einst_SuMk1W0_zeit_1_0"),
            287: TimeOfDay("ID_Einst_SuMk1W0_zeit_1_1"),
            288: TimeOfDay("ID_Einst_SuMk1W0_zeit_2_0"),
            289: TimeOfDay("ID_Einst_SuMk1W0_zeit_2_1"),
            290: TimeOfDay("ID_Einst_SuMk125_zeit_0_0"),
            291: TimeOfDay("ID_Einst_SuMk125_zeit_0_1"),
            292: TimeOfDay("ID_Einst_SuMk125_zeit_1_0"),
            293: TimeOfDay("ID_Einst_SuMk125_zeit_1_1"),
            294: TimeOfDay("ID_Einst_SuMk125_zeit_2_0"),
            295: TimeOfDay("ID_Einst_SuMk125_zeit_2_1"),
            296: TimeOfDay("ID_Einst_SuMk125_zeit_0_2"),
            297: TimeOfDay("ID_Einst_SuMk125_zeit_0_3"),
            298: TimeOfDay("ID_Einst_SuMk125_zeit_1_2"),
            299: TimeOfDay("ID_Einst_SuMk125_zeit_1_3"),
            300: TimeOfDay("ID_Einst_SuMk125_zeit_2_2"),
            301: TimeOfDay("ID_Einst_SuMk125_zeit_2_3"),
            302: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_0"),
            303: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_1"),
            304: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_0"),
            305: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_1"),
            306: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_0"),
            307: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_1"),
            308: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_2"),
            309: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_3"),
            310: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_2"),
            311: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_3"),
            312: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_2"),
            313: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_3"),
            314: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_4"),
            315: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_5"),
            316: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_4"),
            317: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_5"),
            318: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_4"),
            319: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_5"),
            320: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_6"),
            321: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_7"),
            322: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_6"),
            323: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_7"),
            324: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_6"),
            325: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_7"),
            326: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_8"),
            327: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_9"),
            328: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_8"),
            329: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_9"),
            330: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_8"),
            331: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_9"),
            332: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_10"),
            333: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_11"),
            334: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_10"),
            335: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_11"),
            336: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_10"),
            337: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_11"),
            338: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_12"),
            339: TimeOfDay("ID_Einst_SuMk1TG_zeit_0_13"),
            340: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_12"),
            341: TimeOfDay("ID_Einst_SuMk1TG_zeit_1_13"),
            342: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_12"),
            343: TimeOfDay("ID_Einst_SuMk1TG_zeit_2_13"),
            344: TimerProgram("ID_Einst_SuMk2_akt2"),
            345: TimeOfDay("ID_Einst_SuMk2Wo_zeit_0_0"),
            346: TimeOfDay("ID_Einst_SuMk2Wo_zeit_0_1"),
            347: TimeOfDay("ID_Einst_SuMk2Wo_zeit_1_0"),
            348: TimeOfDay("ID_Einst_SuMk2Wo_zeit_1_1"),
            349: TimeOfDay("ID_Einst_SuMk2Wo_zeit_2_0"),
            350: TimeOfDay("ID_Einst_SuMk2Wo_zeit_2_1"),
            351: TimeOfDay("ID_Einst_SuMk225_zeit_0_0"),
            352: TimeOfDay("ID_Einst_SuMk225_zeit_0_1"),
            353: TimeOfDay("ID_Einst_SuMk225_zeit_1_0"),
            354: TimeOfDay("ID_Einst_SuMk225_zeit_1_1"),
            355: TimeOfDay("ID_Einst_SuMk225_zeit_2_0"),
            356: TimeOfDay("ID_Einst_SuMk225_zeit_2_1"),
            357: TimeOfDay("ID_Einst_SuMk225_zeit_0_2"),
            358: TimeOfDay("ID_Einst_SuMk225_zeit_0_3"),
            359: TimeOfDay("ID_Einst_SuMk225_zeit_1_2"),
            360: TimeOfDay("ID_Einst_SuMk225_zeit_1_3"),
            361: TimeOfDay("ID_Einst_SuMk225_zeit_2_2"),
            362: TimeOfDay("ID_Einst_SuMk225_zeit_2_3"),
            363: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_0"),
            364: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_1"),
            365: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_0"),
            366: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_1"),
            367: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_0"),
            368: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_1"),
            369: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_2"),
            370: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_3"),
            371: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_2"),
            372: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_3"),
            373: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_2"),
            374: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_3"),
            375: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_4"),
            376: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_5"),
            377: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_4"),
            378: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_5"),
            379: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_4"),
            380: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_5"),
            381: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_6"),
            382: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_7"),
            383: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_6"),
            384: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_7"),
            385: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_6"),
            386: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_7"),
            387: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_8"),
            388: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_9"),
            389: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_8"),
            390: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_9"),
            391: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_8"),
            392: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_9"),
            393: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_10"),
            394: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_11"),
            395: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_10"),
            396: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_11"),
            397: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_10"),
            398: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_11"),
            399: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_12"),
            400: TimeOfDay("ID_Einst_SuMk2Tg_zeit_0_13"),
            401: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_12"),
            402: TimeOfDay("ID_Einst_SuMk2Tg_zeit_1_13"),
            403: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_12"),
            404: TimeOfDay("ID_Einst_SuMk2Tg_zeit_2_13"),
            405: TimerProgram("ID_Einst_SUBW_akt2", True),
            406: TimeOfDay("ID_Einst_SuBwWO_zeit_0_0", True),
            407: TimeOfDay("ID_Einst_SuBwWO_zeit_0_1", True),
            408: TimeOfDay("ID_Einst_SuBwWO_zeit_1_0", True),
            409: TimeOfDay("ID_Einst_SuBwWO_zeit_1_1", True),
            410: TimeOfDay("ID_Einst_SuBwWO_zeit_2_0", True),
            411: TimeOfDay("ID_Einst_SuBwWO_zeit_2_1", True),
            412: TimeOfDay("ID_Einst_SuBwWO_zeit_3_0", True),
            413: TimeOfDay("ID_Einst_SuBwWO_zeit_3_1", True),
            414: TimeOfDay("ID_Einst_SuBwWO_zeit_4_0", True),
            415: TimeOfDay("ID_Einst_SuBwWO_zeit_4_1", True),
            416: TimeOfDay("ID_Einst_SuBw25_zeit_0_0", True),
            417: TimeOfDay("ID_Einst_SuBw25_zeit_0_1", True),
            418: TimeOfDay("ID_Einst_SuBw25_zeit_1_0", True),
            419: TimeOfDay("ID_Einst_SuBw25_zeit_1_1", True),
            420: TimeOfDay("ID_Einst_SuBw25_zeit_2_0", True),
            421: TimeOfDay("ID_Einst_SuBw25_zeit_2_1", True),
            422: TimeOfDay("ID_Einst_SuBw25_zeit_3_0", True),
            423: TimeOfDay("ID_Einst_SuBw25_zeit_3_1", True),
            424: TimeOfDay("ID_Einst_SuBw25_zeit_4_0", True),
            425: TimeOfDay("ID_Einst_SuBw25_zeit_4_1", True),
            426: TimeOfDay("ID_Einst_SuBw25_zeit_0_2", True),
            427: TimeOfDay("ID_Einst_SuBw25_zeit_0_3", True),
            428: TimeOfDay("ID_Einst_SuBw25_zeit_1_2", True),
            429: TimeOfDay("ID_Einst_SuBw25_zeit_1_3", True),
            430: TimeOfDay("ID_Einst_SuBw25_zeit_2_2", True),
            431: TimeOfDay("ID_Einst_SuBw25_zeit_2_3", True),
            432: TimeOfDay("ID_Einst_SuBw25_zeit_3_2", True),
            433: TimeOfDay("ID_Einst_SuBw25_zeit_3_3", True),
            434: TimeOfDay("ID_Einst_SuBw25_zeit_4_2", True),
            435: TimeOfDay("ID_Einst_SuBw25_zeit_4_3", True),
            436: TimeOfDay("ID_Einst_SuBwTG_zeit_0_0", True),
            437: TimeOfDay("ID_Einst_SuBwTG_zeit_0_1", True),
            438: TimeOfDay("ID_Einst_SuBwTG_zeit_1_0", True),
            439: TimeOfDay("ID_Einst_SuBwTG_zeit_1_1", True),
            440: TimeOfDay("ID_Einst_SuBwTG_zeit_2_0", True),
            441: TimeOfDay("ID_Einst_SuBwTG_zeit_2_1", True),
            442: TimeOfDay("ID_Einst_SuBwTG_zeit_3_0", True),
            443: TimeOfDay("ID_Einst_SuBwTG_zeit_3_1", True),
            444: TimeOfDay("ID_Einst_SuBwTG_zeit_4_0", True),
            445: TimeOfDay("ID_Einst_SuBwTG_zeit_4_1", True),
            446: TimeOfDay("ID_Einst_SuBwTG_zeit_0_2", True),
            447: TimeOfDay("ID_Einst_SuBwTG_zeit_0_3", True),
            448: TimeOfDay("ID_Einst_SuBwTG_zeit_1_2", True),
            449: TimeOfDay("ID_Einst_SuBwTG_zeit_1_3", True),
            450: TimeOfDay("ID_Einst_SuBwTG_zeit_2_2", True),
            451: TimeOfDay("ID_Einst_SuBwTG_zeit_2_3", True),
            452: TimeOfDay("ID_Einst_SuBwTG_zeit_3_2", True),
            453: TimeOfDay("ID_Einst_SuBwTG_zeit_3_3", True),
            454: TimeOfDay("ID_Einst_SuBwTG_zeit_4_2", True),
            455: TimeOfDay("ID_Einst_SuBwTG_zeit_4_3", True),
            456: TimeOfDay("ID_Einst_SuBwTG_zeit_0_4", True),
            457: TimeOfDay("ID_Einst_SuBwTG_zeit_0_5", True),
            458: TimeOfDay("ID_Einst_SuBwTG_zeit_1_4", True),
            459: TimeOfDay("ID_Einst_SuBwTG_zeit_1_5", True),
            460: TimeOfDay("ID_Einst_SuBwTG_zeit_2_4", True),
            461: TimeOfDay("ID_Einst_SuBwTG_zeit_2_5", True),
            462: TimeOfDay("ID_Einst_SuBwTG_zeit_3_4", True),
            463: TimeOfDay("ID_Einst_SuBwTG_zeit_3_5", True),
            464: TimeOfDay("ID_Einst_SuBwTG_zeit_4_4", True),
            465: TimeOfDay("ID_Einst_SuBwTG_zeit_4_5", True),
            466: TimeOfDay("ID_Einst_SuBwTG_zeit_0_6", True),
            467: TimeOfDay("ID_Einst_SuBwTG_zeit_0_7", True),
            468: TimeOfDay("ID_Einst_SuBwTG_zeit_1_6", True),
            469: TimeOfDay("ID_Einst_SuBwTG_zeit_1_7", True),
            470: TimeOfDay("ID_Einst_SuBwTG_zeit_2_6", True),
            471: TimeOfDay("ID_Einst_SuBwTG_zeit_2_7", True),
            472: TimeOfDay("ID_Einst_SuBwTG_zeit_3_6", True),
            473: TimeOfDay("ID_Einst_SuBwTG_zeit_3_7", True),
            474: TimeOfDay("ID_Einst_SuBwTG_zeit_4_6", True),
            475: TimeOfDay("ID_Einst_SuBwTG_zeit_4_7", True),
            476: TimeOfDay("ID_Einst_SuBwTG_zeit_0_8", True),
            477: TimeOfDay("ID_Einst_SuBwTG_zeit_0_9", True),
            478: TimeOfDay("ID_Einst_SuBwTG_zeit_1_8", True),
            479: TimeOfDay("ID_Einst_SuBwTG_zeit_1_9", True),
            480: TimeOfDay("ID_Einst_SuBwTG_zeit_2_8", True),
            481: TimeOfDay("ID_Einst_SuBwTG_zeit_2_9", True),
            482: TimeOfDay("ID_Einst_SuBwTG_zeit_3_8", True),
            483: TimeOfDay("ID_Einst_SuBwTG_zeit_3_9", True),
            484: TimeOfDay("ID_Einst_SuBwTG_zeit_4_8", True),
            485: TimeOfDay("ID_Einst_SuBwTG_zeit_4_9", True),
            486: TimeOfDay("ID_Einst_SuBwTG_zeit_0_10", True),
            487: TimeOfDay("ID_Einst_SuBwTG_zeit_0_11", True),
            488: TimeOfDay("ID_Einst_SuBwTG_zeit_1_10", True),
            489: TimeOfDay("ID_Einst_SuBwTG_zeit_1_11", True),
            490: TimeOfDay("ID_Einst_SuBwTG_zeit_2_10", True),
            491: TimeOfDay("ID_Einst_SuBwTG_zeit_2_11", True),
            492: TimeOfDay("ID_Einst_SuBwTG_zeit_3_10", True),
            493: TimeOfDay("ID_Einst_SuBwTG_zeit_3_11", True),
            494: TimeOfDay("ID_Einst_SuBwTG_zeit_4_10", True),
            495: TimeOfDay("ID_Einst_SuBwTG_zeit_4_11", True),
            496: TimeOfDay("ID_Einst_SuBwTG_zeit_0_12", True),
            497: TimeOfDay("ID_Einst_SuBwTG_zeit_0_13", True),
            498: TimeOfDay("ID_Einst_SuBwTG_zeit_1_12", True),
            499: TimeOfDay("ID_Einst_SuBwTG_zeit_1_13", True),
            500: TimeOfDay("ID_Einst_SuBwTG_zeit_2_12", True),
            501: TimeOfDay("ID_Einst_SuBwTG_zeit_2_13", True),
            502: TimeOfDay("ID_Einst_SuBwTG_zeit_3_12", True),
            503: TimeOfDay("ID_Einst_SuBwTG_zeit_3_13", True),
            504: TimeOfDay("ID_Einst_SuBwTG_zeit_4_12", True),
            505: TimeOfDay("ID_Einst_SuBwTG_zeit_4_13", True),
            506: TimerProgram("ID_Einst_SuZIP_akt", True),
            507: TimeOfDay("ID_Einst_SuZIPWo_zeit_0_0", True),
            508: TimeOfDay("ID_Einst_SuZIPWo_zeit_0_1", True),
            509: TimeOfDay("ID_Einst_SuZIPWo_zeit_1_0", True),
            510: TimeOfDay("ID_Einst_SuZIPWo_zeit_1_1", True),
            511: TimeOfDay("ID_Einst_SuZIPWo_zeit_2_0", True),
            512: TimeOfDay("ID_Einst_SuZIPWo_zeit_2_1", True),
            513: TimeOfDay("ID_Einst_SuZIPWo_zeit_3_0", True),
            514: TimeOfDay("ID_Einst_SuZIPWo_zeit_3_1", True),
            515: TimeOfDay("ID_Einst_SuZIPWo_zeit_4_0", True),
            516: TimeOfDay("ID_Einst_SuZIPWo_zeit_4_1", True),
            517: TimeOfDay("ID_Einst_SuZIP25_zeit_0_0", True),
            518: TimeOfDay("ID_Einst_SuZIP25_zeit_0_1", True),
            519: TimeOfDay("ID_Einst_SuZIP25_zeit_1_0", True),
            520: TimeOfDay("ID_Einst_SuZIP25_zeit_1_1", True),
            521: TimeOfDay("ID_Einst_SuZIP25_zeit_2_0", True),
            522: TimeOfDay("ID_Einst_SuZIP25_zeit_2_1", True),
            523: TimeOfDay("ID_Einst_SuZIP25_zeit_3_0", True),
            524: TimeOfDay("ID_Einst_SuZIP25_zeit_3_1", True),
            525: TimeOfDay("ID_Einst_SuZIP25_zeit_4_0", True),
            526: TimeOfDay("ID_Einst_SuZIP25_zeit_4_1", True),
            527: TimeOfDay("ID_Einst_SuZIP25_zeit_0_2", True),
            528: TimeOfDay("ID_Einst_SuZIP25_zeit_0_3", True),
            529: TimeOfDay("ID_Einst_SuZIP25_zeit_1_2", True),
            530: TimeOfDay("ID_Einst_SuZIP25_zeit_1_3", True),
            531: TimeOfDay("ID_Einst_SuZIP25_zeit_2_2", True),
            532: TimeOfDay("ID_Einst_SuZIP25_zeit_2_3", True),
            533: TimeOfDay("ID_Einst_SuZIP25_zeit_3_2", True),
            534: TimeOfDay("ID_Einst_SuZIP25_zeit_3_3", True),
            535: TimeOfDay("ID_Einst_SuZIP25_zeit_4_2", True),
            536: TimeOfDay("ID_Einst_SuZIP25_zeit_4_3", True),
            537: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_0", True),
            538: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_1", True),
            539: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_0", True),
            540: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_1", True),
            541: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_0", True),
            542: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_1", True),
            543: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_0", True),
            544: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_1", True),
            545: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_0", True),
            546: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_1", True),
            547: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_2", True),
            548: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_3", True),
            549: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_2", True),
            550: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_3", True),
            551: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_2", True),
            552: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_3", True),
            553: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_2", True),
            554: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_3", True),
            555: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_2", True),
            556: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_3", True),
            557: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_4", True),
            558: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_5", True),
            559: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_4", True),
            560: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_5", True),
            561: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_4", True),
            562: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_5", True),
            563: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_4", True),
            564: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_5", True),
            565: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_4", True),
            566: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_5", True),
            567: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_6", True),
            568: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_7", True),
            569: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_6", True),
            570: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_7", True),
            571: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_6", True),
            572: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_7", True),
            573: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_6", True),
            574: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_7", True),
            575: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_6", True),
            576: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_7", True),
            577: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_8", True),
            578: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_9", True),
            579: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_8", True),
            580: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_9", True),
            581: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_8", True),
            582: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_9", True),
            583: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_8", True),
            584: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_9", True),
            585: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_8", True),
            586: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_9", True),
            587: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_10", True),
            588: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_11", True),
            589: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_10", True),
            590: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_11", True),
            591: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_10", True),
            592: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_11", True),
            593: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_10", True),
            594: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_11", True),
            595: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_10", True),
            596: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_11", True),
            597: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_12", True),
            598: TimeOfDay("ID_Einst_SuZIPTg_zeit_0_13", True),
            599: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_12", True),
            600: TimeOfDay("ID_Einst_SuZIPTg_zeit_1_13", True),
            601: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_12", True),
            602: TimeOfDay("ID_Einst_SuZIPTg_zeit_2_13", True),
            603: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_12", True),
            604: TimeOfDay("ID_Einst_SuZIPTg_zeit_3_13", True),
            605: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_12", True),
            606: TimeOfDay("ID_Einst_SuZIPTg_zeit_4_13", True),
            607: TimerProgram("ID_Einst_SuSwb_akt"),
            608: TimeOfDay("ID_Einst_SuSwbWo_zeit_0_0"),
            609: TimeOfDay("ID_Einst_SuSwbWo_zeit_0_1"),
            610: TimeOfDay("ID_Einst_SuSwbWo_zeit_1_0"),
            611: TimeOfDay("ID_Einst_SuSwbWo_zeit_1_1"),
            612: TimeOfDay("ID_Einst_SuSwbWo_zeit_2_0"),
            613: TimeOfDay("ID_Einst_SuSwbWo_zeit_2_1"),
            614: TimeOfDay("ID_Einst_SuSwb25_zeit_0_0"),
            615: TimeOfDay("ID_Einst_SuSwb25_zeit_0_1"),
            616: TimeOfDay("ID_Einst_SuSwb25_zeit_1_0"),
            617: TimeOfDay("ID_Einst_SuSwb25_zeit_1_1"),
            618: TimeOfDay("ID_Einst_SuSwb25_zeit_2_0"),
            619: TimeOfDay("ID_Einst_SuSwb25_zeit_2_1"),
            620: TimeOfDay("ID_Einst_SuSwb25_zeit_0_2"),
            621: TimeOfDay("ID_Einst_SuSwb25_zeit_0_3"),
            622: TimeOfDay("ID_Einst_SuSwb25_zeit_1_2"),
            623: TimeOfDay("ID_Einst_SuSwb25_zeit_1_3"),
            624: TimeOfDay("ID_Einst_SuSwb25_zeit_2_2"),
            625: TimeOfDay("ID_Einst_SuSwb25_zeit_2_3"),
            626: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_0"),
            627: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_1"),
            628: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_0"),
            629: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_1"),
            630: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_0"),
            631: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_1"),
            632: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_2"),
            633: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_3"),
            634: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_2"),
            635: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_3"),
            636: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_2"),
            637: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_3"),
            638: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_4"),
            639: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_5"),
            640: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_4"),
            641: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_5"),
            642: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_4"),
            643: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_5"),
            644: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_6"),
            645: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_7"),
            646: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_6"),
            647: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_7"),
            648: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_6"),
            649: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_7"),
            650: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_8"),
            651: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_9"),
            652: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_8"),
            653: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_9"),
            654: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_8"),
            655: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_9"),
            656: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_10"),
            657: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_11"),
            658: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_10"),
            659: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_11"),
            660: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_10"),
            661: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_11"),
            662: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_12"),
            663: TimeOfDay("ID_Einst_SuSwbTg_zeit_0_13"),
            664: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_12"),
            665: TimeOfDay("ID_Einst_SuSwbTg_zeit_1_13"),
            666: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_12"),
            667: TimeOfDay("ID_Einst_SuSwbTg_zeit_2_13"),
            668: Seconds("ID_Zaehler_BetrZeitWP"),
            669: Seconds("ID_Zaehler_BetrZeitVD1"),
            670: Seconds("ID_Zaehler_BetrZeitVD2"),
            671: Seconds("ID_Zaehler_BetrZeitZWE1"),
            672: Seconds("ID_Zaehler_BetrZeitZWE2"),
            673: Seconds("ID_Zaehler_BetrZeitZWE3"),
            674: Count("ID_Zaehler_BetrZeitImpVD1"),
            675: Count("ID_Zaehler_BetrZeitImpVD2"),
            676: Unknown("ID_Zaehler_BetrZeitEZMVD1"),
            677: Unknown("ID_Zaehler_BetrZeitEZMVD2"),
            678: Unknown("ID_Einst_Entl_Typ_0"),
            679: Unknown("ID_Einst_Entl_Typ_1"),
            680: Unknown("ID_Einst_Entl_Typ_2"),
            681: Unknown("ID_Einst_Entl_Typ_3"),
            682: Unknown("ID_Einst_Entl_Typ_4"),
            683: Unknown("ID_Einst_Entl_Typ_5"),
            684: Unknown("ID_Einst_Entl_Typ_6"),
            685: Unknown("ID_Einst_Entl_Typ_7"),
            686: Unknown("ID_Einst_Entl_Typ_8"),
            687: Unknown("ID_Einst_Entl_Typ_9"),
            688: Unknown("ID_Einst_Entl_Typ_10"),
            689: Unknown("ID_Einst_Entl_Typ_11"),
            690: Unknown("ID_Einst_Entl_Typ_12"),
            691: Unknown("ID_Einst_Vorl_max_MK1"),
            692: Unknown("ID_Einst_Vorl_max_MK2"),
            693: Unknown("ID_SU_FrkdMK1"),
            694: Unknown("ID_SU_FrkdMK2"),
            695: MixedCircuitMode("ID_Ba_Hz_MK1_akt"),
            696: MixedCircuitMode("ID_Ba_Hz_MK2_akt"),
            697: Unknown("ID_Einst_Zirk_Ein_akt"),
            698: Unknown("ID_Einst_Zirk_Aus_akt"),
            699: Unknown("ID_Einst_Heizgrenze"),
            700: Celsius("ID_Einst_Heizgrenze_Temp"),
            701: Unknown("ID_VariablenIBNgespeichert"),
            702: Unknown("ID_SchonIBNAssistant"),
            703: Unknown("ID_Heizgrenze_0"),
            704: Unknown("ID_Heizgrenze_1"),
            705: Unknown("ID_Heizgrenze_2"),
            706: Unknown("ID_Heizgrenze_3"),
            707: Unknown("ID_Heizgrenze_4"),
            708: Unknown("ID_Heizgrenze_5"),
            709: Unknown("ID_Heizgrenze_6"),
            710: Unknown("ID_Heizgrenze_7"),
            711: Unknown("ID_Heizgrenze_8"),
            712: Unknown("ID_Heizgrenze_9"),
            713: Unknown("ID_Heizgrenze_10"),
            714: Unknown("ID_Heizgrenze_11"),
            715: Unknown("ID_SchemenIBNgewahlt"),
            716: Unknown("ID_Switchoff_file_0_0"),
            717: Unknown("ID_Switchoff_file_1_0"),
            718: Unknown("ID_Switchoff_file_2_0"),
            719: Unknown("ID_Switchoff_file_3_0"),
            720: Unknown("ID_Switchoff_file_4_0"),
            721: Unknown("ID_Switchoff_file_0_1"),
            722: Unknown("ID_Switchoff_file_1_1"),
            723: Unknown("ID_Switchoff_file_2_1"),
            724: Unknown("ID_Switchoff_file_3_1"),
            725: Unknown("ID_Switchoff_file_4_1"),
            726: Unknown("ID_DauerDatenLoggerAktiv"),
            727: Unknown("ID_Laufvar_Heizgrenze"),
            728: Seconds("ID_Zaehler_BetrZeitHz"),
            729: Seconds("ID_Zaehler_BetrZeitBW"),
            730: Seconds("ID_Zaehler_BetrZeitKue"),
            731: Unknown("ID_SU_FstdHz"),
            732: Unknown("ID_SU_FstdBw"),
            733: Unknown("ID_SU_FstdSwb"),
            734: Unknown("ID_SU_FstdMK1"),
            735: Unknown("ID_SU_FstdMK2"),
            736: Unknown("ID_FerienAbsenkungHz"),
            737: Unknown("ID_FerienAbsenkungMK1"),
            738: Unknown("ID_FerienAbsenkungMK2"),
            739: Unknown("ID_FerienModusAktivHz"),
            740: Unknown("ID_FerienModusAktivBw"),
            741: Unknown("ID_FerienModusAktivSwb"),
            742: Unknown("ID_FerienModusAktivMk1"),
            743: Unknown("ID_FerienModusAktivMk2"),
            744: Unknown("ID_DisplayContrast_akt"),
            745: Unknown("ID_Ba_Hz_saved"),
            746: Unknown("ID_Ba_Bw_saved"),
            747: Unknown("ID_Ba_Sw_saved"),
            748: Unknown("ID_Ba_Hz_MK1_saved"),
            749: Unknown("ID_Ba_Hz_MK2_saved"),
            750: Unknown("ID_AdresseIP_akt"),
            751: Unknown("ID_SubNetMask_akt"),
            752: Unknown("ID_Add_Broadcast_akt"),
            753: Unknown("ID_Add_StdGateway_akt"),
            754: Unknown("ID_DHCPServerAktiv_akt"),
            755: Unknown("ID_WebserverPasswort_1_akt"),
            756: Unknown("ID_WebserverPasswort_2_akt"),
            757: Unknown("ID_WebserverPasswort_3_akt"),
            758: Unknown("ID_WebserverPasswort_4_akt"),
            759: Unknown("ID_WebserverPasswort_5_akt"),
            760: Unknown("ID_WebserverPasswort_6_akt"),
            761: Unknown("ID_WebServerWerteBekommen"),
            762: Unknown("ID_Einst_ParBetr_akt"),
            763: Unknown("ID_Einst_WpAnz_akt"),
            764: Unknown("ID_Einst_PhrTime_akt"),
            765: Unknown("ID_Einst_HysPar_akt"),
            766: Unknown("ID_IP_PB_Slave_0"),
            767: Unknown("ID_IP_PB_Slave_1"),
            768: Unknown("ID_IP_PB_Slave_2"),
            769: Unknown("ID_IP_PB_Slave_3"),
            770: Unknown("ID_IP_PB_Slave_4"),
            771: Unknown("ID_IP_PB_Slave_5"),
            772: Unknown("ID_Einst_BwHup_akt_backup"),
            773: Unknown("ID_Einst_SuMk3_akt"),
            774: Celsius("ID_Einst_HzMK3E_akt", True),
            775: Celsius("ID_Einst_HzMK3ANH_akt", True),
            776: Celsius("ID_Einst_HzMK3ABS_akt", True),
            777: Unknown("ID_Einst_HzMK3Hgr_akt"),
            778: Unknown("ID_Einst_HzFtMK3Vl_akt"),
            779: MixedCircuitMode("ID_Ba_Hz_MK3_akt", True),
            780: Unknown("ID_Einst_MK3Typ_akt"),
            781: Unknown("ID_Einst_RTypMK3_akt"),
            782: Unknown("ID_Einst_MK3LzFaktor_akt"),
            783: Unknown("ID_Einst_MK3PerFaktor_akt"),
            784: Unknown("ID_FerienModusAktivMk3"),
            785: Unknown("ID_SU_FrkdMK3"),
            786: Unknown("ID_FerienAbsenkungMK3"),
            787: Unknown("ID_SU_FstdMK3"),
            788: TimerProgram("ID_Einst_SuMk3_akt2"),
            789: TimeOfDay("ID_Einst_SuMk3Wo_zeit_0_0"),
            790: TimeOfDay("ID_Einst_SuMk3Wo_zeit_0_1"),
            791: TimeOfDay("ID_Einst_SuMk3Wo_zeit_1_0"),
            792: TimeOfDay("ID_Einst_SuMk3Wo_zeit_1_1"),
            793: TimeOfDay("ID_Einst_SuMk3Wo_zeit_2_0"),
            794: TimeOfDay("ID_Einst_SuMk3Wo_zeit_2_1"),
            795: TimeOfDay("ID_Einst_SuMk325_zeit_0_0"),
            796: TimeOfDay("ID_Einst_SuMk325_zeit_0_1"),
            797: TimeOfDay("ID_Einst_SuMk325_zeit_1_0"),
            798: TimeOfDay("ID_Einst_SuMk325_zeit_1_1"),
            799: TimeOfDay("ID_Einst_SuMk325_zeit_2_0"),
            800: TimeOfDay("ID_Einst_SuMk325_zeit_2_1"),
            801: TimeOfDay("ID_Einst_SuMk325_zeit_0_2"),
            802: TimeOfDay("ID_Einst_SuMk325_zeit_0_3"),
            803: TimeOfDay("ID_Einst_SuMk325_zeit_1_2"),
            804: TimeOfDay("ID_Einst_SuMk325_zeit_1_3"),
            805: TimeOfDay("ID_Einst_SuMk325_zeit_2_2"),
            806: TimeOfDay("ID_Einst_SuMk325_zeit_2_3"),
            807: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_0"),
            808: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_1"),
            809: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_0"),
            810: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_1"),
            811: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_0"),
            812: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_1"),
            813: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_2"),
            814: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_3"),
            815: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_2"),
            816: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_3"),
            817: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_2"),
            818: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_3"),
            819: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_4"),
            820: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_5"),
            821: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_4"),
            822: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_5"),
            823: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_4"),
            824: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_5"),
            825: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_6"),
            826: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_7"),
            827: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_6"),
            828: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_7"),
            829: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_6"),
            830: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_7"),
            831: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_8"),
            832: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_9"),
            833: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_8"),
            834: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_9"),
            835: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_8"),
            836: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_9"),
            837: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_10"),
            838: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_11"),
            839: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_10"),
            840: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_11"),
            841: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_10"),
            842: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_11"),
            843: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_12"),
            844: TimeOfDay("ID_Einst_SuMk3Tg_zeit_0_13"),
            845: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_12"),
            846: TimeOfDay("ID_Einst_SuMk3Tg_zeit_1_13"),
            847: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_12"),
            848: TimeOfDay("ID_Einst_SuMk3Tg_zeit_2_13"),
            849: Unknown("ID_Ba_Hz_MK3_saved"),
            850: Hours("ID_Einst_Kuhl_Zeit_Ein_akt", True),
            851: Hours("ID_Einst_Kuhl_Zeit_Aus_akt", True),
            852: Energy("ID_Waermemenge_Seit"),
            853: Unknown("ID_Waermemenge_WQ"),
            854: Energy("ID_Waermemenge_Hz"),
            855: Unknown("ID_Waermemenge_WQ_ges"),
            856: Unknown("ID_Einst_Entl_Typ_13"),
            857: Unknown("ID_Einst_Entl_Typ_14"),
            858: Unknown("ID_Einst_Entl_Typ_15"),
            859: Seconds("ID_Zaehler_BetrZeitSW"),
            860: Unknown("ID_Einst_Fernwartung_akt"),
            861: Unknown("ID_AdresseIPServ_akt"),
            862: Unknown("ID_Einst_TA_EG_akt"),
            863: Unknown("ID_Einst_TVLmax_EG_akt"),
            864: Minutes("ID_Einst_Popt_Nachlauf_akt", True),
            865: Unknown("ID_FernwartungVertrag_akt"),
            866: Unknown("ID_FernwartungAktuZeit"),
            867: Unknown("ID_Einst_Effizienzpumpe_Nominal_akt"),
            868: Unknown("ID_Einst_Effizienzpumpe_Minimal_akt"),
            869: Unknown("ID_Einst_Effizienzpumpe_akt"),
            870: Unknown("ID_Einst_Waermemenge_akt"),
            871: Unknown("ID_Einst_Wm_Versorgung_Korrektur_akt"),
            872: Unknown("ID_Einst_Wm_Auswertung_Korrektur_akt"),
            873: Unknown("ID_SoftwareUpdateJetztGemacht_akt"),
            874: Unknown("ID_WP_SerienNummer_DATUM"),
            875: Unknown("ID_WP_SerienNummer_HEX"),
            876: Unknown("ID_WP_SerienNummer_INDEX"),
            877: Unknown("ID_ProgWerteWebSrvBeobarten"),
            878: Energy("ID_Waermemenge_BW"),
            879: Energy("ID_Waermemenge_SW"),
            880: Timestamp("ID_Waermemenge_Datum"),
            881: SolarMode("ID_Einst_Solar_akt", True),
            882: Unknown("ID_BSTD_Solar"),
            883: Celsius("ID_Einst_TDC_Koll_Max_akt"),
            884: Unknown("ID_Einst_Akt_Kuehlung_akt"),
            885: Unknown("ID_Einst_Vorlauf_VBO_akt"),
            886: Unknown("ID_Einst_KRHyst_akt"),
            887: Unknown("ID_Einst_Akt_Kuehl_Speicher_min_akt"),
            888: Unknown("ID_Einst_Akt_Kuehl_Freig_WQE_akt"),
            889: Unknown("ID_NDAB_WW_Anzahl"),
            890: Unknown("ID_NDS_WW_KD_Quitt"),
            891: Unknown("ID_Einst_AbtZykMin_akt"),
            892: Unknown("ID_Einst_VD2_Zeit_Min_akt"),
            893: Unknown("ID_Einst_Hysterese_HR_verkuerzt_akt"),
            894: VentilationMode("ID_Einst_BA_Lueftung_akt", True),
            895: TimerProgram("ID_Einst_SuLuf_akt"),
            896: TimeOfDay2("ID_Einst_SuLufWo_zeit_0_0_0"),
            897: TimeOfDay2("ID_Einst_SuLufWo_zeit_0_1_0"),
            898: TimeOfDay2("ID_Einst_SuLufWo_zeit_0_2_0"),
            899: TimeOfDay2("ID_Einst_SuLuf25_zeit_0_0_0"),
            900: TimeOfDay2("ID_Einst_SuLuf25_zeit_0_1_0"),
            901: TimeOfDay2("ID_Einst_SuLuf25_zeit_0_2_0"),
            902: TimeOfDay2("ID_Einst_SuLuf25_zeit_0_0_2"),
            903: TimeOfDay2("ID_Einst_SuLuf25_zeit_0_1_2"),
            904: TimeOfDay2("ID_Einst_SuLuf25_zeit_0_2_2"),
            905: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_0_0"),
            906: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_1_0"),
            907: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_2_0"),
            908: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_0_2"),
            909: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_1_2"),
            910: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_2_2"),
            911: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_0_4"),
            912: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_1_4"),
            913: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_2_4"),
            914: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_0_6"),
            915: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_1_6"),
            916: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_2_6"),
            917: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_0_8"),
            918: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_1_8"),
            919: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_2_8"),
            920: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_0_10"),
            921: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_1_10"),
            922: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_2_10"),
            923: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_0_12"),
            924: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_1_12"),
            925: TimeOfDay2("ID_Einst_SuLufTg_zeit_0_2_12"),
            926: TimeOfDay2("ID_Einst_SuLufWo_zeit_1_0_0"),
            927: TimeOfDay2("ID_Einst_SuLufWo_zeit_1_1_0"),
            928: TimeOfDay2("ID_Einst_SuLufWo_zeit_1_2_0"),
            929: TimeOfDay2("ID_Einst_SuLuf25_zeit_1_0_0"),
            930: TimeOfDay2("ID_Einst_SuLuf25_zeit_1_1_0"),
            931: TimeOfDay2("ID_Einst_SuLuf25_zeit_1_2_0"),
            932: TimeOfDay2("ID_Einst_SuLuf25_zeit_1_0_2"),
            933: TimeOfDay2("ID_Einst_SuLuf25_zeit_1_1_2"),
            934: TimeOfDay2("ID_Einst_SuLuf25_zeit_1_2_2"),
            935: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_0_0"),
            936: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_1_0"),
            937: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_2_0"),
            938: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_0_2"),
            939: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_1_2"),
            940: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_2_2"),
            941: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_0_4"),
            942: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_1_4"),
            943: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_2_4"),
            944: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_0_6"),
            945: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_1_6"),
            946: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_2_6"),
            947: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_0_8"),
            948: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_1_8"),
            949: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_2_8"),
            950: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_0_10"),
            951: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_1_10"),
            952: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_2_10"),
            953: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_0_12"),
            954: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_1_12"),
            955: TimeOfDay2("ID_Einst_SuLufTg_zeit_1_2_12"),
            956: Unknown("ID_FerienModusAktivLueftung"),
            957: Unknown("ID_Einst_BA_Lueftung_saved"),
            958: Unknown("ID_SU_FrkdLueftung"),
            959: Unknown("ID_SU_FstdLueftung"),
            960: Unknown("ID_Einst_Luf_Feuchteschutz_akt"),
            961: Unknown("ID_Einst_Luf_Reduziert_akt"),
            962: Unknown("ID_Einst_Luf_Nennlueftung_akt"),
            963: Unknown("ID_Einst_Luf_Intensivlueftung_akt"),
            964: Unknown("ID_Timer_Fil_4Makt"),
            965: Unknown("ID_Timer_Fil_WoAkt"),
            966: Celsius("ID_Sollwert_KuCft3_akt", True),
            967: Celsius("ID_Sollwert_AtDif3_akt", True),
            968: Unknown("ID_Bitmaske_0"),
            969: Unknown("ID_Einst_Lueftungsstufen"),
            970: Unknown("ID_SysEin_Meldung_TDI"),
            971: Unknown("ID_SysEin_Typ_WZW"),
            972: Unknown("ID_Einst_GLT_aktiviert"),
            973: Unknown("ID_Einst_BW_max"),
            974: Unknown("ID_Einst_Sollwert_TRL_Kuehlen"),
            975: Unknown("ID_Einst_Medium_Waermequelle"),
            976: Unknown("ID_Einst_Photovoltaik_akt"),
            977: Unknown("ID_Einst_Multispeicher_akt"),
            978: Unknown("ID_Einst_PKuehlTime_akt"),
            979: Celsius("ID_Einst_Minimale_Ruecklaufsolltemperatur", True),
            980: Unknown("ID_RBE_Einflussfaktor_RT_akt"),
            981: Unknown("ID_RBE_Freigabe_Kuehlung_akt"),
            982: Unknown("ID_RBE_Waermeverteilsystem_akt"),
            983: Unknown("ID_RBE_Zeit_Heizstab_aktiv"),
            984: Unknown("ID_SEC_ND_Alarmgrenze"),
            985: Unknown("ID_SEC_HD_Alarmgrenze"),
            986: Unknown("ID_SEC_Abtauendtemperatur"),
            987: Unknown("ID_Einst_Min_RPM_BW"),
            988: Unknown("ID_Einst_Luf_Feuchteschutz_Faktor_akt"),
            989: Unknown("ID_Einst_Luf_Reduziert_Faktor_akt"),
            990: Unknown("ID_Einst_Luf_Nennlueftung_Faktor_akt"),
            991: Unknown("ID_Einst_Luf_Intensivlueftung_Faktor_akt"),
            992: Minutes("ID_Einst_Freigabe_Zeit_ZWE", True),
            993: Unknown("ID_Einst_min_VL_Kuehl"),
            994: Bool("ID_Einst_Warmwasser_Nachheizung", True),
            995: Unknown("ID_Switchoff_file_LWD2_0_0"),
            996: Unknown("ID_Switchoff_file_LWD2_1_0"),
            997: Unknown("ID_Switchoff_file_LWD2_2_0"),
            998: Unknown("ID_Switchoff_file_LWD2_3_0"),
            999: Unknown("ID_Switchoff_file_LWD2_4_0"),
            1000: Unknown("ID_Switchoff_file_LWD2_0_1"),
            1001: Unknown("ID_Switchoff_file_LWD2_1_1"),
            1002: Unknown("ID_Switchoff_file_LWD2_2_1"),
            1003: Unknown("ID_Switchoff_file_LWD2_3_1"),
            1004: Unknown("ID_Switchoff_file_LWD2_4_1"),
            1005: Unknown("ID_Switchoff_index_LWD2"),
            1006: Unknown("ID_Einst_Effizienzpumpe_Nominal_2"),
            1007: Unknown("ID_Einst_Effizienzpumpe_Minimal_2"),
            1008: Unknown("ID_Einst_Wm_Versorgung_Korrektur_2"),
            1009: Unknown("ID_Einst_Wm_Auswertung_Korrektur_2"),
            1010: Unknown("ID_Einst_isTwin"),
            1011: Unknown("ID_Einst_TAmin_2"),
            1012: Unknown("ID_Einst_TVLmax_2"),
            1013: Unknown("ID_Einst_TA_EG_2"),
            1014: Unknown("ID_Einst_TVLmax_EG_2"),
            1015: Unknown("ID_Waermemenge_Hz_2"),
            1016: Unknown("ID_Waermemenge_BW_2"),
            1017: Unknown("ID_Waermemenge_SW_2"),
            1018: Unknown("ID_Waermemenge_Seit_2"),
            1019: Unknown("ID_Einst_Entl_Typ_15_2"),
            1020: Hours2("ID_Einst_WW_Nachheizung_max", True),
            1021: Unknown("ID_Einst_Kuhl_Zeit_Ein_RT"),
            1022: Unknown("ID_Einst_ZWE1_Pos"),
            1023: Unknown("ID_Einst_ZWE2_Pos"),
            1024: Unknown("ID_Einst_ZWE3_Pos"),
            1025: Unknown("ID_Einst_Leistung_ZWE"),
            1026: Unknown("ID_WP_SN2_DATUM"),
            1027: Unknown("ID_WP_SN2_HEX"),
            1028: Unknown("ID_WP_SN2_INDEX"),
            1029: Unknown("ID_CWP_saved2"),
            1030: Unknown("ID_Einst_SmartGrid"),
            1031: Unknown("ID_Einst_P155_HDS"),
            1032: Unknown("ID_Einst_P155_PumpHeat_Max"),
            1033: Unknown("ID_Einst_P155_PumpHeatCtrl"),
            1034: Unknown("ID_Einst_P155_PumpDHWCtrl"),
            1035: Unknown("ID_Einst_P155_PumpDHW_RPM"),
            1036: Unknown("ID_Einst_P155_PumpPoolCtrl"),
            1037: Unknown("ID_Einst_P155_PumpPool_RPM"),
            1038: Unknown("ID_Einst_P155_PumpCool_RPM"),
            1039: Unknown("ID_Einst_P155_PumpVBOCtrl"),
            1040: Unknown("ID_Einst_P155_PumpVBO_RPM_C"),
            1041: Unknown("ID_Einst_P155_PumpDHW_Max"),
            1042: Unknown("ID_Einst_P155_PumpPool_Max"),
            1043: Unknown("ID_Einst_P155_Sperrband_1"),
            1044: Unknown("ID_Einst_P155_Leistungsfreigabe"),
            1045: Unknown("ID_Einst_P155_DHW_Freq"),
            1046: Unknown("ID_Einst_SWHUP"),
            1047: Unknown("ID_Einst_P155_SWB_Freq"),
            1048: Unknown("ID_Einst_MK1_Regelung"),
            1049: Unknown("ID_Einst_MK2_Regelung"),
            1050: Unknown("ID_Einst_MK3_Regelung"),
            1051: Unknown("ID_Einst_PV_WW_Sperrzeit"),
            1052: Unknown("ID_Einst_Warmwasser_extra"),
            1053: Unknown("ID_Einst_Vorl_akt_Kuehl"),
            1054: Unknown("ID_WP_SN3_DATUM"),
            1055: Unknown("ID_WP_SN3_HEX"),
            1056: Unknown("ID_WP_SN3_INDEX"),
            1057: Unknown("ID_Einst_Vorlauf_ZUP"),
            1058: Unknown("ID_Einst_Abtauen_im_Warmwasser"),
            1059: Energy("ID_Waermemenge_ZWE"),
            1060: Energy("ID_Waermemenge_Reset"),
            1061: Unknown("ID_Waermemenge_Reset_2"),
            1062: Unknown("ID_Einst_Brunnenpumpe_min"),
            1063: Unknown("ID_Einst_Brunnenpumpe_max"),
            1064: Unknown("ID_Einst_SmartHomeID"),
            1065: Unknown("ID_Einst_SmartHK"),
            1066: Unknown("ID_Einst_SmartMK1"),
            1067: Unknown("ID_Einst_SmartMK2"),
            1068: Unknown("ID_Einst_SmartMK3"),
            1069: Unknown("ID_Einst_SmartWW"),
            1070: Unknown("ID_Einst_SmartDefrost"),
            1071: Unknown("ID_Einst_Empty1071"),
            1072: Unknown("ID_Einst_MinVLMK1"),
            1073: Unknown("ID_Einst_MinVLMK2"),
            1074: Unknown("ID_Einst_MinVLMK3"),
            1075: Unknown("ID_Einst_MaxVLMK1"),
            1076: Unknown("ID_Einst_MaxVLMK2"),
            1077: Unknown("ID_Einst_MaxVLMK3"),
            1078: Unknown("ID_Einst_SmartPlusHz"),
            1079: Unknown("ID_Einst_SmartMinusHz"),
            1080: Unknown("ID_Einst_SmartPlusMK1"),
            1081: Unknown("ID_Einst_SmartMinusMK1"),
            1082: Unknown("ID_Einst_SmartPlusMK2"),
            1083: Unknown("ID_Einst_SmartMinusMK2"),
            1084: Unknown("ID_Einst_SmartPlusMK3"),
            1085: Unknown("ID_Einst_SmartMinusMK3"),
            1086: Unknown("Unknown_Parameter_1086"),
            1087: Unknown("Unknown_Parameter_1087"),
            1088: Unknown("Unknown_Parameter_1088"),
            1089: Unknown("Unknown_Parameter_1089"),
            1090: Unknown("Unknown_Parameter_1090"),
            1091: Unknown("Unknown_Parameter_1091"),
            1092: TimerProgram("ID_Einst_SuSilence"),
            1093: TimeOfDay2("ID_Einst_SilenceTimer_0"),
            1094: TimeOfDay2("ID_Einst_SilenceTimer_1"),
            1095: TimeOfDay2("ID_Einst_SilenceTimer_2"),
            1096: TimeOfDay2("ID_Einst_SilenceTimer_3"),
            1097: TimeOfDay2("ID_Einst_SilenceTimer_4"),
            1098: TimeOfDay2("ID_Einst_SilenceTimer_5"),
            1099: TimeOfDay2("ID_Einst_SilenceTimer_6"),
            1100: TimeOfDay2("ID_Einst_SilenceTimer_7"),
            1101: TimeOfDay2("ID_Einst_SilenceTimer_8"),
            1102: TimeOfDay2("ID_Einst_SilenceTimer_9"),
            1103: TimeOfDay2("ID_Einst_SilenceTimer_10"),
            1104: TimeOfDay2("ID_Einst_SilenceTimer_11"),
            1105: TimeOfDay2("ID_Einst_SilenceTimer_12"),
            1106: TimeOfDay2("ID_Einst_SilenceTimer_13"),
            1107: TimeOfDay2("ID_Einst_SilenceTimer_14"),
            1108: TimeOfDay2("ID_Einst_SilenceTimer_15"),
            1109: TimeOfDay2("ID_Einst_SilenceTimer_16"),
            1110: TimeOfDay2("ID_Einst_SilenceTimer_17"),
            1111: TimeOfDay2("ID_Einst_SilenceTimer_18"),
            1112: TimeOfDay2("ID_Einst_SilenceTimer_19"),
            1113: TimeOfDay2("ID_Einst_SilenceTimer_20"),
            1114: Unknown("Unknown_Parameter_1114"),
            1115: Unknown("Unknown_Parameter_1115"),
            1116: Unknown("Unknown_Parameter_1116"),
            1117: Unknown("Unknown_Parameter_1117"),
            1118: Unknown("Unknown_Parameter_1118"),
            1119: Unknown("Unknown_Parameter_1119"),
            1120: Unknown("Unknown_Parameter_1120"),
            1121: Unknown("Unknown_Parameter_1121"),
            1122: Unknown("Unknown_Parameter_1122"),
            1123: Unknown("Unknown_Parameter_1123"),
            1124: Unknown("Unknown_Parameter_1124"),
            1125: Unknown("Unknown_Parameter_1125"),
            1126: Unknown("Unknown_Parameter_1126"),
            1127: Unknown("Unknown_Parameter_1127"),
            1128: Unknown("Unknown_Parameter_1128"),
            1129: Unknown("Unknown_Parameter_1129"),
            1130: Unknown("Unknown_Parameter_1130"),
            1131: Unknown("Unknown_Parameter_1131"),
            1132: Unknown("Unknown_Parameter_1132"),
            1133: Unknown("Unknown_Parameter_1133"),
            1134: Unknown("Unknown_Parameter_1134"),
            1135: Unknown("Unknown_Parameter_1135"),
            1136: Unknown("Unknown_Parameter_1136"),
            1137: Unknown("Unknown_Parameter_1137"),
            1138: Unknown("Unknown_Parameter_1138"),
            1139: Unknown("Unknown_Parameter_1139"),
            1140: Unknown("Unknown_Parameter_1140"),
            1141: Unknown("Unknown_Parameter_1141"),
            1142: Unknown("Unknown_Parameter_1142"),
            1143: Unknown("Unknown_Parameter_1143"),
            1144: Unknown("Unknown_Parameter_1144"),
            1145: Unknown("Unknown_Parameter_1145"),
            1146: Unknown("Unknown_Parameter_1146"),
            1147: Unknown("Unknown_Parameter_1147"),
            1148: Unknown("Unknown_Parameter_1148"),
            1149: Unknown("Unknown_Parameter_1149"),
            1150: Unknown("Unknown_Parameter_1150"),
            1151: Unknown("Unknown_Parameter_1151"),
            1152: Unknown("Unknown_Parameter_1152"),
        }

    def set(self, target, value):
        """Set parameter to new value."""
        index, parameter = self._lookup(target, with_index=True)
        if index is not None:
            if parameter.writeable or not self.safe:
                self.queue[index] = parameter.to_heatpump(value)
            else:
                self.logger.warning("Parameter '%s' not safe for writing!", parameter.name)
        else:
            self.logger.warning("Parameter '%s' not found", target)
