"""Parse luxtronik visibilities."""

import logging

from luxtronik.data_vector import DataVector

from luxtronik.datatypes import Unknown


class Visibilities(DataVector):
    """Class that holds all visibilities."""

    logger = logging.getLogger("Luxtronik.Visibilities")
    name = "Visibility"

    def __init__(self):
        super().__init__()
        self._data = {
            0: Unknown(["ID_Visi_NieAnzeigen", "Unknown_Visibility_0"]),
            1: Unknown(["ID_Visi_ImmerAnzeigen", "Unknown_Visibility_1"]),
            2: Unknown(["ID_Visi_Heizung", "Unknown_Visibility_2"]),
            3: Unknown(["ID_Visi_Brauwasser", "Unknown_Visibility_3"]),
            4: Unknown(["ID_Visi_Schwimmbad", "Unknown_Visibility_4"]),
            5: Unknown(["ID_Visi_Kuhlung", "Unknown_Visibility_5"]),
            6: Unknown(["ID_Visi_Lueftung", "Unknown_Visibility_6"]),
            7: Unknown(["ID_Visi_MK1", "Unknown_Visibility_7"]),
            8: Unknown(["ID_Visi_MK2", "Unknown_Visibility_8"]),
            9: Unknown(["ID_Visi_ThermDesinfekt", "Unknown_Visibility_9"]),
            10: Unknown(["ID_Visi_Zirkulation", "Unknown_Visibility_10"]),
            11: Unknown(["ID_Visi_KuhlTemp_SolltempMK1", "Unknown_Visibility_11"]),
            12: Unknown(["ID_Visi_KuhlTemp_SolltempMK2", "Unknown_Visibility_12"]),
            13: Unknown(["ID_Visi_KuhlTemp_ATDiffMK1", "Unknown_Visibility_13"]),
            14: Unknown(["ID_Visi_KuhlTemp_ATDiffMK2", "Unknown_Visibility_14"]),
            15: Unknown(["ID_Visi_Service_Information", "Unknown_Visibility_15"]),
            16: Unknown(["ID_Visi_Service_Einstellung", "Unknown_Visibility_16"]),
            17: Unknown(["ID_Visi_Service_Sprache", "Unknown_Visibility_17"]),
            18: Unknown(["ID_Visi_Service_DatumUhrzeit", "Unknown_Visibility_18"]),
            19: Unknown(["ID_Visi_Service_Ausheiz", "Unknown_Visibility_19"]),
            20: Unknown(["ID_Visi_Service_Anlagenkonfiguration", "Unknown_Visibility_20"]),
            21: Unknown(["ID_Visi_Service_IBNAssistant", "Unknown_Visibility_21"]),
            22: Unknown(["ID_Visi_Service_ParameterIBNZuruck", "Unknown_Visibility_22"]),
            23: Unknown(["ID_Visi_Temp_Vorlauf", "Unknown_Visibility_23"]),
            24: Unknown(["ID_Visi_Temp_Rucklauf", "Unknown_Visibility_24"]),
            25: Unknown(["ID_Visi_Temp_RL_Soll", "Unknown_Visibility_25"]),
            26: Unknown(["ID_Visi_Temp_Ruecklext", "Unknown_Visibility_26"]),
            27: Unknown(["ID_Visi_Temp_Heissgas", "Unknown_Visibility_27"]),
            28: Unknown(["ID_Visi_Temp_Aussent", "Unknown_Visibility_28"]),
            29: Unknown(["ID_Visi_Temp_BW_Ist", "Unknown_Visibility_29"]),
            30: Unknown(["ID_Visi_Temp_BW_Soll", "Unknown_Visibility_30"]),
            31: Unknown(["ID_Visi_Temp_WQ_Ein", "Unknown_Visibility_31"]),
            32: Unknown(["ID_Visi_Temp_Kaltekreis", "Unknown_Visibility_32"]),
            33: Unknown(["ID_Visi_Temp_MK1_Vorlauf", "Unknown_Visibility_33"]),
            34: Unknown(["ID_Visi_Temp_MK1VL_Soll", "Unknown_Visibility_34"]),
            35: Unknown(["ID_Visi_Temp_Raumstation", "Unknown_Visibility_35"]),
            36: Unknown(["ID_Visi_Temp_MK2_Vorlauf", "Unknown_Visibility_36"]),
            37: Unknown(["ID_Visi_Temp_MK2VL_Soll", "Unknown_Visibility_37"]),
            38: Unknown(["ID_Visi_Temp_Solarkoll", "Unknown_Visibility_38"]),
            39: Unknown(["ID_Visi_Temp_Solarsp", "Unknown_Visibility_39"]),
            40: Unknown(["ID_Visi_Temp_Ext_Energ", "Unknown_Visibility_40"]),
            41: Unknown(["ID_Visi_IN_ASD", "Unknown_Visibility_41"]),
            42: Unknown(["ID_Visi_IN_BWT", "Unknown_Visibility_42"]),
            43: Unknown(["ID_Visi_IN_EVU", "Unknown_Visibility_43"]),
            44: Unknown(["ID_Visi_IN_HD", "Unknown_Visibility_44"]),
            45: Unknown(["ID_Visi_IN_MOT", "Unknown_Visibility_45"]),
            46: Unknown(["ID_Visi_IN_ND", "Unknown_Visibility_46"]),
            47: Unknown(["ID_Visi_IN_PEX", "Unknown_Visibility_47"]),
            48: Unknown(["ID_Visi_IN_SWT", "Unknown_Visibility_48"]),
            49: Unknown(["ID_Visi_OUT_Abtauventil", "Unknown_Visibility_49"]),
            50: Unknown(["ID_Visi_OUT_BUP", "Unknown_Visibility_50"]),
            51: Unknown(["ID_Visi_OUT_FUP1", "Unknown_Visibility_51"]),
            52: Unknown(["ID_Visi_OUT_HUP", "Unknown_Visibility_52"]),
            53: Unknown(["ID_Visi_OUT_Mischer1Auf", "Unknown_Visibility_53"]),
            54: Unknown(["ID_Visi_OUT_Mischer1Zu", "Unknown_Visibility_54"]),
            55: Unknown(["ID_Visi_OUT_Ventilation", "Unknown_Visibility_55"]),
            56: Unknown(["ID_Visi_OUT_Ventil_BOSUP", "Unknown_Visibility_56"]),
            57: Unknown(["ID_Visi_OUT_Verdichter1", "Unknown_Visibility_57"]),
            58: Unknown(["ID_Visi_OUT_Verdichter2", "Unknown_Visibility_58"]),
            59: Unknown(["ID_Visi_OUT_ZIP", "Unknown_Visibility_59"]),
            60: Unknown(["ID_Visi_OUT_ZUP", "Unknown_Visibility_60"]),
            61: Unknown(["ID_Visi_OUT_ZWE1", "Unknown_Visibility_61"]),
            62: Unknown(["ID_Visi_OUT_ZWE2_SST", "Unknown_Visibility_62"]),
            63: Unknown(["ID_Visi_OUT_ZWE3", "Unknown_Visibility_63"]),
            64: Unknown(["ID_Visi_OUT_FUP2", "Unknown_Visibility_64"]),
            65: Unknown(["ID_Visi_OUT_SLP", "Unknown_Visibility_65"]),
            66: Unknown(["ID_Visi_OUT_SUP", "Unknown_Visibility_66"]),
            67: Unknown(["ID_Visi_OUT_Mischer2Auf", "Unknown_Visibility_67"]),
            68: Unknown(["ID_Visi_OUT_Mischer2Zu", "Unknown_Visibility_68"]),
            69: Unknown(["ID_Visi_AblaufZ_WP_Seit", "Unknown_Visibility_69"]),
            70: Unknown(["ID_Visi_AblaufZ_ZWE1_seit", "Unknown_Visibility_70"]),
            71: Unknown(["ID_Visi_AblaufZ_ZWE2_seit", "Unknown_Visibility_71"]),
            72: Unknown(["ID_Visi_AblaufZ_ZWE3_seit", "Unknown_Visibility_72"]),
            73: Unknown(["ID_Visi_AblaufZ_Netzeinv", "Unknown_Visibility_73"]),
            74: Unknown(["ID_Visi_AblaufZ_SSP_Zeit1", "Unknown_Visibility_74"]),
            75: Unknown(["ID_Visi_AblaufZ_VD_Stand", "Unknown_Visibility_75"]),
            76: Unknown(["ID_Visi_AblaufZ_HRM_Zeit", "Unknown_Visibility_76"]),
            77: Unknown(["ID_Visi_AblaufZ_HRW_Zeit", "Unknown_Visibility_77"]),
            78: Unknown(["ID_Visi_AblaufZ_TDI_seit", "Unknown_Visibility_78"]),
            79: Unknown(["ID_Visi_AblaufZ_Sperre_BW", "Unknown_Visibility_79"]),
            80: Unknown(["ID_Visi_Bst_BStdVD1", "Unknown_Visibility_80"]),
            81: Unknown(["ID_Visi_Bst_ImpVD1", "Unknown_Visibility_81"]),
            82: Unknown(["ID_Visi_Bst_dEZVD1", "Unknown_Visibility_82"]),
            83: Unknown(["ID_Visi_Bst_BStdVD2", "Unknown_Visibility_83"]),
            84: Unknown(["ID_Visi_Bst_ImpVD2", "Unknown_Visibility_84"]),
            85: Unknown(["ID_Visi_Bst_dEZVD2", "Unknown_Visibility_85"]),
            86: Unknown(["ID_Visi_Bst_BStdZWE1", "Unknown_Visibility_86"]),
            87: Unknown(["ID_Visi_Bst_BStdZWE2", "Unknown_Visibility_87"]),
            88: Unknown(["ID_Visi_Bst_BStdZWE3", "Unknown_Visibility_88"]),
            89: Unknown(["ID_Visi_Bst_BStdWP", "Unknown_Visibility_89"]),
            90: Unknown(["ID_Visi_Text_Kurzprogramme", "Unknown_Visibility_90"]),
            91: Unknown(["ID_Visi_Text_Zwangsheizung", "Unknown_Visibility_91"]),
            92: Unknown(["ID_Visi_Text_Zwangsbrauchwasser", "Unknown_Visibility_92"]),
            93: Unknown(["ID_Visi_Text_Abtauen", "Unknown_Visibility_93"]),
            94: Unknown(["ID_Visi_EinstTemp_RucklBegr", "Unknown_Visibility_94"]),
            95: Unknown(["ID_Visi_EinstTemp_HystereseHR", "Unknown_Visibility_95"]),
            96: Unknown(["ID_Visi_EinstTemp_TRErhmax", "Unknown_Visibility_96"]),
            97: Unknown(["ID_Visi_EinstTemp_Freig2VD", "Unknown_Visibility_97"]),
            98: Unknown(["ID_Visi_EinstTemp_FreigZWE", "Unknown_Visibility_98"]),
            99: Unknown(["ID_Visi_EinstTemp_Tluftabt", "Unknown_Visibility_99"]),
            100: Unknown(["ID_Visi_EinstTemp_TDISolltemp", "Unknown_Visibility_100"]),
            101: Unknown(["ID_Visi_EinstTemp_HystereseBW", "Unknown_Visibility_101"]),
            102: Unknown(["ID_Visi_EinstTemp_Vorl2VDBW", "Unknown_Visibility_102"]),
            103: Unknown(["ID_Visi_EinstTemp_TAussenmax", "Unknown_Visibility_103"]),
            104: Unknown(["ID_Visi_EinstTemp_TAussenmin", "Unknown_Visibility_104"]),
            105: Unknown(["ID_Visi_EinstTemp_TWQmin", "Unknown_Visibility_105"]),
            106: Unknown(["ID_Visi_EinstTemp_THGmax", "Unknown_Visibility_106"]),
            107: Unknown(["ID_Visi_EinstTemp_TLABTEnde", "Unknown_Visibility_107"]),
            108: Unknown(["ID_Visi_EinstTemp_Absenkbis", "Unknown_Visibility_108"]),
            109: Unknown(["ID_Visi_EinstTemp_Vorlaufmax", "Unknown_Visibility_109"]),
            110: Unknown(["ID_Visi_EinstTemp_TDiffEin", "Unknown_Visibility_110"]),
            111: Unknown(["ID_Visi_EinstTemp_TDiffAus", "Unknown_Visibility_111"]),
            112: Unknown(["ID_Visi_EinstTemp_TDiffmax", "Unknown_Visibility_112"]),
            113: Unknown(["ID_Visi_EinstTemp_TEEHeizung", "Unknown_Visibility_113"]),
            114: Unknown(["ID_Visi_EinstTemp_TEEBrauchw", "Unknown_Visibility_114"]),
            115: Unknown(["ID_Visi_EinstTemp_Vorl2VDSW", "Unknown_Visibility_115"]),
            116: Unknown(["ID_Visi_EinstTemp_VLMaxMk1", "Unknown_Visibility_116"]),
            117: Unknown(["ID_Visi_EinstTemp_VLMaxMk2", "Unknown_Visibility_117"]),
            118: Unknown(["ID_Visi_Priori_Brauchwasser", "Unknown_Visibility_118"]),
            119: Unknown(["ID_Visi_Priori_Heizung", "Unknown_Visibility_119"]),
            120: Unknown(["ID_Visi_Priori_Schwimmbad", "Unknown_Visibility_120"]),
            121: Unknown(["ID_Visi_SysEin_EVUSperre", "Unknown_Visibility_121"]),
            122: Unknown(["ID_Visi_SysEin_Raumstation", "Unknown_Visibility_122"]),
            123: Unknown(["ID_Visi_SysEin_Einbindung", "Unknown_Visibility_123"]),
            124: Unknown(["ID_Visi_SysEin_Mischkreis1", "Unknown_Visibility_124"]),
            125: Unknown(["ID_Visi_SysEin_Mischkreis2", "Unknown_Visibility_125"]),
            126: Unknown(["ID_Visi_SysEin_ZWE1Art", "Unknown_Visibility_126"]),
            127: Unknown(["ID_Visi_SysEin_ZWE1Fkt", "Unknown_Visibility_127"]),
            128: Unknown(["ID_Visi_SysEin_ZWE2Art", "Unknown_Visibility_128"]),
            129: Unknown(["ID_Visi_SysEin_ZWE2Fkt", "Unknown_Visibility_129"]),
            130: Unknown(["ID_Visi_SysEin_ZWE3Art", "Unknown_Visibility_130"]),
            131: Unknown(["ID_Visi_SysEin_ZWE3Fkt", "Unknown_Visibility_131"]),
            132: Unknown(["ID_Visi_SysEin_Stoerung", "Unknown_Visibility_132"]),
            133: Unknown(["ID_Visi_SysEin_Brauchwasser1", "Unknown_Visibility_133"]),
            134: Unknown(["ID_Visi_SysEin_Brauchwasser2", "Unknown_Visibility_134"]),
            135: Unknown(["ID_Visi_SysEin_Brauchwasser3", "Unknown_Visibility_135"]),
            136: Unknown(["ID_Visi_SysEin_Brauchwasser4", "Unknown_Visibility_136"]),
            137: Unknown(["ID_Visi_SysEin_Brauchwasser5", "Unknown_Visibility_137"]),
            138: Unknown(["ID_Visi_SysEin_BWWPmax", "Unknown_Visibility_138"]),
            139: Unknown(["ID_Visi_SysEin_Abtzykmax", "Unknown_Visibility_139"]),
            140: Unknown(["ID_Visi_SysEin_Luftabt", "Unknown_Visibility_140"]),
            141: Unknown(["ID_Visi_SysEin_LuftAbtmax", "Unknown_Visibility_141"]),
            142: Unknown(["ID_Visi_SysEin_Abtauen1", "Unknown_Visibility_142"]),
            143: Unknown(["ID_Visi_SysEin_Abtauen2", "Unknown_Visibility_143"]),
            144: Unknown(["ID_Visi_SysEin_Pumpenoptim", "Unknown_Visibility_144"]),
            145: Unknown(["ID_Visi_SysEin_Zusatzpumpe", "Unknown_Visibility_145"]),
            146: Unknown(["ID_Visi_SysEin_Zugang", "Unknown_Visibility_146"]),
            147: Unknown(["ID_Visi_SysEin_SoledrDurchf", "Unknown_Visibility_147"]),
            148: Unknown(["ID_Visi_SysEin_UberwachungVD", "Unknown_Visibility_148"]),
            149: Unknown(["ID_Visi_SysEin_RegelungHK", "Unknown_Visibility_149"]),
            150: Unknown(["ID_Visi_SysEin_RegelungMK1", "Unknown_Visibility_150"]),
            151: Unknown(["ID_Visi_SysEin_RegelungMK2", "Unknown_Visibility_151"]),
            152: Unknown(["ID_Visi_SysEin_Kuhlung", "Unknown_Visibility_152"]),
            153: Unknown(["ID_Visi_SysEin_Ausheizen", "Unknown_Visibility_153"]),
            154: Unknown(["ID_Visi_SysEin_ElektrAnode", "Unknown_Visibility_154"]),
            155: Unknown(["ID_Visi_SysEin_SWBBer", "Unknown_Visibility_155"]),
            156: Unknown(["ID_Visi_SysEin_SWBMin", "Unknown_Visibility_156"]),
            157: Unknown(["ID_Visi_SysEin_Heizung", "Unknown_Visibility_157"]),
            158: Unknown(["ID_Visi_SysEin_PeriodeMk1", "Unknown_Visibility_158"]),
            159: Unknown(["ID_Visi_SysEin_LaufzeitMk1", "Unknown_Visibility_159"]),
            160: Unknown(["ID_Visi_SysEin_PeriodeMk2", "Unknown_Visibility_160"]),
            161: Unknown(["ID_Visi_SysEin_LaufzeitMk2", "Unknown_Visibility_161"]),
            162: Unknown(["ID_Visi_SysEin_Heizgrenze", "Unknown_Visibility_162"]),
            163: Unknown(["ID_Visi_Enlt_HUP", "Unknown_Visibility_163"]),
            164: Unknown(["ID_Visi_Enlt_ZUP", "Unknown_Visibility_164"]),
            165: Unknown(["ID_Visi_Enlt_BUP", "Unknown_Visibility_165"]),
            166: Unknown(["ID_Visi_Enlt_Ventilator_BOSUP", "Unknown_Visibility_166"]),
            167: Unknown(["ID_Visi_Enlt_MA1", "Unknown_Visibility_167"]),
            168: Unknown(["ID_Visi_Enlt_MZ1", "Unknown_Visibility_168"]),
            169: Unknown(["ID_Visi_Enlt_ZIP", "Unknown_Visibility_169"]),
            170: Unknown(["ID_Visi_Enlt_MA2", "Unknown_Visibility_170"]),
            171: Unknown(["ID_Visi_Enlt_MZ2", "Unknown_Visibility_171"]),
            172: Unknown(["ID_Visi_Enlt_SUP", "Unknown_Visibility_172"]),
            173: Unknown(["ID_Visi_Enlt_SLP", "Unknown_Visibility_173"]),
            174: Unknown(["ID_Visi_Enlt_FP2", "Unknown_Visibility_174"]),
            175: Unknown(["ID_Visi_Enlt_Laufzeit", "Unknown_Visibility_175"]),
            176: Unknown(["ID_Visi_Anlgkonf_Heizung", "Unknown_Visibility_176"]),
            177: Unknown(["ID_Visi_Anlgkonf_Brauchwarmwasser", "Unknown_Visibility_177"]),
            178: Unknown(["ID_Visi_Anlgkonf_Schwimmbad", "Unknown_Visibility_178"]),
            179: Unknown(["ID_Visi_Heizung_Betriebsart", "Unknown_Visibility_179"]),
            180: Unknown(["ID_Visi_Heizung_TemperaturPlusMinus", "Unknown_Visibility_180"]),
            181: Unknown(["ID_Visi_Heizung_Heizkurven", "Unknown_Visibility_181"]),
            182: Unknown(["ID_Visi_Heizung_Zeitschaltprogramm", "ID_Visi_Heizung_Zeitschlaltprogramm", "Unknown_Visibility_182"]),
            183: Unknown(["ID_Visi_Heizung_Heizgrenze", "Unknown_Visibility_183"]),
            184: Unknown(["ID_Visi_Mitteltemperatur", "Unknown_Visibility_184"]),
            185: Unknown(["ID_Visi_Dataenlogger", "Unknown_Visibility_185"]),
            186: Unknown(["ID_Visi_Sprachen_DEUTSCH", "Unknown_Visibility_186"]),
            187: Unknown(["ID_Visi_Sprachen_ENGLISH", "Unknown_Visibility_187"]),
            188: Unknown(["ID_Visi_Sprachen_FRANCAIS", "Unknown_Visibility_188"]),
            189: Unknown(["ID_Visi_Sprachen_NORWAY", "Unknown_Visibility_189"]),
            190: Unknown(["ID_Visi_Sprachen_TCHECH", "Unknown_Visibility_190"]),
            191: Unknown(["ID_Visi_Sprachen_ITALIANO", "Unknown_Visibility_191"]),
            192: Unknown(["ID_Visi_Sprachen_NEDERLANDS", "Unknown_Visibility_192"]),
            193: Unknown(["ID_Visi_Sprachen_SVENSKA", "Unknown_Visibility_193"]),
            194: Unknown(["ID_Visi_Sprachen_POLSKI", "Unknown_Visibility_194"]),
            195: Unknown(["ID_Visi_Sprachen_MAGYARUL", "Unknown_Visibility_195"]),
            196: Unknown(["ID_Visi_ErrorUSBspeichern", "Unknown_Visibility_196"]),
            197: Unknown(["ID_Visi_Bst_BStdHz", "Unknown_Visibility_197"]),
            198: Unknown(["ID_Visi_Bst_BStdBW", "Unknown_Visibility_198"]),
            199: Unknown(["ID_Visi_Bst_BStdKue", "Unknown_Visibility_199"]),
            200: Unknown(["ID_Visi_Service_Systemsteuerung", "Unknown_Visibility_200"]),
            201: Unknown(["ID_Visi_Service_Systemsteuerung_Contrast", "Unknown_Visibility_201"]),
            202: Unknown(["ID_Visi_Service_Systemsteuerung_Webserver", "Unknown_Visibility_202"]),
            203: Unknown(["ID_Visi_Service_Systemsteuerung_IPAdresse", "Unknown_Visibility_203"]),
            204: Unknown(["ID_Visi_Service_Systemsteuerung_Fernwartung", "Unknown_Visibility_204"]),
            205: Unknown(["ID_Visi_Paralleleschaltung", "Unknown_Visibility_205"]),
            206: Unknown(["ID_Visi_SysEin_Paralleleschaltung", "Unknown_Visibility_206"]),
            207: Unknown(["ID_Visi_Sprachen_DANSK", "Unknown_Visibility_207"]),
            208: Unknown(["ID_Visi_Sprachen_PORTUGES", "Unknown_Visibility_208"]),
            209: Unknown(["ID_Visi_Heizkurve_Heizung", "Unknown_Visibility_209"]),
            210: Unknown(["ID_Visi_SysEin_Mischkreis3", "Unknown_Visibility_210"]),
            211: Unknown(["ID_Visi_MK3", "Unknown_Visibility_211"]),
            212: Unknown(["ID_Visi_Temp_MK3_Vorlauf", "Unknown_Visibility_212"]),
            213: Unknown(["ID_Visi_Temp_MK3VL_Soll", "Unknown_Visibility_213"]),
            214: Unknown(["ID_Visi_OUT_Mischer3Auf", "Unknown_Visibility_214"]),
            215: Unknown(["ID_Visi_OUT_Mischer3Zu", "Unknown_Visibility_215"]),
            216: Unknown(["ID_Visi_SysEin_RegelungMK3", "Unknown_Visibility_216"]),
            217: Unknown(["ID_Visi_SysEin_PeriodeMk3", "Unknown_Visibility_217"]),
            218: Unknown(["ID_Visi_SysEin_LaufzeitMk3", "Unknown_Visibility_218"]),
            219: Unknown(["ID_Visi_SysEin_Kuhl_Zeit_Ein", "Unknown_Visibility_219"]),
            220: Unknown(["ID_Visi_SysEin_Kuhl_Zeit_Aus", "Unknown_Visibility_220"]),
            221: Unknown(["ID_Visi_AblaufZ_AbtauIn", "Unknown_Visibility_221"]),
            222: Unknown(["ID_Visi_Waermemenge_WS", "Unknown_Visibility_222"]),
            223: Unknown(["ID_Visi_Waermemenge_WQ", "Unknown_Visibility_223"]),
            224: Unknown(["ID_Visi_Enlt_MA3", "Unknown_Visibility_224"]),
            225: Unknown(["ID_Visi_Enlt_MZ3", "Unknown_Visibility_225"]),
            226: Unknown(["ID_Visi_Enlt_FP3", "Unknown_Visibility_226"]),
            227: Unknown(["ID_Visi_OUT_FUP3", "Unknown_Visibility_227"]),
            228: Unknown(["ID_Visi_Temp_Raumstation2", "Unknown_Visibility_228"]),
            229: Unknown(["ID_Visi_Temp_Raumstation3", "Unknown_Visibility_229"]),
            230: Unknown(["ID_Visi_Bst_BStdSW", "Unknown_Visibility_230"]),
            231: Unknown(["ID_Visi_Sprachen_LITAUISCH", "Unknown_Visibility_231"]),
            232: Unknown(["ID_Visi_Sprachen_ESTNICH", "Unknown_Visibility_232"]),
            233: Unknown(["ID_Visi_SysEin_Fernwartung", "Unknown_Visibility_233"]),
            234: Unknown(["ID_Visi_Sprachen_SLOVENISCH", "Unknown_Visibility_234"]),
            235: Unknown(["ID_Visi_EinstTemp_TA_EG", "Unknown_Visibility_235"]),
            236: Unknown(["ID_Visi_Einst_TVLmax_EG", "Unknown_Visibility_236"]),
            237: Unknown(["ID_Visi_SysEin_PoptNachlauf", "Unknown_Visibility_237"]),
            238: Unknown(["ID_Visi_RFV_K_Kuehlin", "Unknown_Visibility_238"]),
            239: Unknown(["ID_Visi_SysEin_EffizienzpumpeNom", "Unknown_Visibility_239"]),
            240: Unknown(["ID_Visi_SysEin_EffizienzpumpeMin", "Unknown_Visibility_240"]),
            241: Unknown(["ID_Visi_SysEin_Effizienzpumpe", "Unknown_Visibility_241"]),
            242: Unknown(["ID_Visi_SysEin_Waermemenge", "Unknown_Visibility_242"]),
            243: Unknown(["ID_Visi_Service_WMZ_Effizienz", "Unknown_Visibility_243"]),
            244: Unknown(["ID_Visi_SysEin_Wm_Versorgung_Korrektur", "Unknown_Visibility_244"]),
            245: Unknown(["ID_Visi_SysEin_Wm_Auswertung_Korrektur", "Unknown_Visibility_245"]),
            246: Unknown(["ID_Visi_IN_AnalogIn", "Unknown_Visibility_246"]),
            247: Unknown(["ID_Visi_Eins_SN_Eingabe", "Unknown_Visibility_247"]),
            248: Unknown(["ID_Visi_OUT_Analog_1", "Unknown_Visibility_248"]),
            249: Unknown(["ID_Visi_OUT_Analog_2", "Unknown_Visibility_249"]),
            250: Unknown(["ID_Visi_Solar", "Unknown_Visibility_250"]),
            251: Unknown(["ID_Visi_SysEin_Solar", "Unknown_Visibility_251"]),
            252: Unknown(["ID_Visi_EinstTemp_TDiffKollmax", "Unknown_Visibility_252"]),
            253: Unknown(["ID_Visi_AblaufZ_HG_Sperre", "Unknown_Visibility_253"]),
            254: Unknown(["ID_Visi_SysEin_Akt_Kuehlung", "Unknown_Visibility_254"]),
            255: Unknown(["ID_Visi_SysEin_Vorlauf_VBO", "Unknown_Visibility_255"]),
            256: Unknown(["ID_Visi_Einst_KRHyst", "Unknown_Visibility_256"]),
            257: Unknown(["ID_Visi_Einst_Akt_Kuehl_Speicher_min", "Unknown_Visibility_257"]),
            258: Unknown(["ID_Visi_Einst_Akt_Kuehl_Freig_WQE", "Unknown_Visibility_258"]),
            259: Unknown(["ID_Visi_SysEin_AbtZykMin", "Unknown_Visibility_259"]),
            260: Unknown(["ID_Visi_SysEin_VD2_Zeit_Min", "Unknown_Visibility_260"]),
            261: Unknown(["ID_Visi_EinstTemp_Hysterese_HR_verkuerzt", "Unknown_Visibility_261"]),
            262: Unknown(["ID_Visi_Einst_Luf_Feuchteschutz_akt", "Unknown_Visibility_262"]),
            263: Unknown(["ID_Visi_Einst_Luf_Reduziert_akt", "Unknown_Visibility_263"]),
            264: Unknown(["ID_Visi_Einst_Luf_Nennlueftung_akt", "Unknown_Visibility_264"]),
            265: Unknown(["ID_Visi_Einst_Luf_Intensivlueftung_akt", "Unknown_Visibility_265"]),
            266: Unknown(["ID_Visi_Temperatur_Lueftung_Zuluft", "Unknown_Visibility_266"]),
            267: Unknown(["ID_Visi_Temperatur_Lueftung_Abluft", "Unknown_Visibility_267"]),
            268: Unknown(["ID_Visi_OUT_Analog_3", "Unknown_Visibility_268"]),
            269: Unknown(["ID_Visi_OUT_Analog_4", "Unknown_Visibility_269"]),
            270: Unknown(["ID_Visi_IN_Analog_2", "Unknown_Visibility_270"]),
            271: Unknown(["ID_Visi_IN_Analog_3", "Unknown_Visibility_271"]),
            272: Unknown(["ID_Visi_IN_SAX", "Unknown_Visibility_272"]),
            273: Unknown(["ID_Visi_OUT_VZU", "Unknown_Visibility_273"]),
            274: Unknown(["ID_Visi_OUT_VAB", "Unknown_Visibility_274"]),
            275: Unknown(["ID_Visi_OUT_VSK", "Unknown_Visibility_275"]),
            276: Unknown(["ID_Visi_OUT_FRH", "Unknown_Visibility_276"]),
            277: Unknown(["ID_Visi_KuhlTemp_SolltempMK3", "Unknown_Visibility_277"]),
            278: Unknown(["ID_Visi_KuhlTemp_ATDiffMK3", "Unknown_Visibility_278"]),
            279: Unknown(["ID_Visi_IN_SPL", "Unknown_Visibility_279"]),
            280: Unknown(["ID_Visi_SysEin_Lueftungsstufen", "Unknown_Visibility_280"]),
            281: Unknown(["ID_Visi_SysEin_Meldung_TDI", "Unknown_Visibility_281"]),
            282: Unknown(["ID_Visi_SysEin_Typ_WZW", "Unknown_Visibility_282"]),
            283: Unknown(["ID_Visi_BACnet", "Unknown_Visibility_283"]),
            284: Unknown(["ID_Visi_Sprachen_SLOWAKISCH", "Unknown_Visibility_284"]),
            285: Unknown(["ID_Visi_Sprachen_LETTISCH", "Unknown_Visibility_285"]),
            286: Unknown(["ID_Visi_Sprachen_FINNISCH", "Unknown_Visibility_286"]),
            287: Unknown(["ID_Visi_Kalibrierung_LWD", "Unknown_Visibility_287"]),
            288: Unknown(["ID_Visi_IN_Durchfluss", "Unknown_Visibility_288"]),
            289: Unknown(["ID_Visi_LIN_ANSAUG_VERDICHTER", "Unknown_Visibility_289"]),
            290: Unknown(["ID_Visi_LIN_VDH", "Unknown_Visibility_290"]),
            291: Unknown(["ID_Visi_LIN_UH", "Unknown_Visibility_291"]),
            292: Unknown(["ID_Visi_LIN_Druck", "Unknown_Visibility_292"]),
            293: Unknown(["ID_Visi_Einst_Sollwert_TRL_Kuehlen", "Unknown_Visibility_293"]),
            294: Unknown(["ID_Visi_Entl_ExVentil", "Unknown_Visibility_294"]),
            295: Unknown(["ID_Visi_Einst_Medium_Waermequelle", "Unknown_Visibility_295"]),
            296: Unknown(["ID_Visi_Einst_Multispeicher", "Unknown_Visibility_296"]),
            297: Unknown(["ID_Visi_Einst_Minimale_Ruecklaufsolltemperatur", "Unknown_Visibility_297"]),
            298: Unknown(["ID_Visi_Einst_PKuehlTime", "Unknown_Visibility_298"]),
            299: Unknown(["ID_Visi_Sprachen_TUERKISCH", "Unknown_Visibility_299"]),
            300: Unknown(["ID_Visi_RBE", "Unknown_Visibility_300"]),
            301: Unknown(["ID_Visi_Einst_Luf_Stufen_Faktor", "Unknown_Visibility_301"]),
            302: Unknown(["ID_Visi_Freigabe_Zeit_ZWE", "Unknown_Visibility_302"]),
            303: Unknown(["ID_Visi_Einst_min_VL_Kuehl", "Unknown_Visibility_303"]),
            304: Unknown(["ID_Visi_ZWE1", "Unknown_Visibility_304"]),
            305: Unknown(["ID_Visi_ZWE2", "Unknown_Visibility_305"]),
            306: Unknown(["ID_Visi_ZWE3", "Unknown_Visibility_306"]),
            307: Unknown(["ID_Visi_SEC", "Unknown_Visibility_307"]),
            308: Unknown(["ID_Visi_HZIO", "Unknown_Visibility_308"]),
            309: Unknown(["ID_Visi_WPIO", "Unknown_Visibility_309"]),
            310: Unknown(["ID_Visi_LIN_ANSAUG_VERDAMPFER", "Unknown_Visibility_310"]),
            311: Unknown(["ID_Visi_LIN_MULTI1", "Unknown_Visibility_311"]),
            312: Unknown(["ID_Visi_LIN_MULTI2", "Unknown_Visibility_312"]),
            313: Unknown(["ID_Visi_Einst_Leistung_ZWE", "Unknown_Visibility_313"]),
            314: Unknown(["ID_Visi_Sprachen_ESPANOL", "Unknown_Visibility_314"]),
            315: Unknown(["ID_Visi_Temp_BW_oben", "Unknown_Visibility_315"]),
            316: Unknown(["ID_Visi_MAXIO", "Unknown_Visibility_316"]),
            317: Unknown(["ID_Visi_OUT_Abtauwunsch", "Unknown_Visibility_317"]),
            318: Unknown(["ID_Visi_SmartGrid", "Unknown_Visibility_318"]),
            319: Unknown(["ID_Visi_Drehzahlgeregelt", "Unknown_Visibility_319"]),
            320: Unknown(["ID_Visi_P155_Inverter", "Unknown_Visibility_320"]),
            321: Unknown(["ID_Visi_Leistungsfreigabe", "Unknown_Visibility_321"]),
            322: Unknown(["ID_Visi_Einst_Vorl_akt_Kuehl", "Unknown_Visibility_322"]),
            323: Unknown(["ID_Visi_Einst_Abtauen_im_Warmwasser", "Unknown_Visibility_323"]),
            324: Unknown(["ID_Visi_Waermemenge_ZWE", "Unknown_Visibility_324"]),
            325: Unknown("Unknown_Visibility_325"),
            326: Unknown("Unknown_Visibility_326"),
            327: Unknown("Unknown_Visibility_327"),
            328: Unknown("Unknown_Visibility_328"),
            329: Unknown("Unknown_Visibility_329"),
            330: Unknown("Unknown_Visibility_330"),
            331: Unknown("Unknown_Visibility_331"),
            332: Unknown("Unknown_Visibility_332"),
            333: Unknown("Unknown_Visibility_333"),
            334: Unknown("Unknown_Visibility_334"),
            335: Unknown("Unknown_Visibility_335"),
            336: Unknown("Unknown_Visibility_336"),
            337: Unknown("Unknown_Visibility_337"),
            338: Unknown("Unknown_Visibility_338"),
            339: Unknown("Unknown_Visibility_339"),
            340: Unknown("Unknown_Visibility_340"),
            341: Unknown("Unknown_Visibility_341"),
            342: Unknown("Unknown_Visibility_342"),
            343: Unknown("Unknown_Visibility_343"),
            344: Unknown("Unknown_Visibility_344"),
            345: Unknown("Unknown_Visibility_345"),
            346: Unknown("Unknown_Visibility_346"),
            347: Unknown("Unknown_Visibility_347"),
            348: Unknown("Unknown_Visibility_348"),
            349: Unknown("Unknown_Visibility_349"),
            350: Unknown("Unknown_Visibility_350"),
            351: Unknown("Unknown_Visibility_351"),
            352: Unknown("Unknown_Visibility_352"),
            353: Unknown("Unknown_Visibility_353"),
            354: Unknown("Unknown_Visibility_354"),
            355: Unknown(["Unknown_Visibility_355", "Unknown_Parameter_355"]),
            356: Unknown(["Unknown_Visibility_356", "Unknown_Parameter_356"]),
            357: Unknown(["Unknown_Visibility_357", "Unknown_Parameter_357"]),
            358: Unknown(["Unknown_Visibility_358", "Unknown_Parameter_358"]),
            359: Unknown(["Unknown_Visibility_359", "Unknown_Parameter_359"]),
            360: Unknown(["Unknown_Visibility_360", "Unknown_Parameter_360"]),
            361: Unknown(["Unknown_Visibility_361", "Unknown_Parameter_361"]),
            362: Unknown(["Unknown_Visibility_362", "Unknown_Parameter_362"]),
            363: Unknown(["Unknown_Visibility_363", "Unknown_Parameter_363"]),
            364: Unknown(["Unknown_Visibility_364", "Unknown_Parameter_364"]),
            365: Unknown(["Unknown_Visibility_365", "Unknown_Parameter_365"]),
            366: Unknown(["Unknown_Visibility_366", "Unknown_Parameter_366"]),
            367: Unknown(["Unknown_Visibility_367", "Unknown_Parameter_367"]),
            368: Unknown(["Unknown_Visibility_368", "Unknown_Parameter_368"]),
            369: Unknown(["Unknown_Visibility_369", "Unknown_Parameter_369"]),
            370: Unknown(["Unknown_Visibility_370", "Unknown_Parameter_370"]),
            371: Unknown(["Unknown_Visibility_371", "Unknown_Parameter_371"]),
            372: Unknown(["Unknown_Visibility_372", "Unknown_Parameter_372"]),
            373: Unknown(["Unknown_Visibility_373", "Unknown_Parameter_373"]),
            374: Unknown(["Unknown_Visibility_374", "Unknown_Parameter_374"]),
            375: Unknown(["Unknown_Visibility_375", "Unknown_Parameter_375"]),
            376: Unknown(["Unknown_Visibility_376", "Unknown_Parameter_376"]),
            377: Unknown(["Unknown_Visibility_377", "Unknown_Parameter_377"]),
            378: Unknown(["Unknown_Visibility_378", "Unknown_Parameter_378"]),
            379: Unknown(["Unknown_Visibility_379", "Unknown_Parameter_379"]),
        }
