"""
Constant list containing all 'calculation' definitions
used by the config interface (CFI) of the Luxtronik controller.

The calculations holds values based on the currently measured values,
are read-only and are used for control and display purposes.

NOTES:
- If there are multiple definitions for an index, the newest and
preferred one should be inserted as the last one in the same index.
"""

from typing import Final

from luxtronik.datatypes import (
    BivalenceLevel,
    Bool,
    Celsius,
    Character,
    Count,
    Energy,
    Errorcode,
    Flow,
    Frequency,
    HeatpumpCode,
    Icon,
    IPv4Address,
    Kelvin,
    Level,
    MainMenuStatusLine1,
    MainMenuStatusLine2,
    MainMenuStatusLine3,
    OperationMode,
    Percent2,
    Power,
    Pressure,
    Seconds,
    SecOperationMode,
    Speed,
    SwitchoffFile,
    Timestamp,
    Unknown,
    MajorMinorVersion,
    Voltage,
)

# Offset which must be added to the calculation indices
# to obtain the correct address of the data fields
CALCULATIONS_OFFSET: Final = 0
CALCULATIONS_DEFAULT_DATA_TYPE: Final = 'INT32'

CALCULATIONS_DEFINITIONS_LIST: Final = [
    {
        "index": 0,
        "count": 1,
        "names": ['Unknown_Calculation_0'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 1,
        "count": 1,
        "names": ['Unknown_Calculation_1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 2,
        "count": 1,
        "names": ['Unknown_Calculation_2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 3,
        "count": 1,
        "names": ['Unknown_Calculation_3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 4,
        "count": 1,
        "names": ['Unknown_Calculation_4'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 5,
        "count": 1,
        "names": ['Unknown_Calculation_5'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 6,
        "count": 1,
        "names": ['Unknown_Calculation_6'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 7,
        "count": 1,
        "names": ['Unknown_Calculation_7'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 8,
        "count": 1,
        "names": ['Unknown_Calculation_8'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 9,
        "count": 1,
        "names": ['Unknown_Calculation_9'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 10,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TVL'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 11,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TRL'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 12,
        "count": 1,
        "names": ['ID_WEB_Sollwert_TRL_HZ'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 13,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TRL_ext'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 14,
        "count": 1,
        "names": ['ID_WEB_Temperatur_THG'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 15,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TA'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 16,
        "count": 1,
        "names": ['ID_WEB_Mitteltemperatur'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 17,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TBW'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 18,
        "count": 1,
        "names": ['ID_WEB_Einst_BWS_akt'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 19,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TWE'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 20,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TWA'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 21,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TFB1'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 22,
        "count": 1,
        "names": ['ID_WEB_Sollwert_TVL_MK1'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 23,
        "count": 1,
        "names": ['ID_WEB_Temperatur_RFV'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 24,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TFB2'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 25,
        "count": 1,
        "names": ['ID_WEB_Sollwert_TVL_MK2'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 26,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TSK'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 27,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TSS'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 28,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TEE'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 29,
        "count": 1,
        "names": ['ID_WEB_ASDin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 30,
        "count": 1,
        "names": ['ID_WEB_BWTin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 31,
        "count": 1,
        "names": ['ID_WEB_EVUin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 32,
        "count": 1,
        "names": ['ID_WEB_HDin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 33,
        "count": 1,
        "names": ['ID_WEB_MOTin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 34,
        "count": 1,
        "names": ['ID_WEB_NDin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 35,
        "count": 1,
        "names": ['ID_WEB_PEXin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 36,
        "count": 1,
        "names": ['ID_WEB_SWTin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 37,
        "count": 1,
        "names": ['ID_WEB_AVout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 38,
        "count": 1,
        "names": ['ID_WEB_BUPout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 39,
        "count": 1,
        "names": ['ID_WEB_HUPout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 40,
        "count": 1,
        "names": ['ID_WEB_MA1out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 41,
        "count": 1,
        "names": ['ID_WEB_MZ1out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 42,
        "count": 1,
        "names": ['ID_WEB_VENout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 43,
        "count": 1,
        "names": ['ID_WEB_VBOout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 44,
        "count": 1,
        "names": ['ID_WEB_VD1out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 45,
        "count": 1,
        "names": ['ID_WEB_VD2out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 46,
        "count": 1,
        "names": ['ID_WEB_ZIPout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 47,
        "count": 1,
        "names": ['ID_WEB_ZUPout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 48,
        "count": 1,
        "names": ['ID_WEB_ZW1out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 49,
        "count": 1,
        "names": ['ID_WEB_ZW2SSTout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 50,
        "count": 1,
        "names": ['ID_WEB_ZW3SSTout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 51,
        "count": 1,
        "names": ['ID_WEB_FP2out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 52,
        "count": 1,
        "names": ['ID_WEB_SLPout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 53,
        "count": 1,
        "names": ['ID_WEB_SUPout'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 54,
        "count": 1,
        "names": ['ID_WEB_MZ2out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 55,
        "count": 1,
        "names": ['ID_WEB_MA2out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 56,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitVD1'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 57,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitImpVD1'],
        "type": Count,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 58,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitVD2'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 59,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitImpVD2'],
        "type": Count,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 60,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitZWE1'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 61,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitZWE2'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 62,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitZWE3'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 63,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitWP'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 64,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitHz'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 65,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitBW'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 66,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitKue'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 67,
        "count": 1,
        "names": ['ID_WEB_Time_WPein_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 68,
        "count": 1,
        "names": ['ID_WEB_Time_ZWE1_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 69,
        "count": 1,
        "names": ['ID_WEB_Time_ZWE2_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 70,
        "count": 1,
        "names": ['ID_WEB_Timer_EinschVerz'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 71,
        "count": 1,
        "names": ['ID_WEB_Time_SSPAUS_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 72,
        "count": 1,
        "names": ['ID_WEB_Time_SSPEIN_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 73,
        "count": 1,
        "names": ['ID_WEB_Time_VDStd_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 74,
        "count": 1,
        "names": ['ID_WEB_Time_HRM_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 75,
        "count": 1,
        "names": ['ID_WEB_Time_HRW_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 76,
        "count": 1,
        "names": ['ID_WEB_Time_LGS_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 77,
        "count": 1,
        "names": ['ID_WEB_Time_SBW_akt'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 78,
        "count": 1,
        "names": ['ID_WEB_Code_WP_akt'],
        "type": HeatpumpCode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 79,
        "count": 1,
        "names": ['ID_WEB_BIV_Stufe_akt'],
        "type": BivalenceLevel,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 80,
        "count": 1,
        "names": ['ID_WEB_WP_BZ_akt'],
        "type": OperationMode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 81,
        "count": 1,
        "names": ['ID_WEB_SoftStand_0'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 82,
        "count": 1,
        "names": ['ID_WEB_SoftStand_1'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 83,
        "count": 1,
        "names": ['ID_WEB_SoftStand_2'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 84,
        "count": 1,
        "names": ['ID_WEB_SoftStand_3'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 85,
        "count": 1,
        "names": ['ID_WEB_SoftStand_4'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 86,
        "count": 1,
        "names": ['ID_WEB_SoftStand_5'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 87,
        "count": 1,
        "names": ['ID_WEB_SoftStand_6'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 88,
        "count": 1,
        "names": ['ID_WEB_SoftStand_7'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 89,
        "count": 1,
        "names": ['ID_WEB_SoftStand_8'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 90,
        "count": 1,
        "names": ['ID_WEB_SoftStand_9'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 91,
        "count": 1,
        "names": ['ID_WEB_AdresseIP_akt'],
        "type": IPv4Address,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 92,
        "count": 1,
        "names": ['ID_WEB_SubNetMask_akt'],
        "type": IPv4Address,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 93,
        "count": 1,
        "names": ['ID_WEB_Add_Broadcast'],
        "type": IPv4Address,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 94,
        "count": 1,
        "names": ['ID_WEB_Add_StdGateway'],
        "type": IPv4Address,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 95,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time0'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 96,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time1'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 97,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time2'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 98,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time3'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 99,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time4'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 100,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr0'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 101,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr1'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 102,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr2'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 103,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr3'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 104,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr4'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 105,
        "count": 1,
        "names": ['ID_WEB_AnzahlFehlerInSpeicher'],
        "type": Count,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 106,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr0'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 107,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr1'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 108,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr2'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 109,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr3'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 110,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr4'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 111,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time0'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 112,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time1'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 113,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time2'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 114,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time3'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 115,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time4'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 116,
        "count": 1,
        "names": ['ID_WEB_Comfort_exists'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 117,
        "count": 1,
        "names": ['ID_WEB_HauptMenuStatus_Zeile1'],
        "type": MainMenuStatusLine1,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 118,
        "count": 1,
        "names": ['ID_WEB_HauptMenuStatus_Zeile2'],
        "type": MainMenuStatusLine2,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 119,
        "count": 1,
        "names": ['ID_WEB_HauptMenuStatus_Zeile3'],
        "type": MainMenuStatusLine3,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 120,
        "count": 1,
        "names": ['ID_WEB_HauptMenuStatus_Zeit'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 121,
        "count": 1,
        "names": ['ID_WEB_HauptMenuAHP_Stufe'],
        "type": Level,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 122,
        "count": 1,
        "names": ['ID_WEB_HauptMenuAHP_Temp'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 123,
        "count": 1,
        "names": ['ID_WEB_HauptMenuAHP_Zeit'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 124,
        "count": 1,
        "names": ['ID_WEB_SH_BWW'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 125,
        "count": 1,
        "names": ['ID_WEB_SH_HZ'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 126,
        "count": 1,
        "names": ['ID_WEB_SH_MK1'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 127,
        "count": 1,
        "names": ['ID_WEB_SH_MK2'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 128,
        "count": 1,
        "names": ['ID_WEB_Einst_Kurzrpgramm'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 129,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 130,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 131,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 132,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_4'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 133,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_5'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 134,
        "count": 1,
        "names": ['ID_WEB_AktuelleTimeStamp'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 135,
        "count": 1,
        "names": ['ID_WEB_SH_MK3'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 136,
        "count": 1,
        "names": ['ID_WEB_Sollwert_TVL_MK3'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 137,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TFB3'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 138,
        "count": 1,
        "names": ['ID_WEB_MZ3out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 139,
        "count": 1,
        "names": ['ID_WEB_MA3out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 140,
        "count": 1,
        "names": ['ID_WEB_FP3out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 141,
        "count": 1,
        "names": ['ID_WEB_Time_AbtIn'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 142,
        "count": 1,
        "names": ['ID_WEB_Temperatur_RFV2'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 143,
        "count": 1,
        "names": ['ID_WEB_Temperatur_RFV3'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 144,
        "count": 1,
        "names": ['ID_WEB_SH_SW'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 145,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitSW'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 146,
        "count": 1,
        "names": ['ID_WEB_FreigabKuehl'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 147,
        "count": 1,
        "names": ['ID_WEB_AnalogIn'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 148,
        "count": 1,
        "names": ['ID_WEB_SonderZeichen'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 149,
        "count": 1,
        "names": ['ID_WEB_SH_ZIP'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 150,
        "count": 1,
        "names": ['ID_WEB_WebsrvProgrammWerteBeobarten'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 151,
        "count": 1,
        "names": ['ID_WEB_WMZ_Heizung'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 152,
        "count": 1,
        "names": ['ID_WEB_WMZ_Brauchwasser'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 153,
        "count": 1,
        "names": ['ID_WEB_WMZ_Schwimmbad'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 154,
        "count": 1,
        "names": ['ID_WEB_WMZ_Seit'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 155,
        "count": 1,
        "names": ['ID_WEB_WMZ_Durchfluss'],
        "type": Flow,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'l/h',
        "description": '',
    },
    {
        "index": 156,
        "count": 1,
        "names": ['ID_WEB_AnalogOut1'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 157,
        "count": 1,
        "names": ['ID_WEB_AnalogOut2'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 158,
        "count": 1,
        "names": ['ID_WEB_Time_Heissgas'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 159,
        "count": 1,
        "names": ['ID_WEB_Temp_Lueftung_Zuluft'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 160,
        "count": 1,
        "names": ['ID_WEB_Temp_Lueftung_Abluft'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 161,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitSolar'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 162,
        "count": 1,
        "names": ['ID_WEB_AnalogOut3'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 163,
        "count": 1,
        "names": ['ID_WEB_AnalogOut4'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 164,
        "count": 1,
        "names": ['ID_WEB_Out_VZU'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 165,
        "count": 1,
        "names": ['ID_WEB_Out_VAB'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 166,
        "count": 1,
        "names": ['ID_WEB_Out_VSK'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 167,
        "count": 1,
        "names": ['ID_WEB_Out_FRH'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 168,
        "count": 1,
        "names": ['ID_WEB_AnalogIn2'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 169,
        "count": 1,
        "names": ['ID_WEB_AnalogIn3'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 170,
        "count": 1,
        "names": ['ID_WEB_SAXin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 171,
        "count": 1,
        "names": ['ID_WEB_SPLin'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 172,
        "count": 1,
        "names": ['ID_WEB_Compact_exists'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 173,
        "count": 1,
        "names": ['ID_WEB_Durchfluss_WQ'],
        "type": Flow,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'l/h',
        "description": '',
    },
    {
        "index": 174,
        "count": 1,
        "names": ['ID_WEB_LIN_exists'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 175,
        "count": 1,
        "names": ['ID_WEB_LIN_ANSAUG_VERDAMPFER'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 176,
        "count": 1,
        "names": ['ID_WEB_LIN_ANSAUG_VERDICHTER'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 177,
        "count": 1,
        "names": ['ID_WEB_LIN_VDH'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 178,
        "count": 1,
        "names": ['ID_WEB_LIN_UH'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 179,
        "count": 1,
        "names": ['ID_WEB_LIN_UH_Soll'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 180,
        "count": 1,
        "names": ['ID_WEB_LIN_HD'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 181,
        "count": 1,
        "names": ['ID_WEB_LIN_ND'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 182,
        "count": 1,
        "names": ['ID_WEB_LIN_VDH_out'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 183,
        "count": 1,
        "names": ['ID_WEB_HZIO_PWM'],
        "type": Percent2,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '%',
        "description": '',
    },
    {
        "index": 184,
        "count": 1,
        "names": ['ID_WEB_HZIO_VEN'],
        "type": Speed,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'rpm',
        "description": '',
    },
    {
        "index": 185,
        "count": 1,
        "names": ['ID_WEB_HZIO_EVU2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 186,
        "count": 1,
        "names": ['ID_WEB_HZIO_STB'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 187,
        "count": 1,
        "names": ['ID_WEB_SEC_Qh_Soll'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 188,
        "count": 1,
        "names": ['ID_WEB_SEC_Qh_Ist'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 189,
        "count": 1,
        "names": ['ID_WEB_SEC_TVL_Soll'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 190,
        "count": 1,
        "names": ['ID_WEB_SEC_Software'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 191,
        "count": 1,
        "names": ['ID_WEB_SEC_BZ'],
        "type": SecOperationMode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 192,
        "count": 1,
        "names": ['ID_WEB_SEC_VWV'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 193,
        "count": 1,
        "names": ['ID_WEB_SEC_VD'],
        "type": Speed,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'rpm',
        "description": '',
    },
    {
        "index": 194,
        "count": 1,
        "names": ['ID_WEB_SEC_VerdEVI'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 195,
        "count": 1,
        "names": ['ID_WEB_SEC_AnsEVI'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 196,
        "count": 1,
        "names": ['ID_WEB_SEC_UEH_EVI'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 197,
        "count": 1,
        "names": ['ID_WEB_SEC_UEH_EVI_S'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 198,
        "count": 1,
        "names": ['ID_WEB_SEC_KondTemp'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 199,
        "count": 1,
        "names": ['ID_WEB_SEC_FlussigEx'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 200,
        "count": 1,
        "names": ['ID_WEB_SEC_UK_EEV'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 201,
        "count": 1,
        "names": ['ID_WEB_SEC_EVI_Druck'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 202,
        "count": 1,
        "names": ['ID_WEB_SEC_U_Inv'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 203,
        "count": 1,
        "names": ['ID_WEB_Temperatur_THG_2'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 204,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TWE_2'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 205,
        "count": 1,
        "names": ['ID_WEB_LIN_ANSAUG_VERDAMPFER_2'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 206,
        "count": 1,
        "names": ['ID_WEB_LIN_ANSAUG_VERDICHTER_2'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 207,
        "count": 1,
        "names": ['ID_WEB_LIN_VDH_2'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 208,
        "count": 1,
        "names": ['ID_WEB_LIN_UH_2'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 209,
        "count": 1,
        "names": ['ID_WEB_LIN_UH_Soll_2'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 210,
        "count": 1,
        "names": ['ID_WEB_LIN_HD_2'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 211,
        "count": 1,
        "names": ['ID_WEB_LIN_ND_2'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 212,
        "count": 1,
        "names": ['ID_WEB_HDin_2'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 213,
        "count": 1,
        "names": ['ID_WEB_AVout_2'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 214,
        "count": 1,
        "names": ['ID_WEB_VBOout_2'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 215,
        "count": 1,
        "names": ['ID_WEB_VD1out_2'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 216,
        "count": 1,
        "names": ['ID_WEB_LIN_VDH_out_2'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 217,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr0'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 218,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr1'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 219,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr2'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 220,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr3'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 221,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr4'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 222,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time0'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 223,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time1'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 224,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time2'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 225,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time3'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 226,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time4'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 227,
        "count": 1,
        "names": ['ID_WEB_RBE_RT_Ist'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 228,
        "count": 1,
        "names": ['ID_WEB_RBE_RT_Soll'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 229,
        "count": 1,
        "names": ['ID_WEB_Temperatur_BW_oben'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 230,
        "count": 1,
        "names": ['ID_WEB_Code_WP_akt_2'],
        "type": HeatpumpCode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 231,
        "count": 1,
        "names": ['ID_WEB_Freq_VD'],
        "type": Frequency,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'Hz',
        "description": '',
    },
    {
        "index": 232,
        "count": 1,
        "names": ['Vapourisation_Temperature', 'Unknown_Calculation_232'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 233,
        "count": 1,
        "names": ['Liquefaction_Temperature', 'Unknown_Calculation_233'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 234,
        "count": 1,
        "names": ['Unknown_Calculation_234'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 235,
        "count": 1,
        "names": ['Unknown_Calculation_235'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 236,
        "count": 1,
        "names": ['ID_WEB_Freq_VD_Soll', 'Unknown_Calculation_236'],
        "type": Frequency,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'Hz',
        "description": '',
    },
    {
        "index": 237,
        "count": 1,
        "names": ['ID_WEB_Freq_VD_Min', 'Unknown_Calculation_237'],
        "type": Frequency,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'Hz',
        "description": '',
    },
    {
        "index": 238,
        "count": 1,
        "names": ['ID_WEB_Freq_VD_Max', 'Unknown_Calculation_238'],
        "type": Frequency,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'Hz',
        "description": '',
    },
    {
        "index": 239,
        "count": 1,
        "names": ['VBO_Temp_Spread_Soll', 'Unknown_Calculation_239'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 240,
        "count": 1,
        "names": ['VBO_Temp_Spread_Ist', 'Unknown_Calculation_240'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 241,
        "count": 1,
        "names": ['HUP_PWM', 'Circulation_Pump'],
        "type": Percent2,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '%',
        "description": '',
    },
    {
        "index": 242,
        "count": 1,
        "names": ['HUP_Temp_Spread_Soll', 'Unknown_Calculation_242'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 243,
        "count": 1,
        "names": ['HUP_Temp_Spread_Ist', 'Unknown_Calculation_243'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 244,
        "count": 1,
        "names": ['Unknown_Calculation_244'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 245,
        "count": 1,
        "names": ['Unknown_Calculation_245'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 246,
        "count": 1,
        "names": ['Unknown_Calculation_246'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 247,
        "count": 1,
        "names": ['Unknown_Calculation_247'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 248,
        "count": 1,
        "names": ['Unknown_Calculation_248'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 249,
        "count": 1,
        "names": ['Unknown_Calculation_249'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 250,
        "count": 1,
        "names": ['Unknown_Calculation_250'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 251,
        "count": 1,
        "names": ['Unknown_Calculation_251'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 252,
        "count": 1,
        "names": ['Unknown_Calculation_252'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 253,
        "count": 1,
        "names": ['Unknown_Calculation_253'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 254,
        "count": 1,
        "names": ['Flow_Rate_254'],
        "type": Flow,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'l/h',
        "description": '',
    },
    {
        "index": 255,
        "count": 1,
        "names": ['Unknown_Calculation_255'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 256,
        "count": 1,
        "names": ['Unknown_Calculation_256'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 257,
        "count": 1,
        "names": ['Heat_Output'],
        "type": Power,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'W',
        "description": '',
    },
    {
        "index": 258,
        "count": 1,
        "names": ['RBE_Version', 'Unknown_Calculation_258'],
        "type": MajorMinorVersion,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 259,
        "count": 1,
        "names": ['Unknown_Calculation_259'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 260,
        "count": 1,
        "names": ['Unknown_Calculation_260'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 261,
        "count": 1,
        "names": ['Unknown_Calculation_261'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 262,
        "count": 1,
        "names": ['Unknown_Calculation_262'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 263,
        "count": 1,
        "names": ['Unknown_Calculation_263'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 264,
        "count": 1,
        "names": ['Unknown_Calculation_264'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 265,
        "count": 1,
        "names": ['Unknown_Calculation_265'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 266,
        "count": 1,
        "names": ['Unknown_Calculation_266'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 267,
        "count": 1,
        "names": ['Desired_Room_Temperature'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 268,
        "count": 1,
        "names": ['AC_Power_Input'],
        "type": Power,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'W',
        "description": '',
    },
]
