"""
Constant list containing all 'calculation' definitions
used by the config interface (CFI) of the Luxtronik controller.

The calculations holds values based on the currently measured values,
are read-only and are used for control and display purposes.

NOTES:
- If there are multiple definitions for an index, the newest and
preferred one should be inserted as the last one in the same index.
"""

from typing import Final

from luxtronik.datatypes import (
    BivalenceLevel,
    Bool,
    Celsius,
    Character,
    Count,
    Energy,
    Errorcode,
    Flow,
    Frequency,
    HeatpumpCode,
    Icon,
    IPv4Address,
    Kelvin,
    Level,
    MainMenuStatusLine1,
    MainMenuStatusLine2,
    MainMenuStatusLine3,
    OperationMode,
    Percent2,
    Power,
    Pressure,
    Seconds,
    SecOperationMode,
    Speed,
    SwitchoffFile,
    Timestamp,
    Unknown,
    MajorMinorVersion,
    Voltage,
)

# Offset which must be added to the calculation indices
# to obtain the correct address of the data fields
CALCULATIONS_OFFSET: Final = 0
CALCULATIONS_DEFAULT_DATA_TYPE: Final = 'INT32'

CALCULATIONS_DEFINITIONS_LIST: Final = [
    {
        "index": 0,
        "count": 1,
        "names": ['Unknown_Calculation_0'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 1,
        "count": 1,
        "names": ['Unknown_Calculation_1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 2,
        "count": 1,
        "names": ['Unknown_Calculation_2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 3,
        "count": 1,
        "names": ['Unknown_Calculation_3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 4,
        "count": 1,
        "names": ['Unknown_Calculation_4'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 5,
        "count": 1,
        "names": ['Unknown_Calculation_5'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 6,
        "count": 1,
        "names": ['Unknown_Calculation_6'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 7,
        "count": 1,
        "names": ['Unknown_Calculation_7'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 8,
        "count": 1,
        "names": ['Unknown_Calculation_8'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 9,
        "count": 1,
        "names": ['Unknown_Calculation_9'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 10,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TVL', 'Unknown_Calculation_10'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 11,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TRL', 'Unknown_Calculation_11'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 12,
        "count": 1,
        "names": ['ID_WEB_Sollwert_TRL_HZ', 'Unknown_Calculation_12'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 13,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TRL_ext', 'Unknown_Calculation_13'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 14,
        "count": 1,
        "names": ['ID_WEB_Temperatur_THG', 'Unknown_Calculation_14'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 15,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TA', 'Unknown_Calculation_15'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 16,
        "count": 1,
        "names": ['ID_WEB_Mitteltemperatur', 'Unknown_Calculation_16'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 17,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TBW', 'Unknown_Calculation_17'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 18,
        "count": 1,
        "names": ['ID_WEB_Einst_BWS_akt', 'Unknown_Calculation_18'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 19,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TWE', 'Unknown_Calculation_19'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 20,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TWA', 'Unknown_Calculation_20'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 21,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TFB1', 'Unknown_Calculation_21'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 22,
        "count": 1,
        "names": ['ID_WEB_Sollwert_TVL_MK1', 'Unknown_Calculation_22'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 23,
        "count": 1,
        "names": ['ID_WEB_Temperatur_RFV', 'Unknown_Calculation_23'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 24,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TFB2', 'Unknown_Calculation_24'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 25,
        "count": 1,
        "names": ['ID_WEB_Sollwert_TVL_MK2', 'Unknown_Calculation_25'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 26,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TSK', 'Unknown_Calculation_26'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 27,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TSS', 'Unknown_Calculation_27'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 28,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TEE', 'Unknown_Calculation_28'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 29,
        "count": 1,
        "names": ['ID_WEB_ASDin', 'Unknown_Calculation_29'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 30,
        "count": 1,
        "names": ['ID_WEB_BWTin', 'Unknown_Calculation_30'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 31,
        "count": 1,
        "names": ['ID_WEB_EVUin', 'Unknown_Calculation_31'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 32,
        "count": 1,
        "names": ['ID_WEB_HDin', 'Unknown_Calculation_32'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 33,
        "count": 1,
        "names": ['ID_WEB_MOTin', 'Unknown_Calculation_33'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 34,
        "count": 1,
        "names": ['ID_WEB_NDin', 'Unknown_Calculation_34'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 35,
        "count": 1,
        "names": ['ID_WEB_PEXin', 'Unknown_Calculation_35'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 36,
        "count": 1,
        "names": ['ID_WEB_SWTin', 'Unknown_Calculation_36'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 37,
        "count": 1,
        "names": ['ID_WEB_AVout', 'Unknown_Calculation_37'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 38,
        "count": 1,
        "names": ['ID_WEB_BUPout', 'Unknown_Calculation_38'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 39,
        "count": 1,
        "names": ['ID_WEB_HUPout', 'Unknown_Calculation_39'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 40,
        "count": 1,
        "names": ['ID_WEB_MA1out', 'Unknown_Calculation_40'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 41,
        "count": 1,
        "names": ['ID_WEB_MZ1out', 'Unknown_Calculation_41'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 42,
        "count": 1,
        "names": ['ID_WEB_VENout', 'Unknown_Calculation_42'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 43,
        "count": 1,
        "names": ['ID_WEB_VBOout', 'Unknown_Calculation_43'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 44,
        "count": 1,
        "names": ['ID_WEB_VD1out', 'Unknown_Calculation_44'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 45,
        "count": 1,
        "names": ['ID_WEB_VD2out', 'Unknown_Calculation_45'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 46,
        "count": 1,
        "names": ['ID_WEB_ZIPout', 'Unknown_Calculation_46'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 47,
        "count": 1,
        "names": ['ID_WEB_ZUPout', 'Unknown_Calculation_47'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 48,
        "count": 1,
        "names": ['ID_WEB_ZW1out', 'Unknown_Calculation_48'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 49,
        "count": 1,
        "names": ['ID_WEB_ZW2SSTout', 'Unknown_Calculation_49'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 50,
        "count": 1,
        "names": ['ID_WEB_ZW3SSTout', 'Unknown_Calculation_50'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 51,
        "count": 1,
        "names": ['ID_WEB_FP2out', 'Unknown_Calculation_51'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 52,
        "count": 1,
        "names": ['ID_WEB_SLPout', 'Unknown_Calculation_52'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 53,
        "count": 1,
        "names": ['ID_WEB_SUPout', 'Unknown_Calculation_53'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 54,
        "count": 1,
        "names": ['ID_WEB_MZ2out', 'Unknown_Calculation_54'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 55,
        "count": 1,
        "names": ['ID_WEB_MA2out', 'Unknown_Calculation_55'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 56,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitVD1', 'Unknown_Calculation_56'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 57,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitImpVD1', 'Unknown_Calculation_57'],
        "type": Count,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 58,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitVD2', 'Unknown_Calculation_58'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 59,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitImpVD2', 'Unknown_Calculation_59'],
        "type": Count,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 60,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitZWE1', 'Unknown_Calculation_60'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 61,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitZWE2', 'Unknown_Calculation_61'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 62,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitZWE3', 'Unknown_Calculation_62'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 63,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitWP', 'Unknown_Calculation_63'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 64,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitHz', 'Unknown_Calculation_64'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 65,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitBW', 'Unknown_Calculation_65'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 66,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitKue', 'Unknown_Calculation_66'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 67,
        "count": 1,
        "names": ['ID_WEB_Time_WPein_akt', 'Unknown_Calculation_67'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 68,
        "count": 1,
        "names": ['ID_WEB_Time_ZWE1_akt', 'Unknown_Calculation_68'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 69,
        "count": 1,
        "names": ['ID_WEB_Time_ZWE2_akt', 'Unknown_Calculation_69'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 70,
        "count": 1,
        "names": ['ID_WEB_Timer_EinschVerz', 'Unknown_Calculation_70'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 71,
        "count": 1,
        "names": ['ID_WEB_Time_SSPAUS_akt', 'Unknown_Calculation_71'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 72,
        "count": 1,
        "names": ['ID_WEB_Time_SSPEIN_akt', 'Unknown_Calculation_72'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 73,
        "count": 1,
        "names": ['ID_WEB_Time_VDStd_akt', 'Unknown_Calculation_73'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 74,
        "count": 1,
        "names": ['ID_WEB_Time_HRM_akt', 'Unknown_Calculation_74'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 75,
        "count": 1,
        "names": ['ID_WEB_Time_HRW_akt', 'Unknown_Calculation_75'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 76,
        "count": 1,
        "names": ['ID_WEB_Time_LGS_akt', 'Unknown_Calculation_76'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 77,
        "count": 1,
        "names": ['ID_WEB_Time_SBW_akt', 'Unknown_Calculation_77'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 78,
        "count": 1,
        "names": ['ID_WEB_Code_WP_akt', 'Unknown_Calculation_78'],
        "type": HeatpumpCode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 79,
        "count": 1,
        "names": ['ID_WEB_BIV_Stufe_akt', 'Unknown_Calculation_79'],
        "type": BivalenceLevel,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 80,
        "count": 1,
        "names": ['ID_WEB_WP_BZ_akt', 'Unknown_Calculation_80'],
        "type": OperationMode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 81,
        "count": 1,
        "names": ['ID_WEB_SoftStand_0', 'Unknown_Calculation_81'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 82,
        "count": 1,
        "names": ['ID_WEB_SoftStand_1', 'Unknown_Calculation_82'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 83,
        "count": 1,
        "names": ['ID_WEB_SoftStand_2', 'Unknown_Calculation_83'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 84,
        "count": 1,
        "names": ['ID_WEB_SoftStand_3', 'Unknown_Calculation_84'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 85,
        "count": 1,
        "names": ['ID_WEB_SoftStand_4', 'Unknown_Calculation_85'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 86,
        "count": 1,
        "names": ['ID_WEB_SoftStand_5', 'Unknown_Calculation_86'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 87,
        "count": 1,
        "names": ['ID_WEB_SoftStand_6', 'Unknown_Calculation_87'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 88,
        "count": 1,
        "names": ['ID_WEB_SoftStand_7', 'Unknown_Calculation_88'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 89,
        "count": 1,
        "names": ['ID_WEB_SoftStand_8', 'Unknown_Calculation_89'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 90,
        "count": 1,
        "names": ['ID_WEB_SoftStand_9', 'Unknown_Calculation_90'],
        "type": Character,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 91,
        "count": 1,
        "names": ['ID_WEB_AdresseIP_akt', 'Unknown_Calculation_91'],
        "type": IPv4Address,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 92,
        "count": 1,
        "names": ['ID_WEB_SubNetMask_akt', 'Unknown_Calculation_92'],
        "type": IPv4Address,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 93,
        "count": 1,
        "names": ['ID_WEB_Add_Broadcast', 'Unknown_Calculation_93'],
        "type": IPv4Address,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 94,
        "count": 1,
        "names": ['ID_WEB_Add_StdGateway', 'Unknown_Calculation_94'],
        "type": IPv4Address,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 95,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time0', 'Unknown_Calculation_95'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 96,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time1', 'Unknown_Calculation_96'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 97,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time2', 'Unknown_Calculation_97'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 98,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time3', 'Unknown_Calculation_98'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 99,
        "count": 1,
        "names": ['ID_WEB_ERROR_Time4', 'Unknown_Calculation_99'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 100,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr0', 'Unknown_Calculation_100'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 101,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr1', 'Unknown_Calculation_101'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 102,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr2', 'Unknown_Calculation_102'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 103,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr3', 'Unknown_Calculation_103'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 104,
        "count": 1,
        "names": ['ID_WEB_ERROR_Nr4', 'Unknown_Calculation_104'],
        "type": Errorcode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 105,
        "count": 1,
        "names": ['ID_WEB_AnzahlFehlerInSpeicher', 'Unknown_Calculation_105'],
        "type": Count,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 106,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr0', 'Unknown_Calculation_106'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 107,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr1', 'Unknown_Calculation_107'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 108,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr2', 'Unknown_Calculation_108'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 109,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr3', 'Unknown_Calculation_109'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 110,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Nr4', 'Unknown_Calculation_110'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 111,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time0', 'Unknown_Calculation_111'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 112,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time1', 'Unknown_Calculation_112'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 113,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time2', 'Unknown_Calculation_113'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 114,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time3', 'Unknown_Calculation_114'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 115,
        "count": 1,
        "names": ['ID_WEB_Switchoff_file_Time4', 'Unknown_Calculation_115'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 116,
        "count": 1,
        "names": ['ID_WEB_Comfort_exists', 'Unknown_Calculation_116'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 117,
        "count": 1,
        "names": ['ID_WEB_HauptMenuStatus_Zeile1', 'Unknown_Calculation_117'],
        "type": MainMenuStatusLine1,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 118,
        "count": 1,
        "names": ['ID_WEB_HauptMenuStatus_Zeile2', 'Unknown_Calculation_118'],
        "type": MainMenuStatusLine2,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 119,
        "count": 1,
        "names": ['ID_WEB_HauptMenuStatus_Zeile3', 'Unknown_Calculation_119'],
        "type": MainMenuStatusLine3,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 120,
        "count": 1,
        "names": ['ID_WEB_HauptMenuStatus_Zeit', 'Unknown_Calculation_120'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 121,
        "count": 1,
        "names": ['ID_WEB_HauptMenuAHP_Stufe', 'Unknown_Calculation_121'],
        "type": Level,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 122,
        "count": 1,
        "names": ['ID_WEB_HauptMenuAHP_Temp', 'Unknown_Calculation_122'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 123,
        "count": 1,
        "names": ['ID_WEB_HauptMenuAHP_Zeit', 'Unknown_Calculation_123'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 124,
        "count": 1,
        "names": ['ID_WEB_SH_BWW', 'Unknown_Calculation_124'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 125,
        "count": 1,
        "names": ['ID_WEB_SH_HZ', 'Unknown_Calculation_125'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 126,
        "count": 1,
        "names": ['ID_WEB_SH_MK1', 'Unknown_Calculation_126'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 127,
        "count": 1,
        "names": ['ID_WEB_SH_MK2', 'Unknown_Calculation_127'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 128,
        "count": 1,
        "names": ['ID_WEB_Einst_Kurzrpgramm', 'Unknown_Calculation_128'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 129,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_1', 'Unknown_Calculation_129'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 130,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_2', 'Unknown_Calculation_130'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 131,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_3', 'Unknown_Calculation_131'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 132,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_4', 'Unknown_Calculation_132'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 133,
        "count": 1,
        "names": ['ID_WEB_StatusSlave_5', 'Unknown_Calculation_133'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 134,
        "count": 1,
        "names": ['ID_WEB_AktuelleTimeStamp', 'Unknown_Calculation_134'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 135,
        "count": 1,
        "names": ['ID_WEB_SH_MK3', 'Unknown_Calculation_135'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 136,
        "count": 1,
        "names": ['ID_WEB_Sollwert_TVL_MK3', 'Unknown_Calculation_136'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 137,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TFB3', 'Unknown_Calculation_137'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 138,
        "count": 1,
        "names": ['ID_WEB_MZ3out', 'Unknown_Calculation_138'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 139,
        "count": 1,
        "names": ['ID_WEB_MA3out', 'Unknown_Calculation_139'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 140,
        "count": 1,
        "names": ['ID_WEB_FP3out', 'Unknown_Calculation_140'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 141,
        "count": 1,
        "names": ['ID_WEB_Time_AbtIn', 'Unknown_Calculation_141'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 142,
        "count": 1,
        "names": ['ID_WEB_Temperatur_RFV2', 'Unknown_Calculation_142'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 143,
        "count": 1,
        "names": ['ID_WEB_Temperatur_RFV3', 'Unknown_Calculation_143'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 144,
        "count": 1,
        "names": ['ID_WEB_SH_SW', 'Unknown_Calculation_144'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 145,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitSW', 'Unknown_Calculation_145'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 146,
        "count": 1,
        "names": ['ID_WEB_FreigabKuehl', 'Unknown_Calculation_146'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 147,
        "count": 1,
        "names": ['ID_WEB_AnalogIn', 'Unknown_Calculation_147'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 148,
        "count": 1,
        "names": ['ID_WEB_SonderZeichen', 'Unknown_Calculation_148'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 149,
        "count": 1,
        "names": ['ID_WEB_SH_ZIP', 'Unknown_Calculation_149'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 150,
        "count": 1,
        "names": ['ID_WEB_WebsrvProgrammWerteBeobarten', 'Unknown_Calculation_150'],
        "type": Icon,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 151,
        "count": 1,
        "names": ['ID_WEB_WMZ_Heizung', 'Unknown_Calculation_151'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 152,
        "count": 1,
        "names": ['ID_WEB_WMZ_Brauchwasser', 'Unknown_Calculation_152'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 153,
        "count": 1,
        "names": ['ID_WEB_WMZ_Schwimmbad', 'Unknown_Calculation_153'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 154,
        "count": 1,
        "names": ['ID_WEB_WMZ_Seit', 'Unknown_Calculation_154'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 155,
        "count": 1,
        "names": ['ID_WEB_WMZ_Durchfluss', 'Unknown_Calculation_155'],
        "type": Flow,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'l/h',
        "description": '',
    },
    {
        "index": 156,
        "count": 1,
        "names": ['ID_WEB_AnalogOut1', 'Unknown_Calculation_156'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 157,
        "count": 1,
        "names": ['ID_WEB_AnalogOut2', 'Unknown_Calculation_157'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 158,
        "count": 1,
        "names": ['ID_WEB_Time_Heissgas', 'Unknown_Calculation_158'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 159,
        "count": 1,
        "names": ['ID_WEB_Temp_Lueftung_Zuluft', 'Unknown_Calculation_159'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 160,
        "count": 1,
        "names": ['ID_WEB_Temp_Lueftung_Abluft', 'Unknown_Calculation_160'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 161,
        "count": 1,
        "names": ['ID_WEB_Zaehler_BetrZeitSolar', 'Unknown_Calculation_161'],
        "type": Seconds,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 's',
        "description": '',
    },
    {
        "index": 162,
        "count": 1,
        "names": ['ID_WEB_AnalogOut3', 'Unknown_Calculation_162'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 163,
        "count": 1,
        "names": ['ID_WEB_AnalogOut4', 'Unknown_Calculation_163'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 164,
        "count": 1,
        "names": ['ID_WEB_Out_VZU', 'Unknown_Calculation_164'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 165,
        "count": 1,
        "names": ['ID_WEB_Out_VAB', 'Unknown_Calculation_165'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 166,
        "count": 1,
        "names": ['ID_WEB_Out_VSK', 'Unknown_Calculation_166'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 167,
        "count": 1,
        "names": ['ID_WEB_Out_FRH', 'Unknown_Calculation_167'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 168,
        "count": 1,
        "names": ['ID_WEB_AnalogIn2', 'Unknown_Calculation_168'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 169,
        "count": 1,
        "names": ['ID_WEB_AnalogIn3', 'Unknown_Calculation_169'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 170,
        "count": 1,
        "names": ['ID_WEB_SAXin', 'Unknown_Calculation_170'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 171,
        "count": 1,
        "names": ['ID_WEB_SPLin', 'Unknown_Calculation_171'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 172,
        "count": 1,
        "names": ['ID_WEB_Compact_exists', 'Unknown_Calculation_172'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 173,
        "count": 1,
        "names": ['ID_WEB_Durchfluss_WQ', 'Unknown_Calculation_173'],
        "type": Flow,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'l/h',
        "description": '',
    },
    {
        "index": 174,
        "count": 1,
        "names": ['ID_WEB_LIN_exists', 'Unknown_Calculation_174'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 175,
        "count": 1,
        "names": ['ID_WEB_LIN_ANSAUG_VERDAMPFER', 'Unknown_Calculation_175'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 176,
        "count": 1,
        "names": ['ID_WEB_LIN_ANSAUG_VERDICHTER', 'Unknown_Calculation_176'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 177,
        "count": 1,
        "names": ['ID_WEB_LIN_VDH', 'Unknown_Calculation_177'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 178,
        "count": 1,
        "names": ['ID_WEB_LIN_UH', 'Unknown_Calculation_178'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 179,
        "count": 1,
        "names": ['ID_WEB_LIN_UH_Soll', 'Unknown_Calculation_179'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 180,
        "count": 1,
        "names": ['ID_WEB_LIN_HD', 'Unknown_Calculation_180'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 181,
        "count": 1,
        "names": ['ID_WEB_LIN_ND', 'Unknown_Calculation_181'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 182,
        "count": 1,
        "names": ['ID_WEB_LIN_VDH_out', 'Unknown_Calculation_182'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 183,
        "count": 1,
        "names": ['ID_WEB_HZIO_PWM', 'Unknown_Calculation_183'],
        "type": Percent2,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '%',
        "description": '',
    },
    {
        "index": 184,
        "count": 1,
        "names": ['ID_WEB_HZIO_VEN', 'Unknown_Calculation_184'],
        "type": Speed,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'rpm',
        "description": '',
    },
    {
        "index": 185,
        "count": 1,
        "names": ['ID_WEB_HZIO_EVU2', 'Unknown_Calculation_185'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 186,
        "count": 1,
        "names": ['ID_WEB_HZIO_STB', 'Unknown_Calculation_186'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 187,
        "count": 1,
        "names": ['ID_WEB_SEC_Qh_Soll', 'Unknown_Calculation_187'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 188,
        "count": 1,
        "names": ['ID_WEB_SEC_Qh_Ist', 'Unknown_Calculation_188'],
        "type": Energy,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'kWh/10',
        "description": '',
    },
    {
        "index": 189,
        "count": 1,
        "names": ['ID_WEB_SEC_TVL_Soll', 'Unknown_Calculation_189'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 190,
        "count": 1,
        "names": ['ID_WEB_SEC_Software', 'Unknown_Calculation_190'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 191,
        "count": 1,
        "names": ['ID_WEB_SEC_BZ', 'Unknown_Calculation_191'],
        "type": SecOperationMode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 192,
        "count": 1,
        "names": ['ID_WEB_SEC_VWV', 'Unknown_Calculation_192'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 193,
        "count": 1,
        "names": ['ID_WEB_SEC_VD', 'Unknown_Calculation_193'],
        "type": Speed,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'rpm',
        "description": '',
    },
    {
        "index": 194,
        "count": 1,
        "names": ['ID_WEB_SEC_VerdEVI', 'Unknown_Calculation_194'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 195,
        "count": 1,
        "names": ['ID_WEB_SEC_AnsEVI', 'Unknown_Calculation_195'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 196,
        "count": 1,
        "names": ['ID_WEB_SEC_UEH_EVI', 'Unknown_Calculation_196'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 197,
        "count": 1,
        "names": ['ID_WEB_SEC_UEH_EVI_S', 'Unknown_Calculation_197'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 198,
        "count": 1,
        "names": ['ID_WEB_SEC_KondTemp', 'Unknown_Calculation_198'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 199,
        "count": 1,
        "names": ['ID_WEB_SEC_FlussigEx', 'Unknown_Calculation_199'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 200,
        "count": 1,
        "names": ['ID_WEB_SEC_UK_EEV', 'Unknown_Calculation_200'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 201,
        "count": 1,
        "names": ['ID_WEB_SEC_EVI_Druck', 'Unknown_Calculation_201'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 202,
        "count": 1,
        "names": ['ID_WEB_SEC_U_Inv', 'Unknown_Calculation_202'],
        "type": Voltage,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'V/10',
        "description": '',
    },
    {
        "index": 203,
        "count": 1,
        "names": ['ID_WEB_Temperatur_THG_2', 'Unknown_Calculation_203'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 204,
        "count": 1,
        "names": ['ID_WEB_Temperatur_TWE_2', 'Unknown_Calculation_204'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 205,
        "count": 1,
        "names": ['ID_WEB_LIN_ANSAUG_VERDAMPFER_2', 'Unknown_Calculation_205'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 206,
        "count": 1,
        "names": ['ID_WEB_LIN_ANSAUG_VERDICHTER_2', 'Unknown_Calculation_206'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 207,
        "count": 1,
        "names": ['ID_WEB_LIN_VDH_2', 'Unknown_Calculation_207'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 208,
        "count": 1,
        "names": ['ID_WEB_LIN_UH_2', 'Unknown_Calculation_208'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 209,
        "count": 1,
        "names": ['ID_WEB_LIN_UH_Soll_2', 'Unknown_Calculation_209'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 210,
        "count": 1,
        "names": ['ID_WEB_LIN_HD_2', 'Unknown_Calculation_210'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 211,
        "count": 1,
        "names": ['ID_WEB_LIN_ND_2', 'Unknown_Calculation_211'],
        "type": Pressure,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'bar/100',
        "description": '',
    },
    {
        "index": 212,
        "count": 1,
        "names": ['ID_WEB_HDin_2', 'Unknown_Calculation_212'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 213,
        "count": 1,
        "names": ['ID_WEB_AVout_2', 'Unknown_Calculation_213'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 214,
        "count": 1,
        "names": ['ID_WEB_VBOout_2', 'Unknown_Calculation_214'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 215,
        "count": 1,
        "names": ['ID_WEB_VD1out_2', 'Unknown_Calculation_215'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 216,
        "count": 1,
        "names": ['ID_WEB_LIN_VDH_out_2', 'Unknown_Calculation_216'],
        "type": Bool,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 217,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr0', 'Unknown_Calculation_217'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 218,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr1', 'Unknown_Calculation_218'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 219,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr2', 'Unknown_Calculation_219'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 220,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr3', 'Unknown_Calculation_220'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 221,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Nr4', 'Unknown_Calculation_221'],
        "type": SwitchoffFile,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 222,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time0', 'Unknown_Calculation_222'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 223,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time1', 'Unknown_Calculation_223'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 224,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time2', 'Unknown_Calculation_224'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 225,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time3', 'Unknown_Calculation_225'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 226,
        "count": 1,
        "names": ['ID_WEB_Switchoff2_file_Time4', 'Unknown_Calculation_226'],
        "type": Timestamp,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 227,
        "count": 1,
        "names": ['ID_WEB_RBE_RT_Ist', 'Unknown_Calculation_227'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 228,
        "count": 1,
        "names": ['ID_WEB_RBE_RT_Soll', 'Unknown_Calculation_228'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 229,
        "count": 1,
        "names": ['ID_WEB_Temperatur_BW_oben', 'Unknown_Calculation_229'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 230,
        "count": 1,
        "names": ['ID_WEB_Code_WP_akt_2', 'Unknown_Calculation_230'],
        "type": HeatpumpCode,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'enum',
        "description": '',
    },
    {
        "index": 231,
        "count": 1,
        "names": ['ID_WEB_Freq_VD', 'Unknown_Calculation_231'],
        "type": Frequency,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'Hz',
        "description": '',
    },
    {
        "index": 232,
        "count": 1,
        "names": ['Vapourisation_Temperature', 'Unknown_Calculation_232'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 233,
        "count": 1,
        "names": ['Liquefaction_Temperature', 'Unknown_Calculation_233'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 234,
        "count": 1,
        "names": ['Unknown_Calculation_234'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 235,
        "count": 1,
        "names": ['Unknown_Calculation_235'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 236,
        "count": 1,
        "names": ['ID_WEB_Freq_VD_Soll', 'Unknown_Calculation_236'],
        "type": Frequency,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'Hz',
        "description": '',
    },
    {
        "index": 237,
        "count": 1,
        "names": ['ID_WEB_Freq_VD_Min', 'Unknown_Calculation_237'],
        "type": Frequency,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'Hz',
        "description": '',
    },
    {
        "index": 238,
        "count": 1,
        "names": ['ID_WEB_Freq_VD_Max', 'Unknown_Calculation_238'],
        "type": Frequency,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'Hz',
        "description": '',
    },
    {
        "index": 239,
        "count": 1,
        "names": ['VBO_Temp_Spread_Soll', 'Unknown_Calculation_239'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 240,
        "count": 1,
        "names": ['VBO_Temp_Spread_Ist', 'Unknown_Calculation_240'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 241,
        "count": 1,
        "names": ['HUP_PWM', 'Circulation_Pump', 'Unknown_Calculation_241'],
        "type": Percent2,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '%',
        "description": '',
    },
    {
        "index": 242,
        "count": 1,
        "names": ['HUP_Temp_Spread_Soll', 'Unknown_Calculation_242'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 243,
        "count": 1,
        "names": ['HUP_Temp_Spread_Ist', 'Unknown_Calculation_243'],
        "type": Kelvin,
        "writeable": False,
        "datatype": 'INT32',
        "unit": 'K/10',
        "description": '',
    },
    {
        "index": 244,
        "count": 1,
        "names": ['Unknown_Calculation_244'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 245,
        "count": 1,
        "names": ['Unknown_Calculation_245'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 246,
        "count": 1,
        "names": ['Unknown_Calculation_246'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 247,
        "count": 1,
        "names": ['Unknown_Calculation_247'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 248,
        "count": 1,
        "names": ['Unknown_Calculation_248'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 249,
        "count": 1,
        "names": ['Unknown_Calculation_249'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 250,
        "count": 1,
        "names": ['Unknown_Calculation_250'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 251,
        "count": 1,
        "names": ['Unknown_Calculation_251'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 252,
        "count": 1,
        "names": ['Unknown_Calculation_252'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 253,
        "count": 1,
        "names": ['Unknown_Calculation_253'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 254,
        "count": 1,
        "names": ['Flow_Rate_254', 'Unknown_Calculation_254'],
        "type": Flow,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'l/h',
        "description": '',
    },
    {
        "index": 255,
        "count": 1,
        "names": ['Unknown_Calculation_255'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 256,
        "count": 1,
        "names": ['Unknown_Calculation_256'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 257,
        "count": 1,
        "names": ['Heat_Output', 'Unknown_Calculation_257'],
        "type": Power,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'W',
        "description": '',
    },
    {
        "index": 258,
        "count": 1,
        "names": ['RBE_Version', 'Unknown_Calculation_258'],
        "type": MajorMinorVersion,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 259,
        "count": 1,
        "names": ['Unknown_Calculation_259'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 260,
        "count": 1,
        "names": ['Unknown_Calculation_260'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 261,
        "count": 1,
        "names": ['Unknown_Calculation_261'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 262,
        "count": 1,
        "names": ['Unknown_Calculation_262'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 263,
        "count": 1,
        "names": ['Unknown_Calculation_263'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 264,
        "count": 1,
        "names": ['Unknown_Calculation_264'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 265,
        "count": 1,
        "names": ['Unknown_Calculation_265'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 266,
        "count": 1,
        "names": ['Unknown_Calculation_266'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 267,
        "count": 1,
        "names": ['Desired_Room_Temperature', 'Unknown_Calculation_267'],
        "type": Celsius,
        "writeable": False,
        "datatype": 'INT32',
        "unit": '°C/10',
        "description": '',
    },
    {
        "index": 268,
        "count": 1,
        "names": ['AC_Power_Input', 'Unknown_Calculation_268'],
        "type": Power,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": 'W',
        "description": '',
    },
]
