"""
Constant list containing the complete holdings definitions.
"""
from luxtronik.datatypes import (
    Celsius,
    ControlMode,
    Kelvin,
    LevelMode,
    LockMode,
    LpcMode,
    OnOffMode,
    PowerLimit,
)

HOLDINGS_DEFINITIONS_LIST = [
    {
        "index": 0,
        "count": 1,
        "names": ["heating_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode of the heating function",
    },
    {
        "index": 1,
        "count": 1,
        "names": ["heating_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 15, "max": 75},
        "since": "3.90.1",
        "description": "Desired target temperature for heating in °C",
    },
    {
        "index": 2,
        "count": 1,
        "names": ["heating_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 20},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin for heating",
    },
    {
        "index": 3,
        "count": 1,
        "names": ["heating_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the temperature by the SHI-offsets-setting",
    },
    {
        "index": 5,
        "count": 1,
        "names": ["hot_water_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode of the hot water system",
    },
    {
        "index": 6,
        "count": 1,
        "names": ["hot_water_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 30, "max": 75},
        "since": "3.90.1",
        "description": "Target temperature for hot water in °C",
    },
    {
        "index": 7,
        "count": 1,
        "names": ["hot_water_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 20},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin for hot water",
    },
    {
        "index": 8,
        "count": 1,
        "names": ["hot_water_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the temperature by the SHI-offsets-setting",
    },
    {
        "index": 10,
        "count": 1,
        "names": ["MK1_heat_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for heating circuit 1",
    },
    {
        "index": 11,
        "count": 1,
        "names": ["MK1_heat_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 20, "max": 65},
        "since": "3.90.1",
        "description": "Target temperature for heating circuit 1 in °C",
    },
    {
        "index": 12,
        "count": 1,
        "names": ["MK1_heat_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin for heating circuit 1",
    },
    {
        "index": 13,
        "count": 1,
        "names": ["MK1_heat_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the temperature by the SHI-offsets-setting",
    },
    {
        "index": 15,
        "count": 1,
        "names": ["MK1_cool_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for cooling circuit 1",
    },
    {
        "index": 16,
        "count": 1,
        "names": ["MK1_cool_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 5, "max": 25},
        "since": "3.90.1",
        "description": "Target temperature for cooling circuit 1 in °C",
    },
    {
        "index": 17,
        "count": 1,
        "names": ["MK1_cool_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin for cooling circuit 1",
    },
    {
        "index": 20,
        "count": 1,
        "names": ["MK2_heat_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for heating circuit 2",
    },
    {
        "index": 21,
        "count": 1,
        "names": ["MK2_heat_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 20, "max": 65},
        "since": "3.90.1",
        "description": "Target temperature for heating circuit 2 in °C",
    },
    {
        "index": 22,
        "count": 1,
        "names": ["MK2_heat_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin for heating circuit 2",
    },
    {
        "index": 23,
        "count": 1,
        "names": ["MK2_heat_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the temperature by the SHI-offsets-setting",
    },
    {
        "index": 25,
        "count": 1,
        "names": ["MK2_cool_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for cooling circuit 2",
    },
    {
        "index": 26,
        "count": 1,
        "names": ["MK2_cool_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 5, "max": 25},
        "since": "3.90.1",
        "description": "Target temperature for cooling circuit 2 in °C",
    },
    {
        "index": 27,
        "count": 1,
        "names": ["MK2_cool_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin for cooling circuit 2",
    },
    {
        "index": 30,
        "count": 1,
        "names": ["MK3_heat_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for heating circuit 3",
    },
    {
        "index": 31,
        "count": 1,
        "names": ["MK3_heat_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 20, "max": 65},
        "since": "3.90.1",
        "description": "Target temperature for heating circuit 3 in °C",
    },
    {
        "index": 32,
        "count": 1,
        "names": ["MK3_heat_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin for heating circuit 3",
    },
    {
        "index": 33,
        "count": 1,
        "names": ["MK3_heat_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the temperature by the SHI-offsets-setting",
    },
    {
        "index": 35,
        "count": 1,
        "names": ["MK3_cool_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for cooling circuit 3",
    },
    {
        "index": 36,
        "count": 1,
        "names": ["MK3_cool_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 5, "max": 25},
        "since": "3.90.1",
        "description": "Target temperature for cooling circuit 3 in °C",
    },
    {
        "index": 37,
        "count": 1,
        "names": ["MK3_cool_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin for cooling circuit 3",
    },
    {
        "index": 40,
        "count": 1,
        "names": ["LPC_mode"],
        "type": LpcMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode of the load power control",
    },
    {
        "index": 41,
        "count": 1,
        "names": ["PC_limit"],
        "type": PowerLimit,
        "writeable": True,
        "range": {"min": 0, "max": 30},
        "since": "3.90.1",
        "description": "Maximum power limit",
    },
    {
        "index": 50,
        "count": 1,
        "names": ["lock_heating"],
        "type": LockMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Lock state for heating",
    },
    {
        "index": 51,
        "count": 1,
        "names": ["lock_hot_water"],
        "type": LockMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Lock state for hot water",
    },
    {
        "index": 52,
        "count": 1,
        "names": ["lock_cooling"],
        "type": LockMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Lock state for cooling",
    },
    {
        "index": 53,
        "count": 1,
        "names": ["lock_swimming_pool"],
        "type": LockMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Lock state for the swimming pool function",
    },
    {
        "index": 65,
        "count": 1,
        "names": ["heat_overall_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Operating mode of all heating functions (no setpoint available)",
    },
    {
        "index": 66,
        "count": 1,
        "names": ["heat_overall_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 20},
        "since": "3.92.0",
        "description": "Temperature correction in Kelvin for all heating functions",
    },
    {
        "index": 67,
        "count": 1,
        "names": ["heat_overall_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease all temperatures by the SHI-offsets-setting",
    },
    {
        "index": 70,
        "count": 1,
        "names": ["circulation"],
        "type": OnOffMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "When set to ON, the circulation pump is activated, but only if no time schedule is configured for it.",
    },
    {
        "index": 71,
        "count": 1,
        "names": ["hot_water_extra"],
        "type": OnOffMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "When set to ON, the hot water heating is activated and will run until the maximum temperature is reached.",
    },
]
