"""
Constant list containing all 'holdings' definitions
used by the Smart Home Interface (SHI) of the Luxtronik controller.

Unlike the setting registers, these SHI register are volatile and intended for
communication with smart home systems. 'Holding' registers are readable
and writable and are used to control the heat pump externally.
"""
from typing import Final

from luxtronik.datatypes import (
    Celsius,
    ControlMode,
    Kelvin,
    LevelMode,
    LockMode,
    LpcMode,
    OnOffMode,
    PowerLimit,
)

# Offset which must be added to the indices
# to obtain the correct address of the data fields
HOLDINGS_OFFSET: Final = 10000

HOLDINGS_DEFINITIONS_LIST: Final = [
    {
        "index": 0,
        "count": 1,
        "names": ["heating_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode of the heating function",
    },
    {
        "index": 1,
        "count": 1,
        "names": ["heating_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 15, "max": 75},
        "since": "3.90.1",
        "description": "Desired target temperature in °C " \
            "for the heating function",
    },
    {
        "index": 2,
        "count": 1,
        "names": ["heating_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 20},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin " \
            "for the heating function",
    },
    {
        "index": 3,
        "count": 1,
        "names": ["heating_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the heating temperature " \
            "using the SHI offset settings.",
    },
    {
        "index": 5,
        "count": 1,
        "names": ["hot_water_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode of the hot water system",
    },
    {
        "index": 6,
        "count": 1,
        "names": ["hot_water_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 30, "max": 75},
        "since": "3.90.1",
        "description": "Desired target temperature in °C " \
            "for hot water",
    },
    {
        "index": 7,
        "count": 1,
        "names": ["hot_water_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 20},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin " \
            "for hot water",
    },
    {
        "index": 8,
        "count": 1,
        "names": ["hot_water_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the hot water temperature " \
            "using the SHI offset settings.",
    },
    {
        "index": 10,
        "count": 1,
        "names": ["mc1_heat_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for mixing circuit 1 in heating mode",
    },
    {
        "index": 11,
        "count": 1,
        "names": ["mc1_heat_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 20, "max": 65},
        "since": "3.90.1",
        "description": "Desired target temperature in °C " \
            "for mixing circuit 1 in heating mode",
    },
    {
        "index": 12,
        "count": 1,
        "names": ["mc1_heat_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin " \
            "for mixing circuit 1 in heating mode",
    },
    {
        "index": 13,
        "count": 1,
        "names": ["mc1_heat_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the mixing circuit 1 temperature " \
            "using the SHI offset settings.",
    },
    {
        "index": 15,
        "count": 1,
        "names": ["mc1_cool_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for mixing circuit 1 in cooling mode",
    },
    {
        "index": 16,
        "count": 1,
        "names": ["mc1_cool_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 5, "max": 25},
        "since": "3.90.1",
        "description": "Desired target temperature in °C " \
            "for mixing circuit 1 in cooling mode",
    },
    {
        "index": 17,
        "count": 1,
        "names": ["mc1_cool_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin " \
            "for mixing circuit 1 in cooling mode",
    },
    {
        "index": 20,
        "count": 1,
        "names": ["mc2_heat_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for mixing circuit 2 in heating mode",
    },
    {
        "index": 21,
        "count": 1,
        "names": ["mc2_heat_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 20, "max": 65},
        "since": "3.90.1",
        "description": "Desired target temperature in °C " \
            "for mixing circuit 2 in heating mode",
    },
    {
        "index": 22,
        "count": 1,
        "names": ["mc2_heat_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin " \
            "for mixing circuit 2 in heating mode",
    },
    {
        "index": 23,
        "count": 1,
        "names": ["mc2_heat_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the mixing circuit 2 temperature " \
            "using the SHI offset settings.",
    },
    {
        "index": 25,
        "count": 1,
        "names": ["mc2_cool_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for mixing circuit 2 in cooling mode",
    },
    {
        "index": 26,
        "count": 1,
        "names": ["mc2_cool_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 5, "max": 25},
        "since": "3.90.1",
        "description": "Desired target temperature in °C " \
            "for mixing circuit 2 in cooling mode",
    },
    {
        "index": 27,
        "count": 1,
        "names": ["mc2_cool_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin " \
            "for mixing circuit 2 in cooling mode",
    },
    {
        "index": 30,
        "count": 1,
        "names": ["mc3_heat_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for mixing circuit 3 in heating mode",
    },
    {
        "index": 31,
        "count": 1,
        "names": ["mc3_heat_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 20, "max": 65},
        "since": "3.90.1",
        "description": "Desired target temperature in °C " \
            "for mixing circuit 3 in heating mode",
    },
    {
        "index": 32,
        "count": 1,
        "names": ["mc3_heat_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin " \
            "for mixing circuit 3 in heating mode",
    },
    {
        "index": 33,
        "count": 1,
        "names": ["mc3_heat_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease the mixing circuit 3 temperature " \
            "using the SHI offset settings.",
    },
    {
        "index": 35,
        "count": 1,
        "names": ["mc3_cool_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode for mixing circuit 3 in cooling mode",
    },
    {
        "index": 36,
        "count": 1,
        "names": ["mc3_cool_setpoint"],
        "type": Celsius,
        "writeable": True,
        "range": {"min": 5, "max": 25},
        "since": "3.90.1",
        "description": "Desired target temperature in °C " \
            "for mixing circuit 3 in cooling mode",
    },
    {
        "index": 37,
        "count": 1,
        "names": ["mc3_cool_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 5},
        "since": "3.90.1",
        "description": "Temperature correction in Kelvin " \
            "for mixing circuit 3 in cooling mode",
    },
    {
        "index": 40,
        "count": 1,
        "names": ["lpc_mode"],
        "type": LpcMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Operating mode of the load power control",
    },
    {
        "index": 41,
        "count": 1,
        "names": ["pc_limit"],
        "type": PowerLimit,
        "writeable": True,
        "range": {"min": 0, "max": 30},
        "since": "3.90.1",
        "description": "Maximum power limit",
    },
    {
        "index": 50,
        "count": 1,
        "names": ["lock_heating"],
        "type": LockMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Lock state for the heating function",
    },
    {
        "index": 51,
        "count": 1,
        "names": ["lock_hot_water"],
        "type": LockMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Lock state for the hot water system",
    },
    {
        "index": 52,
        "count": 1,
        "names": ["lock_cooling"],
        "type": LockMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Lock state for the cooling function",
    },
    {
        "index": 53,
        "count": 1,
        "names": ["lock_swimming_pool"],
        "type": LockMode,
        "writeable": True,
        "since": "3.90.1",
        "description": "Lock state for the swimming pool function",
    },
    {
        "index": 65,
        "count": 1,
        "names": ["heat_overall_mode"],
        "type": ControlMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Operating mode of all heating functions (no setpoint available)",
    },
    {
        "index": 66,
        "count": 1,
        "names": ["heat_overall_offset"],
        "type": Kelvin,
        "writeable": True,
        "range": {"min": 0, "max": 20},
        "since": "3.92.0",
        "description": "Temperature correction in Kelvin " \
            "for all heating functions",
    },
    {
        "index": 67,
        "count": 1,
        "names": ["heat_overall_level"],
        "type": LevelMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "Increase or decrease all heating temperatures " \
            "using the SHI offset settings.",
    },
    {
        "index": 70,
        "count": 1,
        "names": ["circulation"],
        "type": OnOffMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "When set to ON, the circulation pump is activated, but only if no time schedule is configured for it.",
    },
    {
        "index": 71,
        "count": 1,
        "names": ["hot_water_extra"],
        "type": OnOffMode,
        "writeable": True,
        "since": "3.92.0",
        "description": "When set to ON, the hot water heating is activated and will run until the maximum temperature is reached.",
    },
]
