"""
Constant list containing the complete inputs definitions.
"""
from luxtronik.datatypes import (
    Celsius,
    Energy,
    FullVersion,
    HeatPumpState,
    ModeState,
    OperationMode,
    Unknown,
)

INPUTS_DEFINITIONS_LIST = [
    {
        "index": 0,
        "count": 1,
        "names": ["Heatpump_state"],
        "type": HeatPumpState,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current operating state of the heat pump",
    },
    {
        "index": 2,
        "count": 1,
        "names": ["Operation_mode"],
        "type": OperationMode,
        "writeable": False,
        "since": "3.90.1",
        "description": "Overall operation mode of the system",
    },
    {
        "index": 3,
        "count": 1,
        "names": ["Heating_state"],
        "type": ModeState,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current state of the heating function",
    },
    {
        "index": 4,
        "count": 1,
        "names": ["Hot_water_state"],
        "type": ModeState,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current state of the hot water function",
    },
    {
        "index": 6,
        "count": 1,
        "names": ["Unknown_Input_6"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 7,
        "count": 1,
        "names": ["Unknown_Input_7"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 100,
        "count": 1,
        "names": ["TRL"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current return line temperature",
    },
    {
        "index": 101,
        "count": 1,
        "names": ["TRL_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Target return line temperature",
    },
    {
        "index": 102,
        "count": 1,
        "names": ["TRL_ext"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "External return line temperature sensor reading",
    },
    {
        "index": 103,
        "count": 1,
        "names": ["TRL_limit"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum allowed return line temperature",
    },
    {
        "index": 104,
        "count": 1,
        "names": ["TRL_min_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum target return line temperature",
    },
    {
        "index": 105,
        "count": 1,
        "names": ["TVL"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current flow line temperature",
    },
    {
        "index": 106,
        "count": 1,
        "names": ["Unknown_Input_106"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 107,
        "count": 1,
        "names": ["Inside_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Measured indoor temperature",
    },
    {
        "index": 108,
        "count": 1,
        "names": ["Outside_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Measured outdoor temperature",
    },
    {
        "index": 109,
        "count": 1,
        "names": ["Unknown_Input_109"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 110,
        "count": 1,
        "names": ["Unknown_Input_110"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 111,
        "count": 1,
        "names": ["Unknown_Input_111"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 112,
        "count": 1,
        "names": ["Unknown_Input_112"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 113,
        "count": 1,
        "names": ["Unknown_Input_113"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 120,
        "count": 1,
        "names": ["Hot_water_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current hot water temperature",
    },
    {
        "index": 121,
        "count": 1,
        "names": ["Hot_water_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Target hot water temperature",
    },
    {
        "index": 122,
        "count": 1,
        "names": ["Hot_water_min"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum hot water temperature",
    },
    {
        "index": 123,
        "count": 1,
        "names": ["Hot_water_max"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum hot water temperature",
    },
    {
        "index": 124,
        "count": 1,
        "names": ["Unknown_Input_124"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – possibly hot water idle/running indicator",
    },
    {
        "index": 140,
        "count": 1,
        "names": ["MK1_heat_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current heating circuit 1 temperature",
    },
    {
        "index": 141,
        "count": 1,
        "names": ["MK1_heat_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Target heating circuit 1 temperature",
    },
    {
        "index": 142,
        "count": 1,
        "names": ["MK1_heat_min"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum heating circuit 1 temperature",
    },
    {
        "index": 143,
        "count": 1,
        "names": ["MK1_heat_max"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum heating circuit 1 temperature",
    },
    {
        "index": 150,
        "count": 1,
        "names": ["MK2_heat_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current heating circuit 2 temperature",
    },
    {
        "index": 151,
        "count": 1,
        "names": ["MK2_heat_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Target heating circuit 2 temperature",
    },
    {
        "index": 152,
        "count": 1,
        "names": ["MK2_heat_min"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum heating circuit 2 temperature",
    },
    {
        "index": 153,
        "count": 1,
        "names": ["MK2_heat_max"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum heating circuit 2 temperature",
    },
    {
        "index": 160,
        "count": 1,
        "names": ["MK3_heat_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current heating circuit 3 temperature",
    },
    {
        "index": 161,
        "count": 1,
        "names": ["MK3_heat_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Target heating circuit 3 temperature",
    },
    {
        "index": 162,
        "count": 1,
        "names": ["MK3_heat_min"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum heating circuit 3 temperature",
    },
    {
        "index": 163,
        "count": 1,
        "names": ["MK3_heat_max"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum heating circuit 3 temperature",
    },
    {
        "index": 201,
        "count": 1,
        "names": ["Unknown_Input_201"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 202,
        "count": 1,
        "names": ["Unknown_Input_202"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 203,
        "count": 1,
        "names": ["Unknown_Input_203"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 204,
        "count": 1,
        "names": ["Unknown_Input_204"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 205,
        "count": 1,
        "names": ["Unknown_Input_205"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 206,
        "count": 1,
        "names": ["Unknown_Input_206"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 207,
        "count": 1,
        "names": ["Unknown_Input_207"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 300,
        "count": 1,
        "names": ["Unknown_Input_300"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 301,
        "count": 1,
        "names": ["Unknown_Input_301"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 302,
        "count": 1,
        "names": ["Unknown_Input_302"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 310,
        "count": 1,
        "names": ["Unknown_Input_310"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 311,
        "count": 1,
        "names": ["Total_power_consumption"],
        "type": Energy,
        "writeable": False,
        "since": "3.90.1",
        "description": "Total electrical energy consumption",
    },
    {
        "index": 312,
        "count": 1,
        "names": ["Unknown_Input_312"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 313,
        "count": 1,
        "names": ["Heat_power_consumption"],
        "type": Energy,
        "writeable": False,
        "since": "3.90.1",
        "description": "Electrical energy consumption for heating",
    },
    {
        "index": 314,
        "count": 1,
        "names": ["Unknown_Input_314"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 315,
        "count": 1,
        "names": ["Hot_water_power_consumption"],
        "type": Energy,
        "writeable": False,
        "since": "3.90.1",
        "description": "Electrical energy consumption for hot water",
    },
    {
        "index": 316,
        "count": 1,
        "names": ["Unknown_Input_316"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 317,
        "count": 1,
        "names": ["Unknown_Input_317"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 318,
        "count": 1,
        "names": ["Unknown_Input_318"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 319,
        "count": 1,
        "names": ["Unknown_Input_319"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 320,
        "count": 1,
        "names": ["Unknown_Input_320"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 321,
        "count": 1,
        "names": ["Unknown_Input_321"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 322,
        "count": 1,
        "names": ["Unknown_Input_322"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 323,
        "count": 1,
        "names": ["Unknown_Input_323"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 324,
        "count": 1,
        "names": ["Unknown_Input_324"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 325,
        "count": 1,
        "names": ["Unknown_Input_325"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 326,
        "count": 1,
        "names": ["Unknown_Input_326"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 327,
        "count": 1,
        "names": ["Unknown_Input_327"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 328,
        "count": 1,
        "names": ["Unknown_Input_328"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 329,
        "count": 1,
        "names": ["Unknown_Input_329"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 350,
        "count": 1,
        "names": ["Unknown_Input_350"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 351,
        "count": 1,
        "names": ["Unknown_Input_351"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 352,
        "count": 1,
        "names": ["Unknown_Input_352"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 353,
        "count": 1,
        "names": ["Unknown_Input_353"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 354,
        "count": 1,
        "names": ["Unknown_Input_354"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 355,
        "count": 1,
        "names": ["Unknown_Input_355"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 356,
        "count": 1,
        "names": ["Unknown_Input_356"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 360,
        "count": 1,
        "names": ["Unknown_Input_360"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 361,
        "count": 1,
        "names": ["Unknown_Input_361"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 400,
        "count": 3,
        "names": ["Version"],
        "type": FullVersion,
        "writeable": False,
        "since": "3.90.1",
        "description": "Full firmware version information",
    },
    {
        "index": 404,
        "count": 1,
        "names": ["Unknown_Input_404"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 405,
        "count": 1,
        "names": ["Unknown_Input_405"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 406,
        "count": 1,
        "names": ["Unknown_Input_406"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 407,
        "count": 1,
        "names": ["Unknown_Input_407"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 408,
        "count": 1,
        "names": ["Unknown_Input_408"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 409,
        "count": 1,
        "names": ["Unknown_Input_409"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 410,
        "count": 1,
        "names": ["Unknown_Input_410"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 411,
        "count": 1,
        "names": ["Unknown_Input_411"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 412,
        "count": 1,
        "names": ["Unknown_Input_412"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 413,
        "count": 1,
        "names": ["Unknown_Input_413"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 416,
        "count": 1,
        "names": ["Unknown_Input_416"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 417,
        "count": 1,
        "names": ["Unknown_Input_417"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 500,
        "count": 1,
        "names": ["Unknown_Input_500"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 501,
        "count": 1,
        "names": ["Unknown_Input_501"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 502,
        "count": 1,
        "names": ["Unknown_Input_502"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
]
