"""
Constant list containing all 'inputs' definitions
used by the Smart Home Interface (SHI) of the Luxtronik controller.

Unlike the setting registers, these SHI register are volatile and intended for
communication with smart home systems. 'Input' register are read-only
and are used for display or to control other devices.
"""
from typing import Final

from luxtronik.datatypes import (
    Celsius,
    Energy,
    FullVersion,
    HeatPumpState,
    ModeState,
    OperationMode,
    Unknown,
)

# Offset which must be added to the input indices
# to obtain the correct address of the data fields
INPUTS_OFFSET: Final = 10000

INPUTS_DEFINITIONS_LIST: Final = [
    {
        "index": 0,
        "count": 1,
        "names": ["heatpump_state"],
        "type": HeatPumpState,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current operating state of the heat pump",
    },
    {
        "index": 2,
        "count": 1,
        "names": ["operation_mode"],
        "type": OperationMode,
        "writeable": False,
        "since": "3.90.1",
        "description": "Overall operation mode of the system",
    },
    {
        "index": 3,
        "count": 1,
        "names": ["heating_state"],
        "type": ModeState,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current state of the heating function",
    },
    {
        "index": 4,
        "count": 1,
        "names": ["hot_water_state"],
        "type": ModeState,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current state of the hot water system",
    },
    {
        "index": 6,
        "count": 1,
        "names": ["unknown_input_6"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 7,
        "count": 1,
        "names": ["unknown_input_7"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 100,
        "count": 1,
        "names": ["return_line_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current return line temperature",
    },
    {
        "index": 101,
        "count": 1,
        "names": ["return_line_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Target return line temperature",
    },
    {
        "index": 102,
        "count": 1,
        "names": ["return_line_ext"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current value of the external return temperature sensor",
    },
    {
        "index": 103,
        "count": 1,
        "names": ["return_line_limit"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum allowed return line temperature",
    },
    {
        "index": 104,
        "count": 1,
        "names": ["return_line_min_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum target return line temperature",
    },
    {
        "index": 105,
        "count": 1,
        "names": ["flow_line_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current flow line temperature",
    },
    {
        "index": 106,
        "count": 1,
        "names": ["unknown_input_106"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 107,
        "count": 1,
        "names": ["inside_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Measured indoor temperature",
    },
    {
        "index": 108,
        "count": 1,
        "names": ["outside_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Measured outdoor temperature",
    },
    {
        "index": 109,
        "count": 1,
        "names": ["unknown_input_109"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 110,
        "count": 1,
        "names": ["unknown_input_110"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 111,
        "count": 1,
        "names": ["unknown_input_111"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 112,
        "count": 1,
        "names": ["unknown_input_112"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 113,
        "count": 1,
        "names": ["unknown_input_113"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 120,
        "count": 1,
        "names": ["hot_water_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current hot water temperature",
    },
    {
        "index": 121,
        "count": 1,
        "names": ["hot_water_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Target hot water temperature",
    },
    {
        "index": 122,
        "count": 1,
        "names": ["hot_water_min"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum hot water temperature",
    },
    {
        "index": 123,
        "count": 1,
        "names": ["hot_water_max"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum hot water temperature",
    },
    {
        "index": 124,
        "count": 1,
        "names": ["unknown_input_124"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – possibly hot water idle/running indicator",
    },
    {
        "index": 140,
        "count": 1,
        "names": ["mc1_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current temperature of mixing circuit 1",
    },
    {
        "index": 141,
        "count": 1,
        "names": ["mc1_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Desired target temperature of mixing circuit 1",
    },
    {
        "index": 142,
        "count": 1,
        "names": ["mc1_min"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum temperature of mixing circuit 1",
    },
    {
        "index": 143,
        "count": 1,
        "names": ["mc1_max"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum temperature of mixing circuit 1",
    },
    {
        "index": 150,
        "count": 1,
        "names": ["mc2_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current temperature of mixing circuit 2",
    },
    {
        "index": 151,
        "count": 1,
        "names": ["mc2_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Desired target temperature of mixing circuit 2",
    },
    {
        "index": 152,
        "count": 1,
        "names": ["mc2_min"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum temperature of mixing circuit 2",
    },
    {
        "index": 153,
        "count": 1,
        "names": ["mc2_max"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum temperature of mixing circuit 2",
    },
    {
        "index": 160,
        "count": 1,
        "names": ["mc3_temp"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Current temperature of mixing circuit 3",
    },
    {
        "index": 161,
        "count": 1,
        "names": ["mc3_target"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Desired target temperature of mixing circuit 3",
    },
    {
        "index": 162,
        "count": 1,
        "names": ["mc3_min"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Minimum temperature of mixing circuit 3",
    },
    {
        "index": 163,
        "count": 1,
        "names": ["mc3_heat_max"],
        "type": Celsius,
        "writeable": False,
        "since": "3.90.1",
        "description": "Maximum temperature of mixing circuit 3",
    },
    {
        "index": 201,
        "count": 1,
        "names": ["unknown_input_201"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 202,
        "count": 1,
        "names": ["unknown_input_202"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 203,
        "count": 1,
        "names": ["unknown_input_203"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 204,
        "count": 1,
        "names": ["unknown_input_204"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 205,
        "count": 1,
        "names": ["unknown_input_205"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 206,
        "count": 1,
        "names": ["unknown_input_206"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 207,
        "count": 1,
        "names": ["unknown_input_207"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 300,
        "count": 1,
        "names": ["unknown_input_300"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 301,
        "count": 1,
        "names": ["unknown_input_301"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 302,
        "count": 1,
        "names": ["unknown_input_302"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 310,
        "count": 1,
        "names": ["unknown_input_310"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 311,
        "count": 1,
        "names": ["total_power_consumption"],
        "type": Energy,
        "writeable": False,
        "since": "3.90.1",
        "description": "Total electrical energy consumption",
    },
    {
        "index": 312,
        "count": 1,
        "names": ["unknown_input_312"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 313,
        "count": 1,
        "names": ["heat_power_consumption"],
        "type": Energy,
        "writeable": False,
        "since": "3.90.1",
        "description": "Electrical energy consumption for heating",
    },
    {
        "index": 314,
        "count": 1,
        "names": ["unknown_input_314"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 315,
        "count": 1,
        "names": ["hot_water_power_consumption"],
        "type": Energy,
        "writeable": False,
        "since": "3.90.1",
        "description": "Electrical energy consumption for hot water",
    },
    {
        "index": 316,
        "count": 1,
        "names": ["unknown_input_316"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 317,
        "count": 1,
        "names": ["unknown_input_317"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 318,
        "count": 1,
        "names": ["unknown_input_318"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 319,
        "count": 1,
        "names": ["unknown_input_319"],
        "type": Unknown,
        "writeable": False,
        "since": "3.90.1",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 320,
        "count": 1,
        "names": ["unknown_input_320"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 321,
        "count": 1,
        "names": ["unknown_input_321"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 322,
        "count": 1,
        "names": ["unknown_input_322"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 323,
        "count": 1,
        "names": ["unknown_input_323"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 324,
        "count": 1,
        "names": ["unknown_input_324"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 325,
        "count": 1,
        "names": ["unknown_input_325"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 326,
        "count": 1,
        "names": ["unknown_input_326"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 327,
        "count": 1,
        "names": ["unknown_input_327"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 328,
        "count": 1,
        "names": ["unknown_input_328"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 329,
        "count": 1,
        "names": ["unknown_input_329"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 350,
        "count": 1,
        "names": ["unknown_input_350"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 351,
        "count": 1,
        "names": ["unknown_input_351"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 352,
        "count": 1,
        "names": ["unknown_input_352"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 353,
        "count": 1,
        "names": ["unknown_input_353"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 354,
        "count": 1,
        "names": ["unknown_input_354"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 355,
        "count": 1,
        "names": ["unknown_input_355"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 356,
        "count": 1,
        "names": ["unknown_input_356"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 360,
        "count": 1,
        "names": ["unknown_input_360"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 361,
        "count": 1,
        "names": ["unknown_input_361"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 400,
        "count": 3,
        "names": ["version"],
        "type": FullVersion,
        "writeable": False,
        "since": "3.90.1",
        "description": "Full firmware version information",
    },
    {
        "index": 404,
        "count": 1,
        "names": ["unknown_input_404"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 405,
        "count": 1,
        "names": ["unknown_input_405"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 406,
        "count": 1,
        "names": ["unknown_input_406"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 407,
        "count": 1,
        "names": ["unknown_input_407"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 408,
        "count": 1,
        "names": ["unknown_input_408"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 409,
        "count": 1,
        "names": ["unknown_input_409"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 410,
        "count": 1,
        "names": ["unknown_input_410"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 411,
        "count": 1,
        "names": ["unknown_input_411"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 412,
        "count": 1,
        "names": ["unknown_input_412"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 413,
        "count": 1,
        "names": ["unknown_input_413"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 416,
        "count": 1,
        "names": ["unknown_input_416"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 417,
        "count": 1,
        "names": ["unknown_input_417"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 500,
        "count": 1,
        "names": ["unknown_input_500"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 501,
        "count": 1,
        "names": ["unknown_input_501"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
    {
        "index": 502,
        "count": 1,
        "names": ["unknown_input_502"],
        "type": Unknown,
        "writeable": False,
        "since": "3.92.0",
        "description": "TODO: Function unknown – requires further analysis",
    },
]
