"""
Constant list containing all 'visibility' definitions
used by the config interface (CFI) of the Luxtronik controller.

The visibilities holds values for display purposes and are read-only.

NOTES:
- If there are multiple definitions for an index, the newest and
preferred one should be inserted as the last one in the same index.
"""

from typing import Final

from luxtronik.datatypes import (
    Unknown,
)

# Offset which must be added to the visibility indices
# to obtain the correct address of the data fields
VISIBILITIES_OFFSET: Final = 0
VISIBILITIES_DEFAULT_DATA_TYPE: Final = 'INT32'

VISIBILITIES_DEFINITIONS_LIST: Final = [
    {
        "index": 0,
        "count": 1,
        "names": ['ID_Visi_NieAnzeigen'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 1,
        "count": 1,
        "names": ['ID_Visi_ImmerAnzeigen'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 2,
        "count": 1,
        "names": ['ID_Visi_Heizung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 3,
        "count": 1,
        "names": ['ID_Visi_Brauwasser'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 4,
        "count": 1,
        "names": ['ID_Visi_Schwimmbad'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 5,
        "count": 1,
        "names": ['ID_Visi_Kuhlung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 6,
        "count": 1,
        "names": ['ID_Visi_Lueftung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 7,
        "count": 1,
        "names": ['ID_Visi_MK1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 8,
        "count": 1,
        "names": ['ID_Visi_MK2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 9,
        "count": 1,
        "names": ['ID_Visi_ThermDesinfekt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 10,
        "count": 1,
        "names": ['ID_Visi_Zirkulation'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 11,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_SolltempMK1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 12,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_SolltempMK2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 13,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_ATDiffMK1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 14,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_ATDiffMK2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 15,
        "count": 1,
        "names": ['ID_Visi_Service_Information'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 16,
        "count": 1,
        "names": ['ID_Visi_Service_Einstellung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 17,
        "count": 1,
        "names": ['ID_Visi_Service_Sprache'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 18,
        "count": 1,
        "names": ['ID_Visi_Service_DatumUhrzeit'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 19,
        "count": 1,
        "names": ['ID_Visi_Service_Ausheiz'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 20,
        "count": 1,
        "names": ['ID_Visi_Service_Anlagenkonfiguration'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 21,
        "count": 1,
        "names": ['ID_Visi_Service_IBNAssistant'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 22,
        "count": 1,
        "names": ['ID_Visi_Service_ParameterIBNZuruck'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 23,
        "count": 1,
        "names": ['ID_Visi_Temp_Vorlauf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 24,
        "count": 1,
        "names": ['ID_Visi_Temp_Rucklauf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 25,
        "count": 1,
        "names": ['ID_Visi_Temp_RL_Soll'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 26,
        "count": 1,
        "names": ['ID_Visi_Temp_Ruecklext'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 27,
        "count": 1,
        "names": ['ID_Visi_Temp_Heissgas'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 28,
        "count": 1,
        "names": ['ID_Visi_Temp_Aussent'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 29,
        "count": 1,
        "names": ['ID_Visi_Temp_BW_Ist'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 30,
        "count": 1,
        "names": ['ID_Visi_Temp_BW_Soll'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 31,
        "count": 1,
        "names": ['ID_Visi_Temp_WQ_Ein'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 32,
        "count": 1,
        "names": ['ID_Visi_Temp_Kaltekreis'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 33,
        "count": 1,
        "names": ['ID_Visi_Temp_MK1_Vorlauf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 34,
        "count": 1,
        "names": ['ID_Visi_Temp_MK1VL_Soll'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 35,
        "count": 1,
        "names": ['ID_Visi_Temp_Raumstation'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 36,
        "count": 1,
        "names": ['ID_Visi_Temp_MK2_Vorlauf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 37,
        "count": 1,
        "names": ['ID_Visi_Temp_MK2VL_Soll'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 38,
        "count": 1,
        "names": ['ID_Visi_Temp_Solarkoll'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 39,
        "count": 1,
        "names": ['ID_Visi_Temp_Solarsp'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 40,
        "count": 1,
        "names": ['ID_Visi_Temp_Ext_Energ'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 41,
        "count": 1,
        "names": ['ID_Visi_IN_ASD'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 42,
        "count": 1,
        "names": ['ID_Visi_IN_BWT'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 43,
        "count": 1,
        "names": ['ID_Visi_IN_EVU'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 44,
        "count": 1,
        "names": ['ID_Visi_IN_HD'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 45,
        "count": 1,
        "names": ['ID_Visi_IN_MOT'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 46,
        "count": 1,
        "names": ['ID_Visi_IN_ND'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 47,
        "count": 1,
        "names": ['ID_Visi_IN_PEX'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 48,
        "count": 1,
        "names": ['ID_Visi_IN_SWT'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 49,
        "count": 1,
        "names": ['ID_Visi_OUT_Abtauventil'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 50,
        "count": 1,
        "names": ['ID_Visi_OUT_BUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 51,
        "count": 1,
        "names": ['ID_Visi_OUT_FUP1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 52,
        "count": 1,
        "names": ['ID_Visi_OUT_HUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 53,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer1Auf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 54,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer1Zu'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 55,
        "count": 1,
        "names": ['ID_Visi_OUT_Ventilation'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 56,
        "count": 1,
        "names": ['ID_Visi_OUT_Ventil_BOSUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 57,
        "count": 1,
        "names": ['ID_Visi_OUT_Verdichter1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 58,
        "count": 1,
        "names": ['ID_Visi_OUT_Verdichter2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 59,
        "count": 1,
        "names": ['ID_Visi_OUT_ZIP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 60,
        "count": 1,
        "names": ['ID_Visi_OUT_ZUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 61,
        "count": 1,
        "names": ['ID_Visi_OUT_ZWE1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 62,
        "count": 1,
        "names": ['ID_Visi_OUT_ZWE2_SST'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 63,
        "count": 1,
        "names": ['ID_Visi_OUT_ZWE3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 64,
        "count": 1,
        "names": ['ID_Visi_OUT_FUP2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 65,
        "count": 1,
        "names": ['ID_Visi_OUT_SLP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 66,
        "count": 1,
        "names": ['ID_Visi_OUT_SUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 67,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer2Auf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 68,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer2Zu'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 69,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_WP_Seit'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 70,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_ZWE1_seit'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 71,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_ZWE2_seit'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 72,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_ZWE3_seit'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 73,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_Netzeinv'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 74,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_SSP_Zeit1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 75,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_VD_Stand'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 76,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_HRM_Zeit'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 77,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_HRW_Zeit'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 78,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_TDI_seit'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 79,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_Sperre_BW'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 80,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdVD1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 81,
        "count": 1,
        "names": ['ID_Visi_Bst_ImpVD1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 82,
        "count": 1,
        "names": ['ID_Visi_Bst_dEZVD1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 83,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdVD2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 84,
        "count": 1,
        "names": ['ID_Visi_Bst_ImpVD2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 85,
        "count": 1,
        "names": ['ID_Visi_Bst_dEZVD2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 86,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdZWE1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 87,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdZWE2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 88,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdZWE3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 89,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdWP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 90,
        "count": 1,
        "names": ['ID_Visi_Text_Kurzprogramme'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 91,
        "count": 1,
        "names": ['ID_Visi_Text_Zwangsheizung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 92,
        "count": 1,
        "names": ['ID_Visi_Text_Zwangsbrauchwasser'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 93,
        "count": 1,
        "names": ['ID_Visi_Text_Abtauen'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 94,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_RucklBegr'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 95,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_HystereseHR'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 96,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TRErhmax'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 97,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Freig2VD'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 98,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_FreigZWE'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 99,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Tluftabt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 100,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDISolltemp'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 101,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_HystereseBW'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 102,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Vorl2VDBW'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 103,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TAussenmax'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 104,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TAussenmin'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 105,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TWQmin'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 106,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_THGmax'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 107,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TLABTEnde'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 108,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Absenkbis'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 109,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Vorlaufmax'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 110,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDiffEin'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 111,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDiffAus'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 112,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDiffmax'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 113,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TEEHeizung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 114,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TEEBrauchw'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 115,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Vorl2VDSW'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 116,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_VLMaxMk1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 117,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_VLMaxMk2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 118,
        "count": 1,
        "names": ['ID_Visi_Priori_Brauchwasser'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 119,
        "count": 1,
        "names": ['ID_Visi_Priori_Heizung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 120,
        "count": 1,
        "names": ['ID_Visi_Priori_Schwimmbad'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 121,
        "count": 1,
        "names": ['ID_Visi_SysEin_EVUSperre'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 122,
        "count": 1,
        "names": ['ID_Visi_SysEin_Raumstation'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 123,
        "count": 1,
        "names": ['ID_Visi_SysEin_Einbindung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 124,
        "count": 1,
        "names": ['ID_Visi_SysEin_Mischkreis1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 125,
        "count": 1,
        "names": ['ID_Visi_SysEin_Mischkreis2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 126,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE1Art'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 127,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE1Fkt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 128,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE2Art'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 129,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE2Fkt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 130,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE3Art'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 131,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE3Fkt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 132,
        "count": 1,
        "names": ['ID_Visi_SysEin_Stoerung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 133,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 134,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 135,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 136,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser4'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 137,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser5'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 138,
        "count": 1,
        "names": ['ID_Visi_SysEin_BWWPmax'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 139,
        "count": 1,
        "names": ['ID_Visi_SysEin_Abtzykmax'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 140,
        "count": 1,
        "names": ['ID_Visi_SysEin_Luftabt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 141,
        "count": 1,
        "names": ['ID_Visi_SysEin_LuftAbtmax'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 142,
        "count": 1,
        "names": ['ID_Visi_SysEin_Abtauen1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 143,
        "count": 1,
        "names": ['ID_Visi_SysEin_Abtauen2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 144,
        "count": 1,
        "names": ['ID_Visi_SysEin_Pumpenoptim'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 145,
        "count": 1,
        "names": ['ID_Visi_SysEin_Zusatzpumpe'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 146,
        "count": 1,
        "names": ['ID_Visi_SysEin_Zugang'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 147,
        "count": 1,
        "names": ['ID_Visi_SysEin_SoledrDurchf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 148,
        "count": 1,
        "names": ['ID_Visi_SysEin_UberwachungVD'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 149,
        "count": 1,
        "names": ['ID_Visi_SysEin_RegelungHK'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 150,
        "count": 1,
        "names": ['ID_Visi_SysEin_RegelungMK1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 151,
        "count": 1,
        "names": ['ID_Visi_SysEin_RegelungMK2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 152,
        "count": 1,
        "names": ['ID_Visi_SysEin_Kuhlung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 153,
        "count": 1,
        "names": ['ID_Visi_SysEin_Ausheizen'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 154,
        "count": 1,
        "names": ['ID_Visi_SysEin_ElektrAnode'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 155,
        "count": 1,
        "names": ['ID_Visi_SysEin_SWBBer'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 156,
        "count": 1,
        "names": ['ID_Visi_SysEin_SWBMin'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 157,
        "count": 1,
        "names": ['ID_Visi_SysEin_Heizung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 158,
        "count": 1,
        "names": ['ID_Visi_SysEin_PeriodeMk1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 159,
        "count": 1,
        "names": ['ID_Visi_SysEin_LaufzeitMk1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 160,
        "count": 1,
        "names": ['ID_Visi_SysEin_PeriodeMk2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 161,
        "count": 1,
        "names": ['ID_Visi_SysEin_LaufzeitMk2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 162,
        "count": 1,
        "names": ['ID_Visi_SysEin_Heizgrenze'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 163,
        "count": 1,
        "names": ['ID_Visi_Enlt_HUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 164,
        "count": 1,
        "names": ['ID_Visi_Enlt_ZUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 165,
        "count": 1,
        "names": ['ID_Visi_Enlt_BUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 166,
        "count": 1,
        "names": ['ID_Visi_Enlt_Ventilator_BOSUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 167,
        "count": 1,
        "names": ['ID_Visi_Enlt_MA1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 168,
        "count": 1,
        "names": ['ID_Visi_Enlt_MZ1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 169,
        "count": 1,
        "names": ['ID_Visi_Enlt_ZIP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 170,
        "count": 1,
        "names": ['ID_Visi_Enlt_MA2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 171,
        "count": 1,
        "names": ['ID_Visi_Enlt_MZ2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 172,
        "count": 1,
        "names": ['ID_Visi_Enlt_SUP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 173,
        "count": 1,
        "names": ['ID_Visi_Enlt_SLP'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 174,
        "count": 1,
        "names": ['ID_Visi_Enlt_FP2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 175,
        "count": 1,
        "names": ['ID_Visi_Enlt_Laufzeit'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 176,
        "count": 1,
        "names": ['ID_Visi_Anlgkonf_Heizung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 177,
        "count": 1,
        "names": ['ID_Visi_Anlgkonf_Brauchwarmwasser'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 178,
        "count": 1,
        "names": ['ID_Visi_Anlgkonf_Schwimmbad'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 179,
        "count": 1,
        "names": ['ID_Visi_Heizung_Betriebsart'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 180,
        "count": 1,
        "names": ['ID_Visi_Heizung_TemperaturPlusMinus'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 181,
        "count": 1,
        "names": ['ID_Visi_Heizung_Heizkurven'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 182,
        "count": 1,
        "names": ['ID_Visi_Heizung_Zeitschaltprogramm', 'ID_Visi_Heizung_Zeitschlaltprogramm'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 183,
        "count": 1,
        "names": ['ID_Visi_Heizung_Heizgrenze'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 184,
        "count": 1,
        "names": ['ID_Visi_Mitteltemperatur'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 185,
        "count": 1,
        "names": ['ID_Visi_Dataenlogger'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 186,
        "count": 1,
        "names": ['ID_Visi_Sprachen_DEUTSCH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 187,
        "count": 1,
        "names": ['ID_Visi_Sprachen_ENGLISH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 188,
        "count": 1,
        "names": ['ID_Visi_Sprachen_FRANCAIS'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 189,
        "count": 1,
        "names": ['ID_Visi_Sprachen_NORWAY'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 190,
        "count": 1,
        "names": ['ID_Visi_Sprachen_TCHECH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 191,
        "count": 1,
        "names": ['ID_Visi_Sprachen_ITALIANO'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 192,
        "count": 1,
        "names": ['ID_Visi_Sprachen_NEDERLANDS'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 193,
        "count": 1,
        "names": ['ID_Visi_Sprachen_SVENSKA'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 194,
        "count": 1,
        "names": ['ID_Visi_Sprachen_POLSKI'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 195,
        "count": 1,
        "names": ['ID_Visi_Sprachen_MAGYARUL'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 196,
        "count": 1,
        "names": ['ID_Visi_ErrorUSBspeichern'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 197,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdHz'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 198,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdBW'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 199,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdKue'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 200,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 201,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung_Contrast'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 202,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung_Webserver'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 203,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung_IPAdresse'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 204,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung_Fernwartung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 205,
        "count": 1,
        "names": ['ID_Visi_Paralleleschaltung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 206,
        "count": 1,
        "names": ['ID_Visi_SysEin_Paralleleschaltung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 207,
        "count": 1,
        "names": ['ID_Visi_Sprachen_DANSK'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 208,
        "count": 1,
        "names": ['ID_Visi_Sprachen_PORTUGES'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 209,
        "count": 1,
        "names": ['ID_Visi_Heizkurve_Heizung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 210,
        "count": 1,
        "names": ['ID_Visi_SysEin_Mischkreis3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 211,
        "count": 1,
        "names": ['ID_Visi_MK3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 212,
        "count": 1,
        "names": ['ID_Visi_Temp_MK3_Vorlauf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 213,
        "count": 1,
        "names": ['ID_Visi_Temp_MK3VL_Soll'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 214,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer3Auf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 215,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer3Zu'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 216,
        "count": 1,
        "names": ['ID_Visi_SysEin_RegelungMK3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 217,
        "count": 1,
        "names": ['ID_Visi_SysEin_PeriodeMk3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 218,
        "count": 1,
        "names": ['ID_Visi_SysEin_LaufzeitMk3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 219,
        "count": 1,
        "names": ['ID_Visi_SysEin_Kuhl_Zeit_Ein'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 220,
        "count": 1,
        "names": ['ID_Visi_SysEin_Kuhl_Zeit_Aus'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 221,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_AbtauIn'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 222,
        "count": 1,
        "names": ['ID_Visi_Waermemenge_WS'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 223,
        "count": 1,
        "names": ['ID_Visi_Waermemenge_WQ'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 224,
        "count": 1,
        "names": ['ID_Visi_Enlt_MA3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 225,
        "count": 1,
        "names": ['ID_Visi_Enlt_MZ3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 226,
        "count": 1,
        "names": ['ID_Visi_Enlt_FP3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 227,
        "count": 1,
        "names": ['ID_Visi_OUT_FUP3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 228,
        "count": 1,
        "names": ['ID_Visi_Temp_Raumstation2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 229,
        "count": 1,
        "names": ['ID_Visi_Temp_Raumstation3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 230,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdSW'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 231,
        "count": 1,
        "names": ['ID_Visi_Sprachen_LITAUISCH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 232,
        "count": 1,
        "names": ['ID_Visi_Sprachen_ESTNICH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 233,
        "count": 1,
        "names": ['ID_Visi_SysEin_Fernwartung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 234,
        "count": 1,
        "names": ['ID_Visi_Sprachen_SLOVENISCH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 235,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TA_EG'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 236,
        "count": 1,
        "names": ['ID_Visi_Einst_TVLmax_EG'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 237,
        "count": 1,
        "names": ['ID_Visi_SysEin_PoptNachlauf'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 238,
        "count": 1,
        "names": ['ID_Visi_RFV_K_Kuehlin'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 239,
        "count": 1,
        "names": ['ID_Visi_SysEin_EffizienzpumpeNom'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 240,
        "count": 1,
        "names": ['ID_Visi_SysEin_EffizienzpumpeMin'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 241,
        "count": 1,
        "names": ['ID_Visi_SysEin_Effizienzpumpe'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 242,
        "count": 1,
        "names": ['ID_Visi_SysEin_Waermemenge'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 243,
        "count": 1,
        "names": ['ID_Visi_Service_WMZ_Effizienz'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 244,
        "count": 1,
        "names": ['ID_Visi_SysEin_Wm_Versorgung_Korrektur'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 245,
        "count": 1,
        "names": ['ID_Visi_SysEin_Wm_Auswertung_Korrektur'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 246,
        "count": 1,
        "names": ['ID_Visi_IN_AnalogIn'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 247,
        "count": 1,
        "names": ['ID_Visi_Eins_SN_Eingabe'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 248,
        "count": 1,
        "names": ['ID_Visi_OUT_Analog_1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 249,
        "count": 1,
        "names": ['ID_Visi_OUT_Analog_2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 250,
        "count": 1,
        "names": ['ID_Visi_Solar'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 251,
        "count": 1,
        "names": ['ID_Visi_SysEin_Solar'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 252,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDiffKollmax'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 253,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_HG_Sperre'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 254,
        "count": 1,
        "names": ['ID_Visi_SysEin_Akt_Kuehlung'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 255,
        "count": 1,
        "names": ['ID_Visi_SysEin_Vorlauf_VBO'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 256,
        "count": 1,
        "names": ['ID_Visi_Einst_KRHyst'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 257,
        "count": 1,
        "names": ['ID_Visi_Einst_Akt_Kuehl_Speicher_min'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 258,
        "count": 1,
        "names": ['ID_Visi_Einst_Akt_Kuehl_Freig_WQE'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 259,
        "count": 1,
        "names": ['ID_Visi_SysEin_AbtZykMin'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 260,
        "count": 1,
        "names": ['ID_Visi_SysEin_VD2_Zeit_Min'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 261,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Hysterese_HR_verkuerzt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 262,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Feuchteschutz_akt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 263,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Reduziert_akt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 264,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Nennlueftung_akt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 265,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Intensivlueftung_akt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 266,
        "count": 1,
        "names": ['ID_Visi_Temperatur_Lueftung_Zuluft'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 267,
        "count": 1,
        "names": ['ID_Visi_Temperatur_Lueftung_Abluft'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 268,
        "count": 1,
        "names": ['ID_Visi_OUT_Analog_3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 269,
        "count": 1,
        "names": ['ID_Visi_OUT_Analog_4'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 270,
        "count": 1,
        "names": ['ID_Visi_IN_Analog_2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 271,
        "count": 1,
        "names": ['ID_Visi_IN_Analog_3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 272,
        "count": 1,
        "names": ['ID_Visi_IN_SAX'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 273,
        "count": 1,
        "names": ['ID_Visi_OUT_VZU'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 274,
        "count": 1,
        "names": ['ID_Visi_OUT_VAB'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 275,
        "count": 1,
        "names": ['ID_Visi_OUT_VSK'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 276,
        "count": 1,
        "names": ['ID_Visi_OUT_FRH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 277,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_SolltempMK3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 278,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_ATDiffMK3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 279,
        "count": 1,
        "names": ['ID_Visi_IN_SPL'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 280,
        "count": 1,
        "names": ['ID_Visi_SysEin_Lueftungsstufen'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 281,
        "count": 1,
        "names": ['ID_Visi_SysEin_Meldung_TDI'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 282,
        "count": 1,
        "names": ['ID_Visi_SysEin_Typ_WZW'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 283,
        "count": 1,
        "names": ['ID_Visi_BACnet'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 284,
        "count": 1,
        "names": ['ID_Visi_Sprachen_SLOWAKISCH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 285,
        "count": 1,
        "names": ['ID_Visi_Sprachen_LETTISCH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 286,
        "count": 1,
        "names": ['ID_Visi_Sprachen_FINNISCH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 287,
        "count": 1,
        "names": ['ID_Visi_Kalibrierung_LWD'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 288,
        "count": 1,
        "names": ['ID_Visi_IN_Durchfluss'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 289,
        "count": 1,
        "names": ['ID_Visi_LIN_ANSAUG_VERDICHTER'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 290,
        "count": 1,
        "names": ['ID_Visi_LIN_VDH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 291,
        "count": 1,
        "names": ['ID_Visi_LIN_UH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 292,
        "count": 1,
        "names": ['ID_Visi_LIN_Druck'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 293,
        "count": 1,
        "names": ['ID_Visi_Einst_Sollwert_TRL_Kuehlen'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 294,
        "count": 1,
        "names": ['ID_Visi_Entl_ExVentil'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 295,
        "count": 1,
        "names": ['ID_Visi_Einst_Medium_Waermequelle'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 296,
        "count": 1,
        "names": ['ID_Visi_Einst_Multispeicher'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 297,
        "count": 1,
        "names": ['ID_Visi_Einst_Minimale_Ruecklaufsolltemperatur'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 298,
        "count": 1,
        "names": ['ID_Visi_Einst_PKuehlTime'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 299,
        "count": 1,
        "names": ['ID_Visi_Sprachen_TUERKISCH'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 300,
        "count": 1,
        "names": ['ID_Visi_RBE'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 301,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Stufen_Faktor'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 302,
        "count": 1,
        "names": ['ID_Visi_Freigabe_Zeit_ZWE'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 303,
        "count": 1,
        "names": ['ID_Visi_Einst_min_VL_Kuehl'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 304,
        "count": 1,
        "names": ['ID_Visi_ZWE1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 305,
        "count": 1,
        "names": ['ID_Visi_ZWE2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 306,
        "count": 1,
        "names": ['ID_Visi_ZWE3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 307,
        "count": 1,
        "names": ['ID_Visi_SEC'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 308,
        "count": 1,
        "names": ['ID_Visi_HZIO'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 309,
        "count": 1,
        "names": ['ID_Visi_WPIO'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 310,
        "count": 1,
        "names": ['ID_Visi_LIN_ANSAUG_VERDAMPFER'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 311,
        "count": 1,
        "names": ['ID_Visi_LIN_MULTI1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 312,
        "count": 1,
        "names": ['ID_Visi_LIN_MULTI2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 313,
        "count": 1,
        "names": ['ID_Visi_Einst_Leistung_ZWE'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 314,
        "count": 1,
        "names": ['ID_Visi_Sprachen_ESPANOL'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 315,
        "count": 1,
        "names": ['ID_Visi_Temp_BW_oben'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 316,
        "count": 1,
        "names": ['ID_Visi_MAXIO'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 317,
        "count": 1,
        "names": ['ID_Visi_OUT_Abtauwunsch'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 318,
        "count": 1,
        "names": ['ID_Visi_SmartGrid'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 319,
        "count": 1,
        "names": ['ID_Visi_Drehzahlgeregelt'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 320,
        "count": 1,
        "names": ['ID_Visi_P155_Inverter'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 321,
        "count": 1,
        "names": ['ID_Visi_Leistungsfreigabe'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 322,
        "count": 1,
        "names": ['ID_Visi_Einst_Vorl_akt_Kuehl'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 323,
        "count": 1,
        "names": ['ID_Visi_Einst_Abtauen_im_Warmwasser'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 324,
        "count": 1,
        "names": ['ID_Visi_Waermemenge_ZWE'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 325,
        "count": 1,
        "names": ['Unknown_Visibility_325'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 326,
        "count": 1,
        "names": ['Unknown_Visibility_326'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 327,
        "count": 1,
        "names": ['Unknown_Visibility_327'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 328,
        "count": 1,
        "names": ['Unknown_Visibility_328'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 329,
        "count": 1,
        "names": ['Unknown_Visibility_329'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 330,
        "count": 1,
        "names": ['Unknown_Visibility_330'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 331,
        "count": 1,
        "names": ['Unknown_Visibility_331'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 332,
        "count": 1,
        "names": ['Unknown_Visibility_332'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 333,
        "count": 1,
        "names": ['Unknown_Visibility_333'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 334,
        "count": 1,
        "names": ['Unknown_Visibility_334'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 335,
        "count": 1,
        "names": ['Unknown_Visibility_335'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 336,
        "count": 1,
        "names": ['Unknown_Visibility_336'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 337,
        "count": 1,
        "names": ['Unknown_Visibility_337'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 338,
        "count": 1,
        "names": ['Unknown_Visibility_338'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 339,
        "count": 1,
        "names": ['Unknown_Visibility_339'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 340,
        "count": 1,
        "names": ['Unknown_Visibility_340'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 341,
        "count": 1,
        "names": ['Unknown_Visibility_341'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 342,
        "count": 1,
        "names": ['Unknown_Visibility_342'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 343,
        "count": 1,
        "names": ['Unknown_Visibility_343'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 344,
        "count": 1,
        "names": ['Unknown_Visibility_344'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 345,
        "count": 1,
        "names": ['Unknown_Visibility_345'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 346,
        "count": 1,
        "names": ['Unknown_Visibility_346'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 347,
        "count": 1,
        "names": ['Unknown_Visibility_347'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 348,
        "count": 1,
        "names": ['Unknown_Visibility_348'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 349,
        "count": 1,
        "names": ['Unknown_Visibility_349'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 350,
        "count": 1,
        "names": ['Unknown_Visibility_350'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 351,
        "count": 1,
        "names": ['Unknown_Visibility_351'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 352,
        "count": 1,
        "names": ['Unknown_Visibility_352'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 353,
        "count": 1,
        "names": ['Unknown_Visibility_353'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 354,
        "count": 1,
        "names": ['Unknown_Visibility_354'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 355,
        "count": 1,
        "names": ['Unknown_Visibility_355', 'Unknown_Parameter_355'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 356,
        "count": 1,
        "names": ['Unknown_Visibility_356', 'Unknown_Parameter_356'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 357,
        "count": 1,
        "names": ['ELECTRICAL_POWER_LIMITATION_SWITCH', 'Unknown_Visibility_357', 'Unknown_Parameter_357'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 358,
        "count": 1,
        "names": ['Unknown_Visibility_358', 'Unknown_Parameter_358'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 359,
        "count": 1,
        "names": ['Unknown_Visibility_359', 'Unknown_Parameter_359'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 360,
        "count": 1,
        "names": ['Unknown_Visibility_360', 'Unknown_Parameter_360'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 361,
        "count": 1,
        "names": ['Unknown_Visibility_361', 'Unknown_Parameter_361'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 362,
        "count": 1,
        "names": ['Unknown_Visibility_362', 'Unknown_Parameter_362'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 363,
        "count": 1,
        "names": ['Unknown_Visibility_363', 'Unknown_Parameter_363'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 364,
        "count": 1,
        "names": ['Unknown_Visibility_364', 'Unknown_Parameter_364'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 365,
        "count": 1,
        "names": ['Unknown_Visibility_365', 'Unknown_Parameter_365'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 366,
        "count": 1,
        "names": ['Unknown_Visibility_366', 'Unknown_Parameter_366'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 367,
        "count": 1,
        "names": ['Unknown_Visibility_367', 'Unknown_Parameter_367'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 368,
        "count": 1,
        "names": ['Unknown_Visibility_368', 'Unknown_Parameter_368'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 369,
        "count": 1,
        "names": ['Unknown_Visibility_369', 'Unknown_Parameter_369'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 370,
        "count": 1,
        "names": ['Unknown_Visibility_370', 'Unknown_Parameter_370'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 371,
        "count": 1,
        "names": ['Unknown_Visibility_371', 'Unknown_Parameter_371'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 372,
        "count": 1,
        "names": ['Unknown_Visibility_372', 'Unknown_Parameter_372'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 373,
        "count": 1,
        "names": ['Unknown_Visibility_373', 'Unknown_Parameter_373'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 374,
        "count": 1,
        "names": ['Unknown_Visibility_374', 'Unknown_Parameter_374'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 375,
        "count": 1,
        "names": ['Unknown_Visibility_375', 'Unknown_Parameter_375'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 376,
        "count": 1,
        "names": ['Unknown_Visibility_376', 'Unknown_Parameter_376'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 377,
        "count": 1,
        "names": ['Unknown_Visibility_377', 'Unknown_Parameter_377'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 378,
        "count": 1,
        "names": ['Unknown_Visibility_378', 'Unknown_Parameter_378'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 379,
        "count": 1,
        "names": ['Unknown_Visibility_379', 'Unknown_Parameter_379'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
]
