"""
Constant list containing all 'visibility' definitions
used by the config interface (CFI) of the Luxtronik controller.

The visibilities holds values for display purposes and are read-only.

NOTES:
- If there are multiple definitions for an index, the newest and
preferred one should be inserted as the last one in the same index.
"""

from typing import Final

from luxtronik.datatypes import (
    Unknown,
)

# Offset which must be added to the visibility indices
# to obtain the correct address of the data fields
VISIBILITIES_OFFSET: Final = 0
VISIBILITIES_DEFAULT_DATA_TYPE: Final = 'INT32'

VISIBILITIES_DEFINITIONS_LIST: Final = [
    {
        "index": 0,
        "count": 1,
        "names": ['ID_Visi_NieAnzeigen', 'Unknown_Visibility_0'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 1,
        "count": 1,
        "names": ['ID_Visi_ImmerAnzeigen', 'Unknown_Visibility_1'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 2,
        "count": 1,
        "names": ['ID_Visi_Heizung', 'Unknown_Visibility_2'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 3,
        "count": 1,
        "names": ['ID_Visi_Brauwasser', 'Unknown_Visibility_3'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 4,
        "count": 1,
        "names": ['ID_Visi_Schwimmbad', 'Unknown_Visibility_4'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 5,
        "count": 1,
        "names": ['ID_Visi_Kuhlung', 'Unknown_Visibility_5'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 6,
        "count": 1,
        "names": ['ID_Visi_Lueftung', 'Unknown_Visibility_6'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 7,
        "count": 1,
        "names": ['ID_Visi_MK1', 'Unknown_Visibility_7'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 8,
        "count": 1,
        "names": ['ID_Visi_MK2', 'Unknown_Visibility_8'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 9,
        "count": 1,
        "names": ['ID_Visi_ThermDesinfekt', 'Unknown_Visibility_9'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 10,
        "count": 1,
        "names": ['ID_Visi_Zirkulation', 'Unknown_Visibility_10'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 11,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_SolltempMK1', 'Unknown_Visibility_11'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 12,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_SolltempMK2', 'Unknown_Visibility_12'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 13,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_ATDiffMK1', 'Unknown_Visibility_13'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 14,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_ATDiffMK2', 'Unknown_Visibility_14'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 15,
        "count": 1,
        "names": ['ID_Visi_Service_Information', 'Unknown_Visibility_15'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 16,
        "count": 1,
        "names": ['ID_Visi_Service_Einstellung', 'Unknown_Visibility_16'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 17,
        "count": 1,
        "names": ['ID_Visi_Service_Sprache', 'Unknown_Visibility_17'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 18,
        "count": 1,
        "names": ['ID_Visi_Service_DatumUhrzeit', 'Unknown_Visibility_18'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 19,
        "count": 1,
        "names": ['ID_Visi_Service_Ausheiz', 'Unknown_Visibility_19'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 20,
        "count": 1,
        "names": ['ID_Visi_Service_Anlagenkonfiguration', 'Unknown_Visibility_20'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 21,
        "count": 1,
        "names": ['ID_Visi_Service_IBNAssistant', 'Unknown_Visibility_21'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 22,
        "count": 1,
        "names": ['ID_Visi_Service_ParameterIBNZuruck', 'Unknown_Visibility_22'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 23,
        "count": 1,
        "names": ['ID_Visi_Temp_Vorlauf', 'Unknown_Visibility_23'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 24,
        "count": 1,
        "names": ['ID_Visi_Temp_Rucklauf', 'Unknown_Visibility_24'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 25,
        "count": 1,
        "names": ['ID_Visi_Temp_RL_Soll', 'Unknown_Visibility_25'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 26,
        "count": 1,
        "names": ['ID_Visi_Temp_Ruecklext', 'Unknown_Visibility_26'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 27,
        "count": 1,
        "names": ['ID_Visi_Temp_Heissgas', 'Unknown_Visibility_27'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 28,
        "count": 1,
        "names": ['ID_Visi_Temp_Aussent', 'Unknown_Visibility_28'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 29,
        "count": 1,
        "names": ['ID_Visi_Temp_BW_Ist', 'Unknown_Visibility_29'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 30,
        "count": 1,
        "names": ['ID_Visi_Temp_BW_Soll', 'Unknown_Visibility_30'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 31,
        "count": 1,
        "names": ['ID_Visi_Temp_WQ_Ein', 'Unknown_Visibility_31'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 32,
        "count": 1,
        "names": ['ID_Visi_Temp_Kaltekreis', 'Unknown_Visibility_32'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 33,
        "count": 1,
        "names": ['ID_Visi_Temp_MK1_Vorlauf', 'Unknown_Visibility_33'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 34,
        "count": 1,
        "names": ['ID_Visi_Temp_MK1VL_Soll', 'Unknown_Visibility_34'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 35,
        "count": 1,
        "names": ['ID_Visi_Temp_Raumstation', 'Unknown_Visibility_35'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 36,
        "count": 1,
        "names": ['ID_Visi_Temp_MK2_Vorlauf', 'Unknown_Visibility_36'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 37,
        "count": 1,
        "names": ['ID_Visi_Temp_MK2VL_Soll', 'Unknown_Visibility_37'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 38,
        "count": 1,
        "names": ['ID_Visi_Temp_Solarkoll', 'Unknown_Visibility_38'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 39,
        "count": 1,
        "names": ['ID_Visi_Temp_Solarsp', 'Unknown_Visibility_39'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 40,
        "count": 1,
        "names": ['ID_Visi_Temp_Ext_Energ', 'Unknown_Visibility_40'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 41,
        "count": 1,
        "names": ['ID_Visi_IN_ASD', 'Unknown_Visibility_41'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 42,
        "count": 1,
        "names": ['ID_Visi_IN_BWT', 'Unknown_Visibility_42'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 43,
        "count": 1,
        "names": ['ID_Visi_IN_EVU', 'Unknown_Visibility_43'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 44,
        "count": 1,
        "names": ['ID_Visi_IN_HD', 'Unknown_Visibility_44'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 45,
        "count": 1,
        "names": ['ID_Visi_IN_MOT', 'Unknown_Visibility_45'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 46,
        "count": 1,
        "names": ['ID_Visi_IN_ND', 'Unknown_Visibility_46'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 47,
        "count": 1,
        "names": ['ID_Visi_IN_PEX', 'Unknown_Visibility_47'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 48,
        "count": 1,
        "names": ['ID_Visi_IN_SWT', 'Unknown_Visibility_48'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 49,
        "count": 1,
        "names": ['ID_Visi_OUT_Abtauventil', 'Unknown_Visibility_49'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 50,
        "count": 1,
        "names": ['ID_Visi_OUT_BUP', 'Unknown_Visibility_50'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 51,
        "count": 1,
        "names": ['ID_Visi_OUT_FUP1', 'Unknown_Visibility_51'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 52,
        "count": 1,
        "names": ['ID_Visi_OUT_HUP', 'Unknown_Visibility_52'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 53,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer1Auf', 'Unknown_Visibility_53'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 54,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer1Zu', 'Unknown_Visibility_54'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 55,
        "count": 1,
        "names": ['ID_Visi_OUT_Ventilation', 'Unknown_Visibility_55'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 56,
        "count": 1,
        "names": ['ID_Visi_OUT_Ventil_BOSUP', 'Unknown_Visibility_56'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 57,
        "count": 1,
        "names": ['ID_Visi_OUT_Verdichter1', 'Unknown_Visibility_57'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 58,
        "count": 1,
        "names": ['ID_Visi_OUT_Verdichter2', 'Unknown_Visibility_58'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 59,
        "count": 1,
        "names": ['ID_Visi_OUT_ZIP', 'Unknown_Visibility_59'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 60,
        "count": 1,
        "names": ['ID_Visi_OUT_ZUP', 'Unknown_Visibility_60'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 61,
        "count": 1,
        "names": ['ID_Visi_OUT_ZWE1', 'Unknown_Visibility_61'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 62,
        "count": 1,
        "names": ['ID_Visi_OUT_ZWE2_SST', 'Unknown_Visibility_62'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 63,
        "count": 1,
        "names": ['ID_Visi_OUT_ZWE3', 'Unknown_Visibility_63'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 64,
        "count": 1,
        "names": ['ID_Visi_OUT_FUP2', 'Unknown_Visibility_64'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 65,
        "count": 1,
        "names": ['ID_Visi_OUT_SLP', 'Unknown_Visibility_65'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 66,
        "count": 1,
        "names": ['ID_Visi_OUT_SUP', 'Unknown_Visibility_66'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 67,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer2Auf', 'Unknown_Visibility_67'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 68,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer2Zu', 'Unknown_Visibility_68'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 69,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_WP_Seit', 'Unknown_Visibility_69'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 70,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_ZWE1_seit', 'Unknown_Visibility_70'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 71,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_ZWE2_seit', 'Unknown_Visibility_71'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 72,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_ZWE3_seit', 'Unknown_Visibility_72'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 73,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_Netzeinv', 'Unknown_Visibility_73'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 74,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_SSP_Zeit1', 'Unknown_Visibility_74'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 75,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_VD_Stand', 'Unknown_Visibility_75'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 76,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_HRM_Zeit', 'Unknown_Visibility_76'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 77,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_HRW_Zeit', 'Unknown_Visibility_77'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 78,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_TDI_seit', 'Unknown_Visibility_78'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 79,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_Sperre_BW', 'Unknown_Visibility_79'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 80,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdVD1', 'Unknown_Visibility_80'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 81,
        "count": 1,
        "names": ['ID_Visi_Bst_ImpVD1', 'Unknown_Visibility_81'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 82,
        "count": 1,
        "names": ['ID_Visi_Bst_dEZVD1', 'Unknown_Visibility_82'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 83,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdVD2', 'Unknown_Visibility_83'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 84,
        "count": 1,
        "names": ['ID_Visi_Bst_ImpVD2', 'Unknown_Visibility_84'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 85,
        "count": 1,
        "names": ['ID_Visi_Bst_dEZVD2', 'Unknown_Visibility_85'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 86,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdZWE1', 'Unknown_Visibility_86'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 87,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdZWE2', 'Unknown_Visibility_87'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 88,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdZWE3', 'Unknown_Visibility_88'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 89,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdWP', 'Unknown_Visibility_89'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 90,
        "count": 1,
        "names": ['ID_Visi_Text_Kurzprogramme', 'Unknown_Visibility_90'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 91,
        "count": 1,
        "names": ['ID_Visi_Text_Zwangsheizung', 'Unknown_Visibility_91'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 92,
        "count": 1,
        "names": ['ID_Visi_Text_Zwangsbrauchwasser', 'Unknown_Visibility_92'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 93,
        "count": 1,
        "names": ['ID_Visi_Text_Abtauen', 'Unknown_Visibility_93'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 94,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_RucklBegr', 'Unknown_Visibility_94'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 95,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_HystereseHR', 'Unknown_Visibility_95'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 96,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TRErhmax', 'Unknown_Visibility_96'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 97,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Freig2VD', 'Unknown_Visibility_97'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 98,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_FreigZWE', 'Unknown_Visibility_98'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 99,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Tluftabt', 'Unknown_Visibility_99'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 100,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDISolltemp', 'Unknown_Visibility_100'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 101,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_HystereseBW', 'Unknown_Visibility_101'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 102,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Vorl2VDBW', 'Unknown_Visibility_102'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 103,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TAussenmax', 'Unknown_Visibility_103'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 104,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TAussenmin', 'Unknown_Visibility_104'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 105,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TWQmin', 'Unknown_Visibility_105'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 106,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_THGmax', 'Unknown_Visibility_106'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 107,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TLABTEnde', 'Unknown_Visibility_107'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 108,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Absenkbis', 'Unknown_Visibility_108'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 109,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Vorlaufmax', 'Unknown_Visibility_109'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 110,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDiffEin', 'Unknown_Visibility_110'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 111,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDiffAus', 'Unknown_Visibility_111'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 112,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDiffmax', 'Unknown_Visibility_112'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 113,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TEEHeizung', 'Unknown_Visibility_113'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 114,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TEEBrauchw', 'Unknown_Visibility_114'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 115,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Vorl2VDSW', 'Unknown_Visibility_115'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 116,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_VLMaxMk1', 'Unknown_Visibility_116'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 117,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_VLMaxMk2', 'Unknown_Visibility_117'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 118,
        "count": 1,
        "names": ['ID_Visi_Priori_Brauchwasser', 'Unknown_Visibility_118'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 119,
        "count": 1,
        "names": ['ID_Visi_Priori_Heizung', 'Unknown_Visibility_119'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 120,
        "count": 1,
        "names": ['ID_Visi_Priori_Schwimmbad', 'Unknown_Visibility_120'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 121,
        "count": 1,
        "names": ['ID_Visi_SysEin_EVUSperre', 'Unknown_Visibility_121'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 122,
        "count": 1,
        "names": ['ID_Visi_SysEin_Raumstation', 'Unknown_Visibility_122'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 123,
        "count": 1,
        "names": ['ID_Visi_SysEin_Einbindung', 'Unknown_Visibility_123'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 124,
        "count": 1,
        "names": ['ID_Visi_SysEin_Mischkreis1', 'Unknown_Visibility_124'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 125,
        "count": 1,
        "names": ['ID_Visi_SysEin_Mischkreis2', 'Unknown_Visibility_125'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 126,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE1Art', 'Unknown_Visibility_126'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 127,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE1Fkt', 'Unknown_Visibility_127'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 128,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE2Art', 'Unknown_Visibility_128'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 129,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE2Fkt', 'Unknown_Visibility_129'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 130,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE3Art', 'Unknown_Visibility_130'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 131,
        "count": 1,
        "names": ['ID_Visi_SysEin_ZWE3Fkt', 'Unknown_Visibility_131'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 132,
        "count": 1,
        "names": ['ID_Visi_SysEin_Stoerung', 'Unknown_Visibility_132'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 133,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser1', 'Unknown_Visibility_133'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 134,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser2', 'Unknown_Visibility_134'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 135,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser3', 'Unknown_Visibility_135'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 136,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser4', 'Unknown_Visibility_136'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 137,
        "count": 1,
        "names": ['ID_Visi_SysEin_Brauchwasser5', 'Unknown_Visibility_137'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 138,
        "count": 1,
        "names": ['ID_Visi_SysEin_BWWPmax', 'Unknown_Visibility_138'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 139,
        "count": 1,
        "names": ['ID_Visi_SysEin_Abtzykmax', 'Unknown_Visibility_139'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 140,
        "count": 1,
        "names": ['ID_Visi_SysEin_Luftabt', 'Unknown_Visibility_140'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 141,
        "count": 1,
        "names": ['ID_Visi_SysEin_LuftAbtmax', 'Unknown_Visibility_141'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 142,
        "count": 1,
        "names": ['ID_Visi_SysEin_Abtauen1', 'Unknown_Visibility_142'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 143,
        "count": 1,
        "names": ['ID_Visi_SysEin_Abtauen2', 'Unknown_Visibility_143'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 144,
        "count": 1,
        "names": ['ID_Visi_SysEin_Pumpenoptim', 'Unknown_Visibility_144'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 145,
        "count": 1,
        "names": ['ID_Visi_SysEin_Zusatzpumpe', 'Unknown_Visibility_145'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 146,
        "count": 1,
        "names": ['ID_Visi_SysEin_Zugang', 'Unknown_Visibility_146'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 147,
        "count": 1,
        "names": ['ID_Visi_SysEin_SoledrDurchf', 'Unknown_Visibility_147'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 148,
        "count": 1,
        "names": ['ID_Visi_SysEin_UberwachungVD', 'Unknown_Visibility_148'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 149,
        "count": 1,
        "names": ['ID_Visi_SysEin_RegelungHK', 'Unknown_Visibility_149'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 150,
        "count": 1,
        "names": ['ID_Visi_SysEin_RegelungMK1', 'Unknown_Visibility_150'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 151,
        "count": 1,
        "names": ['ID_Visi_SysEin_RegelungMK2', 'Unknown_Visibility_151'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 152,
        "count": 1,
        "names": ['ID_Visi_SysEin_Kuhlung', 'Unknown_Visibility_152'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 153,
        "count": 1,
        "names": ['ID_Visi_SysEin_Ausheizen', 'Unknown_Visibility_153'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 154,
        "count": 1,
        "names": ['ID_Visi_SysEin_ElektrAnode', 'Unknown_Visibility_154'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 155,
        "count": 1,
        "names": ['ID_Visi_SysEin_SWBBer', 'Unknown_Visibility_155'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 156,
        "count": 1,
        "names": ['ID_Visi_SysEin_SWBMin', 'Unknown_Visibility_156'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 157,
        "count": 1,
        "names": ['ID_Visi_SysEin_Heizung', 'Unknown_Visibility_157'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 158,
        "count": 1,
        "names": ['ID_Visi_SysEin_PeriodeMk1', 'Unknown_Visibility_158'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 159,
        "count": 1,
        "names": ['ID_Visi_SysEin_LaufzeitMk1', 'Unknown_Visibility_159'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 160,
        "count": 1,
        "names": ['ID_Visi_SysEin_PeriodeMk2', 'Unknown_Visibility_160'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 161,
        "count": 1,
        "names": ['ID_Visi_SysEin_LaufzeitMk2', 'Unknown_Visibility_161'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 162,
        "count": 1,
        "names": ['ID_Visi_SysEin_Heizgrenze', 'Unknown_Visibility_162'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 163,
        "count": 1,
        "names": ['ID_Visi_Enlt_HUP', 'Unknown_Visibility_163'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 164,
        "count": 1,
        "names": ['ID_Visi_Enlt_ZUP', 'Unknown_Visibility_164'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 165,
        "count": 1,
        "names": ['ID_Visi_Enlt_BUP', 'Unknown_Visibility_165'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 166,
        "count": 1,
        "names": ['ID_Visi_Enlt_Ventilator_BOSUP', 'Unknown_Visibility_166'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 167,
        "count": 1,
        "names": ['ID_Visi_Enlt_MA1', 'Unknown_Visibility_167'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 168,
        "count": 1,
        "names": ['ID_Visi_Enlt_MZ1', 'Unknown_Visibility_168'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 169,
        "count": 1,
        "names": ['ID_Visi_Enlt_ZIP', 'Unknown_Visibility_169'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 170,
        "count": 1,
        "names": ['ID_Visi_Enlt_MA2', 'Unknown_Visibility_170'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 171,
        "count": 1,
        "names": ['ID_Visi_Enlt_MZ2', 'Unknown_Visibility_171'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 172,
        "count": 1,
        "names": ['ID_Visi_Enlt_SUP', 'Unknown_Visibility_172'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 173,
        "count": 1,
        "names": ['ID_Visi_Enlt_SLP', 'Unknown_Visibility_173'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 174,
        "count": 1,
        "names": ['ID_Visi_Enlt_FP2', 'Unknown_Visibility_174'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 175,
        "count": 1,
        "names": ['ID_Visi_Enlt_Laufzeit', 'Unknown_Visibility_175'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 176,
        "count": 1,
        "names": ['ID_Visi_Anlgkonf_Heizung', 'Unknown_Visibility_176'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 177,
        "count": 1,
        "names": ['ID_Visi_Anlgkonf_Brauchwarmwasser', 'Unknown_Visibility_177'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 178,
        "count": 1,
        "names": ['ID_Visi_Anlgkonf_Schwimmbad', 'Unknown_Visibility_178'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 179,
        "count": 1,
        "names": ['ID_Visi_Heizung_Betriebsart', 'Unknown_Visibility_179'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 180,
        "count": 1,
        "names": ['ID_Visi_Heizung_TemperaturPlusMinus', 'Unknown_Visibility_180'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 181,
        "count": 1,
        "names": ['ID_Visi_Heizung_Heizkurven', 'Unknown_Visibility_181'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 182,
        "count": 1,
        "names": ['ID_Visi_Heizung_Zeitschaltprogramm', 'ID_Visi_Heizung_Zeitschlaltprogramm', 'Unknown_Visibility_182'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 183,
        "count": 1,
        "names": ['ID_Visi_Heizung_Heizgrenze', 'Unknown_Visibility_183'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 184,
        "count": 1,
        "names": ['ID_Visi_Mitteltemperatur', 'Unknown_Visibility_184'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 185,
        "count": 1,
        "names": ['ID_Visi_Dataenlogger', 'Unknown_Visibility_185'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 186,
        "count": 1,
        "names": ['ID_Visi_Sprachen_DEUTSCH', 'Unknown_Visibility_186'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 187,
        "count": 1,
        "names": ['ID_Visi_Sprachen_ENGLISH', 'Unknown_Visibility_187'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 188,
        "count": 1,
        "names": ['ID_Visi_Sprachen_FRANCAIS', 'Unknown_Visibility_188'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 189,
        "count": 1,
        "names": ['ID_Visi_Sprachen_NORWAY', 'Unknown_Visibility_189'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 190,
        "count": 1,
        "names": ['ID_Visi_Sprachen_TCHECH', 'Unknown_Visibility_190'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 191,
        "count": 1,
        "names": ['ID_Visi_Sprachen_ITALIANO', 'Unknown_Visibility_191'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 192,
        "count": 1,
        "names": ['ID_Visi_Sprachen_NEDERLANDS', 'Unknown_Visibility_192'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 193,
        "count": 1,
        "names": ['ID_Visi_Sprachen_SVENSKA', 'Unknown_Visibility_193'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 194,
        "count": 1,
        "names": ['ID_Visi_Sprachen_POLSKI', 'Unknown_Visibility_194'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 195,
        "count": 1,
        "names": ['ID_Visi_Sprachen_MAGYARUL', 'Unknown_Visibility_195'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 196,
        "count": 1,
        "names": ['ID_Visi_ErrorUSBspeichern', 'Unknown_Visibility_196'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 197,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdHz', 'Unknown_Visibility_197'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 198,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdBW', 'Unknown_Visibility_198'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 199,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdKue', 'Unknown_Visibility_199'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 200,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung', 'Unknown_Visibility_200'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 201,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung_Contrast', 'Unknown_Visibility_201'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 202,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung_Webserver', 'Unknown_Visibility_202'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 203,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung_IPAdresse', 'Unknown_Visibility_203'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 204,
        "count": 1,
        "names": ['ID_Visi_Service_Systemsteuerung_Fernwartung', 'Unknown_Visibility_204'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 205,
        "count": 1,
        "names": ['ID_Visi_Paralleleschaltung', 'Unknown_Visibility_205'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 206,
        "count": 1,
        "names": ['ID_Visi_SysEin_Paralleleschaltung', 'Unknown_Visibility_206'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 207,
        "count": 1,
        "names": ['ID_Visi_Sprachen_DANSK', 'Unknown_Visibility_207'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 208,
        "count": 1,
        "names": ['ID_Visi_Sprachen_PORTUGES', 'Unknown_Visibility_208'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 209,
        "count": 1,
        "names": ['ID_Visi_Heizkurve_Heizung', 'Unknown_Visibility_209'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 210,
        "count": 1,
        "names": ['ID_Visi_SysEin_Mischkreis3', 'Unknown_Visibility_210'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 211,
        "count": 1,
        "names": ['ID_Visi_MK3', 'Unknown_Visibility_211'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 212,
        "count": 1,
        "names": ['ID_Visi_Temp_MK3_Vorlauf', 'Unknown_Visibility_212'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 213,
        "count": 1,
        "names": ['ID_Visi_Temp_MK3VL_Soll', 'Unknown_Visibility_213'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 214,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer3Auf', 'Unknown_Visibility_214'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 215,
        "count": 1,
        "names": ['ID_Visi_OUT_Mischer3Zu', 'Unknown_Visibility_215'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 216,
        "count": 1,
        "names": ['ID_Visi_SysEin_RegelungMK3', 'Unknown_Visibility_216'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 217,
        "count": 1,
        "names": ['ID_Visi_SysEin_PeriodeMk3', 'Unknown_Visibility_217'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 218,
        "count": 1,
        "names": ['ID_Visi_SysEin_LaufzeitMk3', 'Unknown_Visibility_218'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 219,
        "count": 1,
        "names": ['ID_Visi_SysEin_Kuhl_Zeit_Ein', 'Unknown_Visibility_219'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 220,
        "count": 1,
        "names": ['ID_Visi_SysEin_Kuhl_Zeit_Aus', 'Unknown_Visibility_220'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 221,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_AbtauIn', 'Unknown_Visibility_221'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 222,
        "count": 1,
        "names": ['ID_Visi_Waermemenge_WS', 'Unknown_Visibility_222'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 223,
        "count": 1,
        "names": ['ID_Visi_Waermemenge_WQ', 'Unknown_Visibility_223'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 224,
        "count": 1,
        "names": ['ID_Visi_Enlt_MA3', 'Unknown_Visibility_224'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 225,
        "count": 1,
        "names": ['ID_Visi_Enlt_MZ3', 'Unknown_Visibility_225'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 226,
        "count": 1,
        "names": ['ID_Visi_Enlt_FP3', 'Unknown_Visibility_226'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 227,
        "count": 1,
        "names": ['ID_Visi_OUT_FUP3', 'Unknown_Visibility_227'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 228,
        "count": 1,
        "names": ['ID_Visi_Temp_Raumstation2', 'Unknown_Visibility_228'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 229,
        "count": 1,
        "names": ['ID_Visi_Temp_Raumstation3', 'Unknown_Visibility_229'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 230,
        "count": 1,
        "names": ['ID_Visi_Bst_BStdSW', 'Unknown_Visibility_230'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 231,
        "count": 1,
        "names": ['ID_Visi_Sprachen_LITAUISCH', 'Unknown_Visibility_231'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 232,
        "count": 1,
        "names": ['ID_Visi_Sprachen_ESTNICH', 'Unknown_Visibility_232'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 233,
        "count": 1,
        "names": ['ID_Visi_SysEin_Fernwartung', 'Unknown_Visibility_233'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 234,
        "count": 1,
        "names": ['ID_Visi_Sprachen_SLOVENISCH', 'Unknown_Visibility_234'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 235,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TA_EG', 'Unknown_Visibility_235'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 236,
        "count": 1,
        "names": ['ID_Visi_Einst_TVLmax_EG', 'Unknown_Visibility_236'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 237,
        "count": 1,
        "names": ['ID_Visi_SysEin_PoptNachlauf', 'Unknown_Visibility_237'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 238,
        "count": 1,
        "names": ['ID_Visi_RFV_K_Kuehlin', 'Unknown_Visibility_238'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 239,
        "count": 1,
        "names": ['ID_Visi_SysEin_EffizienzpumpeNom', 'Unknown_Visibility_239'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 240,
        "count": 1,
        "names": ['ID_Visi_SysEin_EffizienzpumpeMin', 'Unknown_Visibility_240'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 241,
        "count": 1,
        "names": ['ID_Visi_SysEin_Effizienzpumpe', 'Unknown_Visibility_241'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 242,
        "count": 1,
        "names": ['ID_Visi_SysEin_Waermemenge', 'Unknown_Visibility_242'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 243,
        "count": 1,
        "names": ['ID_Visi_Service_WMZ_Effizienz', 'Unknown_Visibility_243'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 244,
        "count": 1,
        "names": ['ID_Visi_SysEin_Wm_Versorgung_Korrektur', 'Unknown_Visibility_244'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 245,
        "count": 1,
        "names": ['ID_Visi_SysEin_Wm_Auswertung_Korrektur', 'Unknown_Visibility_245'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 246,
        "count": 1,
        "names": ['ID_Visi_IN_AnalogIn', 'Unknown_Visibility_246'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 247,
        "count": 1,
        "names": ['ID_Visi_Eins_SN_Eingabe', 'Unknown_Visibility_247'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 248,
        "count": 1,
        "names": ['ID_Visi_OUT_Analog_1', 'Unknown_Visibility_248'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 249,
        "count": 1,
        "names": ['ID_Visi_OUT_Analog_2', 'Unknown_Visibility_249'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 250,
        "count": 1,
        "names": ['ID_Visi_Solar', 'Unknown_Visibility_250'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 251,
        "count": 1,
        "names": ['ID_Visi_SysEin_Solar', 'Unknown_Visibility_251'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 252,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_TDiffKollmax', 'Unknown_Visibility_252'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 253,
        "count": 1,
        "names": ['ID_Visi_AblaufZ_HG_Sperre', 'Unknown_Visibility_253'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 254,
        "count": 1,
        "names": ['ID_Visi_SysEin_Akt_Kuehlung', 'Unknown_Visibility_254'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 255,
        "count": 1,
        "names": ['ID_Visi_SysEin_Vorlauf_VBO', 'Unknown_Visibility_255'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 256,
        "count": 1,
        "names": ['ID_Visi_Einst_KRHyst', 'Unknown_Visibility_256'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 257,
        "count": 1,
        "names": ['ID_Visi_Einst_Akt_Kuehl_Speicher_min', 'Unknown_Visibility_257'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 258,
        "count": 1,
        "names": ['ID_Visi_Einst_Akt_Kuehl_Freig_WQE', 'Unknown_Visibility_258'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 259,
        "count": 1,
        "names": ['ID_Visi_SysEin_AbtZykMin', 'Unknown_Visibility_259'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 260,
        "count": 1,
        "names": ['ID_Visi_SysEin_VD2_Zeit_Min', 'Unknown_Visibility_260'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 261,
        "count": 1,
        "names": ['ID_Visi_EinstTemp_Hysterese_HR_verkuerzt', 'Unknown_Visibility_261'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 262,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Feuchteschutz_akt', 'Unknown_Visibility_262'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 263,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Reduziert_akt', 'Unknown_Visibility_263'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 264,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Nennlueftung_akt', 'Unknown_Visibility_264'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 265,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Intensivlueftung_akt', 'Unknown_Visibility_265'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 266,
        "count": 1,
        "names": ['ID_Visi_Temperatur_Lueftung_Zuluft', 'Unknown_Visibility_266'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 267,
        "count": 1,
        "names": ['ID_Visi_Temperatur_Lueftung_Abluft', 'Unknown_Visibility_267'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 268,
        "count": 1,
        "names": ['ID_Visi_OUT_Analog_3', 'Unknown_Visibility_268'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 269,
        "count": 1,
        "names": ['ID_Visi_OUT_Analog_4', 'Unknown_Visibility_269'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 270,
        "count": 1,
        "names": ['ID_Visi_IN_Analog_2', 'Unknown_Visibility_270'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 271,
        "count": 1,
        "names": ['ID_Visi_IN_Analog_3', 'Unknown_Visibility_271'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 272,
        "count": 1,
        "names": ['ID_Visi_IN_SAX', 'Unknown_Visibility_272'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 273,
        "count": 1,
        "names": ['ID_Visi_OUT_VZU', 'Unknown_Visibility_273'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 274,
        "count": 1,
        "names": ['ID_Visi_OUT_VAB', 'Unknown_Visibility_274'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 275,
        "count": 1,
        "names": ['ID_Visi_OUT_VSK', 'Unknown_Visibility_275'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 276,
        "count": 1,
        "names": ['ID_Visi_OUT_FRH', 'Unknown_Visibility_276'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 277,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_SolltempMK3', 'Unknown_Visibility_277'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 278,
        "count": 1,
        "names": ['ID_Visi_KuhlTemp_ATDiffMK3', 'Unknown_Visibility_278'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 279,
        "count": 1,
        "names": ['ID_Visi_IN_SPL', 'Unknown_Visibility_279'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 280,
        "count": 1,
        "names": ['ID_Visi_SysEin_Lueftungsstufen', 'Unknown_Visibility_280'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 281,
        "count": 1,
        "names": ['ID_Visi_SysEin_Meldung_TDI', 'Unknown_Visibility_281'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 282,
        "count": 1,
        "names": ['ID_Visi_SysEin_Typ_WZW', 'Unknown_Visibility_282'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 283,
        "count": 1,
        "names": ['ID_Visi_BACnet', 'Unknown_Visibility_283'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 284,
        "count": 1,
        "names": ['ID_Visi_Sprachen_SLOWAKISCH', 'Unknown_Visibility_284'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 285,
        "count": 1,
        "names": ['ID_Visi_Sprachen_LETTISCH', 'Unknown_Visibility_285'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 286,
        "count": 1,
        "names": ['ID_Visi_Sprachen_FINNISCH', 'Unknown_Visibility_286'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 287,
        "count": 1,
        "names": ['ID_Visi_Kalibrierung_LWD', 'Unknown_Visibility_287'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 288,
        "count": 1,
        "names": ['ID_Visi_IN_Durchfluss', 'Unknown_Visibility_288'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 289,
        "count": 1,
        "names": ['ID_Visi_LIN_ANSAUG_VERDICHTER', 'Unknown_Visibility_289'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 290,
        "count": 1,
        "names": ['ID_Visi_LIN_VDH', 'Unknown_Visibility_290'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 291,
        "count": 1,
        "names": ['ID_Visi_LIN_UH', 'Unknown_Visibility_291'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 292,
        "count": 1,
        "names": ['ID_Visi_LIN_Druck', 'Unknown_Visibility_292'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 293,
        "count": 1,
        "names": ['ID_Visi_Einst_Sollwert_TRL_Kuehlen', 'Unknown_Visibility_293'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 294,
        "count": 1,
        "names": ['ID_Visi_Entl_ExVentil', 'Unknown_Visibility_294'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 295,
        "count": 1,
        "names": ['ID_Visi_Einst_Medium_Waermequelle', 'Unknown_Visibility_295'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 296,
        "count": 1,
        "names": ['ID_Visi_Einst_Multispeicher', 'Unknown_Visibility_296'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 297,
        "count": 1,
        "names": ['ID_Visi_Einst_Minimale_Ruecklaufsolltemperatur', 'Unknown_Visibility_297'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 298,
        "count": 1,
        "names": ['ID_Visi_Einst_PKuehlTime', 'Unknown_Visibility_298'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 299,
        "count": 1,
        "names": ['ID_Visi_Sprachen_TUERKISCH', 'Unknown_Visibility_299'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 300,
        "count": 1,
        "names": ['ID_Visi_RBE', 'Unknown_Visibility_300'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 301,
        "count": 1,
        "names": ['ID_Visi_Einst_Luf_Stufen_Faktor', 'Unknown_Visibility_301'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 302,
        "count": 1,
        "names": ['ID_Visi_Freigabe_Zeit_ZWE', 'Unknown_Visibility_302'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 303,
        "count": 1,
        "names": ['ID_Visi_Einst_min_VL_Kuehl', 'Unknown_Visibility_303'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 304,
        "count": 1,
        "names": ['ID_Visi_ZWE1', 'Unknown_Visibility_304'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 305,
        "count": 1,
        "names": ['ID_Visi_ZWE2', 'Unknown_Visibility_305'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 306,
        "count": 1,
        "names": ['ID_Visi_ZWE3', 'Unknown_Visibility_306'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 307,
        "count": 1,
        "names": ['ID_Visi_SEC', 'Unknown_Visibility_307'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 308,
        "count": 1,
        "names": ['ID_Visi_HZIO', 'Unknown_Visibility_308'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 309,
        "count": 1,
        "names": ['ID_Visi_WPIO', 'Unknown_Visibility_309'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 310,
        "count": 1,
        "names": ['ID_Visi_LIN_ANSAUG_VERDAMPFER', 'Unknown_Visibility_310'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 311,
        "count": 1,
        "names": ['ID_Visi_LIN_MULTI1', 'Unknown_Visibility_311'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 312,
        "count": 1,
        "names": ['ID_Visi_LIN_MULTI2', 'Unknown_Visibility_312'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 313,
        "count": 1,
        "names": ['ID_Visi_Einst_Leistung_ZWE', 'Unknown_Visibility_313'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 314,
        "count": 1,
        "names": ['ID_Visi_Sprachen_ESPANOL', 'Unknown_Visibility_314'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 315,
        "count": 1,
        "names": ['ID_Visi_Temp_BW_oben', 'Unknown_Visibility_315'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 316,
        "count": 1,
        "names": ['ID_Visi_MAXIO', 'Unknown_Visibility_316'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 317,
        "count": 1,
        "names": ['ID_Visi_OUT_Abtauwunsch', 'Unknown_Visibility_317'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 318,
        "count": 1,
        "names": ['ID_Visi_SmartGrid', 'Unknown_Visibility_318'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 319,
        "count": 1,
        "names": ['ID_Visi_Drehzahlgeregelt', 'Unknown_Visibility_319'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 320,
        "count": 1,
        "names": ['ID_Visi_P155_Inverter', 'Unknown_Visibility_320'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 321,
        "count": 1,
        "names": ['ID_Visi_Leistungsfreigabe', 'Unknown_Visibility_321'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 322,
        "count": 1,
        "names": ['ID_Visi_Einst_Vorl_akt_Kuehl', 'Unknown_Visibility_322'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 323,
        "count": 1,
        "names": ['ID_Visi_Einst_Abtauen_im_Warmwasser', 'Unknown_Visibility_323'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 324,
        "count": 1,
        "names": ['ID_Visi_Waermemenge_ZWE', 'Unknown_Visibility_324'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 325,
        "count": 1,
        "names": ['Unknown_Visibility_325'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 326,
        "count": 1,
        "names": ['Unknown_Visibility_326'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 327,
        "count": 1,
        "names": ['Unknown_Visibility_327'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 328,
        "count": 1,
        "names": ['Unknown_Visibility_328'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 329,
        "count": 1,
        "names": ['Unknown_Visibility_329'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 330,
        "count": 1,
        "names": ['Unknown_Visibility_330'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 331,
        "count": 1,
        "names": ['Unknown_Visibility_331'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 332,
        "count": 1,
        "names": ['Unknown_Visibility_332'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 333,
        "count": 1,
        "names": ['Unknown_Visibility_333'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 334,
        "count": 1,
        "names": ['Unknown_Visibility_334'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 335,
        "count": 1,
        "names": ['Unknown_Visibility_335'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 336,
        "count": 1,
        "names": ['Unknown_Visibility_336'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 337,
        "count": 1,
        "names": ['Unknown_Visibility_337'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 338,
        "count": 1,
        "names": ['Unknown_Visibility_338'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 339,
        "count": 1,
        "names": ['Unknown_Visibility_339'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 340,
        "count": 1,
        "names": ['Unknown_Visibility_340'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 341,
        "count": 1,
        "names": ['Unknown_Visibility_341'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 342,
        "count": 1,
        "names": ['Unknown_Visibility_342'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 343,
        "count": 1,
        "names": ['Unknown_Visibility_343'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 344,
        "count": 1,
        "names": ['Unknown_Visibility_344'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 345,
        "count": 1,
        "names": ['Unknown_Visibility_345'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 346,
        "count": 1,
        "names": ['Unknown_Visibility_346'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 347,
        "count": 1,
        "names": ['Unknown_Visibility_347'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 348,
        "count": 1,
        "names": ['Unknown_Visibility_348'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 349,
        "count": 1,
        "names": ['Unknown_Visibility_349'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 350,
        "count": 1,
        "names": ['Unknown_Visibility_350'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 351,
        "count": 1,
        "names": ['Unknown_Visibility_351'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 352,
        "count": 1,
        "names": ['Unknown_Visibility_352'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 353,
        "count": 1,
        "names": ['Unknown_Visibility_353'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 354,
        "count": 1,
        "names": ['Unknown_Visibility_354'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 355,
        "count": 1,
        "names": ['Unknown_Visibility_355', 'Unknown_Parameter_355'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 356,
        "count": 1,
        "names": ['Unknown_Visibility_356', 'Unknown_Parameter_356'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 357,
        "count": 1,
        "names": ['ELECTRICAL_POWER_LIMITATION_SWITCH', 'Unknown_Visibility_357', 'Unknown_Parameter_357'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 358,
        "count": 1,
        "names": ['Unknown_Visibility_358', 'Unknown_Parameter_358'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 359,
        "count": 1,
        "names": ['Unknown_Visibility_359', 'Unknown_Parameter_359'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 360,
        "count": 1,
        "names": ['Unknown_Visibility_360', 'Unknown_Parameter_360'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 361,
        "count": 1,
        "names": ['Unknown_Visibility_361', 'Unknown_Parameter_361'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 362,
        "count": 1,
        "names": ['Unknown_Visibility_362', 'Unknown_Parameter_362'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 363,
        "count": 1,
        "names": ['Unknown_Visibility_363', 'Unknown_Parameter_363'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 364,
        "count": 1,
        "names": ['Unknown_Visibility_364', 'Unknown_Parameter_364'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 365,
        "count": 1,
        "names": ['Unknown_Visibility_365', 'Unknown_Parameter_365'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 366,
        "count": 1,
        "names": ['Unknown_Visibility_366', 'Unknown_Parameter_366'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 367,
        "count": 1,
        "names": ['Unknown_Visibility_367', 'Unknown_Parameter_367'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 368,
        "count": 1,
        "names": ['Unknown_Visibility_368', 'Unknown_Parameter_368'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 369,
        "count": 1,
        "names": ['Unknown_Visibility_369', 'Unknown_Parameter_369'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 370,
        "count": 1,
        "names": ['Unknown_Visibility_370', 'Unknown_Parameter_370'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 371,
        "count": 1,
        "names": ['Unknown_Visibility_371', 'Unknown_Parameter_371'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 372,
        "count": 1,
        "names": ['Unknown_Visibility_372', 'Unknown_Parameter_372'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 373,
        "count": 1,
        "names": ['Unknown_Visibility_373', 'Unknown_Parameter_373'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 374,
        "count": 1,
        "names": ['Unknown_Visibility_374', 'Unknown_Parameter_374'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 375,
        "count": 1,
        "names": ['Unknown_Visibility_375', 'Unknown_Parameter_375'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 376,
        "count": 1,
        "names": ['Unknown_Visibility_376', 'Unknown_Parameter_376'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 377,
        "count": 1,
        "names": ['Unknown_Visibility_377', 'Unknown_Parameter_377'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 378,
        "count": 1,
        "names": ['Unknown_Visibility_378', 'Unknown_Parameter_378'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
    {
        "index": 379,
        "count": 1,
        "names": ['Unknown_Visibility_379', 'Unknown_Parameter_379'],
        "type": Unknown,
        "writeable": False,
        "datatype": 'UINT32',
        "unit": '',
        "description": '',
    },
]
